### ISSUE TITLE
Crash on server start with fresh download

### ISSUE THREAD

**Issue by VeyezX** [FTBTeam/FTB-Presents-Stoneblock-2#1]
* **Modpack Version**: 1.0.0

* **Issue**: 

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/b3c20928

* **Is it Repeatable?**: Yes, Just start up the server files.

* **Mod/s Affected**: Not sure, but it says something Reborncore

* **Known Fix**: -

**Comment by Sunekaer** [comment]
Remove MainMenuScale-1.1.jar from the mod folder on the server

**Comment by tfox83** [comment]
This file has been removed from the server zip in 1.0.0.  You can either re download the zip or remove that jar manually as Sunekaer said above.

**Comment by frogalo** [comment]
Perfect. Thank you <3
