### ISSUE TITLE
Small recipe change needed?

### ISSUE THREAD

**Issue by Matchyman** [FTBTeam/FTB-Presents-Stoneblock-2#10]
* **Modpack Version**: <1.0.0>

* **Issue**: <Able to make 4 stone sticks from 2 cobblestone. But also 2 stone sticks from 3 cobblestone, then able to be crafted into the stone ladders>

* **Link to Log or Crash File Paste**: <>

* **Is it Repeatable?**: <Yes>

* **Mod/s Affected**: 

* **Known Fix**: <It might just take a recipe change, its not pressing but just though you guys should know -->

**Comment by Sunekaer** [comment]
Well you can also make 4 sticks with 2 cobblestone

**Comment by Sunekaer** [comment]
but ill have a look at it

**Comment by Matchyman** [comment]
Like i said, i just noticed it. If its not likely to impact anything by all means just close this haha

**Comment by TheDCPlaya** [comment]
Wooden hammer recipe conflicts and show the chisel and bits wrench instead on crafting output https://i.imgur.com/vVHcCur.png

**Comment by Sunekaer** [comment]
1.1.0
