### ISSUE TITLE
Server Tick Crash from an iChun mod

### ISSUE THREAD

**Issue by vertex101** [FTBTeam/FTB-Presents-Stoneblock-2#101]
* **Modpack Version**: FTBPresentsStoneblock2-1.0.1-1.12.2

* **Issue**:  server crashing from me.ichun.mods.mmec.common.core.EventHandlerServer.onServerTick

* **Link to Log or Crash File Paste**: https://gist.github.com/vertex101/12caa1fa0035c3aa6f3f8456f7d04d95

* **Is it Repeatable?**:  the server has crashed twice in an hour

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Sunekaer** [comment]
#13
