### ISSUE TITLE
Ender Plate - Glider Keybind does not work.

### ISSUE THREAD

**Issue by RathRyce** [FTBTeam/FTB-Presents-Stoneblock-2#102]
* **Modpack Version**: 1.0.1
* **Issue**: Keybinding 'G' for Ender IO Glider does not work when glider applied to Ender Plate.  Therefore, no way to actually use the Glider on that armor set :(
* **Link to Log or Crash File Paste**: N/A
* **Is it Repeatable?**: Static issue - yes!
* **Mod/s Affected**: Ender IO
* **Known Fix**: Unknown

**Comment by Sunekaer** [comment]
Check your keybinds that there isn’t other things using G and blocking for it

**Comment by RathRyce** [comment]
Wow - way to derp... thanks Sunekaer!
