### ISSUE TITLE
drop of evil not making cursed earth

### ISSUE THREAD

**Issue by mlpcoder** [FTBTeam/FTB-Presents-Stoneblock-2#108]
* **Modpack Version**: 1.1.1

* **Issue**: drop of evil does not convert dirt to cursed earth (has no effect) on dirt inside of a compact machine

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: yes; initially discovered this trying to create a CE mob farm inside of a compact machine and able to repeat it.

* **Mod/s Affected**: Compact Machines? 

* **Known Fix**: You can create CE in the overworld, pick up with silk touch, and place in the compact machine.  Jury still out as to whether it will spread inside of the compact machine.

**Comment by Sunekaer** [comment]
Nothing i can do about this, create a issue on Compact Machines and ask them if its intended
