### ISSUE TITLE
Void Island autoCreate and command name not fixed in 1.0.1 even though reported in 1.0.0

### ISSUE THREAD

**Issue by Gunner76th** [FTBTeam/FTB-Presents-Stoneblock-2#11]
* **Modpack Version**: 1.0.1

* **Issue**: Upon starting a server in SMP all players are spawned at world spawn (0,0) in the same cave and unable to use the command /island create. This is because autoCreate= is set to false, and commandName= is set to cave. These both need to be fixed to their correct values of autoCreate=true and commandName=island
This is issue was reported in 1.0.0 and was not addressed prior to the 1.0.1 release even though this is a Server Multiplayer breaking mechanic. 

* **Link to Log or Crash File Paste**:N/A

* **Is it Repeatable?**: Yes, just create a server with the 1.0.1 server files currently posted on Curseforge

* **Mod/s Affected**: Void Island

* **Known Fix**: 
[voidislandcontrol.cfg.txt](https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/files/2726017/voidislandcontrol.cfg.txt)
This file contains the correct config settings that need to be used on Servers. You will need to rename the file and remove the .txt That had to be added due to GitHub file extension limitations.

**Comment by Sunekaer** [comment]
No this intended, your free to enable autoCreate on your server if you want that

**Comment by Sunekaer** [comment]
And the command is in the desc of the pack

**Comment by Gunner76th** [comment]
If the command to autoCreate is going to be left set to false, that should be added to the pack description as well as most if not all server and community admins are going to expect that command be set to true by default.

**Comment by ArbitraryHubris** [comment]
Honestly, this is just silly.  There is NO server user who will want autoCreate set to false.  Why would you put the wrong setting as default in your SERVER files?

**Comment by Sunekaer** [comment]
Sure ill add it to desc @Gunner76th

**Comment by Sunekaer** [comment]
Arbitrary what do you base it on to be a wrong setting? its up to each server owner if that a thing they want to have, just because it was default on in stoneblock 1 doesnt make it wrong to not be default on this one

**Comment by ArbitraryHubris** [comment]
Thanks for asking.  

If you set autoCreate to true then 100% of servers will work correctly on the first start of the server.  Experienced server owners will likely want to drop people at spawn, decorate it, instruct them on rules, etc., and then either give them the commands or a button to create an island.  Those experienced server owners will change autoCreate to false and build their spawn.  New server owners, especially small server owners, will be successful with your files as delivered and will then gradually have to learn a ton about admin tasks on their server.

If you leave it false, experienced server owners will have no issues.  The new server owners will likely have no idea where to start looking - they will just find that everyone is starting at the same spot.  They will come here, they will post on reddit, they will need support to figure things out.  

The second option is not a disaster situation.  But why not make the default setting one that makes all server owners successful?

What is the reason that you set it to false?  I'm sure you had a rational driver.

**Comment by Sunekaer** [comment]
VoidIslandControl just been updated with an new config "autoCreateServersOnly" which will be able
