### ISSUE TITLE
Repair Talisman Doesn't Repair Tinkers' Construct Tools

### ISSUE THREAD

**Issue by ArchonJK** [FTBTeam/FTB-Presents-Stoneblock-2#110]
Version: 1.1.1

Issue: Repair Talisman from ProjectE does not repair Tinkers' Construct tools.

Crash Report: No crash

Repeatable?: Yes

Mods Affected: ProjectE and Tinkers' Construct

Fix: No fix available

**Comment by Sunekaer** [comment]
To my knowledge its not meant to repair that ( Default in projecte and i dont think it can be change)
