### ISSUE TITLE
Missing Manifest or Minecraftinstance.json

### ISSUE THREAD

**Issue by Kezaraux** [FTBTeam/FTB-Presents-Stoneblock-2#111]
* **Modpack Version**: 1.0.1

* **Issue**: Server randomly crashes and states Missing manifest or minecraftinstance.json.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/1637e3bf

* **Is it Repeatable?**: It has repeated multiple times with varying frequency, unsure as to the cause.

* **Mod/s Affected**: Thaumcraft potentially? EntityPech is mentioned in the crash report.

* **Known Fix**: None at this time (attempting to turn off mob farm located in Magical Forest biome to see if any crashes happen after).

**Comment by Sunekaer** [comment]
https://github.com/Azanor/thaumcraft-beta/issues/1612

**Comment by Sunekaer** [comment]
Closing this issue, as there´s nothing we can do about this other then wait and see if the mod dev fixes it
