### ISSUE TITLE
Bug with Mekanism PRC

### ISSUE THREAD

**Issue by SavageKiller13** [FTBTeam/FTB-Presents-Stoneblock-2#112]
* **Modpack Version**: 1.1.1-->

* **Issue**: The Issue I have is when trying to use the Mekanism Pressurized Reaction chamber it won't convert Substrate into HDPE pellets. I have supplied it with the right resources and a decent amount of power but won't work.

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: The issue is repeatable and easy to cause

* **Mod/s Affected**: Mekanism

* **Known Fix**: A known fix I have is to just change the max base power usage to 10 J/t and it should work. The machine of what I've read needs to use 1000 J/t to convert the item. Since there is no other way to get the pellets it causes progression to be broken.

**Comment by Sunekaer** [comment]
![image](https://user-images.githubusercontent.com/18720460/51075765-678e6e00-1690-11e9-9363-fdfb50b020af.png)
Works fine for me
