### ISSUE TITLE
Unable to make dough with cooking for blockheads

### ISSUE THREAD

**Issue by megamanzteam** [FTBTeam/FTB-Presents-Stoneblock-2#114]
* **Modpack Version**: 1.0.1

* **Issue**: Cooking for blockheads to craft dough will not work. the wheat is supposed to be top left and center, but in the blockhead UI it is showing top left and center left which would create a seed.

* **Link to Log or Crash File Paste**: No error can be found that I am aware of.

* **Is it Repeatable?**: Unsure. If others can repeat please post below.

* **Mod/s Affected**: 

* **Known Fix**: I think you need to tweak the recipe in cooking for blockheads, as crafting dough via crafting table works.

**Comment by Sunekaer** [comment]
Closing issue, as we are waiting for the dev to add this. leaving issue on mod tracker open
