### ISSUE TITLE
Won't launch on Mac

### ISSUE THREAD

**Issue by abso1oot** [FTBTeam/FTB-Presents-Stoneblock-2#115]
* **Modpack Version**:  1.0.1

* **Issue**:  Game won't start up. Crashes immediately.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/24907f04

* **Is it Repeatable?**: Yes. Every time I try to start it.

Not sure what is going on. Any help would be great

**Comment by Shadowhunterpvp** [comment]
Same problem with me. I opened the case it is the most commented but sunekaer did not give any advice to me. Just play on a server man.

**Comment by abso1oot** [comment]
@Shadowhunterpvp How am I supposed to play on a server when I can't get the game to launch?

**Comment by Sunekaer** [comment]
Is this the full log? do you an Antivirus there stops some files from being used? what launcher are you using?

**Comment by abso1oot** [comment]
No antivirus software that is stopping it. This is the log from the launcher. I'm using Twitch and the default Minecraft launcher that it loads (v. 1.6.91).

**Comment by abso1oot** [comment]
It also gives me the following in the "Game Output" tab:

Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option PermSize; support was removed in 8.0
Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by abso1oot** [comment]
@Sunekaer I changed nothing, but tried it again and this time it is showing a [FATAL] where it did not before...

https://paste.feed-the-beast.com/view/26285528

**Comment by Sunekaer** [comment]
Some minecraft file is missing on your PC "File '/Users/andrewharman/Documents/Curse/Minecraft/Install/assets/indexes/1.10.json' does not exist" thats a problem with your launcher and not the pack, recommend reinstalling the launcher or contact twitch
