### ISSUE TITLE
Stellar Energy Conduits chewing up RF

### ISSUE THREAD

**Issue by nzminecraftDOTcom** [FTBTeam/FTB-Presents-Stoneblock-2#116]
* **Modpack Version**: 
V1.0.1

* **Issue**: 
Stellar Energy conduits chewing up RF while sitting idle.

* **Link to Log or Crash File Paste**: 
Not applicable.

* **Is it Repeatable?**: 
For testing to repeat the easiest way is as follows:
Creative RF source with flux plug attached (to see rf being used) and flux point connected to a single piece of stellar energy conduit, both plug and point on the same flux network. It will start to eat RF constantly.
* **Mod/s Affected**: 
EnderIO - the version that came stock with 1.0.1 of Stoneblock 2

* **Known Fix**: 
None that I am aware of, new version of EnderIO perhaps.

**Comment by Sunekaer** [comment]
I know some Enderio machines and stuff has a power loss, if you think this one isnt supposed to have that please contact Ontario

**Comment by tyler489** [comment]
Not a bug. Steller conduits have a huge 2Bill Fe buffer that must be filled.
