### ISSUE TITLE
Game crashes once I create a mob farm using drops of evil

### ISSUE THREAD

**Issue by Jackspegal** [FTBTeam/FTB-Presents-Stoneblock-2#117]
Modpack Version 1.0.1

I am exeperiencing crashes now that I have created a mob farm using the drops of evil.  I do not have a lot of things made in the game that would cause lag, other than an auto sieve setup, which does not lag me out, but when I go to open chests, or search in JEI lately, my game will crash and I will have to restart my client.  I am playing in single player only on my own system as I can;t afford a server.  Is this a known issue, or is it just my system?   I have not modified the modpack in anyway, nor have I changed anything with the modpack.
My crash report is here: https://paste.feed-the-beast.com/view/2800b2d3

* **Modpack Version**: 

* **Issue**: 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Sunekaer** [comment]
#111
