### ISSUE TITLE
Yet another dublication method

### ISSUE THREAD

**Issue by EmanYm** [FTBTeam/FTB-Presents-Stoneblock-2#118]
* **Modpack Version**: It's listed as "Stoneblock 2 - 1.0.0-hotfix" on the [server list](https://i.gyazo.com/61fdf2ae46d3eafa5c00f4f160515cc4.png)

* **Issue**: If two players have a magnet active and one drops an item, both players will acquire the item.

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: Yes.  [Here's a clip from last night's twitch stream](https://www.twitch.tv/videos/362707576).

* **Mod/s Affected**: Unknown.  Likely whatever mod has the item magnets.

* **Known Fix**: Unknown. Probably updating the pack to 1.0.1 or higher?

**Comment by Sunekaer** [comment]
#24
