### ISSUE TITLE
Infinity Drill 

### ISSUE THREAD

**Issue by bruceyboy24804** [FTBTeam/FTB-Presents-Stoneblock-2#119]
* **Modpack Version**: 1.1.1

* **Issue**: The Infinity drill from Industrial foregoing is too overpowered becuase it mines way to fast and max tier of infinty drill is is dimensions are 13 by 13 by by 13 and should be removed

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Industrial Foregoing

**Comment by Sunekaer** [comment]
Wont be changed
