### ISSUE TITLE
Atomic Disassembler is invisible

### ISSUE THREAD

**Issue by SuperBrainAK** [FTBTeam/FTB-Presents-Stoneblock-2#12]
* **Modpack Version**: 1.01

* **Issue**: atomic dissasembler is not showing up at all, it works fine but is invisible.

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Mekanism

![2019-01-04_02 31 24](https://user-images.githubusercontent.com/8132047/50682261-83787c80-0fcb-11e9-8d80-1880a5d15627.png)

**Comment by Sunekaer** [comment]
https://github.com/aidancbrady/Mekanism/issues/5205

**Comment by Sunekaer** [comment]
Setting allowEmissiveItems in forge.cfg to false works as a workaround to make the items visible again.
