### ISSUE TITLE
Config Request: Xaero's Minimap - Hide IPs by default

### ISSUE THREAD

**Issue by VoodooBeard** [FTBTeam/FTB-Presents-Stoneblock-2#121]
* **Modpack Version**: 1.0.1

* **Issue**: Server IPs are, by default, viewable in the Xaero's Minimap Waypoints list. It is far to easy for someone recording or streaming this pack to overlook the minimap setting and inadvertently broadcast their server IP. The Server IP hidden as default would prevent these kinds of mishaps.  

* **Is it Repeatable?**: n/a

* **Mod/s Affected**: Xaero's Minimap

![2019-01-12_16 55 28](https://user-images.githubusercontent.com/20506267/51076091-fea4f700-168b-11e9-90b1-77c8cebdf59b.png)
![2019-01-12_16 56 01](https://user-images.githubusercontent.com/20506267/51076093-019fe780-168c-11e9-8c87-6a08bee2538c.png)
![2019-01-12_16 56 12](https://user-images.githubusercontent.com/20506267/51076094-04024180-168c-11e9-94f9-62fe87d76851.png)

**Comment by Sunekaer** [comment]
Sure

**Comment by VoodooBeard** [comment]
Thank you very much :-)
