### ISSUE TITLE
Iron Plate Craftable with 3 iron ingots?

### ISSUE THREAD

**Issue by DrakusorU** [FTBTeam/FTB-Presents-Stoneblock-2#124]
* **Modpack Version**: 1.1.1
* **Issue**: The iron plate is craftable with 3 iron ingots.. not sure if this is intended but doesnt look like it.. http://prntscr.com/m6exqc

Also, not all the plates are craftable with the IE hammer.. The tin, platinum*, iridium*, infused mana*, invar, bronze, signalum*, lumium and enderium* ( * those with are not used in any crafting anyway )  are not craftable using the IE hammer..

**Comment by Sunekaer** [comment]
ill add recipes for the others
