### ISSUE TITLE
Fire water from Ender IO not working at all.

### ISSUE THREAD

**Issue by danmiau** [FTBTeam/FTB-Presents-Stoneblock-2#126]
* **Stoneblock 2 1.12.2**: 

* **Fire water from Ender IO not working. I put the fire water under crucibles, and they dont get any heating rate. Beside that, i can walk in the fire water and its like im walking on normal cobblestone.**:

**Comment by Sunekaer** [comment]
under crucible? Its shouldnt?
Okay thats something you should report to EnderIO
