### ISSUE TITLE
Specific user leaving DIM-8 crashes server (possibly corruption, work-around found)

### ISSUE THREAD

**Issue by scooter8511** [FTBTeam/FTB-Presents-Stoneblock-2#128]
UPDATE: See https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/issues/13. I overlooked this one, seems like the same issue. Sorry for not catching it sooner.

* **Modpack Version**: 1.0.1 (Release)
* **Issue**: Server crashes when specific user leaves the End (DIM-8)

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/d178afbc

* **Is it Repeatable?**: Likely. The crash does not fail for me, but I am not sure what initiated it. May have just been a corruption? New to troubleshooting... 

I host a small server for 4 people. The issue only occurs for me, first noticed when leaving the End (by mining downward). Issue also occurs when using /spawn and a /home set in the overworld as well as leaving the server while in the End. I can travel to/from the mining dimension without issue using any method. I can enter the End with no issue. 

Possibly similar to https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/issues/111

* **Mod/s Affected**: Unknown. Many Withers, Ender Chickens, and Chaos Chickens were killed there. Some Chance Cubes were opened, one of which spawned a village. Could be related? (I was the one who opened it).

* **Known Fix**: With the End only being what we put there, we removed all valuables and deleted DIM-8. Server created a new dimension on load, and the crash no longer occurs. (I kept the old dimension folder if needed for testing).

**Comment by Sunekaer** [comment]
Yes same as #13 update your server
