### ISSUE TITLE
Extreme lag and rendering issue  with amd

### ISSUE THREAD

**Issue by gtxjgk** [FTBTeam/FTB-Presents-Stoneblock-2#130]
* **Modpack Version**: 1.0.1

* **Issue**:  extree lag and rendering issues  with amd cpu and gpu even though its consuming 5gb of ram

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: yes

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Boomflex** [comment]
Can you try on 6GB of RAM dedicated to MC?

200+ mods can technically work on 5GB, but you will have more fun 6GB+

**Comment by Sataana** [comment]
in: .\config\foamfix.cfg
under textures, set I:fasterAnimation=0
