### ISSUE TITLE
Mob fand distance upgrade has no effect one mob fan.

### ISSUE THREAD

**Issue by chrisisonwildcode** [FTBTeam/FTB-Presents-Stoneblock-2#131]
* **Modpack Version**: 1.1.1

* **Issue**: Mob fan upgrade distance modifier has no effect on mob fan.

* **Link to Log or Crash File Paste**: nothing useful on logs

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Mob Grinding Utils 0.3.13

* **Known Fix**:unknown

**Comment by Sunekaer** [comment]
Works fine for me? are you using the correct upgrades, did you activate the fan?

**Comment by chrisisonwildcode** [comment]
yes and yes, fan is active and blows mobs along. However the mob fan upgrade for distance how no effect on the distance the mob fan blows entities. Width and height modifiers work fine.

**Comment by Boomflex** [comment]
Can confirm works fine as I have my Mob farm using the distance fans.

**Comment by chrisisonwildcode** [comment]
Discovered what was going on. A sign was stopping the range from extending.

Since this is a PEBKAC I'm closing this.
