### ISSUE TITLE
Recipe Issues (Craft tweaker recipes not working properly).

### ISSUE THREAD

**Issue by Lost-Ninja** [FTBTeam/FTB-Presents-Stoneblock-2#132]
* 1.0.1: 

* Recipes removed with Craft Tweaker (et al) still work, recipes added appear in JEI but aren't craftable. Tested with various recipes:
ProjectE (several items), 
ExNihlo (stone hammer using stone rods), 
Flux (no recipe for Flux Dust in a furnace (can still be made by burning redstone).
and so on...

Xaero's Minimap, GooglyEyes, PetRock & IronBackPacks - Disabled
Journey Minimap - Added 

* Seems to be fairly normal (if unwanted) behaviour.: 

* Craftweaker, JEI: 

* **Known Fix**:

**Comment by Sunekaer** [comment]
It works fine for me, try update or reinstalling your pack

**Comment by Boomflex** [comment]
All the above recipes work in v1.1.1

So I would recommend updating to v1.1.1 or totally reinstalling your current instance.

**Comment by Lost-Ninja** [comment]
Updating to 1.1.1 didn't fix the issue.

I then installed an entirely new client and just copied my saves across, still able to use default recipes.

Is it likely to be due to CraftTweaker being unable to run the petrock scripts? (I remove it because it's completely pointless and adds world gen).

**Comment by Lost-Ninja** [comment]
"Is it likely to be due to CraftTweaker being unable to run the petrock scripts? (I remove it because it's completely pointless and adds world gen)."

Yes!

Removing the PetRock.zs script (when I removed the mod), fixes the recipes... :)
