### ISSUE TITLE
Tinkers Tank controller not recognising valid tanks

### ISSUE THREAD

**Issue by chrisisonwildcode** [FTBTeam/FTB-Presents-Stoneblock-2#133]
* **Modpack Version**: 1.1.1
* **Issue**: the 1.1.1 update resulted in the tinkers tank controller no longer working with valid tanks.

* **Link to Log or Crash File Paste**: Nothing useful in logs

* **Is it Repeatable?**: yes, have tried various sized of tanks.

* **Mod/s Affected**:TConstruct 2.12.0.113

* **Known Fix**: unknown

**Comment by Boomflex** [comment]
Sounds like https://github.com/SlimeKnights/TinkersConstruct/issues/3719

Looks like there was some Smeltery changes which may have affected?

Can you send a pic of your tank setup?

**Comment by KnightMiner** [comment]
Yeah, due to a smeltery fix, the Tinker Tank no longer allows the controller in the bottom layer. This will be fixed in the next build, but for now you can place the controller one block higher.
