### ISSUE TITLE
EMC for draconium dust and ingots not balanced.

### ISSUE THREAD

**Issue by MarkSzita** [FTBTeam/FTB-Presents-Stoneblock-2#134]
* **Modpack Version**: 1.1.1

* **Issue**: Draconium Dust is worth 16,384 EMC while the ingots are worth 16,380.

**Comment by Explosivee** [comment]
4 emc for the RF and time you've spend on it, lul

**Comment by Sunekaer** [comment]
wont be changed, to low of a different to make any different in this pack
