### ISSUE TITLE
[Suggestion] Gas Conduits

### ISSUE THREAD

**Issue by pupnewfster** [FTBTeam/FTB-Presents-Stoneblock-2#136]
Not exactly following the issue format as this is more of a suggestion of a mod to be added than a bug. I suggest adding the mod [Gas Conduits](https://minecraft.curseforge.com/projects/gas-conduits) given StoneBlock contains both Mekanism and EnderIO and it makes transferring gas a lot more convenient and easier to condense among other conduits. I probably am a bit biased given I made the mod reducing the space it requires to make machine chains for Mekanism, but I still think it would be a good edition to the pack.

**Comment by Explosivee** [comment]
You can use XNet as a temporary solution, it had gas channels but still this Gas Conduits'd be cool to have in this modpack.

**Comment by Boomflex** [comment]
+1 for me.
