### ISSUE TITLE
Morph / JEI causes crashes

### ISSUE THREAD

**Issue by TheForceteam** [FTBTeam/FTB-Presents-Stoneblock-2#139]
* **Modpack Version**: 1.1.1 

* **Issue**: Game crashed when trying to see the recipe for the Shulker Shell 

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/d65fa9d3

* **Is it Repeatable?**: Yes 

* **Mod/s Affected**: Morph and JEI

* **Known Fix**: REMOVE MORPH

**Comment by Dreamer9206** [comment]
Modpack Version: 1.1.1 
Issue: Game crashed when trying to see the recipe for the Shulker Shell 
Link to Log or Crash File Paste: https://paste.feed-the-beast.com/view/d49c82de
Is it Repeatable?: Yes 
Mod/s Affected: Morph and JEI
Known Fix: REMOVE MORPH

**Comment by Sunekaer** [comment]
closing issue, issue on mods tracker is still open

**Comment by iChun** [comment]
another crash log https://pastebin.com/LNiHe5d0
