### ISSUE TITLE
Fuel disappearing when feeding generator with scroll wheel

### ISSUE THREAD

**Issue by RetekJorr** [FTBTeam/FTB-Presents-Stoneblock-2#14]
I was feeding charcoal into a Furnace Generator and one would load in but all other fuel as long as one was in the generator inventory would void instead of stacking in the generator

* **Modpack Version**: 1.0.1

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Unsure what's causing the issue, but related mods would be: Extra Utilities (generator) and Mouse Tweaks

**Comment by davidgillen** [comment]
Was going to log the similar. Issue when putting coal into the Survival Generator, only ever 1 appearing, others just seem to disappear, when using mouse tweaks scroll wheel insert.

**Comment by Sunekaer** [comment]
Closing this issue, as there´s nothing we can do about this other then wait and see if the mod dev fixes it
