### ISSUE TITLE
Thaumcraft Vis Crystals not working in Transfusion Table

### ISSUE THREAD

**Issue by xellosmetallum** [FTBTeam/FTB-Presents-Stoneblock-2#140]
* **Modpack Version**:  1.0.1

* **Issue**: When teaching the transfusion table any vis crystal you are unable to pull out a specific crystal afterwords. The only vis crystal listed in the table is unaspected and is called %s% crystal.

* **Is it Repeatable?**: Yes it happens every single time.

* **Mod/s Affected**:ProjectE 1.3.2h, Thaumcraft 6.1 BETA 26

* **Known Fix**: None that I know of.

**Comment by Sunekaer** [comment]
That works as it should, you get random crystals out
