### ISSUE TITLE
Tinkers Parts Table

### ISSUE THREAD

**Issue by YuutsuShibo** [FTBTeam/FTB-Presents-Stoneblock-2#141]
* **Modpack Version**: 1.1.1

* **Issue**: Tinkers parts table won't create parts when supplied resources. (Early game so I have only tried using flint, stone and wood.)

* **Link to Log or Crash File Paste**:  n/a, Doesn't causing crash.

* **Is it Repeatable?**: Log in and out, removed block and replaced, and used different sketches and resources with same failed result.

* **Mod/s Affected**: Tinkerer's Construct

**Comment by Sunekaer** [comment]
Are you giving it the correct amount?

**Comment by Boomflex** [comment]
I have just tried all the above and they all worked.

I'd ensure you are using the correct amount.

Even better, send a screenshot here via imgur!

**Comment by YuutsuShibo** [comment]
Issue is fixed now. As for the amount being placed I was putting enough in the slot to change the red text of not having enough, to grey. Material quantity wasn't the problem.

**Comment by YuutsuShibo** [comment]
I'm wrong the problem isn't fixed. When resources are placed in the slot 1 at a time they tool part wont show up unless I click out of the interface and click back in, but if the correct amount if placed in all at once the part will show. So its its ust not working as intended.
