### ISSUE TITLE
Random Items Overpowered

### ISSUE THREAD

**Issue by CarelessSpore** [FTBTeam/FTB-Presents-Stoneblock-2#142]
* **Modpack Version**: Stoneblock 2 1.0.1 

* **Issue**: Random Items are Overpowered I got the max tier for the Mystical Agriculture I then proceeded to get an Imaginary Time Block which is pretty much an instant grow machine and is end game level. I would recommend tweaking what you can get from the random rewards because I just started the pack yesterday and I'm already done it just because of this one mechanic.

* **Link to Log or Crash File Paste**: No Log Given

* **Is it Repeatable?**: By Luck

* **Mod/s Affected**: ---- 

* **Known Fix**: ----

**Comment by AndersWithTheCat** [comment]
Yes i agree on this. :)

**Comment by iKurama** [comment]
Please edit the post and title, so people won't be confused with the mod 'Random Things'.

**Comment by SirioIlBe** [comment]
and here i am getting 3 invar hammers in a row

**Comment by Sunekaer** [comment]
Won’t be changed
