### ISSUE TITLE
Duplication with item magnet from quantum flux 

### ISSUE THREAD

**Issue by Brewty** [FTBTeam/FTB-Presents-Stoneblock-2#143]
* **Modpack Version**: 1.0.1

* **Issue**: When dropping or receiving an item to or from another player while the wires magnet is active causes the item to be dropped and picked up by both the recipient and original player who dropped it. Effectively duplicating the item(s)

* **Link to Log or Crash File Paste**: 

* **Is it repepeatable**: Yes

* **Mod/s Affected**: Quantum Flux

* **Known Fix**:

**Comment by iKurama** [comment]
https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/issues/24
