### ISSUE TITLE
Wood Chippings doesn't come out when the wood is placed horizontally.

### ISSUE THREAD

**Issue by nickseo7** [FTBTeam/FTB-Presents-Stoneblock-2#144]
* **Modpack Version**: 1.1.1

* **Issue**: Wood Chippings are only dropped when 'vertically' placed wood is broken, not for horizontal one.

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Ex compressum

* **Known Fix**:

**Comment by Sunekaer** [comment]
https://github.com/blay09/ExCompressum/issues/265

**Comment by Sunekaer** [comment]
Closing this issue, as there´s nothing we can do about this other then wait and see if the mod dev fixes it
