### ISSUE TITLE
tried to start my server after computer crashes and get this error

### ISSUE THREAD

**Issue by StevieMcgee** [FTBTeam/FTB-Presents-Stoneblock-2#147]
[crash-2019-01-14_20.59.25-server.txt](https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/files/2754689/crash-2019-01-14_20.59.25-server.txt)

**Comment by Sunekaer** [comment]
Template not used, and log not linked via paste.feed-the-beast.com
