### ISSUE TITLE
Ignition: Foundry

### ISSUE THREAD

**Issue by Explosivee** [FTBTeam/FTB-Presents-Stoneblock-2#148]
We have Fluid Cows in the game so it means we have to deal with a lot of liquid ores etc. and the only way to cast them into the ingots is Tinkers' (if i'm mistaken sorry for that) so i think this modpack need machines, especially faster ways to cast liquids into ingots than Tinkers' so there is a mod called as "[Ignition: Foundry](https://minecraft.curseforge.com/projects/ignition-foundry)" and it does the job, it'd be nice if you guys add this mod into the modpack.

**Comment by Sunekaer** [comment]
Hows this mod supposed to help? i dont see from looking at the mod  how it should?

**Comment by Explosivee** [comment]
The Metal Caster can cast ingots a lot more faster than Tinkers' and it's only one block also works with RF, that's how it's gonna help

**Comment by Slyklaw** [comment]
Pumping the liquid to a Casting Basin makes a whole block at a time quite efficiently. Doesn't even need RF.
