### ISSUE TITLE
Minecraft lagging and not rendering (reopen)

### ISSUE THREAD

**Issue by gtxjgk** [FTBTeam/FTB-Presents-Stoneblock-2#149]
* **Modpack Version**: 1.0.1

* **Issue**: sorry reopening issue cause its still 
 minecraft is  lagging and not rendering fast
Getting around  1-2 fps  tried to change config
Of foamfix  but made no difference

Here are specs

Laptop name: Acer  Nitro 5

Cpu: Amd ryzen 5 2500U  2.0 ghz  base processor speed  3.4  ghz  total

Ram: 8gb

Graphics: Amd  Radeon  RX560X  (4gb)

Display: FHD  1920×1080

Integrated graphics : Amd radeon vegas 8 (1gb)

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: YES

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by iKurama** [comment]
Logs. We can't use that as a verification or other stuff, to help you.

**Comment by gtxjgk** [comment]
Well is there any solution

**Comment by iKurama** [comment]
We still need logs no matter what.

**Comment by Kratzwurst** [comment]
u are try to doing this maybe:

-Show in the Launcher what u use and change in the Preferences the Ram maximum to 4 GB (
many Modpacks needs minimum 4 GB also Stoneblock 2, better is 5GB) 
-Shutdown all Background Programs (Browser etc. Windows himself needs 2-3GB of Ram)
-Shutdown Resourcepacks, Shaders etc. (Needs Ram)
-Install optifine (helps a lot)

Last Instance: Upgrade Ram to 16 GB if you can.

**Comment by iKurama** [comment]
If he installs Optifine, it will not be supported.

**Comment by Kratzwurst** [comment]
hey is an optional option for the lowend fps  and i know it, that will be here not supported @iKurama

**Comment by Sunekaer** [comment]
Try turning off Mipmap in video settings

**Comment by triffman33** [comment]
Try using these settings and keeping the window relatively small.  https://imgur.com/jjVixFx
If it still lags try reinstalling java/graphic drivers.
Try disabling foamfix completely.
Reinstall the modpack.

If those don't work your laptop may be using the integrated graphics or some of your hardware might be bamboozled.
