### ISSUE TITLE
Particles/potions effects cause crash, just as in stoneblock "1". Sponge ?

### ISSUE THREAD

**Issue by timitimitimi** [FTBTeam/FTB-Presents-Stoneblock-2#152]
* **Modpack Version**: 

* **Issue**: 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Sunekaer** [comment]
what

**Comment by Sunekaer** [comment]
Template not used, and no log  linked
