### ISSUE TITLE
energy condensers not making or accepting emc

### ISSUE THREAD

**Issue by loadstones** [FTBTeam/FTB-Presents-Stoneblock-2#154]
ver 1.1.1

Energy condensers from Project E do not convert items to emc, tested both mk1 and mk2 versions. They are basically just real expensive chests. They do not accept emc from energy collectors either.

I ran the /reload emc command and tried right and left clicking items in no difference.

**Comment by ttechr** [comment]
Do you have an item in the top left to target the EMC to?

**Comment by loadstones** [comment]
yes in my tests I used a target of an iron ingot, and in the fuel slots
(bottom) a stack of electrum ingots

**Comment by loadstones** [comment]
Have to place the item in the top slot with a right click ONLY.

**Comment by nzminecraftDOTcom** [comment]
Left click, not right click.
Right click removes. Left click places
