### ISSUE TITLE
Game goes into fullscreen when media keys are hit.

### ISSUE THREAD

**Issue by WindFox** [FTBTeam/FTB-Presents-Stoneblock-2#155]
* **Modpack Version**: 1.0.1

* **Issue**: So, for some reason, when I hit a media key (Play/Pause, Next Track, Volume, etc.), the game toggles fullscreen.
I've disabled the fullscreen button  (which was F11) and it still does it. This only happens with this pack, Not in others.

* **Link to Log or Crash File Paste**: Not a crash, Not sure if log will help.

* **Is it Repeatable?**: Every time I hit a media key while it's the active window.

* **Mod/s Affected**: Not sure. Tried a pack with just the borderless fullscreen mod ate no issue there, so it might not be that.

**Comment by iKurama** [comment]
Put fullscreen on a weird combo. 'NONE' will trigger on random unassigned buttons.

**Comment by WindFox** [comment]
I normally put it on none on any pack. Fullscreen does some funky stuff to me (or it did in the past). However, I forgot to change it to none before finding this out.

So it went like this:
* Hit media key and got fullscreen.
* Changed fullscreen keybind from F11 to NONE
* Hit media key and still get full screen.

And I checked the iChun screen, nothing. (That was fun trying to figure out what else was eating ~ but was not in the Controls screen. I hate mods that put keybinds elsewhere.)

**Comment by Sunekaer** [comment]
I just tested on my keyboard my media keys doesnt make my game to full screen
