### ISSUE TITLE
Watch of Flowing Time + Chickens issues

### ISSUE THREAD

**Issue by Moogri** [FTBTeam/FTB-Presents-Stoneblock-2#156]
* **Modpack Version**: 1.0.1

* **Issue**:Server Cpu (nodecraft premium 50 player server)maxes out then crashes with tick error when watch of flowing time is used to make max level chicken farms spawn emeralds for EMC fabrication

* **Link to Log or Crash File Paste**:n/a

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Project E 

* **Known Fix**: Disabling Watch of flowing time in the config

**Comment by Explosivee** [comment]
Just ban the item, that item is not good for any kind of servers.

**Comment by iKurama** [comment]
ProjectE is in the modpack for a purpose. Same goes for _almost_ any of the other mods.

**Comment by Sunekaer** [comment]
Disable the watch in projecte config file

**Comment by AndersWithTheCat** [comment]
For server usage. disable the usage on pedestals. having to use 1-0 watches manuel don't really effect a decent speced server :)

Change 
        I:timePedBonus=12

to 

        I:timePedBonus=0

in the ProjectE.cfg this will help out alot. :)
