### ISSUE TITLE
Mekanism Lack of a solar neutron activator. 

### ISSUE THREAD

**Issue by attu21** [FTBTeam/FTB-Presents-Stoneblock-2#158]
I have noticed a lack of a solar neutron reactor which I can understand since there is no sun however I believe we can use artifical lighting either by the usual minecraft glowstone or more expensive version that is similar to a sun.  It could also be incorporated into the recipe itself and cost MRf per tick due to the use of mekanism turbine and extreme reactors.

* **Modpack Version**: Stoneblock 2 1.12.2 Release

**Comment by lazycooken** [comment]
you can still get solar just need the item called world breaker and break the bedrock with it. but besides that yea your right

**Comment by Sunekaer** [comment]
Added another way to make Tritium

**Comment by xsad60** [comment]
> Added another way to make Tritium

How?  Because i cant find it in NEI

**Comment by Sabster** [comment]
FD means fixed in dev - meaning the new update probably has it.

**Comment by dalran160** [comment]
anyone ever found out what is the new way ?

**Comment by Nutarama** [comment]
Run liquid Lithium through an Electrolytic Separator to produce both Deuterium and Tritium gasses.  Makes fusion reactor setup very easy, may need to be balanced.
