### ISSUE TITLE
Yabba Barrel and Cardboard Box Deletion

### ISSUE THREAD

**Issue by akrodzen** [FTBTeam/FTB-Presents-Stoneblock-2#159]
Modpack Version: 1.12.2

Issue: Cardboard box deletes yabba barrel contents when moving.

Tested multiple times.  Happens every time.

Link to Log or Crash File Paste: None

Is it Repeatable?: Yes

Mod/s Affected: Yabba

Known Fix: Unknown

**Comment by Sunekaer** [comment]
Already fixed update your pack
