### ISSUE TITLE
Gem of Density cant change target.

### ISSUE THREAD

**Issue by Darlith97** [FTBTeam/FTB-Presents-Stoneblock-2#162]
* **v1.0.1**: 

* **When i press G or any other Button i cant change the target of the gem what it transform the items in. I even looked up in the controls and cant find anything.**: 

* **Yes**: 

* **ProjectE**:

**Comment by Sunekaer** [comment]
Works just fine for me, just make sure you dont have any keybind conflicts

**Comment by Darlith97** [comment]
So i rebinded every Key that is binded to G and it still doesnt work
