### ISSUE TITLE
Quests rewards again after updating pack to new version

### ISSUE THREAD

**Issue by TheKrowi** [FTBTeam/FTB-Presents-Stoneblock-2#164]
* **Modpack Version**: 1.1.1

* **Issue**: After updating the pack to a new version and collecting all quests rewards from open quests will also give all already completed quest rewards again.

* **Is it Repeatable?**: Yes

Is there a command I need to run after a pack update?

**Comment by Sunekaer** [comment]
SP, server?

**Comment by TheKrowi** [comment]
SP

**Comment by Sunekaer** [comment]
hmm interesting hasnt happened to me, but nothing we can do about it, up to your self if you want the extra rewards
