### ISSUE TITLE
Stuck at initializing mod phase 2

### ISSUE THREAD

**Issue by rokolix** [FTBTeam/FTB-Presents-Stoneblock-2#165]
Modpack Version :1.0.1

Issue: When I click and modpack start initializing.However,when enter the initializing mod phase 2 (4/7),it stuck at the enderIO part (33/221).I waited 10 min,closed and restart it but it stuck at the same point each time.And if ı click it , program give "not responding" error.   

Link to Log or Crash File Paste: https://paste.feed-the-beast.com/view/6e8ab4ec

Is it Repeatable?: Yes.Each time I try to open the game.

![stoneblock 2 not responding](https://user-images.githubusercontent.com/34215148/51211954-0680c780-1928-11e9-97e2-37c94b97317d.jpg)

**Comment by Boomflex** [comment]
Try updating the pack to the latest version which is v1.1.1, or at least try to reinstall your current version.

Not seen this error at all, so I am guessing it might just be an install issue.

**Comment by rokolix** [comment]
> Try updating the pack to the latest version which is v1.1.1, or at least try to reinstall your current version.
> 
> Not seen this error at all, so I am guessing it might just be an install issue.

New version worked very well.Thanks.
