### ISSUE TITLE
recipe conflict emerald armor

### ISSUE THREAD

**Issue by frenchfryguy78** [FTBTeam/FTB-Presents-Stoneblock-2#167]
* **Modpack Version**: 

* **Issue**: 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Sunekaer** [comment]
It makes TP Armor for me?

**Comment by ukdyl94** [comment]
I can confirm that this does make TP Emerald Armor
