### ISSUE TITLE
[Question] Ender IO Silicon for Electrical Steel (Induction Smelter)

### ISSUE THREAD

**Issue by Kratzwurst** [FTBTeam/FTB-Presents-Stoneblock-2#168]
Hey all,

i found a not so big Problem with this to create Electrical Steel from Ender IO. But in the  Induction Smelter works Steel with the AE2 Silicon to make Electrical Steel and without Ender IO Silicon. 

Is that indeeded?

Greeting

**Comment by Sunekaer** [comment]
ill add recipe for Ender IO Silicon

**Comment by Kratzwurst** [comment]
Thanks a lot Sunkaer for add the Recipe.

Closed.
