### ISSUE TITLE
Request/Question Advanced Big Item filter

### ISSUE THREAD

**Issue by Kibarob** [FTBTeam/FTB-Presents-Stoneblock-2#172]
This is just something i noticed this morning when trying to create the Filter, I tried looking up Shulkers and Stoneblock 2 but could not find any info containing both. Item was wanted for filtering mob farm quicker then Extra Utilities and wanted to try something different. Seems the Shulker Shells are not used in much but makes 6 items useless unless given in creative. 

* **Modpack Version**:  All versions from what i can see

* **Issue**: Trying to create the Advanced big item filter from Ender IO but it requires Shulker Shells, but I am not seeing any info on if Shulkers are spawnable in this pack. Shulker Shells are also not craftable, might need a tweek to recipe?  

* **Mod/s Affected**: Effects vanilla Shulker box from Minecraft, Iron Chests mod has 2 upgrades with the item,  Cyclic has a Rainbow Cannon (no idea what this is), and Ender IO has the Steller Capacitor, and the filter

* **Known Fix**:  Possibly change any wanted recipes in the pack to change the item to something different

**Comment by Sunekaer** [comment]
Quest "Pet Astronaut" tells you how to spawn a shulker..
