### ISSUE TITLE
Both of ye needs to dedicate at least 4 gb of ram to minecraft.

### ISSUE THREAD

**Issue by eldragon3** [FTBTeam/FTB-Presents-Stoneblock-2#173]
Both of ye needs to dedicate at least 4 gb of ram to minecraft.

_Originally posted by @iKurama in https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/issues/150#issuecomment-454008393_

**Comment by Sunekaer** [comment]
log?

**Comment by eldragon3** [comment]
No log because of  shut down. 
I am thinking it maybe  my cpu over working. 
I am going to  run a stress test on it see if it shuts down

**Comment by DrSpghetto** [comment]
Might be having some power supply issues. Maybe when you start up modpacks the cpu's and ram's power usage goes up and as the power supply cant supply it the pc just shuts down...  You could check power consumption on the product page (of whatever you're running), it should have Max power consumption aswell.
