### ISSUE TITLE
Cannot complete chaos shard quest

### ISSUE THREAD

**Issue by Darkmift** [FTBTeam/FTB-Presents-Stoneblock-2#174]
* **Modpack Version**:  1.1.1

* **Issue**: quest in draconic chain "get shard from chaos chicken" will not detect completion

**Comment by Boomflex** [comment]
Works in 1.2.0 as I have just done it.

![image](https://user-images.githubusercontent.com/22868795/51338003-933e9900-1a80-11e9-8dfe-4a39664a2e25.png)

Try updating the pack and then dropping the shard on the floor and picking it back up

**Comment by Darkmift** [comment]
Awesome !
