### ISSUE TITLE
quest reward (dupe?) bug

### ISSUE THREAD

**Issue by AnorakThePrimordial** [FTBTeam/FTB-Presents-Stoneblock-2#175]
* **Modpack Version**: 1.2.0

* **Issue**: I completed the tinker's smeltery and forge quests right after updating the pack, and then clicked the claim all quests button and got i think every reward in the loot table. I got a full double chest's worth of loot including the OP skullfire sword, and a repair talisman, as well as several XU2 upgrades and other misc stuff.

* **Link to Log or Crash File Paste**: I didnt save the log from when the issue happened

* **Is it Repeatable?**: no

**Comment by Sunekaer** [comment]
What version did you update from?

**Comment by AnorakThePrimordial** [comment]
1.1.1

**Comment by Sunekaer** [comment]
hmm okay, nothing i can do about. Up to you if you wanna keep it or not
