### ISSUE TITLE
Script issue when joining a server

### ISSUE THREAD

**Issue by OldManCraft** [FTBTeam/FTB-Presents-Stoneblock-2#176]
* **Modpack Version**: 1.2.0

* **Issue**:  When joining the server A script issue comes up

* **Link to Log or Crash File Paste**: 
![2019-01-16_18 40 34](https://user-images.githubusercontent.com/10180530/51289754-a852f380-19be-11e9-90c9-17fe5db4f8d6.png)

* **Is it Repeatable?**:  yes

* **Mod/s Affected**: n/a

* **Known Fix**:  Mekanism.zs I see you removed the the AE material 5 under the //Enrichment section but not back in, not sure if that matters.

**Comment by Sunekaer** [comment]
hmm, the 5 is there in my file

**Comment by OldManCraft** [comment]
you re-added ?

**Comment by OldManCraft** [comment]
I deleted the pack and re-downloaded, Still the same. I downloaded the server file. They both have the same Mekanism.zs.

**Comment by Sunekaer** [comment]
i just downloaded the server files, and the from h[ttps://www.feed-the-beast.com/projects/ftb-presents-stoneblock-2/files/2661030](FTB) and they work fine for me, i dont get that error

**Comment by Boomflex** [comment]
Just downloaded both server files and client files and can confirm work as intended.

**Comment by OldManCraft** [comment]
Ok, I’ll just keep looking at it.
