### ISSUE TITLE
Game Breaking mod interaction. Item Dupe, Automated

### ISSUE THREAD

**Issue by AndersWithTheCat** [FTBTeam/FTB-Presents-Stoneblock-2#179]
Heres a video one of my server members made for me.
https://www.youtube.com/watch?v=ZQfs4yuwLWE

Known fixs. Temp: Disable tool station FIX: get Tiny pro to remove interaction or inventory slot from cobble gen!

**Comment by AndersWithTheCat** [comment]
Posted to Tiny progressions github too

**Comment by RobertLSnead** [comment]
I'd recommend taking out the tiny progressions recipe for the gens and add the Simple Coblestone Generator!
https://minecraft.curseforge.com/projects/simplecobblestonegenerator

**Comment by AndersWithTheCat** [comment]
> I'd recommend taking out the tiny progressions recipe for the gens and add the Simple Coblestone Generator!
> https://minecraft.curseforge.com/projects/simplecobblestonegenerator

there is no need for Tinker toolstation really it just have to be disabled and alter the tool forge recipe :)

**Comment by RobertLSnead** [comment]
That might be all that is needed :p

**Comment by Explosivee** [comment]
https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/issues/47

**Comment by Sunekaer** [comment]
Wont be removing any mods

**Comment by RobertLSnead** [comment]
Recommend: disabling the tinkers tool table recipe

**Comment by AndersWithTheCat** [comment]
Ain't suggesting removal of mods just disable making of crafting station and alter tool forge recipe. Untill tiny progressions fixes the cobble Gen.. :) its a bug that needs to be fixed by the pack it self since else people would need to upload custom files to play on a server were cobble gens and crafting station is around. I don't see removing cobble gens to be any good for a pack like this. And there is already another dupe with the crafting station. Which have been posted here before. But now there is another reason to get the crafting station disabled until fixed in tiny progressions

**Comment by AndersWithTheCat** [comment]
WOW. that really sad... jesus. yea tinkers might be able to make a blacklist of interactions

**Comment by Sunekaer** [comment]
https://github.com/SlimeKnights/TinkersConstruct/issues/3731

**Comment by AndersWithTheCat** [comment]
Thanks for posting it on tinkers! :)

**Comment by Gunner76th** [comment]
Honestly this is more of an issue one the side of Tiny Progressions than it is Tinker's Construct. The Tcon crafting station is coded to allow it to interact with any block that is next to it that has inventory slots such as chests, crates, machines, furnaces, et cetera. The more appropriate fix would be for Tiny Progressions to simply remove the "visible" inventory slot that is in the cobble generators and make it to where the the user can only receive cobble from the device when either a hopper is placed under it or a storage inventory is placed above it.

**Comment by AndersWithTheCat** [comment]
https://github.com/Kashdeya/Tiny-Progressions/issues/123#event-2102403368 Fixed by Dev at Tiny progressions
