### ISSUE TITLE
Game Freezing/Extremely Laggy?

### ISSUE THREAD

**Issue by SGNepic** [FTBTeam/FTB-Presents-Stoneblock-2#18]
* **Modpack Version**: 1.0.1

* **Issue**: Before, whenever I tried to play in a world (just the world) the game would lag so badly it was unplayable. If I wait for a little then join the world, then the game just freezes on the menu screen while in the world.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/aa87cb08

* **Is it Repeatable?**: Yes, at least the without waiting

* **Mod/s Affected**: I do not know

* **Known Fix**: Maybe eliminate less laggy mods?

**Comment by Sunekaer** [comment]
This is not a lightweight pack
Do you have this problem in single player?
Do you host this server yourself on same pc?

**Comment by twsx** [comment]
To (potentially) add to this:

The game runs - generally - very smooth for me. However, every 10-20 seconds, frame rate drops to near-0 for like 1 second. This does *not* coincide with garbage collection, and doesn't happen to me in other packs.  PC is more than strong enough for the pack.

Let me know if there is anything I can do to provide more/better information.

**Comment by KeatonGregg** [comment]
I've noticed while playing single player I start out locked at 60 fps (with vsync on, 120 with vsync off) and as I play the fps steadily drops little by little after about 30 - 40 mins of playing I'm into the single digits pretty much unable to play. Exiting and resuming doesn't fix it, but restarting the whole game does. Although it will only fix temporarily as it will start back at 60 and steadily drop again. The only way to reliably play for extended periods of time is to reset the whole game every half an hour or so. I don't know if this is related to SGNepic's issues or not, but this seemed like the right place to leave this. If I'm wrong just let me know and I'll make a new thread.
