### ISSUE TITLE
Fluid Cow: Purple Slime quest

### ISSUE THREAD

**Issue by zepanv** [FTBTeam/FTB-Presents-Stoneblock-2#180]
Modpack Version: 1.2.0
Issue: Fluid Cow: Purple Slime quest does not trigger when a cow halter with a "liquid purple slime" cow is inside it.

**Comment by Sunekaer** [comment]
Works fine for me, has the quests before it been detected?

**Comment by zepanv** [comment]
I believe so, I will verify tonight.

**Comment by Boomflex** [comment]
Just tried in 1.2.0 and can confirm that the quest DOES trigger when putting the Liquid Purple Slime Cow in to the Cow Halter.

![image](https://user-images.githubusercontent.com/22868795/51341431-30053480-1a89-11e9-91c0-53ee010ee312.png)

Make sure you have the Obsidian, Lava, Water, Milk and Blue Slime quests done too.

If possible upload a screenshot of your Cow Quest page :)

**Comment by zepanv** [comment]
It was indeed a missing Obsidian cow blocking it, had the cow but it did not trigger for some reason.  Picked it up again and all is well.
