### ISSUE TITLE
Void metal ingots not craftable?

### ISSUE THREAD

**Issue by InflamedSebi** [FTBTeam/FTB-Presents-Stoneblock-2#181]
* **Modpack Version**: 1.1.1

* **Issue**: I cannot find a way to make void metal, which is needed for the crimson ritual. I got the seeds from infusion, but can't turn them into ingots.

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Thaumcraft

**Comment by Sunekaer** [comment]
there is a recipe if you look in JEI

**Comment by InflamedSebi** [comment]
no, there is not.

**Comment by Sunekaer** [comment]
Look at void seed
