### ISSUE TITLE
ProjectE won't accept Applied Energistics 2 items

### ISSUE THREAD

**Issue by 907470** [FTBTeam/FTB-Presents-Stoneblock-2#182]
* **Modpack Version**: 1.1.1

* **Issue**: I can not convert any Applied Energistics 2 items into EMC when placed into both the Condenser MK1 and Condenser MK2. when placed into the item slot it disappears as soon as I leave the chest and while in the chest with items to be converted into the desired item, if its AE2 then nothing will happen.

Edit: some of the items work but not fluix dust, processors, and other not block items.

* **Link to Log or Crash File Paste**: n/a

* **Is it Repeatable?**: Every time.

* **Mod/s Affected**: ProjectE and Applied Energistics 2

* **Known Fix**: n/a

If all I need to do is change the config file, let me know.

**Comment by Sunekaer** [comment]
Do they have an EMC value?

**Comment by Sunekaer** [comment]
I need specific items, so i can test it on my side

**Comment by 907470** [comment]
Yes they do, let me find more items too just in case.

All of the crystals do not work, certus quartz dust does work. They all have emc values.

They can be converted into EMC but not the other way around im finding.

**Comment by 907470** [comment]
On a side note, ender pearls also do not work.

**Comment by Sunekaer** [comment]
hmm weird can you show this not working? because it works just fine for me

**Comment by 907470** [comment]
Strange, it sometimes works sometimes doesn't, the server has suddenly become extremely laggy and i don't know why, maybe its the cause of it not working; but, that's a topic for another post. I had to try a few times and got it to work now, sometimes i have to double or triple click to cause it to work properly, going to re-install it on MultiMC to see if that clears up the issue. I'm assuming its client side on my end if its working for you.
