### ISSUE TITLE
Thaumcraft Void metal recipe not showing in jei.

### ISSUE THREAD

**Issue by InflamedSebi** [FTBTeam/FTB-Presents-Stoneblock-2#183]
* **Modpack Version**: 1.1.1

* **Issue**: relative to https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/issues/181 I cannot see the recipe for void metal ingots. I looked them up in a cheated savegame (/thaumcraft research <player> all) and it is 10 metalum + 5 vitium plus the seed in a crucible.  This recipe however is part of the edrich tab on the thaumonomicon, which is not unlocked in my legit savegame yet, so I m not able to use it.
Yes, i scanned the seed, but this did not unlock the thaumcraft entry. I completed every reseach except the 2 that need taint, since rifts do not appear.
The real issue might be the eldrich tab not unlocking in my thaumonomicon. Scanned all I could find, but no clue what should unlock it.

* **Mod/s Affected**: Thaumcraft

**Comment by Sunekaer** [comment]
Look at void seed

**Comment by InflamedSebi** [comment]
> Look at void seed

I HAVE the seed, but i cannot turn it into the INGOT. and jei displays no uses for the seed (aside from enchantments and aspects). pls elaborate more.

**Comment by Sunekaer** [comment]
there was supposed to be a furnace recipe for void seed to ingot

**Comment by Sunekaer** [comment]
![image](https://user-images.githubusercontent.com/18720460/51351985-9a7b9c00-1aac-11e9-8c94-10ce79726fa9.png)
sorry it was crucible recipe not furnace

**Comment by Sunekaer** [comment]
Could you try restarting your game, or updating to 1.2.0 to see if that fixes it for you

**Comment by InflamedSebi** [comment]
nope. Problem is, this recipe unlocks in the thaumonomicon (eldrich tab) but this tab never unlocked for me ... I have no clue how to unlock this. I theory it should unlock after scanning the seed or something, but that did not happen. and due to wuss mode i cannot build up warp or scan taint/rifts, which might unlocked this...

I cheated the void metal in for now and did the crimson ritual with it. Next thing: the quest did not unlock thaumcraft stuff. 'Player "@Team" cannot be found'

**Comment by Sunekaer** [comment]
Sounds like your on an old version of the guest book as it should be doing this command /thaumcraft research @p all
