### ISSUE TITLE
Mekanism provides a OP sawdust to paper recipe.

### ISSUE THREAD

**Issue by Flanks255** [FTBTeam/FTB-Presents-Stoneblock-2#184]
Mekanism provides a recipe thats 3 sawdust to 6 paper.
making Thermals 4 sawdust and water to 2 paper obsolete.

**Comment by Boomflex** [comment]
In that train of through surely Mekanism being able to x5 ores means that
ALL other options i.e Ender IO/Thermal/Actually Additions are obsolete?

Also isn't the recipe for Mekanism machines harder than Thermal in terms of
materials needed?
