### ISSUE TITLE
Client Freeze with EU2 Generator UI

### ISSUE THREAD

**Issue by DranKof** [FTBTeam/FTB-Presents-Stoneblock-2#186]
* **Modpack Version**: 1.0.1; 1.1.1

* **Issue**: Client freezes/locks when shift+adding items to Survival Generator / Furnace Generator / probably other similar EU2 blocks. To reproduce, sum of item in generator slot and shift clicked stack must be greater than one stack (usu. 64). If it is less than that, entire shift clicked stack is actually eaten (see: https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/issues/14 ).

* **Link to Log or Crash File Paste**: n/a -- no client crash related information as Java just freezes; server is unaffected, reports "NetworkDispatcher exception" and "[player] lost connection: Internal Exception: java.io.IOException: An existing connection was forcibly closed by the remote host"

* **Is it Repeatable?**: Yes, 100% Take two stacks of coal, shift+add one into generator, it should reduce to 63 as the first one burns, then repeat with second stack, client frozen.

* **Mod/s Affected**: Probably extrautils2-1.12-1.9.8

* **Known Fix**: Remove whatever item is in generator before adding something.

**Comment by AndersWithTheCat** [comment]
Its a bug with Extra utilitys and very common atm. it needs to be fixed by the mod dev. just remember not you shift click items in any extra utilitys :)

**Comment by Sunekaer** [comment]
https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/issues/31
