### ISSUE TITLE
Draconic Armor too OP

### ISSUE THREAD

**Issue by kreezxil** [FTBTeam/FTB-Presents-Stoneblock-2#188]
I have player in Stoneblock 2 1.2.0 who is bragging about not being able to be killed with even the cosmos sword while wearing infinity armor powered with infinite energy.

![2019-01-18_08 11 13](https://user-images.githubusercontent.com/3880072/51391870-e05e5180-1af8-11e9-83c4-6871e6954cf1.png)

**Comment by Aminboss2** [comment]
I did have it fully upgraded and the stuff you cant not die to anything the only way the die is if I run out of power or they take off the armor Here is why its op if you have so much power when your low hp the Armor Uses up Power just to make it so you don't die That mean if you have power your cant die and if you make it so you have a big reactor you cant die like me

**Comment by iKurama** [comment]
How is this an issue? It's been like that for ages now.

**Comment by Explosivee** [comment]
Lol, wear infinity armor and you can't kill him not even with ./kill command

**Comment by Aminboss2** [comment]
The Problem with that is That you can die with the infinity armor with the Sword of the Cosmos But with the Draconic you cant

**Comment by Sunekaer** [comment]
Not anything i can do about, plus there armor there more op
