### ISSUE TITLE
Quest Duplication.

### ISSUE THREAD

**Issue by Manrock1** [FTBTeam/FTB-Presents-Stoneblock-2#19]
Stoneblock 2: 1.0.1
Quest Abusing: On a multiplayer server as far as I know you are able to repeatedly claim quest rewards by simply leaving and making a new team and re logging into the server reset all quests making you be able to get infinite rewards from it. 
Fix?: Possibly make it go back to player based instead of team based because then they couoldn't keep resetting the quests.

Sorry if this has already been reported or if this is even a glitch.

**Comment by LatvianModder** [comment]
Created an issue https://github.com/FTBTeam/FTB-Quests/issues/134
