### ISSUE TITLE
Game Crash on trying to add recipe to pattern terminal

### ISSUE THREAD

**Issue by MelleJ** [FTBTeam/FTB-Presents-Stoneblock-2#190]
* **Modpack Version**:
1.2.0
* **Issue**: 
When trying to add the JEI recipe of Nether Quartz Dust in a SAG Mill in the pattern terminal, the game crashes.
* **Link to Log or Crash File Paste**: <
https://paste.feed-the-beast.com/view/5f88b409
* **Is it Repeatable?**: 
Yes, happened 100% on tries.
* **Mod/s Affected**: 
Ender IO, Applied Energistics 2, Just Enough Items; all regular modpack version as in 1.2.0

**Comment by merscever** [comment]
Experiencing same problem when trying to remove dust from crusher or try to smelt anything in a extra utilities furnace

**Comment by MelleJ** [comment]
After a little bit more testing it seems to be with any recipe that involves the Grinding Balls and adding it in the pattern terminal.

**Comment by Gunner76th** [comment]
Just an update, this issue is also releated to the following reported bugs: 

https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3909
https://github.com/p455w0rd/JustEnoughEnergistics/issues/4

The mod author of Just Enough Energistics is aware of the issue, and is at the time of this update working to fix the problem.

**Comment by p455w0rd** [comment]
Update: Fixed-If you wish to update prior to @Sunekaer updating SB2, you can find the fixed version ![here](https://minecraft.curseforge.com/projects/just-enough-energistics-jee/files/2663300)

**Comment by Gunner76th** [comment]
@p455w0rd That is a dead link it would seem. I tried from both my PC and my phone and both give this error
![image](https://user-images.githubusercontent.com/5566872/51507189-c012e900-1dbd-11e9-8104-fae6ad9bef5b.png)

**Comment by Flatts3000** [comment]
It seems that this issue has reappeared in version 1.15
[https://paste.dimdev.org/uyatoruguv.mccrash](https://paste.dimdev.org/uyatoruguv.mccrash)
