### ISSUE TITLE
Crash with FTB Quests, Quest Chest

### ISSUE THREAD

**Issue by elijah-thomas774** [FTBTeam/FTB-Presents-Stoneblock-2#191]
* **Modpack Version**:Beta 1.2.0

Issue: Whenever i am looking at the ftb quest chest, it crashes my game

Log: https://paste.feed-the-beast.com/view/8deebb0a

Repeat?: Happened multiple times, so i guess. All i did was look in the chest for a few seconds after claiming rewards

Fix: Sorry, idk

**Comment by LatvianModder** [comment]
Probably The One Probe trying to read it's inventory which is very custom. I will see what I can do about it
