### ISSUE TITLE
AA Easter egg to get random items is enabled 

### ISSUE THREAD

**Issue by avidgamer5918** [FTBTeam/FTB-Presents-Stoneblock-2#192]
* **Modpack Version**: 1.1.1

* **Issue**: So just wanted to point out that the actually additions easter egg to get random items is still enabled 

* **Mod/s Affected**: actually additions 

* **Known Fix**: set this to 0  
 # 11?I:"What is 11"=11

**Comment by iKurama** [comment]
Default is disabled, so it must be intended.

**Comment by Sunekaer** [comment]
What does this easter egg do?
Not something i have enabled

**Comment by iKurama** [comment]
The easter egg is the Lens of Disruption. A gamebreaking easteregg, to say the least. https://www.youtube.com/watch?v=4uF9ieaoLXY

**Comment by iKurama** [comment]
It is gamebreaking. It can be cheaty, but he sure as hell can corrupt your world and player file. Sacrificed my world in SB1 for testing it when SB2 came out.
