### ISSUE TITLE
Placing Blocks in Other player's Protected Chunks

### ISSUE THREAD

**Issue by monkeybug34** [FTBTeam/FTB-Presents-Stoneblock-2#193]
* Modpack Version: FTB Presents Stoneblock 2 version 1.2.0

* Issue: using the "place block" and probably the "place block sequence" trick from PSI will bypass other player's protected chunks from FTB utils.

* Link to Log or Crash File Paste: There is no crash.

* Is it Repeatable?: 100% Reliably repeatable.

* Mod/s Affected: PSI r1.1-69 and FTB Utilities 5.3.0.74

* Known Fix: No known fix. perhaps contact mod authors?

**Comment by Sunekaer** [comment]
Nothing i can do about this, youll have to report it to PSI, but i dont think it will be changed
