### ISSUE TITLE
Enable Environmental Tech Solar

### ISSUE THREAD

**Issue by nzminecraftDOTcom** [FTBTeam/FTB-Presents-Stoneblock-2#194]
Not a bug.
Is it possible to have for the server side files, the solar setups enabled for Environmental tech? They were a great bulk-ish lag-free way of getting power, even if they had their outputs nerfed, it would give people another mod to attempt in order to get a good power source. And yes I know we're in a cave, that's what the world breaker from Avaritia is for.

**Comment by Sunekaer** [comment]
I wont be changing server files, if you want this on your server, you have to do it yourself
