### ISSUE TITLE
Ender chest crash?

### ISSUE THREAD

**Issue by Hunterboomer** [FTBTeam/FTB-Presents-Stoneblock-2#195]
* **Modpack Version**: 1.2.0

* **Issue**: Crash upon joining my single player world

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/cc94535e

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: It says it is caused by the ender chest

* **Known Fix**:

**Comment by Sunekaer** [comment]
https://github.com/TheCBProject/EnderStorage/issues/102

**Comment by Sunekaer** [comment]
delete this folder C:\Users\hunte\Documents\Curse\Minecraft\Instances\FTB Presents Stoneblock 2\saves\New World\EnderStorage but i dont know if youll lose the content of the enderchest

**Comment by Hunterboomer** [comment]
Upon doing this I was able to join my world but the starter area was reverted back to the original and all the chest in it was destroyed dropping all the items causing lag
