### ISSUE TITLE
Unable to access anything but still in team.

### ISSUE THREAD

**Issue by Keo1711** [FTBTeam/FTB-Presents-Stoneblock-2#196]
* **Modpack Version**:  1.1.1

* **Issue**: No one can access anything in the team without being OP. I installed this pack on my server, created a team, invited 2 others to my team. I then claimed the base and logged off. When we logged back on, none of us could open any chests or access anything unless we had OP privledges. All 3 members are still in the team and the base is still claimed. We are having to play with all users OP.

* **Link to Log or Crash File Paste**: No Crash file available 

* **Is it Repeatable?**: No

* **Mod/s Affected**: I believe it is FTB utilities

* **Known Fix**: This issue is to do with server spawn protection. I have since set Spawn Protection to 0 instead of 16 and it has fixed my issue.

**Comment by Sunekaer** [comment]
Thats default minecraft. and that file generates on first launch of server files, nothing can do about, and this is something i wouldnt change as its up to the server owners
