### ISSUE TITLE
Backpacks without dupes [Suggestion]

### ISSUE THREAD

**Issue by NotASocol** [FTBTeam/FTB-Presents-Stoneblock-2#197]
Because dupes it turns out that in the modpack there is no normal backpacks.

I suggest to put install mod: https://minecraft.curseforge.com/projects/improvedbackpacks?projectID=270457

Dupes in this mod has not yet been found... we tried to work on it xD

**Comment by iKurama** [comment]
![image](https://user-images.githubusercontent.com/7503922/51429310-cb271700-1c0d-11e9-97de-568ccdf38409.png)
Bags. Lots of bags with loads of storage.

**Comment by Sunekaer** [comment]
There is lots of bags already, Thermal, ProjectE and others
