### ISSUE TITLE
Wheat --> Flour Recipe in Quartz Grindstone

### ISSUE THREAD

**Issue by Trailmix23** [FTBTeam/FTB-Presents-Stoneblock-2#20]
* **Modpack Version**: 1.0.1

* **Issue**: When trying to craft flour in the quartz grindstone using the recipe shown in JEI, you cannot place the wheat into the grindstone. I have tried placing the wheat in manually, shift clicking, and using a hopper. I assume either the recipe is disabled and still showing in JEI or something else with Vanilla Minecraft and AE2 is broken.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Vanilla Minecraft and AE2

* **Known Fix**: N/A

**Comment by Sunekaer** [comment]
Thanks ill take a look at it

**Comment by Sunekaer** [comment]
1.1.0

**Comment by Banderi** [comment]
So.... what is the solution with this? Was this fixed in 1.1.0?
I'm playing the latest FTB Unl. Reloaded pack and this issue is still present
