### ISSUE TITLE
Uranium compacting

### ISSUE THREAD

**Issue by merk0** [FTBTeam/FTB-Presents-Stoneblock-2#200]
1.2.0
Uranium does not compact properly when placed in compacting drawers and uranium blocks will not decompress into ingots even when the crafting recipe is shown in the crafting table.

**Comment by Sunekaer** [comment]
Works fine for me?
![image](https://user-images.githubusercontent.com/18720460/51488792-ccd81280-1da6-11e9-8454-3a6cc3e2385d.png)

Could you show me our issue?

**Comment by merk0** [comment]
![2019-01-21_12 55 29](https://user-images.githubusercontent.com/45065503/51491553-ae5d2180-1d7c-11e9-8c0a-080abcbab150.png)
Above is what the drawer looks like when all items are placed inside. using the bottom right box
![2019-01-21_12 55 35](https://user-images.githubusercontent.com/45065503/51501115-9f876680-1d9e-11e9-979e-8787f3bec7ec.png)
If you shift click on the drawer this is what pops up.
![2019-01-21_12 55 39](https://user-images.githubusercontent.com/45065503/51501134-b0d07300-1d9e-11e9-8ebb-544270ebdec7.png)
It then becomes glitched and looks like this.
![2019-01-21_12 56 00](https://user-images.githubusercontent.com/45065503/51501153-c04fbc00-1d9e-11e9-8517-293a77e206a8.png)
If you update the block it goes back to the original version.
All of this is happening on Chosen Architechts server. I asked around and was told that they did not alter any recipes. In single player it works fine, this must be a server thing. 
![2019-01-21_12 56 59](https://user-images.githubusercontent.com/45065503/51501241-10c71980-1d9f-11e9-9f20-bdecbdc603a1.png)
Also for some reason the uranium blocks will not decompress into ingots. This could be part of the problem.
![2019-01-21_13 07 36](https://user-images.githubusercontent.com/45065503/51501268-29373400-1d9f-11e9-8e6f-b2e4c710b621.png)
This is if u put only the uranium block in the drawer.

**Comment by merk0** [comment]
@Sunekaer ![2019-01-21_12 55 29](https://user-images.githubusercontent.com/45065503/51491553-ae5d2180-1d7c-11e9-8c0a-080abcbab150.png)
Above is what the drawer looks like when all items are placed inside. using the bottom right box
![2019-01-21_12 55 35](https://user-images.githubusercontent.com/45065503/51501115-9f876680-1d9e-11e9-979e-8787f3bec7ec.png)
If you shift click on the drawer this is what pops up.
![2019-01-21_12 55 39](https://user-images.githubusercontent.com/45065503/51501134-b0d07300-1d9e-11e9-8ebb-544270ebdec7.png)
It then becomes glitched and looks like this.
![2019-01-21_12 56 00](https://user-images.githubusercontent.com/45065503/51501153-c04fbc00-1d9e-11e9-8517-293a77e206a8.png)
If you update the block it goes back to the original version.
All of this is happening on Chosen Architechts server. I asked around and was told that they did not alter any recipes. In single player it works fine, this must be a server thing. 
![2019-01-21_12 56 59](https://user-images.githubusercontent.com/45065503/51501241-10c71980-1d9f-11e9-9f20-bdecbdc603a1.png)
Also for some reason the uranium blocks will not decompress into ingots. This could be part of the problem.
![2019-01-21_13 07 36](https://user-images.githubusercontent.com/45065503/51501268-29373400-1d9f-11e9-8e6f-b2e4c710b621.png)
This is if u put only the uranium block in the drawer

**Comment by Sunekaer** [comment]
Hmm thats weird because if i put only the block in the draw it works fine

**Comment by Sunekaer** [comment]
ill do some more testing and see if can get it to reproduce the problem and find some kind of solution

**Comment by Sunekaer** [comment]
STill not able you recreate it and havent found anyway to resolved it even if i could
