### ISSUE TITLE
Molten Metals on YABBA Barrels have no texture

### ISSUE THREAD

**Issue by DJBaphomet** [FTBTeam/FTB-Presents-Stoneblock-2#202]
* **Modpack Version**: 1.2.0

* **Issue**: Molten Metlas have no teture, so they turn grey like Molten Electrical Steel. This is kind of annoying as I paint Yabba Barrels with the molten version of the metal essence they're holding

* **Is it Repeatable?**: There's nothing to repeat as it's a texture bug.

* **Mod/s Affected**: Any mod that has a Molten Version of a Metal
![image](https://user-images.githubusercontent.com/44253613/51437802-516c4900-1c60-11e9-88bd-f15202935cf6.png)

**Comment by Sunekaer** [comment]
https://github.com/LatvianModder/YABBA/issues/110
