### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Cofcream** [FTBTeam/FTB-Presents-Stoneblock-2#203]
* **Modpack Version**: 1.20.0.1.

* **Issue**: Can't open any inventory

* **Link to Log or Crash File Paste**: The game crashed whilst rendering entity in world
The game crashed whilst rendering entity in world
Error: java.lang.AbstractMethodError: Method extracells/item/ItemWirelessTerminalUniversal$.getRender()Lp455w0rd/ae2wtlib/api/client/IBaubleRender; is abstract

* **Is it Repeatable?**: I think I put WirelessTerminalUniversal in to ME system

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Sunekaer** [comment]
#190
