### ISSUE TITLE
Failed to download file.

### ISSUE THREAD

**Issue by CoryJS** [FTBTeam/FTB-Presents-Stoneblock-2#204]
* **Modpack Version**: 1.1.1

* **Issue**: After installing all the mods and trying to get to the menu, my game crashed and gave the error "Failed to download file. forge-14.23.5.2796.jar"
* **Link to Log or Crash File Paste**: 
![image](https://user-images.githubusercontent.com/40577274/51439938-dedb8780-1cb8-11e9-8406-1e2a4f5cfaa8.png)

* **Is it Repeatable?**: Yes, but now it does it instantly.

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Sunekaer** [comment]
Nothing I can do about this, you need to contact twitch
