### ISSUE TITLE
Forge Lexicon

### ISSUE THREAD

**Issue by blarghhh** [FTBTeam/FTB-Presents-Stoneblock-2#206]
* **Modpack Version**: 1.1.1

* **Issue**: Forge Lexicon is not working. so why is it a reward option?

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: N/A

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Sunekaer** [comment]
What about it doesnt work? the things i have used it for worked fine

**Comment by blarghhh** [comment]
converting ingots is fine. i want to convert normal sand to red sand and i cant

**Comment by Sunekaer** [comment]
Please report it to Thermal Foundation
