### ISSUE TITLE
World wouldn't save my work and keep reseting to point before updating my modpack

### ISSUE THREAD

**Issue by Sizii** [FTBTeam/FTB-Presents-Stoneblock-2#207]
i have a problem with my world like after i quit the game before updating it then i updated the modpack to the last version. So after that i join the world and  i played it for several hours then i just quit then rejoin the next day and all my work those several hours is gone and kept getting back to the point when i quit before updating the modpack. I don't know what's the issue

**Comment by Sunekaer** [comment]
log?

**Comment by Sizii** [comment]
1.2.0

**Comment by Sunekaer** [comment]
I asked for a log, not version

**Comment by Sunekaer** [comment]
please use http://paste.feed-the-beast.com/ to paste the text of your log file

**Comment by Sunekaer** [comment]
Is it everything there resets or only some things?
What about in another world?

**Comment by Sizii** [comment]
As i said before it keep reseting to the point before that i updated the modpack and it mostly everthing i there after and yes i have tried this in another world and after i quit it and rejoin it reset again

**Comment by Sizii** [comment]
https://paste.feed-the-beast.com/view/a2696056

**Comment by Sunekaer** [comment]
You playing on server? need the log from server and your cords

**Comment by Sizii** [comment]
Nope im was playing on single player
i guess  maybe because i changed the version to be able to join a server to play on it

**Comment by Sizii** [comment]
Ig im going to try to update it again and try the world 1 more time and i will post the log here again

**Comment by Sizii** [comment]
https://paste.feed-the-beast.com/view/1b3c09f8

**Comment by nzminecraftDOTcom** [comment]
Is your computer hard drive (or the drive where the game is stored) full. It sounds like the game can't write any new information to the save (from RAM to Long term storage [hdd/ssd])

**Comment by Sizii** [comment]
The local hard drive isn't full it has like 84.4 GB free space plus i have another hard drive and it has 1.77 TB free space. So should i put the files in the other hard drive to be able to save the files and stop reseting ?

**Comment by nzminecraftDOTcom** [comment]
If that's the case it doesn't sound like that is the problem. Do a backup of everything (everything in the curse folder in your My Documents folder and anywhere else you have saved games that you know of) and delete the save then re-install the twitch launcher and modpack, see if it works then. If it does, copy your saved world into the saves folder and see if it saves now.

**Comment by Sunekaer** [comment]
Issue resolved thanks nzm, information forwarded to the dev of the mod
