### ISSUE TITLE
Fluid Cow Detection doesnt work!

### ISSUE THREAD

**Issue by LuziferSenpai** [FTBTeam/FTB-Presents-Stoneblock-2#210]
Hey,

I have picked up a Molten Platinum and a Molten Gold Cow and both Quests are not finishable!
EDIT: Anti Barrel doesnt work ether!
Version: 1.2.0
![javaw_2019-01-22_00-06-28](https://user-images.githubusercontent.com/38015859/51503122-9f588c80-1dd9-11e9-9874-85abc9f25bc0.jpg)
![javaw_2019-01-22_00-06-33](https://user-images.githubusercontent.com/38015859/51503123-9f588c80-1dd9-11e9-8080-65cf44dfb6ae.jpg)
![javaw_2019-01-22_00-06-39](https://user-images.githubusercontent.com/38015859/51503125-9f588c80-1dd9-11e9-875d-956e515097c7.jpg)

**Comment by iKurama** [comment]
You need to pick up iron cow first.

**Comment by Sunekaer** [comment]
Look like your missing completing iron cow quest...

**Comment by LuziferSenpai** [comment]
But the Anti Barrel doesnt work, I have the Quest before the Anti Barrel done!
