### ISSUE TITLE
Server crash, unable to restart

### ISSUE THREAD

**Issue by foestauf** [FTBTeam/FTB-Presents-Stoneblock-2#211]
Hello. Using version 1.2 on windows server. Java is version 1.8
Crashed while using an air charm and unable to restart server. Tried copying world to fresh server install with the same crash error. Restored old world file and it loads. Here is my crash log.
https://paste.feed-the-beast.com/view/63d8696f

Here is the log from when trying to start the server again.
https://paste.feed-the-beast.com/view/44c38435

**Comment by nzminecraftDOTcom** [comment]
By the looks of it at block location in the overworld -14,91,-40 entity thaumcraft:pech is causing the crash, you may need to manually remove it using an NBT editor.

**Comment by Sunekaer** [comment]
Make sure to take a backup of your world before doing this! edit the forge.cfg in the config folder. There are a couple of lines about removing erroring entities. Change both of them to true and load the world and see if the removes the block. REMEMBER to set these back to false again!.... If that doesn't work, then use mcedit or NBT Editor on the world to remove the block located at (-14,91,-40)
