### ISSUE TITLE
Morph Mod Unending Death Animation

### ISSUE THREAD

**Issue by spokaneatitsbest** [FTBTeam/FTB-Presents-Stoneblock-2#212]
* **Modpack Version**: 1.1.1

* **Issue**: I morphed into a chicken, and then walked into a wall. The game displayed the "You Died" screen, but when I pressed respawn the "you died" text disappeared. I was still in the same place, and still a chicken. I had all my items. When I morphed back into a player, the game started playing the damage animation, so my player was glowing red at a slight angle. I was not losing any health. 

* **Is it Repeatable?**: yes

* **Mod/s Affected**:

* **Known Fix**: Reloading the world fixes the bug.

**Comment by Sunekaer** [comment]
Please recreate and send the latest.log so i can include that to the dev
