### ISSUE TITLE
Quartz glass pattern creation via jei causes freeze/shotdown.

### ISSUE THREAD

**Issue by chrisisonwildcode** [FTBTeam/FTB-Presents-Stoneblock-2#214]
Stoneblock 2 v1.2.0

Attempting to create AE2 quartz glass pattern in AE2 pattern terminal causes the game to lock up or shut down.

https://paste.feed-the-beast.com/view/5efe9548

Yes, this is repeatable by selecting the quartz glass within JEI then select the +, while in the AE2 pattern terminal.(minecraft glass & certus quartz dust). 

Applied Energistics 2 rv6 stable 6

Workaround issue by manually entering recipie into AE2 pattern terminal.

**Comment by Sunekaer** [comment]
#190
