### ISSUE TITLE
Using the /dank/null I can only hold a certain amount and after that the items disappear.

### ISSUE THREAD

**Issue by ChromeFlux** [FTBTeam/FTB-Presents-Stoneblock-2#215]
***Modpack Version**: 1.2.0

* **Issue**: Using the /dank/null Emerald tier item (i'm not sure about other tiers) I can hold only up to about 128 it seems of any item. The mod itself says it can hold 2.14 billion of any one item in its inventory before it starts to void things. I'm also not sure because If i place 64 blocks in while shift right clicking and then drop 2 stacks on the ground, it takes them and voids them and then when i look in the emerald /dank/null It'll have 64 in it. But If i just put in 1 stack after the first 64 and it sucks it up you can look and it'll show 0. I've messed around with it and Its really weird and I have a feeling it relates to the "disabled due to a bug" backpacks / bags of holding interactions but /dank/null is obviously still in the game and therefore should work, right? Is there a config change to /dank/null between any previous versions and 1.2.0 that causes this? I'm just trying to find something to hold a LOT of the same building block *forgot to mention i'm using xtones blocks, for all i know it could be a problem with those, i'll do some more testing in a minute) is there a replacement I can use in the meantime anyone can suggest to me?
Edit: It seems like Every time I increase the amount from 127 to 128 or above and look in the bag the items are deleted. I can see due to the /dank/null's gui that it does show i'm correctly holding anywhere above 128 but the moment i look in the bag they disappear. 
It also seems that it works with other blocks than just xtones, I've currently tried Xtones blocks, Cobblestone, and some random chisel blocks I didn't care about.
* **Link to Log or Crash File Paste**:

* **Is it Repeatable?**: yes, use any /dank/null to my knowledge but i'm specifically using the emerald tier, throw any amount of the item on the ground after you've put some in its inventory and it'll show it either deletes it or can hold only up to a certain amount.

* **Mod/s Affected**: /dank/null

* **Known Fix**: Possibly related to the change with the backpacks since it behaves in the same manner?

**Comment by DrSpghetto** [comment]
From what i've experienced so far, The item in question disappears when you shift + RClick to open the dank/null menu. Happens to me with all types (Redstone dank/null all the way to emerald dank/null) even if i do not reach the limit of blocks that the specific slot can reach.

**Comment by Farinhir** [comment]
This is actually a bug with the recent dank/null release and is repeatable on Enigmatica 2 also. Enigmatica 2 rolled mod version back as their fix

**Comment by Sunekaer** [comment]
Closing this issue, as there´s nothing we can do about this other then wait and see if the mod dev fixes it
