### ISSUE TITLE
Server crashes while connecting a dense energy cell to an ME Controller - Repeatable

### ISSUE THREAD

**Issue by DrSpghetto** [FTBTeam/FTB-Presents-Stoneblock-2#216]
Modpack vers: 1.2.0 (1.12.2)

Issue: Server crashes after placing dense energy cell onto ME Controller (cant boot up)

Crash file paste -  https://paste.feed-the-beast.com/view/7512ed0d

Repeat (Tested in singleplayer, Crashed the game - unable to open the world without crashing) - Make an ME Controller (Mine was 5 blocks long only) in the middle three controllers connect a flux point (Has to provide energy otherwise the problem wont occur), Then remove the middle flux point and replace it with a dense energy cell.

Mods affected - Applied energistics 2 (File name - appliedebergistics2-rv6-stable-6.jar) 

No known fix as of now, Would really appreciate a fix considering how i cant turn on the server at this point and i do not feel like reverting to the backup as ive made alot of progress in the 30 minutes coming up to that point.

**Comment by nzminecraftDOTcom** [comment]
You can manually edit the chunk data using an NBT editor and remove either the flux point or the energy cell.
This bug is to do with AE2 and Flux networks, nothing to do with the pack as it has occurred in multiple packs in the past. To repeat it in its most basic form, connect a flux point to an AE2 energy cell and all hell breaks loose.

**Comment by DrSpghetto** [comment]
> You can manually edit the chunk data using an NBT editor and remove either the flux point or the energy cell.
> This bug is to do with AE2 and Flux networks, nothing to do with the pack as it has occurred in multiple packs in the past. To repeat it in its most basic form, connect a flux point to an AE2 energy cell and all hell breaks loose.

Huh i see, Could u provide me with some info about the NBT Editor (perhaps in private) cause from what  i remember it doesn't have mod support... I may very well be wrong tho

**Comment by DrSpghetto** [comment]
After googling around, I somewhat understand how to use NBTExplorer but ive got no clue what is the exact location (Or coordinates) of the block is, Could anyone help me out with that please?

**Comment by nzminecraftDOTcom** [comment]
I'm guessing the second you placed the two together it crashed (It's how that usually happens)
Go to the player data file in the world you are playing on. Open your file up and find "Position"
Use those X Y Z coords to guess the rough area where the point and cell are placed. Use https://dinnerbone.com/minecraft/tools/coordinates/ that tool, to input the X Y Z coords and to obtain the .mca region file found under the "Regions" folder in your world save. Open that region file and you'll have to hunt around for Fluxnetworks:flux_plug or what ever the in game name is for that item. I would give you more information but I have to leave for work.

**Comment by DrSpghetto** [comment]
> I'm guessing the second you placed the two together it crashed (It's how that usually happens)
> Go to the player data file in the world you are playing on. Open your file up in NBTEditor and find "Position"
> Use those X Y Z coords to guess the rough area where the point and cell are placed. Use https://dinnerbone.com/minecraft/tools/coordinates/ that tool, to input the X Y Z coords and to obtain the .mca region file found under the "Regions" folder in your world save. Open that region file with NBTEditor and you'll have to hunt around for Fluxnetworks:flux_plug or what ever the in game name is for that item. I would give you more information but I have to leave for work.

Thanks alot,  Really appreciated ^^

**Comment by Sunekaer** [comment]
Looks like a dup of #187
