### ISSUE TITLE
Storage Drawers will not face North

### ISSUE THREAD

**Issue by TreeMarie84** [FTBTeam/FTB-Presents-Stoneblock-2#217]
* **Modpack Version**: 1.1.1

* **Issue**: Storage Drawers will not face north. Will face all other cardinal directions.

* **Link to Log or Crash File Paste**: No crash

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Storage Drawers

* **Known Fix**: Don't know a fix
![2019-01-22_10 28 48](https://user-images.githubusercontent.com/10687874/51545712-8af3ae80-1e30-11e9-9d17-310b85a974d7.png)
![2019-01-22_10 28 54](https://user-images.githubusercontent.com/10687874/51545713-8b8c4500-1e30-11e9-98f9-7f9122861e5a.png)

**Comment by Sunekaer** [comment]
https://github.com/jaquadro/StorageDrawers/issues/686
Same issue

**Comment by Lupoid** [comment]
Same issue. Wrench doesn't work. Interestingly only some of mine have this issue (a bank of 56 2x2s and four are still correct).

**Comment by Sunekaer** [comment]
Closing this issue, as there´s nothing we can do about this other then wait and see if the mod dev fixes it
