### ISSUE TITLE
Cant Get Blue Slime

### ISSUE THREAD

**Issue by Pr0ti0us** [FTBTeam/FTB-Presents-Stoneblock-2#218]
* **1.1.1**: 

* ** Cant seem to get blue slime. Blue slime saplings grow green slime. I tried using the Bonzai tree mod. I used a blue slime sapling with every form of slimy dirt/grass and the progress bar doesn't go past 0%. **: 

* **Link to Log or Crash File Paste**: 

* ** yes I made 2 new save files and the issue was there in each one. **: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by DrSpghetto** [comment]
Make sure there is nothing above the bonzai thingy (where you put your tree in) and you should also look into slime chickens as they will provide you with all the slime you need (Tho not blue slime, but theyve got the same crafting usages for the most part)

**Comment by Sunekaer** [comment]
![image](https://user-images.githubusercontent.com/18720460/51557390-13983c00-1e7d-11e9-8d55-6aff76f48fa4.png)
works fine
