### ISSUE TITLE
Better Building Wands

### ISSUE THREAD

**Issue by Pr0ti0us** [FTBTeam/FTB-Presents-Stoneblock-2#219]
* **1.1.1**: 

* ** Not sure if this is a issue. And I have confirmed that optifine isnt causeing it but the wands apear in multiple tabs in creative mode. An example would be that they appear in one of the Ender IO mod Tabs. To be more accurate the Ender IO storage tab.  **: 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Sunekaer** [comment]
https://github.com/portablejim/BetterBuildersWands/issues/88

**Comment by Sunekaer** [comment]
Closing this issue, as there´s nothing we can do about this other then wait and see if the mod dev fixes it
