### ISSUE TITLE
Spawn in over world upon server log-on 1.0.1

### ISSUE THREAD

**Issue by 1999jrj** [FTBTeam/FTB-Presents-Stoneblock-2#22]
* **Modpack Version**: 1.0.1

* **Issue**: Without changing any of the server files downloaded from curseforge website, the server seems to be working incorrectly and spawning in a default world type. Also, the starting items differ, as in no pet rock is given nor its food, several of the starting guidebooks are given, and no quest book is given on start.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: After several clean re-installs of the server files, it still happens every time.

* **Mod/s Affected**: ?

* **Known Fix**: Changing level-type:DEFAULT to level-type:voidworld seemed to fix the issue.

**Comment by Sunekaer** [comment]
Says in the desc. on the curse site that you have to change level-type
