### ISSUE TITLE
Better building wands durability

### ISSUE THREAD

**Issue by DrSpghetto** [FTBTeam/FTB-Presents-Stoneblock-2#220]
As im being lazy (Please do not hate me) Ill shorten this as much as possible without leaving needed info out:

Vers: 1.2.0 (Latest as of now)
The mod im having issues with: Better builder wands
Issue: After using the diamond building wand it does not show the durability (In numbers as in 10/120, Even after enabling advanced tooltips [f3+h]) Causing the ProjectE Repair talisman to NOT work on it.
it shows durability in the form of the bar itself (that turns from green to yellow-brownish over time).

**Comment by Sunekaer** [comment]
Closing this issue, as there´s nothing we can do about this other then wait and see if the mod dev fixes it
