### ISSUE TITLE
Crash Cyclic and Actually additions

### ISSUE THREAD

**Issue by ulobaka** [FTBTeam/FTB-Presents-Stoneblock-2#221]
* **Modpack Version**: Recommended (1.2.0)

* **Issue**: Crash, when i tried to attach  Transfer Energy cell( Cyclic mod) to Canola Generator (Actually Addition mod) 

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/d0bd40fa

* **Is it Repeatable?**: yes, when i trying start a world =/ 

* **Mod/s Affected**: Cyclic mod and Actually addition

**Comment by Sunekaer** [comment]
Make sure to take a backup of your world before doing this! edit the forge.cfg in the config folder. There are a couple of lines about removing erroring entities. Change both of them to true and load the world and see if the removes the block. REMEMBER to set these back to false again!.... If that doesn't work, then use mcedit or NBT Editor on the world to remove the block located at (7,90,16)
