### ISSUE TITLE
Myst Aggra Nether star Not growing

### ISSUE THREAD

**Issue by Pr0ti0us** [FTBTeam/FTB-Presents-Stoneblock-2#222]
>

* **1.2.0**: 

* ** Admittedly I could be impatient or Just out of practice with this mod. But the Nether Star plant isn't growing. Its in the effective rang of a tier 3 growing crystal and I was using a reinforced watering can. I even tried using the mystical fert. It wouldn't even work on it I'm assuming because its from the main mod and not the add on. **: 

* **Link to Log or Crash File Paste**: 

* **yea for me at least**: 

* **Mysitcal Aggradations**: 

* **Known Fix**:

**Comment by ulobaka** [comment]
bro, u need Nether Star Crux block. Place it, under dirt and try again =D

**Comment by Sunekaer** [comment]
answered by ulobaka
