### ISSUE TITLE
Whitch world type i have to choose?

### ISSUE THREAD

**Issue by Toxor123** [FTBTeam/FTB-Presents-Stoneblock-2#225]
* **Modpack Version**: 

* **Issue**: 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by DrSpghetto** [comment]
If you're running a server, change level-type to voidworld (combined), If you're running the game in single player just open a world, it should automatically make the voidworld for you.

**Comment by DrSpghetto** [comment]
Just making sure:
![screenshot_421](https://user-images.githubusercontent.com/41505604/51670540-89acb800-1fcf-11e9-946e-d22a2dc2e48b.png)
![screenshot_420](https://user-images.githubusercontent.com/41505604/51670541-89acb800-1fcf-11e9-98d0-fcb99c4c40cc.png)
![screenshot_419](https://user-images.githubusercontent.com/41505604/51670542-8a454e80-1fcf-11e9-8284-351eb489f4ef.png)

Also try /cave create
