### ISSUE TITLE
Twitch cannot install any version of Stoneblock 2. Twitch cannot find the file folder

### ISSUE THREAD

**Issue by Solverbolt** [FTBTeam/FTB-Presents-Stoneblock-2#228]
* **Modpack Version**: 
Any of them. Not one will install
* **Issue**: 
None of the options work, cannot even install from Twitch, it glitches and tells me that the system cannot find the file. 
* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 
Sure, Attempt to install any of it and it tells me the same error message
* **Mod/s Affected**: 

* **Known Fix**: 
There is none, not surprising

**Comment by Sunekaer** [comment]
Twitch issue not pack issue, contact twitch if you still have this problem

**Comment by M4st3rzz** [comment]
This modpack requires a dependency that is missing or no longer available. Missing Addon ID: 297197
