### ISSUE TITLE
Cant play the game 

### ISSUE THREAD

**Issue by Shadowhunterpvp** [FTBTeam/FTB-Presents-Stoneblock-2#23]
* **Modpack Version**: 

* **Issue**: <!-- [11:59:00] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 3416ms behind, skipping 68 tick(s) this keeps coming up. It loads up the pack just fine but when i make a new world I can't play it. i can hardly make any movements. When i open the esc gui even that is unplayable. Please help. It doesnt crash.It also happened on the orignal stoneblock

**Comment by Sunekaer** [comment]
This is not a lightweight pack
Do you have this problem in single player?
Do you host this server yourself on the same pc?
What's your CPU usage at?

**Comment by SGNepic** [comment]
This is exactly what happens to me, too. I am using a macbook pro, in case that could change something. This is in singleplayer for what I've done.

**Comment by Sunekaer** [comment]
specs? @SGNepic

**Comment by Shadowhunterpvp** [comment]
am also using a macbook pro. i give the pack the max amount of stoprage possible

**Comment by Shadowhunterpvp** [comment]
i have this problem in a single player world.  i am sure something is wrong with this pack because other packs work fine. i have two macs and it doesnt work on either. not the orignal modpack nor the new stoneblock

**Comment by Shadowhunterpvp** [comment]
2.8ghz intel core i5
8 GB 1867 MHz DDR3

**Comment by modmuss50** [comment]
I just tested it on my mac book, and it works.

Ensure you have 4GB of ram assigned to minecraft

**Comment by Shadowhunterpvp** [comment]
i have 12 gb assigned to it

**Comment by Shadowhunterpvp** [comment]
the pack used to work on my mac but i stopped working one day. i dont recall when or which update it stopeed working with or if it is just my mac

**Comment by modmuss50** [comment]
You only have 8GB of ram, how ever you have 12Gb assigned to minecraft, this might be an issue.

I would recommend trying with 4GB of ram assigned to minecraft.

**Comment by Shadowhunterpvp** [comment]
ok

**Comment by SGNepic** [comment]
I am testing 4 gb, but I have a 16 gb ram

**Comment by Shadowhunterpvp** [comment]
yea me too

**Comment by Shadowhunterpvp** [comment]
did not work for me either

**Comment by SGNepic** [comment]
I tried allocating 8GB and 10GB, but it still doesn't work

**Comment by DinnerBeef** [comment]
You can give more than you have

**Comment by Sunekaer** [comment]
What's your CPU usage at?

**Comment by SGNepic** [comment]
How do I check?

**Comment by Sunekaer** [comment]
Dont know how you do that on a mac

**Comment by SGNepic** [comment]
This is while the pack is loading
<img width="563" alt="screen shot 2019-01-05 at 4 09 51 pm" src="https://user-images.githubusercontent.com/46383352/50729231-65626780-1104-11e9-9ccd-625ff5ecacc7.png">

**Comment by SGNepic** [comment]
here is more info for it like what each is
<img width="561" alt="screen shot 2019-01-05 at 4 11 09 pm" src="https://user-images.githubusercontent.com/46383352/50729243-99d62380-1104-11e9-92b0-501b6123e405.png">

**Comment by SGNepic** [comment]
And this is around it while the game is running
<img width="561" alt="screen shot 2019-01-05 at 4 18 00 pm" src="https://user-images.githubusercontent.com/46383352/50729307-91321d00-1105-11e9-84c0-43b056f4ece1.png">

**Comment by SGNepic** [comment]
Also Dinner that's the max amount twitch will let me

**Comment by Shadowhunterpvp** [comment]
<img width="568" alt="screen shot 2019-01-06 at 10 29 53 am" src="https://user-images.githubusercontent.com/46393220/50732304-46b0af00-119e-11e9-8f52-109d5c15e1e1.png"> - my cpu usage
[Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 2508ms behind, skipping 50 tick(s) this keeps on coming up. I dont even get 1 fps when im trying to play in the new word no actions can take place

**Comment by Shadowhunterpvp** [comment]
plz tell me what to do sunekaer

**Comment by SGNepic** [comment]
Please I really want to play stoneblock 2

**Comment by Shadowhunterpvp** [comment]
yea me too

**Comment by nzminecraftDOTcom** [comment]
Have a go at giving java an update if it is out of date.

**Comment by furxia4** [comment]
> Stoneblock one is just fine. It's this one I'm stuck on

Play version 1.0.0
