### ISSUE TITLE
Morph: Game crashes upon morhping

### ISSUE THREAD

**Issue by Snowman-25** [FTBTeam/FTB-Presents-Stoneblock-2#230]
Just updated to Version 1.2.0 of Stoneblock 2 through Twitch client.
When morphing, my game crashes.
Running Windows 7.
Here's my log:
[crash-2019-01-23_18.40.42-client.txt](https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/files/2788476/crash-2019-01-23_18.40.42-client.txt)

_Originally posted by @Snowman-25 in https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/issues/4#issuecomment-456898808_

Known fix: Disable overriding hand rendering in morph config.

**Comment by DranKof** [comment]
My friend had this problem but it didn't affect me. It happened to him only after he tried to morph into me (after killing me), disabling hand rendering worked for him also. I have a custom skin and he has the default male minecraft skin, that may be related.
