### ISSUE TITLE
Error while starting up Stoneblock 2 for the first time

### ISSUE THREAD

**Issue by FearlesPigeon** [FTBTeam/FTB-Presents-Stoneblock-2#232]
Modpack Version**: 
Version 1.2.0
* **Issue**:
When I first started up the mod pack from twitch it loaded for a while then right at the end it failed and said there was an error and I cannot start up the game.
* **Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/0601e1a2
* **Is it Repeatable?**: 
Yes I have tried multiple times now
* **Mod/s Affected**: 
It said there was a problem with Just enough items
* **Known Fix**:
I don't know of any fix

**Comment by triffman33** [comment]
You only have 3GB allocated, try 4-5 if you can, it seems like your mc ran out of memory (or it jei's fault)

**Comment by FearlesPigeon** [comment]
> You only have 3GB allocated, try 4-5 if you can, it seems like your mc ran out of memory (or it jei's fault)

I see I must have my twitch or mc in the wrong drive

**Comment by Sunekaer** [comment]
Assign more ram to minecraft
