### ISSUE TITLE
Hugh FPS Drop while storing "Roost" chicken in "Storage Drawers"

### ISSUE THREAD

**Issue by ketonic** [FTBTeam/FTB-Presents-Stoneblock-2#233]
* **Modpack Version**: 1.3.0

* **Issue**: While storing "Roost"-chickens in "Storage Drawers" 2x2 drawers we are seeing a hugh FPS drop while looking in the direction of the drawers, we do not need to have line of sight. We hade the same issue in 1.1.1.

* **Link to Log or Crash File Paste**: Best i can do is this video https://www.twitch.tv/videos/369190569

* **Is it Repeatable?**: Yes, by hiding/showing the item label with the"Concealment Key" we are able to toggle the issue on and off.

* **Mod/s Affected**: "Roost" and "Storage Drawers"

**Comment by ketonic** [comment]
Thank you @Sunekaer, i was unsure to witch mod dev to report this!

**Comment by triffman33** [comment]
I believe this is actually a Roost issue, i get a huge fps drop when holding shift to look inside an inventory and if theres a roost chicken in there then bye bye fps.

**Comment by triffman33** [comment]
Issue wont be able to be fixed in 1.12 most likely: https://github.com/timrwood/roost/issues/55

**Comment by Sunekaer** [comment]
Doesn't seems like Roost is gonna fix this in 1.12 and storages isn't answering. closing issue, leaving issues opens on both mod trackers
