### ISSUE TITLE
Chorus Fruit

### ISSUE THREAD

**Issue by SherbetYeti** [FTBTeam/FTB-Presents-Stoneblock-2#234]
Is there any way to obtain Chorus Fruit?

* **Modpack Version**: 1.2.0

* **Issue**:  I cant find a way to obtain or craft. 

* **Mod/s Affected**: Lots

**Comment by iKurama** [comment]
Lootcrates gives the flowers. Plant those on end stone.

**Comment by ketonic** [comment]
1x "End Essence", 1x "Nature Essence" and 1x "End Essence" on the top row crafts 12 Fruits. (version 1.3.0)

**Comment by SherbetYeti** [comment]
> Lootcrates gives the flowers. Plant those on end stone.

Thanks ill have a go

**Comment by Iomega0318** [comment]
You can also sieve crushed End Stone for the Chorus Flower, then use that in a Hopping Bonsai with End Stone to grow as much as you want.

![image](https://user-images.githubusercontent.com/5641516/51755922-fc27a180-207c-11e9-9c68-2419ec9880b0.png)

**Comment by SherbetYeti** [comment]
> You can also sieve crushed End Stone for the Chorus Flower, then use that in a Hopping Bonsai with End Stone to grow as much as you want.
> 
> ![image](https://user-images.githubusercontent.com/5641516/51755922-fc27a180-207c-11e9-9c68-2419ec9880b0.png)

Thanks. Can't believe I didn't see that.

**Comment by DranKof** [comment]
The recipes that require lower tier sieve nets have been a bit of a curve-ball for players on my server, too. Especially this one.
