### ISSUE TITLE
Jei+Thaumcraft Bug

### ISSUE THREAD

**Issue by TheError007** [FTBTeam/FTB-Presents-Stoneblock-2#235]
* **Modpack Version**: 1.2.0.

* **Issue**: Whenever in JEI you look up items, that have instrumentum, on 5th page, the game crashes
Edit: Found same bug with 6th page while looking on motus, probably affects more elements aswell

* **Link to Log or Crash File Paste**:  https://pastebin.com/3HuaCRgH 

* **Is it Repeatable?**: Yes, whenever you try to turn to page 5 in JEI(Medium GUI), game crashes

* **Mod/s Affected**:  JEI, Thaumcraft

* **Known Fix**: Haven't found any

**Comment by Sunekaer** [comment]
Backup your world, update to 1.3.0 and try again

**Comment by Sunekaer** [comment]
reopen this issue if its still an issue on 1.3.0
