### ISSUE TITLE
Extra Utilities 2 Transfer Nodes

### ISSUE THREAD

**Issue by sebtech33** [FTBTeam/FTB-Presents-Stoneblock-2#236]
* **Modpack Version**: 1.3.0 

* **Issue**: Shift+Click in Extra Utilities 2 transfer nodes causes the whole game to crash and it's persistent 

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/2dfb1631 

* **Is it Repeatable?**: Yes 

* **Mod/s Affected**: Extra Utilities 2 

* **Known Fix**: Don't Shift+Click, but other than that is do not know of any fix

**Comment by TheKrowi** [comment]
I got something similar with Ctrl clicking flat transfer nodes: https://paste.dimdev.org/qepakipuji.mccrash. All my flat transfer nodes also dissapeared from the game since my last load.

**Comment by TheKrowi** [comment]
Also crashing my world now when I loaded it today for the first time: https://paste.dimdev.org/ogesaduqug.mccrash. Trying to load it again no errors came up and just got in.

**Comment by Sunekaer** [comment]
#31
