### ISSUE TITLE
[IE2+MA][BUG] Seeds not recognized by Cloche

### ISSUE THREAD

**Issue by micheldewit** [FTBTeam/FTB-Presents-Stoneblock-2#237]
* **Modpack Version**: All versions
* **Issue**: T6 seeds are not recognized by Garden Cloches
* **Link to Log or Crash File Paste**: None
* **Is it Repeatable?**: Yes
* **Mod/s Affected**: IE2 and Mystical Aggradditions
* **Known Fix**: https://minecraft.curseforge.com/projects/ie-cloche-compat

**Comment by iKurama** [comment]
It's intentional that they're not being recognized, as you need a dirt block above the crux. That addon breaks the idea of both mods.

**Comment by Sunekaer** [comment]
Intended, mod wont be added

**Comment by tyler489** [comment]
I mean it does use the crux block as the grow on block.
