### ISSUE TITLE
FTB Quests: Quest Chest

### ISSUE THREAD

**Issue by PunchNinja** [FTBTeam/FTB-Presents-Stoneblock-2#238]
* **Modpack Version**: Latest Stoneblock 2 (Twitch client)

* **Issue**: Opening the FTB Quests Quest Chest and quickly/immediately closing (pressing ESC key) causes client to crash.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/df6edfaf

* **Is it Repeatable?**: Yes.

* **Mod/s Affected**: FTB Quests, FTB Library

* **Known Fix**: Don't know.

**Comment by Sunekaer** [comment]
Which is why the recipe was removed in 1.3.0
