### ISSUE TITLE
Personal EMC Link NBT Duplication

### ISSUE THREAD

**Issue by LarcekGiglamesh** [FTBTeam/FTB-Presents-Stoneblock-2#239]
We discovered a grave duplication issue today. Normally with ProjectE you are not allowed to learn items containing nbt data, but ProjectEx allows for export of such data while taking the basic Item as Costs. 

1. Chest, Hopper feeding into Chest, Personal EMC Link onto Hopper
2. Have your ProjectE know of OpenBlocks Tank (128 EMC). 
3. Fill a tank with any Liquid which normally wouldn't make it insertable into either Transmutation Table, Tablet or Energy Condensor. Those would take the basic OpenBlocks Tank as output instead.
4. Put the Filled Tank (for Instance Liquid XP, or let's say Fluid Infinity) into the Personal EMC Link.
5. Profit duplicated Tanks, filled to the same amount as the example, for 128 EMC each.

* **Modpack Version**: 1.3.0

* **Issue**: Duplication of Items containing NBT Data

* **Link to Log or Crash File Paste**: none

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Project Ex - Personal EMC Link

* **Known Fix**: none aside from disabling

**Comment by LatvianModder** [comment]
Fixed in https://jenkins.latmod.com/job/Project-EX/4/
