### ISSUE TITLE
StoneBlock 2 1.3.0 not loading

### ISSUE THREAD

**Issue by TECHNOPLAYZMC** [FTBTeam/FTB-Presents-Stoneblock-2#240]
* **Modpack Version**: 
13.0 (version lower then this one work)
* **Issue**: 
When selected 'play' in the twitch launcher the minecraft launcher is displayed and once 'play' is activated again the launcher disappears and the game does not show up. in task manager the 'javaw.exe shows signalling it should be loading but yet the gamedoesnt show up on either the screen nor the task bar. must force close minecraft.

* **Link to Log or Crash File Paste**: 
none.
* **Is it Repeatable?**: 
Yes.
* **Mod/s Affected**: 
none known. 
* **Known Fix**: 
No known fix.

**Comment by Sunekaer** [comment]
did you try and let it run for a little time before force closing it?

**Comment by TECHNOPLAYZMC** [comment]
Yes. I ran it for about half an hour before closing it in one of my first attempts.

**Comment by triffman33** [comment]
Reinstalling java may help

**Comment by TECHNOPLAYZMC** [comment]
Fix found!
During download an error must of occurred, by deleting the profile and reinstalling it, it works like a charm.
Thank you
