### ISSUE TITLE
Crashing every time I load into world. 

### ISSUE THREAD

**Issue by iDemonz** [FTBTeam/FTB-Presents-Stoneblock-2#242]
* **Modpack Version**: 1.1.1

* **Issue**: I've been playing my world for a few days now. Every so often my game crashes, usually it's fine, it stops responding, I close it and reopen it. The last time it did this, I reopened the game and It crashed before loading into the world. Every time I've tried opening this world it repeats this, crashing before getting past the loading screen.
Right before it crashed the first time, I was troubleshooting something with a creative power source.
(Creative power source into a flux point) (<-- not sure if that helps)

Note: I can open another world, and it will work normally, I presume there's some sort of corrupted block in the save, Idk what it is though... (I don't know how to fix this so.)

* **Link to Log or Crash File Paste**: 
Client/Server Log: https://paste.feed-the-beast.com/view/11a620b8
Crash Log: https://paste.feed-the-beast.com/view/b2aebae3

* **Is it Repeatable?**: Yes, every time I attempt loading into this world

* **Mod/s Affected**: Not Sure

* **Known Fix**: N/A

**Comment by Sunekaer** [comment]
Make sure to take a backup of your world before doing this! edit the forge.cfg in the config folder. There are a couple of lines about removing erroring entities. Change both of them to true and load the world and see if the removes the block. REMEMBER to set these back to false again!.... If that doesn't work, then use mcedit or NBT Editor on the world to remove the block

**Comment by Sunekaer** [comment]
I also recommend updating your pack as you are far behind
