### ISSUE TITLE
Items in Iron Chest Disappear After A Few Seconds

### ISSUE THREAD

**Issue by Fibro-Hurts** [FTBTeam/FTB-Presents-Stoneblock-2#243]
* **Modpack Version**: 1.3.0

* **Issue**: Items in an Iron Chest from the Iron Chests Mod will disappear in a few seconds after opening the chest. The items will reappear after clicking on one of the item stacks. I am not sure if the gold, diamond, crystal, or obsidian chests do this as well. I have not gotten that far yet.

* **Link to Log or Crash File Paste**: I was playing on a server, so I don't know.
EDIT: here is the link to my "latest log" that was on my computer:

https://drive.google.com/file/d/1aFHtVQ96EvPTeE8eYHvlyvPcO9Btj8VE/view?usp=sharing

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Iron Chests

* **Known Fix**: No known fix.

**Comment by iKurama** [comment]
https://github.com/progwml6/ironchest/issues/162

**Comment by Sunekaer** [comment]
Closing this issue, as there´s nothing we can do about this other then wait and see if the mod dev fixes it
