### ISSUE TITLE
Vivid alloy Fluid Cow Impossible to get.

### ISSUE THREAD

**Issue by Cazitron** [FTBTeam/FTB-Presents-Stoneblock-2#245]
I'm attempting to get the vivid alloy fluid cow and after a hundred or so cows i still have gotten a single one is there some trick to these cows or do i just need more of them. Even though the breeding chance is 4% thats still 1/25 and still i've had no luck. So any advice?

**Comment by Sunekaer** [comment]
just bad luck

**Comment by Cazitron** [comment]
Seriously i have three of these things going...
![2019-01-27_16 03 24](https://user-images.githubusercontent.com/46332689/51806860-187a3880-224d-11e9-8f79-e32235c89b13.png)
