### ISSUE TITLE
fluid.energetic_silver

### ISSUE THREAD

**Issue by Cazitron** [FTBTeam/FTB-Presents-Stoneblock-2#246]
Couldn't find any reports on the fluid cow for Energetic Silver, so its named "fluid.energetic_silver" in game thought you'd wanna add that to the next update cause i can easily see how you could miss that one considering how many cows there are. "Molten Energetic Silver" sounds like the perfect fix. Anyways take care and I'll let you know if my vivid alloy quest becomes more than just "bad luck".

**Comment by tyler489** [comment]
This is because a Bug in Enderio caused the Name of liquids to go missing. so therefor the cows don't have the correct name either.

**Comment by Sunekaer** [comment]
Cant do anything about this, we reported this to Enderio many mouths ago, and they still havent fixed it

**Comment by tyler489** [comment]
Should be fixed in next version. Re.inded the devs yesterday
