### ISSUE TITLE
Emc not there.

### ISSUE THREAD

**Issue by OldManCraft** [FTBTeam/FTB-Presents-Stoneblock-2#248]
* **Modpack Version**: 1.3.0

* **Issue**: Was watching direwolf stream last night. He had item's with emc that I don't have and quest I don't have on the latest version. 
Example Quest: One project E he has the Colossal Star Omega Quest. There is more 

Example EMC: Thermal Foundation Hardened/Reinforced upgrade kit's have emc but signalum/resonant Conversion kit's do not. There are more of these as well. 
I'm on a server that I control. 

* **Link to Log or Crash File Paste**: n/a
* **Is it Repeatable?**: n/a
* **Mod/s Affected**: Project E, Thermal Foundation

* **Known Fix**: Do not know

**Comment by Sunekaer** [comment]
Are you sure updated to 1.3.0? are you playing on server?

**Comment by Sunekaer** [comment]
Did you update the quest file and configs?

**Comment by Sunekaer** [comment]
And yes signalum/resonant  doesn't have because it require items that doesn't have EMC values

**Comment by OldManCraft** [comment]
I update the server config, mods, scripts, and resources every time.  Are you referring to questpacks folder ?

**Comment by OldManCraft** [comment]
Ok So I updated the Questpacks folder as well and seem to have fixed it.
