### ISSUE TITLE
JEI  has incorrect recipe for Energy Condenser

### ISSUE THREAD

**Issue by Ladysarajane** [FTBTeam/FTB-Presents-Stoneblock-2#249]
* **Modpack Version**: 1.3.0 (upgraded from previous version not a fresh install)
* **Issue**: Unable to craft Energy Condenser due to JEI being incorrect.  Had all the materials according to JEI to craft the Energy Condenser and I was unable to craft...Noticed in watching Direwolf20 Stoneblock 1 that he needed Draconic Level infusion injectors to craft The Energy Condenser.....My JEI states it needs Wyvern injectors. 
Now I attempted to update my injectors to Draconic level injectors and the recipe is wrong and I cannot upgrade them. Recipe for them in JEI calls for 4 diamonds, 2 wyvern cores, 1 awakened draconium block and the wyvern injector in the  fusion crafting core and I cannot craft it, so I am assuming JEI is wrong...but I do not know this mod very well. What am I missing? (SOLVED this portion of the problem)
* **Link to Log or Crash File Paste**:No crash

* **Is it Repeatable?**: Yes
* **Mod/s Affected**: JEI, Draconic Evolution, Project64
* **Known Fix**: Unknown
![2019-01-28_08 56 39](https://user-images.githubusercontent.com/34258851/51843034-35ac1700-22e0-11e9-941d-29eacb19cc71.png)
![2019-01-28_09 08 56](https://user-images.githubusercontent.com/34258851/51843035-35ac1700-22e0-11e9-8602-275436666f04.png)
![2019-01-28_09 09 35](https://user-images.githubusercontent.com/34258851/51843036-35ac1700-22e0-11e9-96af-f8b2525ec5c0.png)

**Comment by iKurama** [comment]
The center can only accept from injectors 3 blocks from one side. Recommended is to make 3x3 injectors per side, with the center block in the center of the 3x3 injectors.

**Comment by Ladysarajane** [comment]
Thank you iKurama! I was able to craft the Draconic Injectors with that help and using those injectors, I was able to craft the Condenser. That was why I included a photo...I was okay crafting things until I added the extra injector to try craft the Energy Condenser...then when I realized that recipe was wrong....I kept using that extra injector. So JEI is still wrong with the Energy Condenser Recipe.

**Comment by Sunekaer** [comment]
From looking at the first image, you dont have all the items need for the recipe...

**Comment by Ladysarajane** [comment]
I did have all the items, however I had an injector out of place. When iKurama pointed that out I corrected it. I attempted it again and it did not work with the wyvern injectors. I  Put the items in a working chest and I upgraded the injectors to Draconic level, then tried crafting the Condenser  again with the Draconic Level injectors and it worked.

**Comment by Sunekaer** [comment]
![image](https://user-images.githubusercontent.com/18720460/51987522-f974e400-24a2-11e9-818d-3400f66c206b.png)
works just fine for me
