### ISSUE TITLE
Quest Bug

### ISSUE THREAD

**Issue by JuniorDipity** [FTBTeam/FTB-Presents-Stoneblock-2#25]
Modpack Version: 1.0.1

Bug in Quest "Master Tinkerer", will not complete after creating the tool forge.

**Comment by Sunekaer** [comment]
Which tool forge did you make?

**Comment by Craigschultze30** [comment]
Having the same issue and ive made all of the different forges and none complete the quest

**Comment by Loganou974** [comment]
Same here ! Tool forge made of iron (request is "any tool forge") not working

**Comment by Craigschultze30** [comment]
So I figured out the issue with this. You need to complete the quests on the other side of it as well before that will complete. Look at the little arrows.
