### ISSUE TITLE
"waiting for server"  

### ISSUE THREAD

**Issue by SgtPackrat** [FTBTeam/FTB-Presents-Stoneblock-2#250]
Modpack Version:  FTB PresentsStoneblock2 -1.3.0-1.12.2. Beta
    Java Version:  8 Update 201 
    System Ram allotted : 8 gb of 32 gb 
    Server:  Fluctis 6gb

    Issue:  When my self and  a fried  are playing on the server after  10 or 15 mins  I start getting  
"waiting for server"  message  along with  sever lag accessing  things like chest  and machines.
If he logs off every thing clears up.  

    Is it Repeatable?: Like clock work  after playing for  10 or 15 mins

    Mod/s Affected: The whole pack

**Comment by Sunekaer** [comment]
Your friend has something in hes base lagging out the server, probably watch of flowing time or something like that

**Comment by SgtPackrat** [comment]
Thing of it is  we are working in the same base within a chunk or so of each other.  If he moves away from me say  10 plus   chunks the   issue also resolves. , Not sure minimum  safe distance specifically as we never measured it.
