### ISSUE TITLE
YABBA needs update

### ISSUE THREAD

**Issue by DubbaThony** [FTBTeam/FTB-Presents-Stoneblock-2#251]
* **Modpack Version**: 1.2.0

* **Issue**: YABBA is outdated and contains annoying bug where barrel locking does not work for automation.

* **Link to Log or Crash File Paste**: n/a

* **Is it Repeatable?**: yes.
**steps to reproduce:**

I've set up few barrels and connected them with barrel connector.
I've locked every barrel with item I wanted it to hold.
I've added ME storage bus and set it priority highest in system
I've drained all items from barrel via ME system (can be done by hand, works too).
I've added non-barrel whitelisted item into applied energistics.
**Expected result**:
Locked barrel should retain 0 items and locked, let's say redstone, and inserted item should land in ME drives.

**Actual result**:
AE2 bypasses barrel lock, the item lands in barrel even if it's lets say cobblestone, not redstone.

* **Mod/s Affected**: YABBA

* **Known Fix**: Update YABBA to 1.1.2.35 or newer

**Comment by Sunekaer** [comment]
already done in 1.3.0 which been out for a week now
