### ISSUE TITLE
Too many fluid cows crashed server

### ISSUE THREAD

**Issue by Cazitron** [FTBTeam/FTB-Presents-Stoneblock-2#252]
So i accidently left some chunks loaded that had some auto breeders breeding fluid cows. And i cant get back onto the server is there a command that can kill off all fluid cows? I have access to the console and server files but nothing else. I tried /kill @e but that didn't kill the cows. Is there a different command I could use?

**Comment by Sunekaer** [comment]
You have to load the chunks to use any command to remove them,  you could try this but im not sure it will help, if it doesnt you need to use something like mcedit or NBT editor, but thats not something i can guide you in 
Make sure to take a backup of your world before doing this! edit the forge.cfg in the config folder. There are a couple of lines about removing erroring entities. Change both of them to true and load the world and see if the removes the block. REMEMBER to set these back to false again!
