### ISSUE TITLE
StoneBlock 2 world broke, gets stuck on Loading Terrain maybe due to trans-locator. Help?

### ISSUE THREAD

**Issue by Stank132** [FTBTeam/FTB-Presents-Stoneblock-2#254]
* **Modpack Version**:  StoneBlock 2 V1.1.1

* **Issue**: Placed an item trans-locator and it stopped working, machines backed up, when I right clicked it, the world shut down and the game crashed

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**:  Yes, still cant access the world

* **Mod/s Affected**:  I dont know but I think only the Trans-Locator.

* **Known Fix**:  Nope.

**Comment by Stank132** [comment]
Like the FTB logs? Where can I find them and send them, Im a newbie u must guide me and thanks if u do

**Comment by iKurama** [comment]
Curse\Instances\FTB Presents Stoneblock 2\logs - Latest .. Only if latest is proof of you being stuck.

**Comment by iKurama** [comment]
So there might be a couple solutions, not necessary good ones though.
1. K:\Docs\FTBPresentsStoneblock2\minecraft\saves\yos will be remembered\level.dat - Make a backup of this, and delete the original.
2. D:\Curse\Instances\FTB Presents Stoneblock 2 (1)\config\forge - Line 62, B:removeErroringTileEntities=false, turn this to true. (if it works, turn this back to false.)
3. Remove the translocator mod, load the world. Then close minecraft and add it back in.

**Comment by Stank132** [comment]
Thanks will do
