### ISSUE TITLE
Mob farms stopped working after upgrade to 1.2.0

### ISSUE THREAD

**Issue by marcelwirtz** [FTBTeam/FTB-Presents-Stoneblock-2#256]
* **Modpack Version**: 1.2.0 (Server)

* **Issue**: After upgrading our existing world to 1.2.0 all mob farms stopped working. There a no mobs spawning nevermind if there is cursed earth or not.

**Comment by Sunekaer** [comment]
Server, single player? what about 1.3.0, havent heard that anyone has had this problem before tho

**Comment by iKurama** [comment]
Might be one of the annoying light-level bugs. If a random totally black room has light, you need to place blocks around, till the blocks "overwrites" the light "block".

**Comment by marcelwirtz** [comment]
@Sunekaer oh sorry it's server

@iKurama you mean i have to fill my room with blocks and clear it again?

**Comment by marcelwirtz** [comment]
Here is a screenshot with debug infos enabled standing in my mob farm with the entry closed again. This was after i filled it up with blocks and removed them. Still not working.

[http://prntscr.com/mefsdf](http://prntscr.com/mefsdf)

I think light level 2 should be okay.

**Comment by iKurama** [comment]
That's odd alright.
Now the questions are: What is the difficulty on, is it a server with sponge, is cursed earth disabled, can mobs spawn at all?

**Comment by marcelwirtz** [comment]
Mobs can spawn, they spawn outside of a farm on low light level, cursed earth is enabled (it worked before the upgrade, so if the updates hasn't changed the config it should still be enabled), difficulty is normal

**Comment by iKurama** [comment]
Will the farms work if you remove the fans and just let cursed earth do its job without anything near them (except for water candles)

**Comment by Sunekaer** [comment]
Update hasnt change anything in regards to mob/spawning

**Comment by marcelwirtz** [comment]
Okay here some new insights:

The problem seems to be the chunkloading through FTBLibs in combination with a server restart we had to update on 1.2.0...

After disabled the chunk loading for this chunk (it's already claimed) we had to move away to unload the chunk and can go back and it's working again.
