### ISSUE TITLE
The game crashed whilst exception in server tick loop

### ISSUE THREAD

**Issue by nr1craft** [FTBTeam/FTB-Presents-Stoneblock-2#257]
* **Modpack Version**: 1.2.0

* **Issue**: 
The game crashed whilst exception in server tick loop

The game crashed whilst exception in server tick loop Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MineTogetherServer (minetogetherserver)

* **Is it Repeatable?**: everytime i want to load in my world this happens

* **Mod/s Affected**:in the error it says that the mod minetogetherserver is causing the problem 

* **Known Fix**: i dont know

**Comment by Sunekaer** [comment]
log file....

**Comment by nzminecraftDOTcom** [comment]
We need a crash report to solve this. It can be found in your documents folder inside the curse folder. Navigate to the stoneblock 2 folder then the crash reports folder and open the one that occured when you first had the problem, copy it's contents to pastebin (Google it) then copy the URL it creates and paste it here.

**Comment by nr1craft** [comment]
https://pastebin.com/bMEQkxEN

**Comment by Sunekaer** [comment]
Could you try and update to 1.4.0 or 1.3.0 and see if you still have the issue?

**Comment by Andrew3085** [comment]
I have this same error
Here is my pastebin: https://pastebin.com/NyQHawMi
I've tried to update the server then copy and paste the files from the world file, but the world's aren't compatible.

**Comment by Lievargus** [comment]
Same issue. https://pastebin.com/v76naDz5
