### ISSUE TITLE
Big Spender

### ISSUE THREAD

**Issue by DanielSchuerhoff** [FTBTeam/FTB-Presents-Stoneblock-2#258]
So for the quest Big Spender you need like ~9*10^18 EMC ... which you can get comfortably with 30 000 infinity cows in 30 days ... but the problem is ... that most servers only allow you a certain number of cows (e.g. 1 per type) ... so then the quest would a bit more than a slightly unrealistic 14 000 years .... 

Or have I missed a way of generating EMC more efficiently?

* **Modpack Version**: 1.3.0

* **Issue**: Big Spender Problems on restricted servers

* **Is it Repeatable?**: yes

* **Mod/s Affected**: EE

* **Known Fix**: Make Big Spender cheaper

**Comment by iKurama** [comment]
- https://www.reddit.com/r/feedthebeast/comments/akwipq/ftb_stoneblock_2_any_legit_way_to_complete_big/
- https://twitter.com/Direwolf20/status/1089751694752272384

**Comment by Sunekaer** [comment]
Yeah this quest is just gonna take a really long time if you want to do it.
