### ISSUE TITLE
Common Loot Crate misspelled Commen Loot Crate

### ISSUE THREAD

**Issue by ehertlein** [FTBTeam/FTB-Presents-Stoneblock-2#26]
* **Modpack Version**: 1.0.1

* **Issue**: The Common Loot Crate is misspelled Commen Loot Crate

* **Link to Log or Crash File Paste**: No log.

* **Is it Repeatable?**: Yes.

* **Mod/s Affected**: FTB Quests

* **Known Fix**: Fix this spelling?

**Comment by Sunekaer** [comment]
1.1.0
