### ISSUE TITLE
My Game Crash´s

### ISSUE THREAD

**Issue by RushGaming23** [FTBTeam/FTB-Presents-Stoneblock-2#260]
Modpack Version: Stonblock2-1.3.0-1.12.2.zip

Issue: My Game Crash´s

[latest.log](https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/files/2814357/latest.log)

This is my Latest Log.

When u need more pls tell me and wher i can find it

**Comment by iKurama** [comment]
Sponge is not supported.

**Comment by iKurama** [comment]
It means that it's a crashlog that doesn't work, as it's not a part of the original modpack.
In other words, if you edit it just slightly, it will not be supported.

Sponge is a server software to add plugins etc. Forge mods are not made for or with Sponge, which in other words, Sponge will most likely break the mods.

Take it up with the server staff.

**Comment by RushGaming23** [comment]
@Sunekaer can u help [Its only when i start it with the TwitchLauncher] with the FTB Launcher i can play the Modpack

**Comment by Sunekaer** [comment]
please use https://paste.feed-the-beast.com/ for the log, as im not downloading files
