### ISSUE TITLE
cant play

### ISSUE THREAD

**Issue by dkrunk19** [FTBTeam/FTB-Presents-Stoneblock-2#261]
I can open and load the game fine through the twitch fine. When I create a map and load in and try to do anything my game crashes. I messed around with giving it more ram and I still does the same thing. It does this to every pack I try to play.

**Comment by dkrunk19** [comment]
[latest.log](https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/files/2815843/latest.log)

**Comment by Sunekaer** [comment]
please use https://paste.feed-the-beast.com/ for the log, as I'm not downloading files
