### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by thatkiddo** [FTBTeam/FTB-Presents-Stoneblock-2#264]
Modpack Version: 1.3.0
Minecraft Version: 1.12.2

Issue: Keeps on saying that Just Enough Items (JEI) is not allowing minecraft to boot up

Crash Report: https://paste.dimdev.org/edaqudahej.mccrash

Happens every time i try to play the modpack.

Mods: Just Enough Items (JEI)

No Known Fix

**Comment by iKurama** [comment]
- At least 4-6GB of RAM allocated to the pack
You have 3 gigs allocated.

**Comment by Sunekaer** [comment]
https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/blob/master/README.md
