### ISSUE TITLE
Crash on Launch

### ISSUE THREAD

**Issue by Darkheart747** [FTBTeam/FTB-Presents-Stoneblock-2#267]
Title Stoneblock 2 crash on launch 

Launcher Type Curse App

Modpack Stoneblock 2 

Modpack version 1.4.0 

Have you modified the pack? No 

Link to log file https://paste.feed-the-beast.com/view/f9708e90 

Details of the issue Try to launch the game, get almost done and JEI keeps causing a crash

**Comment by Sunekaer** [comment]
https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/blob/master/README.md
