### ISSUE TITLE
Saves and update

### ISSUE THREAD

**Issue by keyko210** [FTBTeam/FTB-Presents-Stoneblock-2#268]
I got problem whit this mod pack i never hav whit any others, my saves are not saved in the folder saves like they should be, the folder is empty, even if i got the world saved, other problem is every time im forced to make update of the modpack my whole mod pack gets f up and it turns into normal mc so to fix that i need to uninstall the pack and install it again other wise it dosnt work:/
Worst part is i cant make like back up files  too copy "save" folder like i did whit other pack becouse hes like empty:( i lost ma world 3 times alredy and im ryly starting to get tired of starting over and over again:( 
Is there any way to retrive ma saves back?? and too stop this to break and also ma saves to be actually saved like they should be?
pls help im ryly like the modpack but im ryly getting annoyed of being losing all ma saves:(

**Comment by Sunekaer** [comment]
Youll have to take to twitch as we dont ship/touch the world folder, in files we push for updates/installation

**Comment by keyko210** [comment]
> 
> 
> Youll have to talk to twitch support as we dont ship/touch the world folder, in files we push for updates/installation

Im not use twitch to play this i use MP Launcher.
