### ISSUE TITLE
FTB Quests but at log in.

### ISSUE THREAD

**Issue by jackrtades** [FTBTeam/FTB-Presents-Stoneblock-2#270]
* **Modpack Version**:1.4.0

* **Issue**:  a bug should have crashed the pack

* **Link to Log or Crash File Paste**: https://paste.dimdev.org/ciyoyomape.mccrash

* **Is it Repeatable?**: It's poped up before

* **Mod/s Affected**: FTB Quests

* **Known Fix**:

**Comment by Sunekaer** [comment]
see if it still happens in https://www.feed-the-beast.com/projects/ftb-presents-stoneblock-2/files/2673992
