### ISSUE TITLE
Crash from Time in a bottle

### ISSUE THREAD

**Issue by CtrlAltPizza** [FTBTeam/FTB-Presents-Stoneblock-2#272]
* **Modpack Version**: 1.3.0

* **Issue**: While playing, I attempted to use the time in a bottle on energetic infuser which was charging a flux jetpack that I just crafted. Right after I clicked on the block, the animation began on it then it crashed. On reboot, it allows me into the world and the animation is running on the infuser, but when attempting to access it, it will crash. 

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/79de4fbd

* **Is it Repeatable?**: Yes, have attempted twice and happened both times

* **Mod/s Affected**: Either Thermal Expansion (Unable to handle the tick acceleration in it's UI) or Random Things (Possibly trying to accelerate something that cannot)

* **Known Fix**: Wait out the timer and then you are able to access the screen again

Note: I originally found this the night before the 1.4.0 update released, and the issue is still present in the latest version. Only difference that I found was that upon crash, VanillaFix prevented the entire game from crashing, and does state that the problem is most likely between Random Things and Thermal Expansion

**Comment by Sunekaer** [comment]
Closing this issue, as there´s nothing we can do about this other then wait and see if the mod dev fixes it
