### ISSUE TITLE
Incompatible FML Modded Server, 0 Mods Loaded

### ISSUE THREAD

**Issue by MudkipTheDank** [FTBTeam/FTB-Presents-Stoneblock-2#273]
* **Modpack Version**:  Stoneblock 2 1.3.0

* **Issue**: I am trying to play Stoneblock 2 through the Twitch launcher, but every time I try to join a server i get an error: "Imcompatible FML Modded Server, 0 Mods Present." I can load into a single player world with no issues, but i can not join the server that I want to play on (MineWonderLand). Also, in the bottom left screen of the menu, it says, "257 mods loaded." I have tried downloading every available version of the game, but none of them work. I have even tried downloading Minecraft and the mod in a different drive. All of my friends downloaded the mod and joined the server with no issues, but for some reason, I just can't figure this out. I feel like I have tried everything. Please help. I have not experienced any crashes either.

* **Is it Repeatable?**: Yes, it has been an issue for weeks.

* **Known Fix**: None

**Comment by iKurama** [comment]
Seems like the server is the cause then. Either they got a wrong version or it's bugged.

**Comment by nzminecraftDOTcom** [comment]
Are you able to join other servers? If you are then it may be their server. Check your version matches the server. If you can not get on to other servers, try reinstalling the pack.

**Comment by Sunekaer** [comment]
Are you connecting to the correct server/ip and port?

**Comment by triffman33** [comment]
I've seen this issue when you hover over the ping of the server in the server list, however connecting to it will still let you join. May be a sponge issue with showing the mods present.
