### ISSUE TITLE
have a crash with fastworkbench

### ISSUE THREAD

**Issue by BlazingLion838** [FTBTeam/FTB-Presents-Stoneblock-2#274]
[<!
Thanks for wanting to report an issue you've found. Please delete
this text and fill in the template below. If unsure about something, just do as
best as you're able. Thank you!
Note: any external modifications to this modpack will render all support useless,
ie; adding mods like optifine to the modpack! So please remove all added content, 
re-test bug/issue and resubmit!
-->

* **Modpack Version**: 

* **Issue**: 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**: [](url)
[](https://paste.dimdev.org/zateqebusi.mccrash)

**Comment by iKurama** [comment]
Invalid
