### ISSUE TITLE
Extra Utilities 2 ran into a problem!

### ISSUE THREAD

**Issue by RuanH8** [FTBTeam/FTB-Presents-Stoneblock-2#275]
* **Modpack Version**: 1.4.0

* **Issue**: Every time I place down a flat transfer node I receive this message. As of this moment, the node can be placed, but does not do anything. The game does not crash, but does generate a crash report.

* **Link to Log or Crash File Paste**: https://paste.dimdev.org/logejemuga.mccrash

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Extra Utilities 2

* **Known Fix**: None

**Comment by iKurama** [comment]
I can partly confirm that.
I can place it, it generates the crashlog without crashing (Thanks to VanillaFix), but NO message of any sorts about not working.

**Comment by Sunekaer** [comment]
#31
