### ISSUE TITLE
JustEnoughItems causing game crash 

### ISSUE THREAD

**Issue by kaskubla** [FTBTeam/FTB-Presents-Stoneblock-2#276]
* **Modpack Version**: 
FTB stoneblock2 1.3.0
* **Issue**: 
crashed while first time loading recipes - just enough items
* **Link to Log or Crash File Paste**: 
https://paste.dimdev.org/begaleteke.mccrash
* **Is it Repeatable?**: 
yes
* **Mod/s Affected**: 
just enough items

**Comment by Sunekaer** [comment]
https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/blob/master/README.md
