### ISSUE TITLE
Jei+Thaumcraft bug (again)

### ISSUE THREAD

**Issue by TheError007** [FTBTeam/FTB-Presents-Stoneblock-2#277]
Modpack Version: 1.2.0., 1.3.0.

Issue: Still the same bug. Whenever in JEI you look up items, that have instrumentum, on 5th page, the game kicks you from the server, same bug with 6th page while looking on motus, probably affects more elements aswell.
Edit: In singleplayer it works fine, just doing messed stuff in Multiplayer.

Link to Log or Crash File Paste: https://pastebin.com/3HuaCRgH, https://paste.dimdev.org/fovicinusi.mccrash

Is it Repeatable?: Yes, whenever you try to turn to page 5 in JEI(Medium GUI), game will kick you from the server.

Mod/s Affected: JEI, Extra Utilities 2, CodeChicken Lib

Known Fix: Haven't found any

**Comment by iKurama** [comment]
The server is sponge.
Sponge is not support.
Therefore, not a valid bug.
