### ISSUE TITLE
Craftpresence make minecraft fail to start

### ISSUE THREAD

**Issue by masterbobli** [FTBTeam/FTB-Presents-Stoneblock-2#278]
* **Modpack Version**: 1.4.0

* **Issue**: 
During the process of mod loading on step 4, when loading the mod Craftpresence, the loading screen lagged, disappeared and the minecraft window show the picture below, suggesting that CraftPresence could be the potential cause.
![2019-02-01 11 16 04](https://user-images.githubusercontent.com/37212918/52132061-4c07f900-2679-11e9-86a4-480d62e10378.png)
PS:  the window at the bottom left corner is the force quit application window. I open it in case minecraft goes wrong and lags the computer 
* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/1d03a776

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: CraftPresence, 1.12.2-1.4.9.9

* **Known Fix**: Remove the mod

**Comment by Sunekaer** [comment]
For now just remove the mod from the pack

**Comment by Sunekaer** [comment]
Please send latest.log file also
Could you also try downgrading CraftPresence to v1.4.9.8 and see if that runs fine

**Comment by masterbobli** [comment]
1.4.9.8 gives the same issue
Here's the link of the entire log
 https://paste.feed-the-beast.com/view/eeed313b

**Comment by Sunekaer** [comment]
Could you try removing the craftpresence folder and the craftpresence config

**Comment by masterbobli** [comment]
Removing the mod does help

**Comment by CDAGaming** [comment]
Removing the mod does indeed help, but doesn't give me a way of reproducing it (Narrowing down these conditions) nor fixing it, as atm I haven't been able to reproduce this issue.

**Comment by masterbobli** [comment]
I would close this issue for now
