### ISSUE TITLE
Chisel blocks no longer animated

### ISSUE THREAD

**Issue by Gunner76th** [FTBTeam/FTB-Presents-Stoneblock-2#279]
So it seems that either a config setting has been changed or the Chisel authors have broken something. Ever since the 1.3.0 update to this pack, none of the Chisel blocks have their animations anymore. This is slightly annoying when you have built a base and made use of those animations to help decorate and hide different things. So now instead of nice big moving fans and simulated ME Controllers, I have static images of circles, and a dead ME controller 
* **Modpack Version**: 
1.4.0
* **Issue**: 
Chisel Blocks no longer show animations
* **Link to Log or Crash File Paste**: 
N/A
* **Is it Repeatable?**: 
Yes, craft a chisel block that is suppose to have animations and place it in the world. 
* **Mod/s Affected**: 
Chisel
* **Known Fix**:

**Comment by Sunekaer** [comment]
Disable "Texture optimizations" in VanillaFix so fix that for you
