### ISSUE TITLE
Silicon Can't Be MADE

### ISSUE THREAD

**Issue by Mini-kun** [FTBTeam/FTB-Presents-Stoneblock-2#28]
* **Modpack Version**: 1.0.0

* **Issue**: Silicon creating

* **Link to Log or Crash File Paste**: it's not a Crash of a Log thing

* **Is it Repeatable?**: Nop 

* **Mod/s Affected**: All of Crusher Mods

* **Known Fix**: Make it Soo that Silicon can be made out of Sand or Dust to make it work.

![2019-01-05_19 13 54](https://user-images.githubusercontent.com/46404340/50727650-1f1a0200-111e-11e9-9b5e-6f02b6dd9fed.png)

**Comment by ArbitraryHubris** [comment]
I understand that you want to use the crusher - just want you to be aware that you can get silicon by putting clay blocks in the sag mill.  It gives you generous amounts of silicon and clay back

**Comment by Mini-kun** [comment]
It's still a nice way to get it from Cobble-Grave-dirt-sand-dust

**Comment by RetekJorr** [comment]
If you do this a "usual" way, then there's no way to automate sand to dust.  

My solution was to get it by smelting crushed certus and then I made a seed for mystical agriculture.  I believe there are also silicon chickens

**Comment by Mini-kun** [comment]
What about people how don't have Any of them yet?
That why i like that Dust to be making Silicon

**Comment by Sunekaer** [comment]
1.1.0
