### ISSUE TITLE
Crucible unable to craft

### ISSUE THREAD

**Issue by archmon** [FTBTeam/FTB-Presents-Stoneblock-2#280]
* **Modpack Version**: 1.3.0 And 1.4.0

* **Issue**: Unable to craft in Crucible (Thaumcraft). Not sure what's causing it, tested thaumcraft alone (instance with only thaumcraft in it), the crafting works, tested in MP and SP and when you go to throw the final item in, it instead is turned into essentia.  Tried this with several recipes and same result.  It doesn't matter what recipe it is, all 3 I've tried are completely broken (Yellow Nitor, Magic Tallow, Alchemical Brass).  

* **Link to Log or Crash File Paste**: No log and no crash

* **Is it Repeatable?**: Yes, both me and my friend tried crafting and same result.

* **Mod/s Affected**: Thaumcraft

* **Video Evidence**: https://youtu.be/9wxNqY_Mg44 

* **Known Fix**: Unknown

**Comment by Sunekaer** [comment]
try right clicking the glowstone on it after dropping the other stuff

**Comment by archmon** [comment]
Looks like that works, I don't know why, but thx.  Might want to drop a note in the achievement book about it.
