### ISSUE TITLE
TickNextTick list out of synch

### ISSUE THREAD

**Issue by zCodeg** [FTBTeam/FTB-Presents-Stoneblock-2#281]
* **Modpack Version**: 1.3.0

* **Issue**:
 Server crashes with error " TickNextTick list out of synch ". 
In 1.2.0 was crashing randomly after hours of running.
In 1.3.0  - server starts, stays online for ~20 seconds and then crashes

Tried enabling removeErroringEntities and removeErroringTileEntities in forge config - no luck

* **Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/8d087d89
https://paste.feed-the-beast.com/view/dba2bfd7 (and same crash without any extra mods we use)
* **Is it Repeatable?**: 
yes

* **Mod/s Affected**: Unknown

* **Known Fix**: Unknown

**Comment by Sunekaer** [comment]
Hmm im not sure whats causing this crash, is there a lot of Watch of flowing time or others like it?

**Comment by zCodeg** [comment]
There are no watches in the world (we don't let players use it), but might be a lot of Imaginary Time blocks.

**Comment by Sunekaer** [comment]
maybe try removing those, i have no clue whats causing your issue
