### ISSUE TITLE
Faithful Modded Resource Pack not working

### ISSUE THREAD

**Issue by AsianBurritos** [FTBTeam/FTB-Presents-Stoneblock-2#282]
* **Modpack Version**: 1.3.0

* **Issue**: I was playing FTB Stoneblock 2 and wanted to use a texture pack I liked which was Faithful x32 modded. I downloaded the texture pack and keep in mind that it was designed to go with mods and I have used it before with other FTB modpacks but this modpack, Stoneblock 2, didn't apply the texture pack at all in the game when I loaded and applied it in the Resource Pack section. I have looked online for fixes but here I am now, reporting the apparent bug. Please help

* **Is it Repeatable?**: I uninstalled FTB Stoneblock 2 when it first happened out of boredom and never touched it until yesterday where I was going to play with friends and loaded in the modded texturepack but it then again, didn't work

**Comment by Sunekaer** [comment]
I just tested, works fine for me, remember some mods isnt in the texture pack

**Comment by AsianBurritos** [comment]
I found out that some mod is interfering with the texture pack so all vanilla textures from the game aren't changing but the modded ones are.

**Comment by AsianBurritos** [comment]
Im trying to look for that mod and hoping that its client side

**Comment by TheEssemCraft** [comment]
Having this same problem, the textures of some blocks/items are loaded (mostly modded textures), but not all of them. As you can see in this screenshot, the torch, hammer, cobblestone chest, and Draconic chest are textured properly, but everything else isn't.
![image](https://user-images.githubusercontent.com/21112968/52307964-b5318a00-2961-11e9-8da8-8b6157d8081f.png)

**Comment by TheEssemCraft** [comment]
Found a fix, you can download the vanilla Faithful pack as well as F32 and apply them both, with the vanilla pack loaded under the modded pack. This will apply the vanilla textures as well as the modded textures, just as intended.
