### ISSUE TITLE
Flat item node error

### ISSUE THREAD

**Issue by Pactastic** [FTBTeam/FTB-Presents-Stoneblock-2#283]
Didn't break my game or anything, just got an error and it recommended reporting it

* **Modpack Version**: 1.3.0

* **Issue**: got an error after placing a flat item node on right side of an ender chest

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/06e81a37

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Extra Utilities 2 1.9.8, Ender Storage 2.4.5

**Comment by Sunekaer** [comment]
#31
