### ISSUE TITLE
Extra utilities generators freezes my game

### ISSUE THREAD

**Issue by MekaSenpai** [FTBTeam/FTB-Presents-Stoneblock-2#284]
I created some Extra Utilities generators and it works, but when i want to Shift + RClick for fill up the content on the generator, minecraft freezes and stops working.

* **Modpack Version**: 1.4.0
* **Issue**: Extra utilities generators freezes my game

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes, just make a slimey generator and put like 32 slimeballs, then Shift+Rclick in your inventory more slimeballs to fill the generator up, then freezes.

* **Mod/s Affected**: Extra Utilities 2

* **Known Fix**: 

![image](https://user-images.githubusercontent.com/43832349/52166427-625f9480-270d-11e9-976d-a55bec26c1b1.png)

**Comment by Sunekaer** [comment]
#31
