### ISSUE TITLE
Personal EMC Link Issues

### ISSUE THREAD

**Issue by UldisAlksnis** [FTBTeam/FTB-Presents-Stoneblock-2#286]
**Modpack Version**: 1.4.0

* **Issue**: Automating EMC production adding ALOT of items into Personal EMC Link causes EMC to break. Basically I am importing around 200 dragon eggs a second and it just cant keep up and EMC stays the same(so the dragon eggs imported are lost) + while its importing all of it into EMC Link, You cannot take out items using Tablet, Either it places them back or Takes the EMC for the item taken out and removes the item itself. This issue fixes after removing the Personal EMC Link
(only using 1 import on EMC Link tried item conduits and me exports)

EDIT: Also while its importing, EMC values "jump" - raise and go back to old value constantly is what i meant by EMC staying the same as it was before.
And same flickering as Indalor1 has mentioned.
* **Link to Log or Crash File Paste**: none

* **Is it Repeatable?**: Yeah

* **Mod/s Affected**: Project E, Project EX

**Comment by Indalor1** [comment]
When adding a large amount of EMC constantly to more than 1 EMC Link the numbers get all wonky. They flicker up and down randomly so there is no way to tell if the EMC being added except by taking items out of a table or tablet. This includes not just the amount of EMC in the system but also the amount per second as well.

Indalor1

Also the numbers are flickering in the tables and Tables as well.
