### ISSUE TITLE
Tinkers Construct smeltery empty after relogging

### ISSUE THREAD

**Issue by roudybeest** [FTBTeam/FTB-Presents-Stoneblock-2#287]
* **Modpack Version**: 1.4.0
* **Issue**: Tinkers smeltery. Last time i logged in i filled the tinkers smeltery with ores and Lava, i saved and quit to title. A few days later (today) i opened up the gamesave only to see my tinkers smeltery completely empty and my casts gone as well. 

* **Link to Log or Crash File Paste**: game didnt crash

* **Is it Repeatable?**: Yes, smelt something in your tinkers construct smeltery, or put some lava in it, save and quit to the title and reopen the gamesave.

* **Mod/s Affected**: Tinkers Construct (?)

* **Known Fix**: --

**Comment by Sunekaer** [comment]
I was not able to recreate this issue, does this happen to you each time? any error in logs?

**Comment by roudybeest** [comment]
> I was not able to recreate this issue, does this happen to you each time? any error in logs?

I have not been able to recreate this after i restarted my pc. I restarted it since i updated some programs that required a restart. Once i logged back into my world, my smeltery still had the remaining lava inside
