### ISSUE TITLE
Cannot Fly Using Angel Ring or Dragon Armor on Server

### ISSUE THREAD

**Issue by Captoblitz** [FTBTeam/FTB-Presents-Stoneblock-2#288]
* **Modpack Version**: 1.4.0

* **Issue**: I am running Stoneblock 2 on a server that my friend and I are playing on. I have tried to fly using a full set of dragon armor and an angel ring but neither works. I have allow-flight set to true in the server properties and I have checked both the non-existent Tiny-Progressions config file, the Morph config file, and the Extra Utilities 2 config file and to no avail have I found anything that seems to be out of place. I have tried using a full set of dragon armor in singleplayer and it works fine but the angel ring from AngelRing 2 or Extra Utilities 2 also does not work in singleplayer for me. I am not sure if I am not using it correctly but I have tried different ways of using the angel ring and I still was not able to fly. I am not sure of any other ways to fly but the ones I have tried are not working for some reason on my server.

* **Link to Log or Crash File Paste**: The game did not crash, the issue is flying in-game.

* **Is it Repeatable?**: Yes, flying is not working on my server.

* **Mod/s Affected**: I am not sure what mods are affecting this other than the ones I have listed above.

* **Known Fix**: I do not know of a known fix to this issue.

**Comment by Sunekaer** [comment]
Dragon armor and angel ring doesnt work together
https://github.com/Kashdeya/Tiny-Progressions/issues/112
