### ISSUE TITLE
Half of the world not saved

### ISSUE THREAD

**Issue by knightofdemons** [FTBTeam/FTB-Presents-Stoneblock-2#290]
* **Modpack Version**: 1.4.0

* **Issue**:
Set up server yesterday, maybe played 6 hours, relogged after sleeping and half of our cave is just solid smoothstone again, like nothing happened.
The worldfile didnt even save the progress due to I was relogging multiple times but the world was okay until I took a break to sleep. So I guess while the chunks were still in RAM, everything was fine. Once everyone logged off, the chunks got unloaded and saved to disk. While relogging and reloading the chunks, either something happened and just defaulted to smooth stone for a few chunks or it just didnt wirte the world that was in RAM onto the disk.
I dont know how that happened - it pretty much looks like an inconsistancy between world in RAM and world on disk.

* **Link to Log or Crash File Paste**:
no crashfile - worldfile: https://drive.google.com/file/d/10p5QMrrTnJxpQ8nAoXA1DYpz6VzEjFP6/
(Use MC Edit and go to the players perspective - both are spawned in a wall, next to the remainings of our cave
Complete log of our session - server was not restarted until I logged on this morning: https://drive.google.com/file/d/1R5aOCuq81m-i5MTgneSPL-msY8tu60_e/

* **Is it Repeatable?**: Not gonna play 8 hours again to respawn in solid blocks

* **Mod/s Affected**: Worldgen

* **Known Fix**:

**Comment by iKurama** [comment]
You made this issue a few days ago, why make a new one?

**Comment by knightofdemons** [comment]
???
First time here, i did not make an issue before?!?
Also I couldnt find anything related in the current issue list, so I opened a new one to describe the problem.

**Comment by boosterdev** [comment]
#42

**Comment by knightofdemons** [comment]
So you are telling me that this problem is know for a month, 3-4 versions ago, could be pinpointed and did not have been fixed or circumvented by offsetting the spawn? Lol
Thanks for the 8 lost hours. Some people need a high five....with a chair...in their face. really.

**Comment by boosterdev** [comment]
Lost 8 hours? wow really. Every night I loose 8 hours, just because I want to sleep.
minecraft is just some game, some people have bugs while other don't have, some problems are therefore harder to fix, I run stoneblock since 1.0.0, and upgraded it till now 1.4.0, and I have not encountered a problem yet. maybe a random crash but nothing serious.

**Comment by knightofdemons** [comment]
Listen...i'm not going in on a rethorical dumb argument like that.
I'm here, spending my free time to report a bug (and vent about inaproperiate patch behaviour).
Yeah maybe you run fine and my server not, that should be an obvious thing. Maybe you are not even using some mods in your world (like craft that stuff) - so yeah its different.
That doesnt change anything on my problem.
What iam saying is, is that you can bring up a warning message or something, if you know the problem but just a workaround. Instead I was happy to play, got disappointed and now I see whats going on on this github...sad but at least you could rely on the "stable" pack with MC modpacks until now

**Comment by Sunekaer** [comment]
#42

**Comment by ThuGie** [comment]
Sunekaer, wouldn't it have been better to reference this to #42,
As #42 contains quite more detail then this one ?
