### ISSUE TITLE
Can't get the eula.txt file to show up when creating a server

### ISSUE THREAD

**Issue by Atomic-Ninja** [FTBTeam/FTB-Presents-Stoneblock-2#291]
* **Modpack Version**: Not an issue with the modpack, Issue with setting up server with the latest files

* **Issue**: When I download the latest server files for SB2, I start the server using the "StartServer.bat" it just says that the "eula.txt" file must be agreed to and that it will create it. There is no trace of the file anywhere on my computer.

* **Link to Log or Crash File Paste**: Server Log: https://pastebin.com/K2X5z2Ra

* **Is it Repeatable?**: Yes, the issue occurs every time I open the "StartServer.bat" file.

* **Mod/s Affected**: No added mods.

**Comment by UldisAlksnis** [comment]
Thats definitely to do with java environment on your machine not modpack related.

Check this out maybe it helps:
https://stackoverflow.com/questions/18040361/java-could-not-reserve-enough-space-for-object-heap-error

As it crashes before being even able to generate the file

Also system specs/java build post would help

**Comment by Atomic-Ninja** [comment]
How would I find the java build?
Also, should I allocate more ram to the server start file?
