### ISSUE TITLE
Payload may not be larger than 32767 bytes

### ISSUE THREAD

**Issue by jamescheats** [FTBTeam/FTB-Presents-Stoneblock-2#292]
* **Modpack Version**:  
1.2.0

* **Issue**: 
I am just wondering does anyone know how I can get my storage bag out of my Me terminal I've tried pipes, export bus and item pipes and nothing seems to work. I have put my drives in my bag and I shift-clicked my bag into the terminal and every time I try to take it out I have an error that says: payload may not be larger than 32767 bytes. Anyone Help

* **Link to Log or Crash File Paste**: 
The issue does not make me crash it kicks me off the server

* **Is it Repeatable?**: 
Yes
* **Mod/s Affected**: 
Applied Energistics and cyclic
* **Known Fix**:

**Comment by zCodeg** [comment]
Export bus with fuzzy card should help you

**Comment by jamescheats** [comment]
Ok I will  try now thank you

**Comment by jamescheats** [comment]
I have just now tried and it is not pulling anything out of the computer

**Comment by jamescheats** [comment]
I've done it thank you so much
