### ISSUE TITLE
Crash: Exception in server tick loop - at uk.gaz492.framland.event.FramlandEventHandler.onServerTick(FramlandEventHandler.java:34)

### ISSUE THREAD

**Issue by crez** [FTBTeam/FTB-Presents-Stoneblock-2#293]
- **Modpack Version:** 1.3.0
- **Problem:** Crash: Exception in server tick loop
- **Is it Repeatable?:** Happens every so often - I cannot seem replicate it on purpose.
- **Mod/s Affected:** Seems to be related to Framland mod - but i barely started my playthrough.
- **Known Fix:** No.

**Pastebin:** https://paste.dimdev.org/kuruwoyego.mccrash

**Comment by iKurama** [comment]
Remove the mods you've added yourself, then try to repeat.
Tiquality is messing with the tickrate, so that might be your issue.

**Comment by crez** [comment]
It's default stoneblock 2 from the FTBlauncher.

**Comment by Sunekaer** [comment]
update to 1.4.0
