### ISSUE TITLE
Avanced Thermal Expansion machnines are missing

### ISSUE THREAD

**Issue by TheLogan** [FTBTeam/FTB-Presents-Stoneblock-2#294]
* **Modpack Version**: 1.4.0

* **Issue**:
The recipes for anything but the most basic thermal expansion machines seem to be missing, yet the recipes for the augments etc are still in place, so I'm guessing this is a bug?

**Comment by boosterdev** [comment]
you can upgrade machines with upgrade kits, then augments can be installed

**Comment by Sunekaer** [comment]
Answered by boosterdev
