### ISSUE TITLE
gravel and compressed gravel give same results

### ISSUE THREAD

**Issue by freopt** [FTBTeam/FTB-Presents-Stoneblock-2#295]
* **Modpack Version**: 
1.3.0

* **Issue**: 
The stuff you get from one gravel is the same you get from compressed gravel according to jei with the according meshes.

**Comment by boosterdev** [comment]
True but with compressed gravel this is 9 times more per item, compressed, uncompressed, same drop rate only 9 times into 1.

**Comment by Sunekaer** [comment]
When you hover of the item youll see "Drop Chance 1x 6%" for copper ore in normal sieve with string mesh with compressed youll see  "Drop Chance 7x 6%"
