### ISSUE TITLE
Quantum Flux magnet Dupe in 1.3.0

### ISSUE THREAD

**Issue by Column01** [FTBTeam/FTB-Presents-Stoneblock-2#297]
This is very much still an issue in version 1.3.0 of the modpack. They can be obtained by Item rewards via the questbook.

[![Video](http://img.youtube.com/vi/pCiMXrdg6CE/0.jpg)](http://www.youtube.com/watch?v=pCiMXrdg6CE "Video")

_Originally posted by @Column01 in https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/issues/24#issuecomment-459996855_

**Comment by Sunekaer** [comment]
Again it’s fixed, then item is removed from the quest loot, and you can’t craft it, if your still receiving it from quest you haven’t updated your quest file on the server, if your still using the item even tho it says disabled don’t report issues
