### ISSUE TITLE
Can't get primordial pearls

### ISSUE THREAD

**Issue by boris11221** [FTBTeam/FTB-Presents-Stoneblock-2#298]
Modpack Version -- The latest one

Issue -- Flux rifts are disabled, so there is no way to get primordial pearls

Is it Repeatable? -- Yes

Mod's Affected -- Thaumcraft 6

**Comment by iKurama** [comment]
Endgame of ProjectE.

**Comment by Sunekaer** [comment]
Right now "Endgame ProjectE", im open for adding a recipe for them, but im not sure what the recipe should be

**Comment by iKurama** [comment]
When doing thaumcraft semi-last, you'd already have the tome of knowledge which is too cheap.
