### ISSUE TITLE
Mod suggestion 

### ISSUE THREAD

**Issue by nightshard** [FTBTeam/FTB-Presents-Stoneblock-2#3]
The original SB was great, it was just missing 2 mods to make it greater, Akashic Tome and Nuclearcraft.

Now is your chance of making it better.

**Comment by Sunekaer** [comment]
Nuclearcraft won't be added, ill have a look at Akashic Tome before ill say anything about that one

**Comment by OldManCraft** [comment]
Is, or are there issues with Nuclearcraft ? If a user was to add the mod for them to play with late game ?

**Comment by Sunekaer** [comment]
Ill add Akashic Tome

**Comment by Sunekaer** [comment]
@OldManCraft Yes you can add it yourself

**Comment by lazycooken** [comment]
I think adding Practical Logistics would make a nice little addition to the mudpack.

**Comment by Sunekaer** [comment]
Practical Logistics won't be added, as we had multiple issue with the mod under testing

**Comment by M3wM3w** [comment]
Akashic tome is neat, but putting your books on fancy bookshelves is even more neat.

**Comment by Sunekaer** [comment]
1.1.0
