### ISSUE TITLE
Thaumcraft workbench Not able to be made

### ISSUE THREAD

**Issue by DeadAssassin96** [FTBTeam/FTB-Presents-Stoneblock-2#30]
* **Modpack Version**: 1.0.1

* **Issue**: When i go to place salsi mundus on a crafting table it dosent make a arcane workbench like the quest says it needs to be

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Thaumcraft

* **Known Fix**: none

**Comment by Sunekaer** [comment]
You just need to right-click the crafting table

**Comment by Sunekaer** [comment]
You also need to open the Thaumonomicon and click on the steps to gain the knowledge to do it
