### ISSUE TITLE
Translocators broken by Forge Multipart CBE

### ISSUE THREAD

**Issue by Dournbrood** [FTBTeam/FTB-Presents-Stoneblock-2#300]
* **Modpack Version**: 1.3.0
* **Issue**: I've got a translocator connected from a crate set to input into a drawer controller. This works fine on any other pack, and i've got some suspicions that Forge Multipart CBE has something to do with this not working.

* **Link to Log or Crash File Paste**: Not relevant for this issue; Generates no log.

* **Is it Repeatable?**: Yes, it's a constant problem. Just get a mob farm going for yourself, and hook some translocators up to feed into a drawer controller. After a while, it just stops working even though the drawers are far from full.

* **Mod/s Affected**: Forge Multipart CBE / Translocators

**Comment by Sunekaer** [comment]
Its because the translocator thinks the drawers is full, the dev needs to allow the locators to "overfill" the drawers
Please create a issue about it here https://github.com/TheCBProject/Translocators/issues
