### ISSUE TITLE
can not enter mining world

### ISSUE THREAD

**Issue by itsdgaming** [FTBTeam/FTB-Presents-Stoneblock-2#301]
* **Modpack Version**: 1.4.0
* **Issue**: i want to go to the mining wold but the bedrock dont teleport me 
* **Link to Log or Crash File Paste**: no crash 
here you have some pics ( inventory + cords for bedrock) and a clip 
[cords](https://prnt.sc/mhjzke)
[inventory](https://prnt.sc/mhk06n)
[clip](https://clips.twitch.tv/SuaveBenevolentCardKeyboardCat)

**Comment by Sunekaer** [comment]
Server, single player?
still a issue? i cant recreate this issue

**Comment by itsdgaming** [comment]
Singleplayer 
The thing is a want to go do a wither in the mining becouse i dont want to destroy my base and i cant enter the mining world i played the next day still got the problem maybe the mining world is broken but dont know what world id it is

**Comment by sephermoor** [comment]
hello
I am also having this problem. single player server. I have tied opening up to a LAN and restarting the game. no change. my inventory is different then itsgaming. Is there a way to pull a log without a crash?

**Comment by P4t0r1kku** [comment]
did you dig up to levl 255 or down to 0 ?, becouse Mining World is at 255, And Going Up in the Mining World brings you to the End. p.s. i broke the Bedrock with my World Breaker pickaxe, closed the Hole with some Obsidian 😏

**Comment by itsdgaming** [comment]
Yes i digged up you can see my cords on the pic and in the clip i even tryed to go to another chunk becouse maybe the chunk was glitch and it still didnt work

**Comment by itsdgaming** [comment]
i just start a new world same problem i broke the bedrock thene i teleport to the mining dim maybe becouse of the hight level is 253 becouse on 254 is the bedrock

**Comment by Sunekaer** [comment]
log file? Is there any érrors in console?

**Comment by samPi0314** [comment]
I had the same issue, Just change overtomining from 254 to 253 in the stoneBlock Dimensions in mod options or the config folder.
