### ISSUE TITLE
This just popped up as a notification about potential corruption to my world

### ISSUE THREAD

**Issue by xFlizz** [FTBTeam/FTB-Presents-Stoneblock-2#302]
https://paste.dimdev.org/panacawupe.mccrash

**Comment by iKurama** [comment]
Modpack version?

**Comment by xFlizz** [comment]
1.3.0

**Comment by Sunekaer** [comment]
You should be fine, but please report the issue on here: https://github.com/BuildCraft/BuildCraft/issues so they can fix it
