### ISSUE TITLE
thaumcraft crash

### ISSUE THREAD

**Issue by glognes** [FTBTeam/FTB-Presents-Stoneblock-2#304]
the thaumcraft crash after a game time, here is the crash link.

https://paste.dimdev.org/unuhihejic.mccrash

**Comment by RelicFades** [comment]
Hey, I'm getting this exact same error too on my home server. I'm playing on Stoneblock 2 version 1.2.0.

**Comment by triffman33** [comment]
Looks to be a Thaumcraft entity thats crashing you and the current version of stoneblock 2 is 1.4.0 which fixes quite a few issues.

**Comment by Sunekaer** [comment]
#111
