### ISSUE TITLE
crash report ingame issue

### ISSUE THREAD

**Issue by Entropy308** [FTBTeam/FTB-Presents-Stoneblock-2#305]
* **Modpack Version**: 1.4.0

* **Issue**:  crafting magmatic generator extra utilities 2 item 

* **Link to Log or Crash File Paste**:  https://paste.feed-the-beast.com/view/5ac9665f 

* **Is it Repeatable?**: 

* **Mod/s Affected**:  extra utilities 2 and jei. might have said another but my short term memory forgot it already with all the effort required to set up this feedback 

* **Known Fix**:

**Comment by Sunekaer** [comment]
I cant recreate this issue, can you recreate this issue in Single Player? as we dont support sponge and the server your playing on runs sponge

**Comment by Entropy308** [comment]
it hasn’t happened again.
