### ISSUE TITLE
EnderIO Memory Leak

### ISSUE THREAD

**Issue by MaxDistructo** [FTBTeam/FTB-Presents-Stoneblock-2#306]
* **Modpack Version**: Believe All (Know for 1.2.0+)

* **Issue**: Current versions of EnderIO have a memory leak resulting in about 0.5GB of extra ram usage that is fixed in the current version. See SleepyTrousers/EnderIO#4990

* **Mod/s Affected**: EnderIO 5.0.39, EnderCore 0.5.43

* **Known Fix**: SleepyTrousers/EnderIO#4990, Update EnderIO and EnderCore to latest release versions. (5.0.40 & 0.5.45 respectively)

(If above issue reference doesn't work, https://github.com/SleepyTrousers/EnderIO/issues/4990)

**Comment by Sunekaer** [comment]
https://www.feed-the-beast.com/projects/ftb-presents-stoneblock-2/files/2673992
