### ISSUE TITLE
Crafting recipe conflict wands and spears

### ISSUE THREAD

**Issue by haruofwater** [FTBTeam/FTB-Presents-Stoneblock-2#308]
* **Modpack Version**: 1.4.0
* **Issue**: recipe conflict with better builders wands and Tiny Progressions Spears, crafting a Diamond or Iron Spear gives Better builders wand as output even though Jei shows different recipe.

* **Is it Repeatable?**: 

* **Mod/s Affected**: Tiny Progressions, Better Builders Wands

**Comment by triffman33** [comment]
Would probably just need to remove and re-add the builders wand recipies as non-mirrored

**Comment by Sunekaer** [comment]
https://www.feed-the-beast.com/projects/ftb-presents-stoneblock-2/files/2673992
