### ISSUE TITLE
Server won't start due to Missing minecraft entities

### ISSUE THREAD

**Issue by Captoblitz** [FTBTeam/FTB-Presents-Stoneblock-2#309]
* **Modpack Version**: 1.5.0

* **Issue**: Whenever I try to start my server it goes through the regular starting sequence and then gets stopped by this error. This is the first time I have tried starting the server on 1.5.0. I have tried running the command that is said in the console to alternatively start the server but it does not work and just leaves the server in an on but not connectable state. On the server list in-game, the server is Old / Vanilla.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/39d27c73

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: I am not sure what mod's are affecting this.

* **Known Fix**: I do not know of any known fix.

**Comment by Sunekaer** [comment]
write "/fml confirm" in the console

**Comment by Captoblitz** [comment]
> write "/fml confirm" in the console

Writing /fml confirm did nothing in the console. When I normally type /fml confirm it normally continues the server start-up sequence.
