### ISSUE TITLE
Extra util freezes / crashes game

### ISSUE THREAD

**Issue by Wolftwitch** [FTBTeam/FTB-Presents-Stoneblock-2#31]
* **Modpack Version**: 1.0.1

* **Issue**:  I wanted to automate sieving of compressed end stone with a heavy sieve and mechanical user, but when I try placing compressed end stone into the mechanical user, by shift clicking the compressed end stone from my inventory into the mechanical user or by placing one stack at a time while dragging it from inventory, I keep freezing and the program goes unresponsive and soon I decide to close Minecraft and the crash log pops up.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/b3eef6b9

* **Is it Repeatable?**: I have repeated this issue around 10 times between yesterday and today.

* **Mod/s Affected**: 
* **Known Fix**:

**Comment by Sunekaer** [comment]
https://github.com/rwtema/Extra-Utilities-2-Source/issues/226

**Comment by ClaudiusMinimus** [comment]
This issue applies to all Extra Utilities machines, please see my issue report at https://github.com/rwtema/Extra-Utilities-2-Source/issues/254
