### ISSUE TITLE
Inconsistent mod versions between server and client

### ISSUE THREAD

**Issue by knightofdemons** [FTBTeam/FTB-Presents-Stoneblock-2#310]
* **Modpack Version**: FTBPresentsStoneblock2-1.4.0-1.12.2

* **Issue**: Clientfiles are newer than server files

* **Link to Log or Crash File Paste**: 
Client-Source: Twitch-Launcher
Server-Source: https://www.feed-the-beast.com/projects/ftb-presents-stoneblock-2/files/2666956

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: 
Server(-Update) has only ExtraCells.jar in mods-folder

[18:04:51] [Netty Server IO #5/ERROR] [FML]: Network Disconnect: Server Mod rejections:
Bookshelf: Requires version 2.3.569 but client has 2.3.573.
Clumps: Requires version 3.1.1 but client has 3.1.2.
Dark Utilities: Requires version 1.8.219 but client has 1.8.223.
Fluid Cows: Requires version 1.1.14 but client has 1.1.15.
Framland: Requires version 1.12.2-1.0.6.8 but client has 1.12.2-1.0.7.11.
Mod Tweaker: Requires version 4.0.15 but client has 4.0.16.
Project EX: Requires version 1.0.0.3 but client has 1.0.0.6.
StoneBlockUtilities: Requires version 2.1.3 but client has 2.1.4.
YABBA: Requires version 1.1.2.35 but client has 1.1.2.39.

* **Known Fix**: Update server manually

**Comment by triffman33** [comment]
Worked fine for me, all the mods are in there.

**Comment by knightofdemons** [comment]
Issue is fixed checked the file again, now its fine.
