### ISSUE TITLE
Issue with cloned vis crystal

### ISSUE THREAD

**Issue by BazGoldenclaw** [FTBTeam/FTB-Presents-Stoneblock-2#312]
* **Modpack Version**: Stoneblock 2 v1.5.0

* **Issue**: Cloned an Aer Vis Crystal using Project E's Energy Condenser, which resulted in a %Vis Crystal with no attribute.  Tried to put it into an ME Crafting Terminal to craft Arcane Blocks when game crashed.

* **Link to Log or Crash File Paste**: https://paste.dimdev.org/vuwitawiwi.mccrash

* **Is it Repeatable?**: yes

**Comment by Sunekaer** [comment]
Please report issue here: https://minecraft.curseforge.com/projects/mouse-tweaks?gameCategorySlug=mc-mods&projectID=60089
