### ISSUE TITLE
The game crashed whilst exception in server tick loop (part 2)

### ISSUE THREAD

**Issue by nr1craft** [FTBTeam/FTB-Presents-Stoneblock-2#313]
* **Modpack Version**: it started in 1.2.0 and i updated to 1.5.0 an

* **Issue**: The game crashed whilst exception in server tick loop 

* **Link to Log or Crash File Paste**: https://paste.dimdev.org/zacexapaxe.mccrash

* **Is it Repeatable?**: every time i want to join my world it happens

* **Mod/s Affected**: minetogether and minetogetherserver

* **Known Fix**: none

* **extra note**: i have the same problem with it when i play sky adventures

**Comment by Goofy23** [comment]
I had to remove minetogether and it worked

**Comment by Sunekaer** [comment]
Please report it here https://github.com/CreeperHost/CreeperHostGui/issues so they can help you find a solution
