### ISSUE TITLE
player arms start flailing, and i cant move without the camera getting messed up

### ISSUE THREAD

**Issue by KyranStorm** [FTBTeam/FTB-Presents-Stoneblock-2#314]
https://drive.google.com/open?id=1zYQKta0oq2EycMMWfaAbGDt7rz_KgmOH

heres the video i took of it.  the game also kept freezing every few seconds.  this happens whenever i make a new savegame.  i was able to play before, but now i cant cause of this bug.

**Comment by KyranStorm** [comment]
how to fix: i had to reinstall the whole pack and it works fine now. but it may start doing it again

**Comment by Sunekaer** [comment]
often because you messed with BetterFPS settings
