### ISSUE TITLE
Unable to access RFLux block

### ISSUE THREAD

**Issue by Vecmor** [FTBTeam/FTB-Presents-Stoneblock-2#315]
Stoneblock 2 - 1.3.0

Once placed, you are unable to access the RFLux light block to change it's settings.

https://paste.dimdev.org/aboxulerit.mccrash

Steps to repeat:

Place Light block and attempt to open it's interface.

**Comment by Sunekaer** [comment]
https://github.com/romelo333/rflux/issues/3

**Comment by Sunekaer** [comment]
Closing this issue, as there´s nothing we can do about this other then wait and see if the mod dev fixes it
