### ISSUE TITLE
failed load minecraft

### ISSUE THREAD

**Issue by Niicolaxx** [FTBTeam/FTB-Presents-Stoneblock-2#316]
https://paste.dimdev.org/anorobakil.mccrash

**Comment by Kratzwurst** [comment]
Is that all of your Ram on your Computer?
Memory: 1086303192 bytes (1035 MB) / 4068999168 bytes (3880 MB) up to **7635730432 bytes (7282 MB)**

And Update your Java x64 

Your Version is: 1.8.0_51, Oracle Corporation
New Version: 1.8.0_201-b09

DL: https://javadl.oracle.com/webapps/download/AutoDL?BundleId=236888_42970487e3af4f5aa5bca3f542482c60

And deinstall all old Java Versions from your Computer before you install the newest Version.

**Comment by Sunekaer** [comment]
answered by Kratzwurst
