### ISSUE TITLE
Morph Crash on server

### ISSUE THREAD

**Issue by TheAgamer554** [FTBTeam/FTB-Presents-Stoneblock-2#318]
* **Modpack Version**: 
1.3.0
* **Issue**: 
I was morphing in my server and i got kicked out and i cant enter now because of this same issue
* **Link to Log or Crash File Paste**: 
https://paste.dimdev.org/ocalepowod.mccrash
* **Is it Repeatable?**: 
Yes, it happens every time i try to enter
* **Mod/s Affected**: 
Morph
* **Known Fix**: 
I think i can edit the files inside of the data folder to edit it, particularly the morph save file

**Comment by TheAgamer554** [comment]
Update: it gives me on a local world that otherwise it worked usually: https://paste.dimdev.org/erelimiyak.mccrash

**Comment by Sunekaer** [comment]
update your pack, this is fixed
