### ISSUE TITLE
ME Fluid Terminal GUI flawed

### ISSUE THREAD

**Issue by PiDabbelju** [FTBTeam/FTB-Presents-Stoneblock-2#319]
* **Modpack Version**: 1.5.0

* **Issue**: ME Fluid Terminal GUI seems to be bugged

* **Link to Log or Crash File Paste**: No crash occured.

* **Is it Repeatable?**: Yes, restart of the game and rebuilding the terminal anywhere else did not fix the issue

* **Mod/s Affected**: Applied Energistics 2

* **Known Fix**: -

The ME Fluid Terminal GUI is missing any possibility to insert fluid containers. Fluids stored in the ME system can also not be selected. My Minecraft installation is as "clean" as it can be when starting Stone Block 2 via Twitch Launcher. Faithful Ressource Pack is installed (also via Twitch Launcher), but disabling it does not fix the issue.

This is how the GUI looks like:
![stoneblock_bug](https://user-images.githubusercontent.com/47504963/52539374-c8878f80-2d7d-11e9-8e96-e0f97b9082d3.PNG)

Either fixing the bug or telling me, why the GUI looks other than in any YT video or screen shot will be very much appreciated. :)

**Comment by Sunekaer** [comment]
please report it here with log https://github.com/AppliedEnergistics/Applied-Energistics-2/issues as i cant do anything about that
