### ISSUE TITLE
Mod Suggestion l Add Tinkers IO for liquid.

### ISSUE THREAD

**Issue by Rokutiz** [FTBTeam/FTB-Presents-Stoneblock-2#32]
Add Tinkers IO for liquid cow liquids. So we can make liquids into ingots easier.
Smart IO is faster and requires way less space.

**Comment by M3wM3w** [comment]
How is that an "Issue" ...

**Comment by Rokutiz** [comment]
Well not an issue. More like mod suggestion then

**Comment by Sunekaer** [comment]
Tinker IO wont be added to the pack, your free to added it your SP play trough
