### ISSUE TITLE
What happened to the rest of the walls?

### ISSUE THREAD

**Issue by Sorbe** [FTBTeam/FTB-Presents-Stoneblock-2#320]
Stoneblock 2 - 1.5.0

There are very few "walls" in this pack.  For example, there is no "smooth stone" or "sugar cane" wall blocks at all.    Just do a JEI search for "wall" and you'll find far fewer than most other modpacks.

Were these intentionally removed or should they have actually been included?

**Comment by Sunekaer** [comment]
no walls was removed in this pack
