### ISSUE TITLE
Game stuck on Phase 2 EnderIO

### ISSUE THREAD

**Issue by Gyunbie** [FTBTeam/FTB-Presents-Stoneblock-2#321]
* **Modpack Version**: Tried all versions.

* **Issue**: When I try to start the game, it goes well until Phase 2. When Phase 2 EnderIO mod comes, my client gets stuck. I have waited around an hour and it just doesn't start. I tried all versions of Stoneblock 2, tried to update Forge, tried to update Java 8 to last version. It just doesnt start.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/84b1aefe

* **Is it Repeatable?**: Yes, always.

EDIT: Fixed after countless tries. I really dont know what fixed it.

**Comment by HenryLoenwind** [comment]
FYI: At that point in the loading process codechicken is accessing the network. Ender IO is done (after that 6th update) and won't do anything until jei, AE2, draconicevolution, packcrashinfo and ModIdentifier have been initialized.

**Comment by Gyunbie** [comment]
> FYI: At that point in the loading process codechicken is accessing the network. Ender IO is done (after that 6th update) and won't do anything until jei, AE2, draconicevolution, packcrashinfo and ModIdentifier have been initialized.

I said EnderIO because it was stuck on there. So it passes EnderIO but I just cant find why it doesnt start.
