### ISSUE TITLE
Mojang (c) notice in main menu is cut off

### ISSUE THREAD

**Issue by HenryLoenwind** [FTBTeam/FTB-Presents-Stoneblock-2#322]
* **Modpack Version**: 1.5.0

* **Issue**: 

![image](https://user-images.githubusercontent.com/1485873/52595351-ff2cdb00-2e4d-11e9-9703-10ada97e22c0.png)

* **Is it Repeatable?**: yes

**Comment by Sunekaer** [comment]
Hmm it seems fine for me
https://S1.sunekaer.com/i/xhanr8r8.png
What res do you play at?

**Comment by HenryLoenwind** [comment]
Windowed mode, any window size.

Seeing that is doesn't happen for everyone, my guess would be that whatever mod(s) manipulate(s) the main menu used the window width instead of the window content width to position the text.

**Comment by Sunekaer** [comment]
i play windowed mode too, just tried many different window sizes, are you windows or linux?
The forge text in the other side is that fine?
