### ISSUE TITLE
Help keep getting locked out due to crash

### ISSUE THREAD

**Issue by Goofy23** [FTBTeam/FTB-Presents-Stoneblock-2#323]
* **Modpack Version**: 1.4.0

* **Issue**: I've had to restart 5 times now because I keep getting this same crash report every other couple days and it completely looks me outta the game

* **Link to Log or Crash File Paste**: https://paste.dimdev.org/porajifugo.mccrash & here's another crash report  https://paste.dimdev.org/akuholesas.mccrash
 
PLZ HELP

**Comment by Goofy23** [comment]
here's another crash report
https://paste.dimdev.org/akuholesas.mccrash

**Comment by Goofy23** [comment]
okay I removed minetogther and it allowed me to go play again

**Comment by Sunekaer** [comment]
please report it here https://github.com/CreeperHost/CreeperHostGui/issues
