### ISSUE TITLE
Thaumcraft 6 needs to be removed from Stoneblock 2

### ISSUE THREAD

**Issue by Solverbolt** [FTBTeam/FTB-Presents-Stoneblock-2#324]
* **Modpack Version**: 
Stoneblock 2 1.4
* **Issue**: 
Thaumcraft corrupting and crashing worlds
* **Link to Log or Crash File Paste**:  Its not generating a file, at all, it is instead corrupting the files to the point complete removal is required

* **Is it Repeatable?**: 
Attempt in any way to get past the beginning stages of Thaumcraft, it will repeat itself
* **Mod/s Affected**: 

* **Known Fix**: 
None that I have seen, other than removing Thaumcraft 6 for incompatibility, and the mod developer, Azanor, refuses to acknowledge the bug, or any bug with Thaumcraft

**Comment by nzminecraftDOTcom** [comment]
Post the log file your game generates while running, if it is on a server, post its log file too.
I've never heard of an issue with it corrupting worlds as my worlds have had no issues with 200+ players using them. Are you sure it isn't to do with how you are saving/closing the game down.

**Comment by Sunekaer** [comment]
Thaumcraft wont be removed, we need some logs so we can see whats happened and report it  to the thaumcraft team
