### ISSUE TITLE
[Suggestion] RFTools Dimensions

### ISSUE THREAD

**Issue by ReiDaTecnologia** [FTBTeam/FTB-Presents-Stoneblock-2#325]
It will be really cool and useful because you could create you own realm with the sun, the stars and the green grass... _the green grassssss_ 😏 
Some people don't like to build you nice-looking base in a cave, u know xD
Some people is not literally a Caveman xD
Btw nice modpack! i'm liking it so much! mainly the chickens :P
<3

**Comment by Sunekaer** [comment]
there wont be added any dim mods to this pack
