### ISSUE TITLE
Applied energetics manual crafting running out of items in crafting grid despite some in system

### ISSUE THREAD

**Issue by Suntonk** [FTBTeam/FTB-Presents-Stoneblock-2#327]
* **Modpack Version**:1.4.0

* **Issue**: Whenever i shift click to craft a recipe in  an applied energistics crafting terminal it runs out of materials even though i have matterials in the system
EX: making iron blocks. put recipe into the crafting grid. Shift click to make a stack , makes some blocks then the bottom right will run out dispite having the materials in the ae system
https://gyazo.com/098c76947a52dbda9748cb13b8efc907
Gif that shows it

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Applied energistics 2 rv6-stable-6

* **Known Fix**:

**Comment by Suntonk** [comment]
ALSO , the issue doesn't happen with the wireless crafting terminal from Wireless crafting terminal 2

**Comment by Sunekaer** [comment]
This happens when your system runs out of power, add some Energy Cell´s to the system and that should help you
