### ISSUE TITLE
FTB Quests server crash/partly reset. Ticking player

### ISSUE THREAD

**Issue by zCodeg** [FTBTeam/FTB-Presents-Stoneblock-2#328]
* **Modpack Version**:  1.4.0
Server, no Sponge

* **Issue**: After server crash FTB Quests progress were partly reset 

![ftbquests](https://user-images.githubusercontent.com/5285811/52695065-2f6e9980-2f74-11e9-936d-608fa0b42991.png)
(in the screenshot, 5 first chapters were reset)
* **Link to Log or Crash File Paste**: 

https://paste.feed-the-beast.com/view/18b0d645

* **Is it Repeatable?**:  Unknown

* **Mod/s Affected**: FTB Quests
* **Known Fix**: -

**Comment by Sunekaer** [comment]
try https://www.feed-the-beast.com/projects/ftb-presents-stoneblock-2/files/2673992
