### ISSUE TITLE
Double Compressed Diamond Hammer Upgrade

### ISSUE THREAD

**Issue by FlyingTornado1** [FTBTeam/FTB-Presents-Stoneblock-2#329]
* **Modpack Version**: 1.0.4-1.12.2

* **Issue**: Tinkers Tools with Double Compressed Diamond Upgrade only get xp with Comressed Cobblestone, not with Compressed Gravel, Dirt, Sand

* **Is it Repeatable?**:  Yes,, Tinkers tool+ Double Compressed Diamond Hammer Upgrade

* **Mod/s Affected**: <Tinker's Construct Version 1.12.2-2.12.0.115

**Comment by FlyingTornado1** [comment]
On 1.0.5 also not working.

**Comment by Sunekaer** [comment]
Please report to mod author, i cant do anything about this
