### ISSUE TITLE
Dark storage drawer icons

### ISSUE THREAD

**Issue by M3wM3w** [FTBTeam/FTB-Presents-Stoneblock-2#33]
* **Modpack Version**: 
1.0.1

* **Issue**: 
Storage Drawers display very dark icons for blocks and maybe other items.
Torches are ignored.

* **Link to Log or Crash File Paste**: 
 https://imgur.com/a/SoA941m

* **Mod/s Affected**:
"Storage Drawers"

**Comment by Sunekaer** [comment]
https://github.com/jaquadro/StorageDrawers/issues/689

**Comment by Sunekaer** [comment]
Closing this issue, as there´s nothing we can do about this other then wait and see if the mod dev fixes it
