### ISSUE TITLE
[Question] More functionality for ME....

### ISSUE THREAD

**Issue by Kratzwurst** [FTBTeam/FTB-Presents-Stoneblock-2#330]
Hey all, 

i have one little Question @Sunekaer  ^.^

Can u please add this little thing "https://minecraft.curseforge.com/projects/capability-adapter" for Compact Machines in the next Version of your Modpack? 
This allows ME-Cable to Connect on the Compact Machines for Auto-Crafting. P2P Tunnels etc.

I hope it's be possible

Greeting

**Comment by Sunekaer** [comment]
There wont be adding anything to this pack only bug fixing
