### ISSUE TITLE
Infinite Instant Power

### ISSUE THREAD

**Issue by spdkils** [FTBTeam/FTB-Presents-Stoneblock-2#331]
* **Modpack Version**: 1.5

* **Issue**: If you use Flux net, and turn off the max amount of power it can transfer, and port it into the Spectre Energy Injector  from random things, it goes negative a billion power or so. When it does, it basically transmits instant power to all its nodes. So random things gets infinite power because Flux networks strange behavior.

* **Is it Repeatable?**: I did it several times, to basically fill 800,000,000 power in 1 tick. Now I could have just sat there for 20 minutes or afk to get the same power, so no big deal. But seems broken you can get 800 million power in 1 tick.

* **Mod/s Affected**:Random Things + Flux Power
![image](https://user-images.githubusercontent.com/11712349/52761186-47bbd400-2fc7-11e9-94e1-cca3ea2f8dbf.png)

**Comment by spdkils** [comment]
The interaction may be more subtle. It seems that my infusion is instant, however it's also in a compact machines dim, that has a ticker on the outer block. I haven't gone thru all the code, but this setup on this map causes it every time. Even after updating from 1.5 to 1.6

**Comment by Sunekaer** [comment]
Please report to mod author, i cant do anything about this
