### ISSUE TITLE
mob drops recipe crash

### ISSUE THREAD

**Issue by AlwaysStijn** [FTBTeam/FTB-Presents-Stoneblock-2#333]
* **Modpack Version**: 1.4.0

* **Issue**: game freezes, then starts to flicker really fast and  can't do anything anymore when looking trough the recipe to get fish,  i tested it a few times and i think it's when i'm looking at the mob drops tab, other people on the server who tested it also got it and also on different items that have the mob drop tab

* **Link to Log or Crash File Paste**:  https://paste.feed-the-beast.com/view/36bd7291

* **Is it Repeatable?**: yes, every time i look at the mob drops tab in recipes

**Comment by Sunekaer** [comment]
#139
