### ISSUE TITLE
Missing file in server download

### ISSUE THREAD

**Issue by Gunner76th** [FTBTeam/FTB-Presents-Stoneblock-2#334]
* **Modpack Version**: 1.6.0

* **Issue**: In the 1.6.0 archive the folder "questpacks" is missing. This folder and the subsequent file "normal.nbt" were previously included in the archives of previous versions. 

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**:Yes, until the 1.6.0 archive is updated

* **Mod/s Affected**: The Questing Mod

* **Known Fix**: Do not delete the questpacks folder on the server when updating from 1.5.0 to 1.6.0

**Comment by Sunekaer** [comment]
The quest file
Is moved from there to inside the config folder
