### ISSUE TITLE
Draconic Evolution advanced dislocator generates error

### ISSUE THREAD

**Issue by wghout** [FTBTeam/FTB-Presents-Stoneblock-2#335]
* **Modpack Version**: 
FTBPresentsStoneblock2-1.6.0-1.12.2

* **Issue**: 
After updating the pack I get an error notification when I try to use the advanced dislocator from Draconic Evolution. I can not use the item to warp to the saved locations. Instead I get the error notification. When I go back to the previous version of the modpack all work fine.
* **Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/099eff1d
* **Is it Repeatable?**: 
Yes. Install the new update a few times and use a backup save. Also did a clean install of the pack.
* **Mod/s Affected**: 
Draconic-Evolution-1.12.2-2.3.19.330-universal
* **Known Fix**:

**Comment by stanleymcc** [comment]
Additionally this affects all Dislocators in Draconic Evolution 1.12.2-2.3.19.330  
https://paste.dimdev.org/woxexevoqu.mccrash

**Comment by 1leotruong2** [comment]
Same with me
https://paste.dimdev.org/isegutacim.mccrash

**Comment by 1leotruong2** [comment]
Also building a teleportation portal with the dislocator crashes as well.
https://paste.dimdev.org/epusesowov.mccrash

**Comment by GridCube** [comment]
same 

https://paste.dimdev.org/ukodubogig.mccrash

**Comment by lilrichy** [comment]
Confirming dislocator portal and on pedestals causes a crash.

Pedestal :  https://paste.dimdev.org/wocoyerenu.mccrash
Portal : https://paste.dimdev.org/soferikeqi.mccrash

**Comment by Sunekaer** [comment]
Fixed in 1.7.0
