### ISSUE TITLE
keeps crashing when trying to get into a world

### ISSUE THREAD

**Issue by d4s0n** [FTBTeam/FTB-Presents-Stoneblock-2#336]
<

* **Modpack Version**: <1.3.0

* **Issue**: Whenever I try to join a server or any world my Java keeps crashing, I have done stuff like update it too

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/06bb638f

* **Is it Repeatable?**: yes

**Comment by nzminecraftDOTcom** [comment]
Post a crash report log, not your latest.log file from your game, its of no use in a crash

**Comment by Sunekaer** [comment]
crash log?
