### ISSUE TITLE
Mob Farm causes Draconic Evolution Crash

### ISSUE THREAD

**Issue by chadfingerson** [FTBTeam/FTB-Presents-Stoneblock-2#338]
* **Modpack Version**: 1.6.0-1.12.2

* **Issue**: When my mob farm is active I consistently get an internal server crash caused by Draconic Evolution. This only happens if the mob farm is active and no other time.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/0c211db9

* **Is it Repeatable?**: Yes, turning on mob farm causes the crash every time.

* **Mod/s Affected**: Crash report states Draconic Evolution.

* **Known Fix**: Updating to Draconic-Evoloution-1.12.2-2.3.20.333

**Comment by Sunekaer** [comment]
Fixed in 1.7.0
