### ISSUE TITLE
Moving Wand Allows for Loot Crate Storage to be Duplicated

### ISSUE THREAD

**Issue by stanleymcc** [FTBTeam/FTB-Presents-Stoneblock-2#339]
* **StoneBlock 2 1.6.0 Mincraft Version 1.12.2 Forge 14.23.5.2808**: 

* **Moving Wand from Not Enough Wands allows for the Loot Crate Storage to be duplicated. It doesn't duplicate loot crates that are stored in the cube, from the test I have run. It moves the cube into the wand and also breaks the cube and puts into your inventory.**: 

* **No Crash Report**: 

* **Yes**: 

* **FTB Quests 1.5.0.130 and Not Enough Wands 1.12-1.7.3**:

**Comment by Sunekaer** [comment]
Fixed in 1.7.0
