### ISSUE TITLE
Infinity Block Tool Forge wrong Emc

### ISSUE THREAD

**Issue by Rokutiz** [FTBTeam/FTB-Presents-Stoneblock-2#34]
Infinity block tool forge has 130 emc for some reason

**Comment by Sunekaer** [comment]
Wrong EMC? wrong how?

**Comment by Rokutiz** [comment]
what do you mean wrong?
it has 4 infinity blocks yet its emc is 130.

**Comment by Rokutiz** [comment]
im actually retarded
