### ISSUE TITLE
Server Crash(probably user related)

### ISSUE THREAD

**Issue by ttechr** [FTBTeam/FTB-Presents-Stoneblock-2#342]
* **Modpack Version**: 1.6.0

* **Issue**: Server crashes constantly. Can't get good information from users to link anything currently

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/b1efa8e1

* **Is it Repeatable?**: Yup. Every time the server comes back up it crashes again.

* **Mod/s Affected**: any and all

* **Known Fix**: Ban all users. lol

**Comment by Sunekaer** [comment]
Make sure to take a backup of your world before doing this! edit the forge.cfg in the config folder. There are a couple of lines about removing erroring entities. Change both of them to true and load the world and see if the removes the block. REMEMBER to set these back to false again!.... If that doesn't work, then you need to create a issue on darkutils github and get help from them
