### ISSUE TITLE
Crashing on start up

### ISSUE THREAD

**Issue by TheFierceDeity** [FTBTeam/FTB-Presents-Stoneblock-2#343]
* **Modpack Version**: 1.6.0
* **Issue**: Upon launching the pack, client crashed on mod initialization phase 1 loading.

* **Link to Log or Crash File Paste**: https://paste.dimdev.org/ipabejipob.mccrash

* **Is it Repeatable?**: No

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Sunekaer** [comment]
Hmm try and reinstall the pack, if that doesnt help create a issue here https://github.com/iLexiconn/LLibrary/issues so they can help you
