### ISSUE TITLE
Thaumcraft Advanced Storage Seal for Quest Book Issue

### ISSUE THREAD

**Issue by thynightmares** [FTBTeam/FTB-Presents-Stoneblock-2#344]
Modpack Version: 1.5.0 (MULTIPLAYER)

Issue: Can't upgrade the "Control Seal: Store" to the advanced version for the quest book. Right clicking on the top just places it, shift right clicking doesn't do anything, just throwing it in like the book says you can dissolves it like everything else, I've also tried using a golem with the "use" seal but it also did nothing, and I've tried just leaving it on the top where it placed it but that didn't work either. I cant see anything in the book that's preventing me from doing it or saying I have to do it differently, the recipes just like any other crucible one. I've done everything else in the book i could to make sure nothing was stopping me there. I've tried looking online for solutions as well but i haven't found anything yet.

Is it Repeatable: Yes

Mod Affected: Thaumcraft

**Comment by Sunekaer** [comment]
Sorry for the delay on the reply, i have no clue why this doesnt work, try asking on the Thaumcraft Github, they should be able to help you
