### ISSUE TITLE
Crash on refuel furnace generator 

### ISSUE THREAD

**Issue by hoeglse** [FTBTeam/FTB-Presents-Stoneblock-2#345]
* **Modpack Version**: 1.6.0

* **Issue**: Game crash after try to add a full stack (64) of fuel (stick/coal) to furnace generator with shift click out of inventory if there is some fuel allready in it.

* **Link to Log or Crash File Paste**: "Das Program ist mit dem Status -805306369 abgestürzt."

* **Is it Repeatable?**: yes

* **Mod/s Affected**: extrautils2-1.12-1.9.8

* **Known Fix**: No shift click to refuel the generator

**Comment by Sunekaer** [comment]
#31
