### ISSUE TITLE
Aluminum Nuggets and Aluminum Ingot's in EnderIO Alloy Smelter

### ISSUE THREAD

**Issue by TheSim14** [FTBTeam/FTB-Presents-Stoneblock-2#346]
* **Modpack Version**: 1.5.0

* **Issue**: Aluminum Nuggets didnt have a Recipe for Ingots in Crafting Field and the Aluminum Dust goes in Alloy Smelter to the Aluminum Ingot's from Ex-Nihilo Mod not from 

* **Is it Repeatable?**: Yes, just convert a Aluminum Ingot to Nuggets and u cant convert them back, and just use Aluminum Ore Chunk from Ex-Nihilo in Sag-Mill and then in a Alloy Smelter from EnderIO with Smelt all Option.

**Comment by Sunekaer** [comment]
Nuggets to ingots works just fine for me in test?

**Comment by TheSim14** [comment]
That's the Recipe's i only get :/
http://puu.sh/CPCsp/dcb82013ed.png

**Comment by Sunekaer** [comment]
try 1.7.0, when i put nuggets in the table in a 3x3 i get a ingot
