### ISSUE TITLE
Failed to load 

### ISSUE THREAD

**Issue by GTRekT** [FTBTeam/FTB-Presents-Stoneblock-2#347]
* **Modpack Version**: 14.23.5.2808

* **Issue**: It cannot load up when fist opening app

* **Link to Log or Crash File Paste**:https://paste.dimdev.org/cuwuyupaku.mccrash

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by AngusX12** [comment]
Same thing happening to me

**Comment by Sunekaer** [comment]
"GC overhead limit exceeded" assign more ram to minecraft
