### ISSUE TITLE
Wont go to main menu

### ISSUE THREAD

**Issue by AngusX12** [FTBTeam/FTB-Presents-Stoneblock-2#348]
* **Modpack Version**:1.5.0

* **Issue**: I open the modpack on twitch and it loads all the mods on the Mojang screen but afterwards it comes up with an error screen saying: error maybe with tinkers construct ender io and ender io opens comp conduits.

* **Link to Log or Crash File Paste**:
[https://paste.dimdev.org/vogosopali.mccrash]

* **Is it Repeatable?**: yes

* **Mod/s Affected**: I think it says tinker construct and ender io.

**Comment by evanstern** [comment]
I'm having this same issue.

**Comment by Sunekaer** [comment]
"GC overhead limit exceeded" assign more ram to minecraft
