### ISSUE TITLE
Extreme reactors Graphite dust Vrs Quantum Flux

### ISSUE THREAD

**Issue by Snowgods** [FTBTeam/FTB-Presents-Stoneblock-2#35]
<Vers 1.01

extreme reactors graphite dust doesn't work to create quantum flux hyper diamonds  (and vice verse) - although quantum flux graphite works fine

ore dicting the quantum flux graphite, and having extreme reactors graphite grind down to quantum flux graphite dust should fix this

**Comment by Sunekaer** [comment]
wont be changed
