### ISSUE TITLE
Void Island users always respawns at (0,x,0).

### ISSUE THREAD

**Issue by Sorbe** [FTBTeam/FTB-Presents-Stoneblock-2#350]
I've created and been playing a void island style Stoneblock 2 for a month now.
But each and every time, when I start the single player game up, I appear at (0,x,0) instead of where I logged off OR where my bed is located (and slept in).

Stoneblock 2 - 1.5.0

100% Repeatable

P.S.> Also, when I put up a "glass ceiling" in the overworld way up at Y=250, I started appearing in the Mining Dimension at (0,x,0) instead.

**Comment by nzminecraftDOTcom** [comment]
What does your config file for VoidIslandControl say in the line:
"Forces players to spawn at the spawn positions......." True or false? Perhaps it sees the stone above you as a cave and tries to spawn you at the next available location - the world spawn.

**Comment by Sunekaer** [comment]
Server, single player?

**Comment by Sorbe** [comment]
"when I start the single player game up"

**Comment by Sorbe** [comment]
voidislandcontrol.cfg:79
"# Forces players to spawn at the spawn position. By default, the player will be teleported to a safe spot above it if spawning fails. This config disables that
        B:forceSpawn=false"

**Comment by Sunekaer** [comment]
Dont know why you spawn at 0,0 talked with the mod dev and he hasnt seen this issue before
