### ISSUE TITLE
Draconic reactor server crash

### ISSUE THREAD

**Issue by filzaw80** [FTBTeam/FTB-Presents-Stoneblock-2#351]
I am using the latest version (1.6.0). I'm playing on a server

After charge the draconic reactor, the server crashes

https://paste.feed-the-beast.com/view/20c8c0fd

Whenever I turn on the server

Draconic-Evolution-1.12.2-2.3.19.330-universal

**Comment by Sunekaer** [comment]
Fixed in 1.7.0
