### ISSUE TITLE
Translocators Close my World

### ISSUE THREAD

**Issue by PudWin** [FTBTeam/FTB-Presents-Stoneblock-2#352]
* **Modpack Version**: 1.7.0

* **Issue**: My game is closed when I use the Translocator items

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/208f2274

* **Is it Repeatable?**: I don't Know

* **Mod/s Affected**: Translocators, I think.

**Comment by Sunekaer** [comment]
Make sure to take a backup of your world before doing this! edit the forge.cfg in the config folder. There are a couple of lines about removing erroring entities. Change both of them to true and load the world and see if the removes the block. REMEMBER to set these back to false again!.... If that doesn't work, then use mcedit or NBT Editor on the world to remove the block located at (-7,90,26)
