### ISSUE TITLE
Rubies, Sapphires, and Peridots are almost useless

### ISSUE THREAD

**Issue by MrEyeballs29** [FTBTeam/FTB-Presents-Stoneblock-2#353]
* **Modpack Version**:  1.6.0

* **Issue**:  I just looked at one of the chest containing rubies, sapphires, and peridots that don't have any recipes available.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/10012403 

![2019-02-21_18 45 27](https://user-images.githubusercontent.com/27930788/53212031-f8018c00-3608-11e9-894c-788af7ed453b.png)
![2019-02-21_18 45 23](https://user-images.githubusercontent.com/27930788/53212218-ba513300-3609-11e9-9a6c-5fe39a3af147.png)
![2019-02-21_18 52 54](https://user-images.githubusercontent.com/27930788/53212262-f4223980-3609-11e9-8134-5e4255ddc62a.png)
![2019-02-21_18 52 58](https://user-images.githubusercontent.com/27930788/53212272-ff756500-3609-11e9-8ed3-bb1402039b57.png)
![2019-02-21_18 53 04](https://user-images.githubusercontent.com/27930788/53212273-013f2880-360a-11e9-999b-6edd0b026b4f.png)

* **Is it Repeatable?**: No

* **Mod/s Affected**: Project Red: Core (I think that is the mod.)

* **Known Fix**: I trashed the useless gems and seems like sapphires can only make PRC screwdrivers

**Comment by Sunekaer** [comment]
This issue is almost useless

**Comment by 016Nojr** [comment]
Generate RF with'em :D
