### ISSUE TITLE
Crashed From MineTogether/MineTogetherServer

### ISSUE THREAD

**Issue by BeholdBlaze** [FTBTeam/FTB-Presents-Stoneblock-2#354]
* **Modpack Version**:  Version 1.6.0

* **Issue**:  When joining my single player server, 10 seconds in it show a screen saying minecraft ran into a problem, also saying the possible cause is MineTogether

* **Link to Log or Crash File Paste**:  https://paste.dimdev.org/dijucuvuye.mccrash

* **Is it Repeatable?**:  Yes, Relaunching or Retrying come with the same outcome.

* **Mod/s Affected**:  MineTogether and MineTogetherServer.

* **Known Fix**:  No idea.

**Comment by Sunekaer** [comment]
Please create an issue here https://github.com/CreeperHost/CreeperHostGui/issues
