### ISSUE TITLE
Missing minecraft items

### ISSUE THREAD

**Issue by HollieSD04** [FTBTeam/FTB-Presents-Stoneblock-2#356]
* **Modpack Version**: FTB presents Stoneblock 2 - v 1.7.0

* **Issue**: I have just installed the recent update for this mod pack and now when I load up my save it says that I have missing items like ftbquest: Uncommon_lootcrate up to the legendary_lootcrates. I don't want to load up my save just for it to corrupt

* **Is it Repeatable?**: it gives me the warning every time I try to load the save.

* **Mod/s Affected**: ftb Quests I think

**Comment by Sunekaer** [comment]
Updated from which version?

**Comment by Sunekaer** [comment]
You should be fine
