### ISSUE TITLE
Unable to craft Thaumonomicon

### ISSUE THREAD

**Issue by 1leotruong2** [FTBTeam/FTB-Presents-Stoneblock-2#357]
* **Modpack Version**: <FTBPresentsStoneBlock2- 1.7.0-1.12.2>

* **Issue**: Cannot craft Thaumonomicon with Salis Mundus or Arcane Workbench No animation is played and neither items are consumed.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Thaumcraft

* **Known Fix**: if you know of a fix please let me know! Thanks

**Comment by zCodeg** [comment]
Did you sleep in a bed? You need to, to unlock Thaumonomicon knowledge

**Comment by 1leotruong2** [comment]
Okay i slept in the bed and it worked thanks.
