### ISSUE TITLE
Shift-click stack upgrade into Extra utilities 2 nodes crashes game

### ISSUE THREAD

**Issue by DrCraven** [FTBTeam/FTB-Presents-Stoneblock-2#359]
Modpack Version: 1.7.0

Issue: Shift-clicking "upgrade stack" into Extra utilities 2 nodes (transfer and retrieval were tested) crashes game if there is already a stack upgrade inside

Link to Log or Crash File Paste: https://paste.feed-the-beast.com/view/e8931775

Repeatbale: yes

**Comment by Sunekaer** [comment]
#31

**Comment by DrCraven** [comment]
sorry for repeating it, thanks
