### ISSUE TITLE
DragonScale Ore Dictionary Overlap

### ISSUE THREAD

**Issue by shymian** [FTBTeam/FTB-Presents-Stoneblock-2#360]
**Modpack Version**: 1.6

* **Issue**: Dragon Scale (Tiny Progressions) and Dragon Scale (Mystical Agradditions) share an ore dictionary name of -dragonScale.  They have different EMC values; a 762k gain is possible converting between the two.

* **Link to Log or Crash File Paste**: NA

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: NA

* **Known Fix**: NA.  I am actually hoping this was purposefully intended as a method towards Big Spender, but erring on the side of caution.

**Comment by Sunekaer** [comment]
woops they are supposed to be the same value
