### ISSUE TITLE
Thaumcraft requires nether

### ISSUE THREAD

**Issue by NeariX67** [FTBTeam/FTB-Presents-Stoneblock-2#361]
* **Modpack Version**: 1.60

* **Issue**: It is not possible to finish "Infernal Furnance" under Thaumonomicon->Artifice->Infernal Furnace-> "Visit a hellish place"

* **Is it Repeatable?**: Ofc

* **Mod/s Affected**: Thaumcraft 6
![2019-02-24_22 54 40](https://user-images.githubusercontent.com/31779313/53305914-40c67880-3887-11e9-8ec8-3b9e5caf823d.png)

**Comment by Sunekaer** [comment]
As said in the quest.. "Biome Marker and Terraformer"
