### ISSUE TITLE
Problems with gettin in the world

### ISSUE THREAD

**Issue by MorfieLife** [FTBTeam/FTB-Presents-Stoneblock-2#363]
Hello,Im askin for help.When i was in pocket world (Compact Machines 3) ,i started transforming into creature and then pressed on a laptop to get back into otherworld.After that my minecraft crashed and for now i still didnt have a good try to get in. 
Thats hastebin link https://paste.dimdev.org/etuzoqojeg.mccrash
Version: Last release from 13.02.19

**Comment by Sunekaer** [comment]
Version number?

**Comment by MorfieLife** [comment]
Well, i solved that problem by using older version of compact machines. I dont how dat helped but now i can keep playing
That means, that u can close this theme😅
