### ISSUE TITLE
Absorption Hopper crash game

### ISSUE THREAD

**Issue by hoeglse** [FTBTeam/FTB-Presents-Stoneblock-2#364]
* **Modpack Version**: 1.7.0

* **Issue**: Configure output for absorption hopper try to get item and fluid output on the same side. It only happen if the block on side is a cyclic energy transfernode.

* **Link to Log or Crash File Paste**: 
Crash ingame: https://paste.dimdev.org/ipazutuvoh.mccrash

Loading world: https://paste.dimdev.org/rigenazofa.mccrash

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: mob_grind_utils and cyclic

* **Known Fix**: Load world with mcedit and remove the connection to cyclic energy transfernode

**Comment by Sunekaer** [comment]
Please report to mob grinding utils
