### ISSUE TITLE
Repetitive Lag Spikes

### ISSUE THREAD

**Issue by Maddog4302** [FTBTeam/FTB-Presents-Stoneblock-2#366]
* **Modpack Version**:  1.6.0

* **Issue**:  every so many seconds. maybe every 15 to 20 seconds the launcher and or game will have a huge lag spike.

* **Link to Log or Crash File Paste**:  

* **Is it Repeatable?**:  Yes

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Sunekaer** [comment]
Well this doenst happen to me, and theres no way i can just say what does that for you, you can try using https://minecraft.curseforge.com/projects/laggoggles or Sampler to try and find the issue
