### ISSUE TITLE
Crashing when loading

### ISSUE THREAD

**Issue by tm20** [FTBTeam/FTB-Presents-Stoneblock-2#367]
* **Modpack Version**: FTBPresentsStoneblock2-1.7.0-1.12.2.zip

* **Issue**: It crashed when I try to open

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/ed11d195
* **Is it Repeatable?**: Yup

**Comment by Sunekaer** [comment]
Something wrong with the minecraft install on your pc " your vanilla jar may be corrupt", try reinstalling the pack or minecraft else contact twitch for help
`Java.lang.RuntimeException: Patcher expecting non-empty class data file for net.minecraft.crash.CrashReport$1, but received empty, your vanilla jar may be corrupt.`
