### ISSUE TITLE
Spawned the Ender Chicken at y level 247 and this is what happened:

### ISSUE THREAD

**Issue by calloatti** [FTBTeam/FTB-Presents-Stoneblock-2#368]
* **Modpack Version**: FTBPresentsStoneblock2-1.6.0-1.12.2

* **Issue**: 

![image](https://user-images.githubusercontent.com/12817862/53439332-93677800-39e0-11e9-9ea1-4cc271e939aa.png)

**Comment by Sunekaer** [comment]
Cant do anything about it
