### ISSUE TITLE
XNet connector won't attach to thermal fluxduct

### ISSUE THREAD

**Issue by urikkiru** [FTBTeam/FTB-Presents-Stoneblock-2#370]
* **Modpack Version**: 
1.7.0
* **Issue**: 
Normally in other packs, I've always been able to connect to a thermal flux duct with an XNet connector. For some reason in this pack, this is not available. Mucks up certain setups with XNet.
* **Is it Repeatable?**: 
Yes

**Comment by Sunekaer** [comment]
i havent disabled any interaction, please report to mod author
