### ISSUE TITLE
Minetogether/EnderStorage mod causes crash when loading saved world after updating from v1.6.0 of pack

### ISSUE THREAD

**Issue by DrunkTaank** [FTBTeam/FTB-Presents-Stoneblock-2#372]
* **Modpack Version**: 1.8.0

* **Issue**: Updated from v1.6.0 to 1.8.0, game launched just fine, but when I tried to load my saved world, it crashed.  Crash log indicated that minetogether was causing the problem, so I disabled it. World save now loads, but the starting room has been regenerated and all items in my chests have spilled out on to the floor.  

* **Link to Log or Crash File Paste**: https://pastebin.com/Ax66Ltpt & https://pastebin.com/tNvqyYcZ  

* **Is it Repeatable?**: yes

* **Mod/s Affected**: minetogether-1.10.2-2.1.3.jar & EnderStorage-1.12.2-2.4.5.135-universal.jar

* **Known Fix**: disabling minetogether and deleting the EnderStorage data files in the world save, but starting room also regenerated.  Rolled back to 1.6.0 and loaded save from backup.

**Comment by Cloudhunter** [comment]
Both of these seem to be symptoms of files being corrupted - looks like the minetogether.cfg was overwritten with a blank file.

I would recommend you restore the minetogether.cfg from the latest update of the pack to fix the minetogether issue.

**Comment by Sunekaer** [comment]
Delete C:\Users\Nick\Documents\Curse\Minecraft\Instances\FTB Presents Stoneblock 2\saves\New World\EnderStorag and what Cloudhunter said

**Comment by DrunkTaank** [comment]
I did both as recommend, however something caused the starting room in the world save to regenerate.  Was that caused by removing the EnderStorage directory, or was there something else in the version update that would have caused that?
> Known Fix: disabling minetogether and deleting the EnderStorage data files in the world save, but starting room also regenerated. Rolled back to 1.6.0 and loaded save from backup.
