### ISSUE TITLE
Sound doesn't work if game is loaded in background

### ISSUE THREAD

**Issue by xiod87** [FTBTeam/FTB-Presents-Stoneblock-2#374]
* **Modpack Version**: 1.7.0

* **Issue**: When loading game in background, to wait the time it takes to load, it will do a long bzzzt sound when the game gets to the main menu and no sounds will play.

* **Link to Log or Crash File Paste**: No crash file and unsure of what log is required

* **Is it Repeatable?**: Intermittent, have reproduced it twice in a row but on third try I was unable to. 

* **Mod/s Affected**: Unsure

* **Known Fix**: Unsure

**Comment by Sunekaer** [comment]
Hmm i cant recreate this issue, and to be honest no clue how to fix it even if i could recreate this issue

**Comment by TheLittleCube** [comment]
Seen this happen before. Did you happen to change your audio output at anytime during the load? MC doesn't like the output being changed.

**Comment by razulwolf** [comment]
I am have a similar problem in 1.8.0  I can get sound at the main menu screen just fine. But once I load into the game; all sound is gone.

**Comment by Lost-Ninja** [comment]
There a "Reload Sound System" keybind that you might try (from Random Tweaks), no idea if that'd help (or even if you haven't tried it). Certainly fixes the issue of no sound if you change the audio source after loading the game (what I use it for).
