### ISSUE TITLE
Crazy rendering issue

### ISSUE THREAD

**Issue by mendel3** [FTBTeam/FTB-Presents-Stoneblock-2#375]
* **Modpack Version**: 
1.7.0

* **Issue**: 
Crazy entity render glitch
* **Link to Log or Crash File Paste**: 
(its really long) https://paste.feed-the-beast.com/view/3367964b
It is for two joins of the same world
* **Is it Repeatable?**: 
I can only repeat the torch issue on this world, but the body movements I can repeat on another world. I haven't had much time to tinker, so I will add more info if I can get some.

This started happening when I told javaw.exe to use my dGPU (a 1070 with latest drivers) instead of my iGPU.
I have a video of what is happening here:
https://youtu.be/LVPGkyC9zDM
My movements were much faster, and pressing W didn't make me go forward. My keybinds were all messed up.

**Comment by Sunekaer** [comment]
Did you mess with betterFPS or foamfix?

**Comment by mendel3** [comment]
I changed the betterFPS algorithm, but that's it.

**Comment by mendel3** [comment]
@Sunekaer I think I found the glitch. The algorithm, Taylor's algorithm, was bugged. More about the issue is here [#62](https://github.com/Guichaguri/BetterFps/issues/62) Maybe you could disable Taylor's algo as a whole?

**Comment by Sunekaer** [comment]
I wont be changing this setting for everyone as you so far is the only one with this issue
