### ISSUE TITLE
Can´t start the game

### ISSUE THREAD

**Issue by Chris2289** [FTBTeam/FTB-Presents-Stoneblock-2#376]
The game don´t start. 

Here are my pastebin: https://paste.feed-the-beast.com/view/2bfefbdb

**Comment by Sunekaer** [comment]
Looks like your client has problems downloading files, nothing i can do about that

**Comment by Chris2289** [comment]
I reinstall the game and after that it started normal but when i would load my map a issue is there.

https://pastebin.com/x6wj9dWw
