### ISSUE TITLE
Mining Dimension/World is empty and bugged

### ISSUE THREAD

**Issue by Scheigy** [FTBTeam/FTB-Presents-Stoneblock-2#377]
* **Modpack Version**: 1.7.0 (Server)

* **Issue**: Whenever I try to access the Mining Dimension, I just get into an entirely empty world. I can't do anything like moving or dropping items. Deleting the DIM-7 didn't change anything.

* **Link to Log or Crash File Paste**: 
The debug.log only gives _[15:13:09] [Server thread/DEBUG] [stoneblockdimensions]: Starting teleport Overworld -> Mining_

Here's a picture:
![Bug Picture](https://i.imgur.com/ybEWWPV.png)

* **Is it Repeatable?**: Everytime.

**Comment by Sunekaer** [comment]
log?

**Comment by Scheigy** [comment]
latest.log: https://paste.feed-the-beast.com/view/f99eeb58

Do note that I added OpenComputers, but the bug already occured before that ; I even had the same issue on my first game, and I only manage to resolve it by re downloading the pack and starting a new world.

Tell me if you need more informations or if you want me to remove the mod and send you another log after.

**Comment by Scheigy** [comment]
I resolved that issue by transfering my world in my previous server folder and resetting the DIM-7.
The issue might have been from using AMP as a server manager, I'm now simply running the server with the shell script.

Although I did have that same issue in the past, you could probably close it, as you wish.

Thanks for your work on the pack

**Comment by Sunekaer** [comment]
Glad you got it fixed

**Comment by UBLICK** [comment]
i'm having the same issue and don't fully understand how you fixed it. I'm running a server though g-portal.com, this issue popped up mid game. Tried starting a bran new server. Bug still occurred.
