### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by ReverseCrown** [FTBTeam/FTB-Presents-Stoneblock-2#378]
* **Modpack Version**: FTBPresentStoneBlock2-1.7.0-1.12.2 ; forge-14.23.5.2808 ; twitch client

* **Issue**: Internal Server Error while trying to go on mining dimension

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/02bc3306

* **Is it Repeatable?**: Yes, every times i try acces the mining dimension

Hello guys, every time i  try to acces mining dimension, i'll be kick from the server with this error : Internal Server Error. Minecraft don't crash, only kick from the server.

**Comment by Sunekaer** [comment]
full log?

**Comment by ReverseCrown** [comment]
There it is : https://paste.feed-the-beast.com/view/0c232429

**Comment by Sunekaer** [comment]
Need the local from the server

**Comment by ReverseCrown** [comment]
It's a public server, i'm gonna ask to the owner...
Which version of forge did you use? Maybe it's help me

**Comment by mendel3** [comment]
> It's a public server, i'm gonna ask to the owner...
> Which version of forge did you use? Maybe it's help me

Look in your original post

**Comment by ReverseCrown** [comment]
I know the version that's i'm using, i ask to Sunekaer which version he use.
Sometime i have to change forge version on modpack, so if anyone use another forge version and can acces to the mining dimension, it can help me

**Comment by mendel3** [comment]
Then the version you are using is the same as the one bundled with 1.7.0 which is working for me.

**Comment by ReverseCrown** [comment]
Oh okay thank's, it's maybe a server issue so

**Comment by Sunekaer** [comment]
i of cause use the forge version i ship the pack with? but yes this is a issue with the server your on

**Comment by Sunekaer** [comment]
reopen this issue with server logs if they cant fix it for you
