### ISSUE TITLE
Psi, AutoRegLib crashes

### ISSUE THREAD

**Issue by 30350n** [FTBTeam/FTB-Presents-Stoneblock-2#379]
* **Modpack Version**: 1.7.0 (Installed using Twitch Launcher)

* **Issue**: When i join my own server (hosted on the same PC my client runs on), i get the crash. Once i go back into the main menu, i can sometimes still join it. I still get constant "crashes" popping up in the right corner of my screen. (These aren't only annoying because they visually block parts of my screen, but there's also a crash log file being generated roughly every second.)
![grafik](https://user-images.githubusercontent.com/34186858/53684237-3daa0d00-3d0b-11e9-972b-b043df88604f.png)
![grafik](https://user-images.githubusercontent.com/34186858/53684248-5ca89f00-3d0b-11e9-8ebd-5971258ff3ae.png)

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/cf84efbd

* **Is it Repeatable?**: Yes.

* **Mod/s Affected**: The crash report says the two mods "Psi" and "AutoRegLib" have been identified as potential causes.

**Comment by Sunekaer** [comment]
Try 1.8.0 PSI Was updated in that

**Comment by 30350n** [comment]
Yep, upgrading to 1.8.0 worked, it's not really a fix but i guess it works. It's just weird because a friend of mine didn't get any crashes, while he pretty much has the same setup as me.
Thanks for the help!
