### ISSUE TITLE
cow stall crashing 

### ISSUE THREAD

**Issue by lazycooken** [FTBTeam/FTB-Presents-Stoneblock-2#38]
spawned in a cow try to use the cow halter on it then try to put it in the cow stall

* **Modpack Version**:2-1.0.1-1.12.2.

* **Issue**: crash when trying to input cow into cow stall

* **Is it Repeatable?**: yes 

* **Mod/s Affected**: fluid cow 1.1.8
[crash-2019-01-05_13.51.02-server.txt](https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/files/2730165/crash-2019-01-05_13.51.02-server.txt)

**Comment by lazycooken** [comment]
i can't get into that world to tell you for sure but think it was the blood cow

**Comment by Sunekaer** [comment]
Okay, so you got a disabled cow. ill talk to the dev about getting that spawn removed or changed

**Comment by lazycooken** [comment]
this other thing did not leave a crash report but when, I mated the cow it also seem to make it so i could no longer put any of the cow in the cow halter. that could of just been because of the disabled thing.

**Comment by Sunekaer** [comment]
Okay is it just a test world, or do you want back in it?

**Comment by lazycooken** [comment]
it a test world

**Comment by Sunekaer** [comment]
1.1.0
