### ISSUE TITLE
Hang on exit from single player

### ISSUE THREAD

**Issue by perlguy** [FTBTeam/FTB-Presents-Stoneblock-2#380]
* **Modpack Version**: 1.8.0

* **Issue**: Game hangs on exit from single player world

Arch Linux 4.20.13-arch1-1-ARCH

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

* **Link to Log or Crash File Paste**:  https://pastebin.com/UNzpJ48S

* **Is it Repeatable?**:  Yes

* **Known Fix**: Disable Mekanism VoiceServer

mekanism.cfg:

    B:VoiceServerEnabled=false

**Comment by Sunekaer** [comment]
Was your game open to lan?

**Comment by perlguy** [comment]
No.

**Comment by Sunekaer** [comment]
A lot of mekanism fixes in 1.9.0 try that
