### ISSUE TITLE
Morph caused a crash and locked my save.

### ISSUE THREAD

**Issue by Wgairborne** [FTBTeam/FTB-Presents-Stoneblock-2#381]
* **Modpack Version**: 1.8.0

* **Issue**: I had tried to morph into a skeleton (while holding an invar hammer) and my game crashed, also locking it to where I can't access it anymore.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/81fedd26

* **Is it Repeatable?**: You could try what I did, but else from that I'm not sure.

* **Mod/s Affected**: Morph 1.12.2-7.1.2

* **Known Fix**: None known.

**Comment by Sunekaer** [comment]
Try updating IchunUtil and Morph

**Comment by Wgairborne** [comment]
Will try.

**Comment by Wgairborne** [comment]
Well... now the game crashes when trying to intialize on the forge loading screen.

**Comment by Sunekaer** [comment]
log..

**Comment by Wgairborne** [comment]
sorry for the wait, https://paste.feed-the-beast.com/view/94ce747c

**Comment by Sunekaer** [comment]
1.9.0
