### ISSUE TITLE
Thaumcraft Alchemy not working

### ISSUE THREAD

**Issue by TimBTB** [FTBTeam/FTB-Presents-Stoneblock-2#382]
* **Modpack Version**: 1.7.0

* **Issue**: When crafting items in the crucible, e.g. a nitor, After throwing in the required essentia, in this case 10 fire, energy and light, provided by 1 coal and 2 torches leaving 2 animal aspect, throwing in the catalyst should create a nitor, instead it adds the essentia to the crucible, making crafting impossible.
This issue happened in MP first, but it also happened in SP.
I also tried to make other recipies but Alchemical Brass was bugged in the same way.

* **Link to Log or Crash File Paste**: No crash

* **Is it Repeatable?**: Yes, this happens during every crafting operation.

* **Mod/s Affected**: Thaumcraft

* **Known Fix**: Right-clicking the catalyst instead of throwing it works

EDIT: Fix Found, when testing in SP I forgot to unlock the research first

**Comment by Wgairborne** [comment]
hey, you should update your game.
