### ISSUE TITLE
Crashing when map loading

### ISSUE THREAD

**Issue by AfterShave22** [FTBTeam/FTB-Presents-Stoneblock-2#383]
Map can´t loading. I make my windows new and reinstall the modpack.

Now i can´t load my map.

https://pastebin.com/x6wj9dWw

Can someone tell me what the problem is?

Thanks for helping :)

**Comment by Sunekaer** [comment]
Hey, 
Is this still an issue?

**Comment by AfterShave22** [comment]
> 
> 
> Hey,
> Is this still an issue?

Yes it is.

**Comment by Sunekaer** [comment]
try in Minecraft\Instances\FTB Presents Stoneblock 2\config find the file called p455w0rdsLib.cfg and change all 3 from true to false and see if that does a difference
