### ISSUE TITLE
Tnt and Explosives not breaking blocks

### ISSUE THREAD

**Issue by CloudChaserSvn** [FTBTeam/FTB-Presents-Stoneblock-2#384]
* **Modpack Version**: 1.7.0

* **Issue**: Most types of tnt and explosives, including minecraft tnt and cyclic dynamite, dont break any blocks and I have no idea how to stop that.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/34ab8f28

* **Is it Repeatable?**: yes

**Comment by Sunekaer** [comment]
is the area claimed?

**Comment by CloudChaserSvn** [comment]
It is so that I can chunkload

**Comment by CloudChaserSvn** [comment]
AE tiny tnt still works

**Comment by Sunekaer** [comment]
You can allow explosions in your team settings

**Comment by CloudChaserSvn** [comment]
That worked, thanks for the quick response and for taking the time with my dumb question. I really appreciate it.
