### ISSUE TITLE
Server crash (probably fluid cow)

### ISSUE THREAD

**Issue by filzaw80** [FTBTeam/FTB-Presents-Stoneblock-2#385]
I have version 1.8.0 minecraft and server. The package has not been changed anything.
 
Most likely, when fluid molten energetic silver and resonant ender born fluid molten vivid alloy server crash.

https://paste.feed-the-beast.com/view/957042d3

whenever I start the server

probably FluidCows-1.1.16.jar

**Comment by Sunekaer** [comment]
Not Fluidcow, fluid cows isnt even in the log 
Its a growth block from tiny progressions

Make sure to take a backup of your world before doing this! edit the forge.cfg in the config folder. There are a couple of lines about removing erroring entities. Change both of them to true and load the world and see if the removes the block. REMEMBER to set these back to false again!
