### ISSUE TITLE
World Crashed, Won't Restart. Tried Uninstalling What it Said the Problematic Mod was but Nothing

### ISSUE THREAD

**Issue by ItsAstrobiology** [FTBTeam/FTB-Presents-Stoneblock-2#386]
What the title says. I tried uninstalling the MineTogether mod that it said was the issue, but no change. Other worlds still work.
Please note: I have the computer know-how of a chimpanzee, so layman's terms would be appreciated in any response.
Here's the link to the crash info it gave me:
https://paste.dimdev.org/ecicanofil.mccrash

**Comment by Sunekaer** [comment]
Seem that the fil has been corruptedor overwritten with a blank file.
I would recommend you restore the minetogether.cfg from the latest update of the pack to fix the issue.
