### ISSUE TITLE
minetogether singleplayer crash

### ISSUE THREAD

**Issue by MCPVP123** [FTBTeam/FTB-Presents-Stoneblock-2#387]
* **Modpack Version**: <1.8.0>

* **Issue**: loading world then crashes saying minetogetherserver 

* **Link to Log or Crash File Paste**: https://paste.dimdev.org/lugizezaha.mccrash

* **Is it Repeatable?**: yes i have tried to find a threat that can help but none of them seem to work

* **Mod/s Affected**: minetogetherserver 

* **Known Fix**: not sure

**Comment by Sunekaer** [comment]
Seem that the fil has been corruptedor overwritten with a blank file.
I would recommend you restore the minetogether.cfg from the latest update of the pack to fix the issue.
