### ISSUE TITLE
Not fully launching

### ISSUE THREAD

**Issue by AmChras** [FTBTeam/FTB-Presents-Stoneblock-2#388]
I recently finished playing the first Stoneblock, I went to start Stoneblock 2 last night, and so I went to open it.  Twitch opened just fine, the minecraft launcher opened just fine, and hitting play appears to work, but the game never actually opens up.  I can see the Java process running in the task manager, and I tried waiting for it to launch but after waiting 10-20 minutes nothing happened, and when I end the process the minecraft launcher pops back up.  This doesnt happen for any other modpack, I tried 3 others and they launched just fine.

Also I looked at some of the solved issues searching for Launched in the closed section but I didnt find anything that seemed to be the same or help.

Modpack Version: 1.7.0

Heres my log: https://paste.feed-the-beast.com/view/c72926d6

Screenshot showing the java process: https://gyazo.com/ddefd7e137ff3f9f5f98188195e697da

**Comment by Sunekaer** [comment]
Try with out sponge

**Comment by AmChras** [comment]
> 
> 
> Try with out sponge

How exactly would I do that, this is my first time ever having an issue like this without it being resolved through some simple googling.

**Comment by Sunekaer** [comment]
Sorry read something wrong in your log, have you tried reinstalling the pack?

**Comment by AmChras** [comment]
I never tried exactly that, I did try changing versions.  But I'm uninstalling and reinstalling right now hopefully that will work.
