### ISSUE TITLE
Rendering Problems

### ISSUE THREAD

**Issue by TheRandomCrafter83** [FTBTeam/FTB-Presents-Stoneblock-2#389]
* **Modpack Version**: 1.4.0 Multiplayer

* **Issue**: I have noticed lately when i sign onto my server, the storage drawers are rotated and some of the me smart cables or enerio conduits doesn't render. I can re-log and everything appears as normal.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: I can repeat the issue every time i launch a new instance and then sign on.

* **Mod/s Affected**: Applied Energistics 2, Storage Drawers, Ender I.O. so far are the only mods affected

* **Known Fix**: At this point in time, the only thing that fixes it is to re-log, but not start a new instance.

**Comment by Sunekaer** [comment]
Very old version of the pack. update your pack before creating any issues
