### ISSUE TITLE
Draconic Evolution Crafters Won't Receive Power 

### ISSUE THREAD

**Issue by MopTK** [FTBTeam/FTB-Presents-Stoneblock-2#390]
Pack version: 1.8.0

Issue: The fusion crafters won't accept power from any source. I've tried hooking them to my reactor and to my draconic energy storage (also it seems the DE energy storage won't output into flux networks or with energy conduits). I was able to extract power from the energy storage with the I/O crystals but they won't power the fusion crafters but will power other machines. 

No crash reports

I tried this in my survival world and inside a creative world using all methods mentioned above (energy conduits, flux networks and DE I/O crystals) with the same results
**Edit:** I also joined back into an online server where I had beaten the pack previously using the same set up to progress all through end game and it's having the same issues as stated above. It was never an issue before. 
Mods Affected: I'd assume it's a DE issue

![2019-03-06_14 20 04](https://user-images.githubusercontent.com/48294845/53907728-c979ad00-401b-11e9-8160-0ec9badca41e.png)
![2019-03-06_14 16 10](https://user-images.githubusercontent.com/48294845/53907729-c979ad00-401b-11e9-87fd-14a80a98f31b.png)

**Comment by Sunekaer** [comment]
I cant recreate this, do u still have this problem?

**Comment by MopTK** [comment]
Yes I'm still experiencing it.
Here is my world download if that helps 
https://drive.google.com/drive/folders/1eNzOdS3HwjkhGAJ9dv82UBzw9kSODCbZ?usp=sharing

the cords are 
11, 114, 7

**Comment by Pyromania5** [comment]
Have you tried crafting something?
I think DE injectors only store power when they are charging up to begin crafting.
i have not had any problems crafting DE items. You can connect the wireless energy crystals directly to the back of the injectors also.

**Comment by MopTK** [comment]
I've used flux networks, energy conduits and cryostabalized fluxducts and none of them transferred power. And I have the I/O crystals working on anything I put them on besides DE stuff.

**Comment by Pyromania5** [comment]
With a set up that is similar to your 2nd screen shot i can get a craft to finish.  the injectors do not store power when they are not doing anything like in your screenshot.
![2019-03-12_21 38 45](https://user-images.githubusercontent.com/48497822/54247528-b5e4af80-450f-11e9-9e6c-318b88cb5e65.png)
When they are in the process they will fill up with power, and empty when it finishes crafting.

**Comment by MopTK** [comment]
It's still broken though 

They don't even register the recipe
