### ISSUE TITLE
AA Empowerer Not Working - Particular Server Instance

### ISSUE THREAD

**Issue by luct** [FTBTeam/FTB-Presents-Stoneblock-2#391]
* **Modpack Version**: 1.8.0-1.12.2 Beta

* **Issue**: On a server instance of this modpack, and confirmed by copying the savefile on a local instance, the Actually Additions Empowerer does not work. On other save files it is fine. As part of trying to sort this issue took the /saves/<name>/data/actualltyadditionsdata.dat and ./capabilities.dat from a known, working save respectively and did not fix the issue. The setup has been copied verbatim into a different save and confirmed working there.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Actually Additions 1.12.2-r145

* **Known Fix**: N/A

**Comment by Sunekaer** [comment]
Works fine on my test server and client, i dont know whats causing your issue, recommend contacting AA on their Github and have them look at the problem with you
