### ISSUE TITLE
"Sender is not a player" issue with FTBLib

### ISSUE THREAD

**Issue by NLBlacky** [FTBTeam/FTB-Presents-Stoneblock-2#393]
* **Modpack Version**: 1.8.0

* **Issue**: Cannot use `/ranks set <playername> <rank>` to set a players rank for FTBUtilities. The error `Sender is not a player!` will happen if you run that command. I reported this earlier and it has been fixed in the new version of FTBLib. [Github report](https://github.com/FTBTeam/FTB-Utilities/issues/951)

* **Mod/s Affected**: FTBUtilities, FTBLib

* **Known Fix**: Update FTBLib to `FTBLib-5.4.1.86.jar `

**Comment by Sunekaer** [comment]
1.9.0
