### ISSUE TITLE
Cant /tpa after the new update

### ISSUE THREAD

**Issue by StoneZon3** [FTBTeam/FTB-Presents-Stoneblock-2#394]
* **Modpack Version**: FTBPresentsStoneBlock2-1.8.0-1.12.2 - release - current
* **Issue**: When i try to /tpa to my friend it says An unknown error occured while attempting to perform this command and obviously i cant tpa, he has the same issue too. P.S Im using Twitch launcher and i updated from the last beta version to this version and this started happening

* **Link to Log or Crash File Paste**: I dont know where to find the log, if its really needed please tell me 

* **Is it Repeatable?**: Yes i can repeat this, it happens every time,
The only fix i found for now is installing the older version, 1.7.0 to be exact

**Comment by Sunekaer** [comment]
1.9.0
