### ISSUE TITLE
Mekanism: Solar Generator

### ISSUE THREAD

**Issue by FlyingTornado1** [FTBTeam/FTB-Presents-Stoneblock-2#395]
Modpack Version: 1.8.0
Issue: Missing Solar Generator from Mekanism
Is it Repeatable?: Yes
Mod/s Affected: Mekanism Version 1.12.2-9.4.13.349, MekanismGenerators 1.12.2-9.4.13.349

Hi it seems the Solar Generators from Mekanisms are not in the Modpack enabled, is that a Mistake?
Because the Thermal Evaporation Plant is and thats misleading, since you need Advanced Solar Generators to make the Thermal Evaporation Plant.

Sincerely

FlyingTornado1

**Comment by FlyingTornado1** [comment]
Also you cant make Induction Matrix, Fusion Reacter, pretty much the whole Mekanism Mod is useless without the Plant.

**Comment by Wgairborne** [comment]
I mean, maybe they were trying to be realistic with the solar gen because... you're stuck in a cave. Maybe they didn't think about the TEP needing that.
