### ISSUE TITLE
Missing server mods

### ISSUE THREAD

**Issue by Fixuuu** [FTBTeam/FTB-Presents-Stoneblock-2#396]
Mod pack ver. 1.8.0
Which mods are missing?
--------------------------------
---- Minecraft Crash Report ----
// You're mean.

Time: 2019-03-10 15:30:48 CET
Description: Exception in server tick loop

Missing Mods:
    unknown : need [0.12,0.13): have missing

Missing Mods:
    unknown : need [2.4.2,): have missing

Missing Mods:
    unknown : need any: have missing

Missing Mods:
    unknown : need any: have missing

net.minecraftforge.fml.common.MultipleModsErrored
    at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:298)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:570)
    at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
    at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:125)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
    at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Linux (amd64) version 4.20.7-042007-generic
  Java Version: 1.8.0_181, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 18733520 bytes (17 MB) / 273678336 bytes (261 MB) up to 7635730432 bytes (7282 MB)
  JVM Flags: 6 total; -Xms256M -Xmx8192M -XX:ParallelGCThreads=2 -XX:CICompilerCount=2 -XX:MinHeapFreeRatio=2 -XX:MaxHeapFreeRatio=7
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2815 232 mods loaded, 232 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                                | Version                  | Source                                             | Signature                                |
       |:----- |:--------------------------------- |:------------------------ |:-------------------------------------------------- |:---------------------------------------- |
       | L     | minecraft                         | 1.12.2                   | minecraft.jar                                      | None                                     |
       | L     | mcp                               | 9.42                     | minecraft.jar                                      | None                                     |
       | L     | FML                               | 8.0.99.99                | forge-1.12.2-14.23.5.2815-universal.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | L     | forge                             | 14.23.5.2815             | forge-1.12.2-14.23.5.2815-universal.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | L     | smoothfontcore                    | mc1.12.2-1.16            | minecraft.jar                                      | None                                     |
       | L     | foamfixcore                       | 7.7.4                    | minecraft.jar                                      | None                                     |
       | L     | randompatches                     | 1.12.2-1.14.0.0          | randompatches-1.12.2-1.14.0.0.jar                  | None                                     |
       | L     | actuallyadditions                 | 1.12.2-r145              | ActuallyAdditions-1.12.2-r145.jar                  | None                                     |
       | L     | actuallybaubles                   | 1.1                      | ActuallyBaubles-1.12-1.1.jar                       | None                                     |
       | L     | ae2stuff                          | 0.7.0.4                  | ae2stuff-0.7.0.4-mc1.12.2.jar                      | None                                     |
       | L     | ae2wtlib                          | 1.0.6                    | AE2WTLib-1.12.2-1.0.6.jar                          | None                                     |
       | L     | akashictome                       | 1.2-12                   | AkashicTome-1.2-12.jar                             | None                                     |
       | L     | flyringbaublemod                  | 0.3.1_1.12-d4e654e       | angelRingToBauble-1.12-0.3.1.50+d4e654e.jar        | None                                     |
       | L     | appleskin                         | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                         | None                                     |
       | L     | appliedenergistics2               | rv6-stable-6             | appliedenergistics2-rv6-stable-6.jar               | None                                     |
       | L     | architecturecraft                 | @VERSION@                | architecturecraft-1.12-3.80.jar                    | None                                     |
       | L     | attributefix                      | 1.0.4                    | AttributeFix-1.12.2-1.0.4.jar                      | None                                     |
       | L     | autoreglib                        | 1.3-26                   | AutoRegLib-1.3-26.jar                              | None                                     |
       | L     | avaritia                          | 3.3.0                    | Avaritia-1.12.2-3.3.0.33-universal.jar             | None                                     |
       | L     | badwithernocookiereloaded         | 1.12.2-3.3.16            | badwithernocookiereloaded-1.12.2-3.3.16.jar        | None                                     |
       | L     | base                              | 3.11.0                   | base-1.12.2-3.11.0.jar                             | None                                     |
       | L     | baubles                           | 1.5.2                    | Baubles-1.12-1.5.2.jar                             | None                                     |
       | L     | bdlib                             | 1.14.3.12                | bdlib-1.14.3.12-mc1.12.2.jar                       | None                                     |
       | L     | bedpatch                          | 2.2                      | bedpatch-2.2-1.12.2.jar                            | None                                     |
       | L     | betterbuilderswands               | 0.13.0                   | BetterBuildersWands-1.12.2-0.13.0.267+dc89c58.jar  | None                                     |
       | L     | blockcraftery                     | 1.12.2-1.1.0             | blockcraftery-1.12.2-1.1.0.jar                     | None                                     |
       | L     | bonsaitrees                       | 1.1.2                    | bonsaitrees-1.1.2-b144.jar                         | None                                     |
       | L     | bookshelf                         | 2.3.574                  | Bookshelf-1.12.2-2.3.574.jar                       | None                                     |
       | L     | botania                           | r1.10-360                | Botania r1.10-360.jar                              | None                                     |
       | L     | brandonscore                      | 2.4.9                    | BrandonsCore-1.12.2-2.4.9.195-universal.jar        | None                                     |
       | L     | buildcraftcompat                  | 7.99.22                  | buildcraft-all-7.99.22.jar                         | None                                     |
       | L     | buildcraftbuilders                | 7.99.22                  | buildcraft-all-7.99.22.jar                         | None                                     |
       | L     | buildcraftcore                    | 7.99.22                  | buildcraft-all-7.99.22.jar                         | None                                     |
       | L     | buildcraftenergy                  | 7.99.22                  | buildcraft-all-7.99.22.jar                         | None                                     |
       | L     | buildcraftfactory                 | 7.99.22                  | buildcraft-all-7.99.22.jar                         | None                                     |
       | L     | buildcraftlib                     | 7.99.22                  | buildcraft-all-7.99.22.jar                         | None                                     |
       | L     | buildcraftrobotics                | 7.99.22                  | buildcraft-all-7.99.22.jar                         | None                                     |
       | L     | buildcraftsilicon                 | 7.99.22                  | buildcraft-all-7.99.22.jar                         | None                                     |
       | L     | buildcrafttransport               | 7.99.22                  | buildcraft-all-7.99.22.jar                         | None                                     |
       | L     | buildinggadgets                   | 2.6.5                    | BuildingGadgets-2.6.5.jar                          | None                                     |
       | L     | ceramics                          | 1.12-1.3.6               | Ceramics-1.12-1.3.6.jar                            | None                                     |
       | L     | chameleon                         | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                           | None                                     |
       | L     | chancecubes                       | 1.12.2-3.2.3.242         | ChanceCubes-1.12.2-3.2.3.242.jar                   | None                                     |
       | L     | chesttransporter                  | 2.8.8                    | ChestTransporter-1.12.2-2.8.8.jar                  | None                                     |
       | L     | chickens                          | 6.1.0                    | chickens-6.1.0.jar                                 | None                                     |
       | L     | chisel                            | MC1.12.2-0.2.1.35        | Chisel-MC1.12.2-0.2.1.35.jar                       | None                                     |
       | L     | chiselsandbits                    | 14.30                    | chiselsandbits-14.30.jar                           | None                                     |
       | L     | clipboard                         | @VERSION@                | Clipboard-1.12-1.3.0.jar                           | None                                     |
       | L     | clumps                            | 3.1.2                    | Clumps-3.1.2.jar                                   | None                                     |
       | L     | codechickenlib                    | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar      | None                                     |
       | L     | cofhcore                          | 4.6.2                    | CoFHCore-1.12.2-4.6.2.25-universal.jar             | None                                     |
       | L     | cofhworld                         | 1.3.0                    | CoFHWorld-1.12.2-1.3.0.6-universal.jar             | None                                     |
       | L     | commoncapabilities                | 2.0.3                    | CommonCapabilities-1.12.2-2.0.3.jar                | None                                     |
       | L     | compactmachines3                  | 3.0.15                   | compactmachines3-1.12.2-3.0.15-b249.jar            | None                                     |
       | L     | contenttweaker                    | 1.12.2-4.9.1             | ContentTweaker-1.12.2-4.9.1.jar                    | None                                     |
       | L     | cookingforblockheads              | 6.4.69                   | CookingForBlockheads_1.12.2-6.4.69.jar             | None                                     |
       | L     | craftingtweaks                    | 8.1.9                    | CraftingTweaks_1.12.2-8.1.9.jar                    | None                                     |
       | L     | crafttweaker                      | 4.1.14                   | CraftTweaker2-1.12-4.1.14.jar                      | None                                     |
       | L     | crafttweakerjei                   | 2.0.2                    | CraftTweaker2-1.12-4.1.14.jar                      | None                                     |
       | L     | cucumber                          | 1.1.3                    | Cucumber-1.12.2-1.1.3.jar                          | None                                     |
       | L     | cxlibrary                         | 1.6.1                    | cxlibrary-1.12.1-1.6.1.jar                         | None                                     |
       | L     | cyclicmagic                       | 1.17.16                  | Cyclic-1.12.2-1.17.16.jar                          | None                                     |
       | L     | cyclopscore                       | 1.0.4                    | CyclopsCore-1.12.2-1.0.4.jar                       | None                                     |
       | L     | danknull                          | 1.4.46                   | DankNull-1.12-1.4.46.jar                           | None                                     |
       | L     | darkutils                         | 1.8.223                  | DarkUtils-1.12.2-1.8.223.jar                       | None                                     |
       | L     | diethopper                        | 1.1                      | diethopper-1.1.jar                                 | None                                     |
       | L     | draconicevolution                 | 2.3.20                   | Draconic-Evolution-1.12.2-2.3.20.333-universal.jar | None                                     |
       | L     | endercore                         | 1.12.2-0.5.45            | EnderCore-1.12.2-0.5.45.jar                        | None                                     |
       | L     | enderio                           | 5.0.40                   | EnderIO-1.12.2-5.0.40.jar                          | None                                     |
       | L     | enderiobase                       | 5.0.40                   | EnderIO-1.12.2-5.0.40.jar                          | None                                     |
       | L     | enderioconduits                   | 5.0.40                   | EnderIO-1.12.2-5.0.40.jar                          | None                                     |
       | L     | enderioconduitsappliedenergistics | 5.0.40                   | EnderIO-1.12.2-5.0.40.jar                          | None                                     |
       | L     | enderioconduitsopencomputers      | 5.0.40                   | EnderIO-1.12.2-5.0.40.jar                          | None                                     |
       | L     | enderioconduitsrefinedstorage     | 5.0.40                   | EnderIO-1.12.2-5.0.40.jar                          | None                                     |
       | L     | enderiointegrationforestry        | 5.0.40                   | EnderIO-1.12.2-5.0.40.jar                          | None                                     |
       | L     | enderiointegrationtic             | 5.0.40                   | EnderIO-1.12.2-5.0.40.jar                          | None                                     |
       | L     | enderiointegrationticlate         | 5.0.40                   | EnderIO-1.12.2-5.0.40.jar                          | None                                     |
       | L     | enderiomachines                   | 5.0.40                   | EnderIO-1.12.2-5.0.40.jar                          | None                                     |
       | L     | enderiopowertools                 | 5.0.40                   | EnderIO-1.12.2-5.0.40.jar                          | None                                     |
       | L     | enderioendergy                    | 5.0.40                   | EnderIO-endergy-1.12.2-5.0.40.jar                  | None                                     |
       | L     | enderstorage                      | 2.4.5.135                | EnderStorage-1.12.2-2.4.5.135-universal.jar        | None                                     |
       | L     | environmentaltech                 | 1.12.2-2.0.19.1          | environmentaltech-1.12.2-2.0.19.1.jar              | None                                     |
       | L     | exchangers                        | 1.12.2-2.8               | Exchangers-1.12.2-2.8.jar                          | None                                     |
       | L     | excompressum                      | 3.0.26                   | ExCompressum_1.12.2-3.0.26.jar                     | None                                     |
       | L     | exnihilocreatio                   | 1.12.2-0.3.8.3           | exnihilocreatio-1.12.2-0.3.8.3.jar                 | None                                     |
       | L     | expequiv                          | 11b                      | ExpandedEquivalence-1.12.2-11b.jar                 | None                                     |
       | L     | extracells                        | 2.6.3                    | ExtraCells-1.12.2-2.6.3aNIGHTLY.jar                | None                                     |
       | L     | extrautils2                       | 1.0                      | extrautils2-1.12-1.9.9.jar                         | None                                     |
       | L     | bigreactors                       | 1.12.2-0.4.5.50          | ExtremeReactors-1.12.2-0.4.5.50.jar                | None                                     |
       | L     | farmingforblockheads              | 3.1.26                   | FarmingForBlockheads_1.12.2-3.1.26.jar             | None                                     |
       | L     | fasterladderclimbing              | 0.1-146                  | FasterLadderClimbing-1.12-0.1-146.jar              | None                                     |
       | L     | fastfurnace                       | 1.2.1                    | FastFurnace-1.12.2-1.2.1.jar                       | None                                     |
       | L     | fastleafdecay                     | v14                      | FastLeafDecay-v14.jar                              | None                                     |
       | L     | fastbench                         | 1.6.1                    | FastWorkbench-1.12.2-1.6.1.jar                     | None                                     |
       | L     | flatcoloredblocks                 | mc1.12-6.6               | flatcoloredblocks-mc1.12-6.6.jar                   | None                                     |
       | L     | fluidcows                         | 1.1.16                   | FluidCows-1.1.16.jar                               | None                                     |
       | L     | fluxnetworks                      | 3.0.19                   | fluxnetworks-1.12.2-3.0.19-21.jar                  | None                                     |
       | L     | foamfix                           | 0.10.3-1.12.2            | foamfix-0.10.3-1.12.2.jar                          | None                                     |
       | L     | forgelin                          | 1.8.2                    | Forgelin-1.8.2.jar                                 | None                                     |
       | L     | framland                          | 1.12.2-1.0.7.11          | framland-1.12.2-1.0.7.11.jar                       | None                                     |
       | L     | ftblib                            | 5.4.1.85                 | FTBLib-5.4.1.85.jar                                | None                                     |
       | L     | ftbquests                         | 1.5.1.132                | FTBQuests-1.5.1.132.jar                            | None                                     |
       | L     | ftbutilities                      | 5.4.0.84                 | FTBUtilities-5.4.0.84.jar                          | None                                     |
       | L     | ftbbackups                        | 0.0.0.ftbbackups         | FTBUtilitiesBackups-1.0.0.1.jar                    | None                                     |
       | L     | gasconduits                       | 1.12.2-1.0.0             | GasConduits-1.12.2-1.0.0.jar                       | None                                     |
       | L     | gravestone                        | 1.10.2                   | gravestone-1.10.2.jar                              | None                                     |
       | L     | hammercore                        | 2.0.4.1                  | HammerCore-1.12.2-2.0.4.1.jar                      | None                                     |
       | L     | hatchery                          | 2.2.1                    | hatchery-1.12.2-2.2.1.jar                          | None                                     |
       | L     | ichunutil                         | 7.1.4                    | iChunUtil-1.12.2-7.1.4.jar                         | None                                     |
       | L     | industrialforegoing               | 1.12.2-1.12.2            | industrialforegoing-1.12.2-1.12.6-230.jar          | None                                     |
       | L     | industrialmeat                    | 1.12-1.0.2               | industrialmeat-1.12-1.0.2.jar                      | None                                     |
       | L     | integrateddynamics                | 1.0.7                    | IntegratedDynamics-1.12.2-1.0.7.jar                | None                                     |
       | L     | integrateddynamicscompat          | 1.0.0                    | IntegratedDynamics-1.12.2-1.0.7.jar                | None                                     |
       | L     | integratedtunnels                 | 1.6.7                    | IntegratedTunnels-1.12.2-1.6.7.jar                 | None                                     |
       | L     | integratedtunnelscompat           | 1.0.0                    | IntegratedTunnels-1.12.2-1.6.7.jar                 | None                                     |
       | L     | integrationforegoing              | 1.12.2-1.9               | IntegrationForegoing-1.12.2-1.9.jar                | None                                     |
       | L     | inventorytweaks                   | 1.64+dev.146.2180b27     | InventoryTweaks-1.64+dev.146.jar                   | None                                     |
       | L     | ironbackpacks                     | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar                  | None                                     |
       | L     | ironchest                         | 1.12.2-7.0.59.842        | ironchest-1.12.2-7.0.59.842.jar                    | None                                     |
       | L     | itemfilters                       | 1.0.1.8                  | ItemFilters-1.0.1.8.jar                            | None                                     |
       | L     | jei                               | 4.14.4.264               | jei_1.12.2-4.14.4.264.jar                          | None                                     |
       | L     | jee                               | 1.0.6                    | JustEnoughEnergistics-1.12.2-1.0.6.jar             | None                                     |
       | L     | kleeslabs                         | 5.4.11                   | KleeSlabs_1.12.2-5.4.11.jar                        | None                                     |
       | L     | letsencryptcraft                  | @VERSION@                | letsencryptcraft-1.10.2-1.2.0.jar                  | None                                     |
       | L     | loottweaker                       | 0.0.8                    | LootTweaker-1.12.2-0.0.8.jar                       | None                                     |
       | L     | malisiscore                       | 1.12.2-6.4.0             | malisiscore-1.12.2-6.4.0.jar                       | None                                     |
       | L     | malisisdoors                      | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar                      | None                                     |
       | L     | mantle                            | 1.12-1.3.3.42            | Mantle-1.12-1.3.3.42.jar                           | None                                     |
       | L     | mcjtylib_ng                       | 3.1.1                    | mcjtylib-1.12-3.1.1.jar                            | None                                     |
       | L     | mekanism                          | 1.12.2-9.4.13.349        | Mekanism-1.12.2-9.4.13.349.jar                     | None                                     |
       | L     | mekanismgenerators                | 9.4.11                   | MekanismGenerators-1.12.2-9.4.13.349.jar           | None                                     |
       | L     | mekanismtools                     | 9.4.11                   | MekanismTools-1.12.2-9.4.13.349.jar                | None                                     |
       | L     | mightyenderchicken                | 7.2.0                    | MightyEnderChicken-1.12.2-7.2.0.jar                | None                                     |
       | L     | minetogether                      | unspecified              | minetogether-1.10.2-2.1.3.jar                      | None                                     |
       | L     | minetogetherserver                | unspecified              | minetogether-1.10.2-2.1.3.jar                      | None                                     |
       | L     | missing_pieces                    | 4.3.0                    | missing_pieces-1.12.2-4.3.0.jar                    | None                                     |
       | L     | mob_grinding_utils                | 0.3.13                   | MobGrindingUtils-0.3.13.jar                        | None                                     |
       | L     | modtweaker                        | 4.0.16                   | modtweaker-4.0.16.jar                              | None                                     |
       | L     | morechickens                      | 3.1.0                    | morechickens-1.12.2-3.1.0.jar                      | None                                     |
       | L     | morefurnaces                      | 1.10.5                   | MoreFurnaces-1.12.2-1.10.6.jar                     | None                                     |
       | L     | morph                             | 7.1.2                    | Morph-1.12.2-7.1.2.jar                             | None                                     |
       | L     | morphtool                         | 1.2-21                   | Morph-o-Tool-1.2-21.jar                            | None                                     |
       | L     | morpheus                          | 1.12.2-3.5.106           | Morpheus-1.12.2-3.5.106.jar                        | None                                     |
       | L     | mputils                           | 1.5.6                    | MPUtils-1.12.2-1.5.6.jar                           | None                                     |
       | L     | mrtjpcore                         | 2.1.3.35                 | MrTJPCore-1.12.2-2.1.3.35-universal.jar            | None                                     |
       | L     | mtlib                             | 3.0.5                    | MTLib-3.0.5.jar                                    | None                                     |
       | L     | mysticalagradditions              | 1.2.10                   | MysticalAgradditions-1.12.2-1.2.10.jar             | None                                     |
       | L     | mysticalagriculture               | 1.7.1                    | MysticalAgriculture-1.12.2-1.7.1.jar               | None                                     |
       | L     | mysticallib                       | 1.12.2-1.0.0             | mysticallib-1.12.2-1.0.0.jar                       | None                                     |
       | L     | nmsot                             | 1.2.2-mc1.12.2           | NoMobSpawningOnTrees-1.2.2-mc1.12.2.jar            | None                                     |
       | L     | notemastahp                       | 1.0.1                    | NoTemaStahp-1.12.2-1.0.1.jar                       | None                                     |
       | L     | notenoughwands                    | 1.7.3                    | notenoughwands-1.12-1.7.3.jar                      | None                                     |
       | L     | openblocks                        | 1.8                      | OpenBlocks-1.12.2-1.8.jar                          | None                                     |
       | L     | oreberries                        | 0.5.0                    | oreberries-1.12.x-0.5.0.jar                        | None                                     |
       | L     | oreexcavation                     | 1.4.137                  | OreExcavation-1.4.137.jar                          | None                                     |
       | L     | p455w0rdslib                      | 2.0.36                   | p455w0rdslib-1.12.2-2.0.36.jar                     | None                                     |
       | L     | packcrashinfo                     | %VERSION%                | packcrashinfo-1.0.1.jar                            | None                                     |
       | L     | harvestcraft                      | 1.12.2zb                 | Pam's HarvestCraft 1.12.2zb.jar                    | None                                     |
       | L     | petrock                           | 0.3.1                    | petrock-0.3.1.jar                                  | None                                     |
       | L     | placebo                           | 1.5.1                    | Placebo-1.12.2-1.5.1.jar                           | None                                     |
       | L     | plustic                           | 7.0.0.0                  | plustic-7.0.0.0.jar                                | None                                     |
       | L     | projecte                          | 1.12-PE1.3.2h            | ProjectE-1.12-PE1.3.2h.jar                         | None                                     |
       | L     | projectex                         | 1.0.0.10                 | ProjectEX-1.0.0.10.jar                             | None                                     |
       | L     | projectintelligence               | 1.0.2                    | ProjectIntelligence-1.12.2-1.0.2.16-universal.jar  | None                                     |
       | L     | projectred-core                   | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-Base.jar                | None                                     |
       | L     | projectred-compat                 | 1.0                      | ProjectRed-1.12.2-4.9.1.92-compat.jar              | None                                     |
       | L     | projectred-fabrication            | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-fabrication.jar         | None                                     |
       | L     | projectred-integration            | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-integration.jar         | None                                     |
       | L     | projectred-transmission           | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-integration.jar         | None                                     |
       | L     | projectred-illumination           | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-lighting.jar            | None                                     |
       | L     | projectred-expansion              | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-mechanical.jar          | None                                     |
       | L     | projectred-relocation             | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-mechanical.jar          | None                                     |
       | L     | projectred-transportation         | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-mechanical.jar          | None                                     |
       | L     | psi                               | r1.1-72                  | Psi-r1.1-72.jar                                    | None                                     |
       | L     | quantumflux                       | 2.0.17                   | quantumflux-1.12.2-2.0.17.jar                      | None                                     |
       | L     | randomthings                      | 4.2.6                    | RandomThings-MC1.12.2-4.2.6.jar                    | None                                     |
       | L     | randomtweaks                      | 1.12.2-2.4.3.2           | randomtweaks-1.12.2-2.4.3.2.jar                    | None                                     |
       | L     | realdrops                         | 1.2.14                   | RealisticItemDrops-1.2.14.jar                      | None                                     |
       | L     | reborncore                        | 3.13.5.421               | RebornCore-1.12.2-3.13.5.421-universal.jar         | None                                     |
       | L     | redstonearsenal                   | 2.6.2                    | RedstoneArsenal-1.12.2-2.6.2.17-universal.jar      | None                                     |
       | L     | redstoneflux                      | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar            | None                                     |
       | L     | rflux                             | 0.3.2                    | rflux-1.12-0.3.2.jar                               | None                                     |
       | L     | rftools                           | 7.61                     | rftools-1.12-7.61.jar                              | None                                     |
       | L     | rftoolscontrol                    | 1.9.3                    | rftoolsctrl-1.12-1.9.3.jar                         | None                                     |
       | L     | rftoolspower                      | 1.1.2                    | rftoolspower-1.12-1.1.2.jar                        | None                                     |
       | L     | roost                             | 1.3.0                    | roost-1.12-1.3.0.jar                               | None                                     |
       | L     | serverleveltype                   | 1.0                      | ServerLevelType-1.2.jar                            | None                                     |
       | L     | shadowmc                          | 3.8.0                    | ShadowMC-1.12-3.8.0.jar                            | None                                     |
       | L     | simplyjetpacks                    | 2.2.10.63                | SimplyJetpacks2-1.12.2-2.2.10.63.jar               | None                                     |
       | L     | simplylight                       | 0.6.0                    | simplylight-0.6.0.jar                              | None                                     |
       | L     | snad                              | 1.12.1-1.7.09.16a        | Snad-1.12.1-1.7.09.16a.jar                         | None                                     |
       | L     | sonarcore                         | 5.0.19                   | sonarcore-1.12.2-5.0.19-20.jar                     | None                                     |
       | L     | stoneblockdimensions              | 1.0.3                    | StoneBlockDimensions-1.0.3.jar                     | None                                     |
       | L     | stoneblockutilities               | 2.1.4                    | StoneBlockUtilities-2.1.4.jar                      | None                                     |
       | L     | stonechest                        | 1.0.4                    | StoneChest-1.0.4.jar                               | None                                     |
       | L     | storagedrawers                    | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.8.jar                    | None                                     |
       | L     | tconstruct                        | 1.12.2-2.12.0.115        | TConstruct-1.12.2-2.12.0.115.jar                   | None                                     |
       | L     | teslacorelib                      | 1.0.15                   | tesla-core-lib-1.12.2-1.0.15.jar                   | None                                     |
       | L     | teslacorelib_registries           | 1.0.15                   | tesla-core-lib-1.12.2-1.0.15.jar                   | None                                     |
       | L     | thaumcraft                        | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar                   | None                                     |
       | L     | tcinventoryscan                   | 2.0.10                   | ThaumicInventoryScanning_1.12.2-2.0.10.jar         | None                                     |
       | L     | thaumicterminal                   | 1.0.10                   | ThaumicTerminal-1.0.10.jar                         | None                                     |
       | L     | theoneprobe                       | 1.4.28                   | theoneprobe-1.12-1.4.28.jar                        | None                                     |
       | L     | thermalcultivation                | 0.3.2                    | ThermalCultivation-1.12.2-0.3.2.11-universal.jar   | None                                     |
       | L     | thermaldynamics                   | 2.5.4                    | ThermalDynamics-1.12.2-2.5.4.18-universal.jar      | None                                     |
       | L     | thermalexpansion                  | 5.5.3                    | ThermalExpansion-1.12.2-5.5.3.41-universal.jar     | None                                     |
       | L     | thermalfoundation                 | 2.6.2                    | ThermalFoundation-1.12.2-2.6.2.26-universal.jar    | None                                     |
       | L     | thermalinnovation                 | 0.3.2                    | ThermalInnovation-1.12.2-0.3.2.11-universal.jar    | None                                     |
       | L     | tinkertoolleveling                | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar                | None                                     |
       | L     | tp                                | 3.2.32                   | tinyprogressions-1.12.2-3.3.32-Release.jar         | None                                     |
       | L     | tmel                              | 1.12.2-1.3.2.2           | tmel-1.12.2-1.3.2.2.jar                            | None                                     |
       | L     | topaddons                         | 1.12.2-1.10.1            | topaddons-1.12.2-1.10.1.jar                        | None                                     |
       | L     | torchmaster                       | 1.7.1.74                 | torchmaster_1.12.2-1.7.1.74.jar                    | None                                     |
       | L     | tramplestopper                    | 1.2.3                    | tramplestopper-1.12.2-1.2.3-universal.jar          | None                                     |
       | L     | translocators                     | 2.5.1.77                 | Translocators-1.12.2-2.5.1.77-universal.jar        | None                                     |
       | L     | ts2k16                            | 1.2.10                   | TS2K16-1.2.10.jar                                  | None                                     |
       | L     | unidict                           | 1.12.2-2.9.2             | UniDict-1.12.2-2.9.2.jar                           | None                                     |
       | L     | uppers                            | 0.0.6                    | Uppers-0.0.6.jar                                   | None                                     |
       | L     | universalmodifiers                | 1.12.2-1.0.16.1          | valkyrielib-1.12.2-2.0.19.1.jar                    | None                                     |
       | L     | valkyrielib                       | 1.12.2-2.0.19.1          | valkyrielib-1.12.2-2.0.19.1.jar                    | None                                     |
       | L     | vanillafix                        | 1.0.10-SNAPSHOT          | VanillaFix-1.0.10-99.jar                           | None                                     |
       | L     | voidislandcontrol                 | 1.5.3                    | voidislandcontrol-1.5.3.jar                        | None                                     |
       | L     | wanionlib                         | 1.12.2-2.2               | WanionLib-1.12.2-2.2.jar                           | None                                     |
       | L     | wct                               | 3.11.88                  | WirelessCraftingTerminal-1.12.2-3.11.88.jar        | None                                     |
       | L     | wrcbe                             | 2.3.1                    | WR-CBE-1.12.2-2.3.1.30-universal.jar               | None                                     |
       | L     | xnet                              | 1.7.6                    | xnet-1.12-1.7.6.jar                                | None                                     |
       | L     | xtones                            | 1.12-1.0.8-11            | Xtones-1.12-1.0.8-11.jar                           | None                                     |
       | L     | yabba                             | 1.1.2.44                 | YABBA-1.1.2.44.jar                                 | None                                     |
       | L     | ynot                              | 0.2.3                    | YNot-0.2.3.jar                                     | None                                     |
       | L     | zerocore                          | 1.12-0.1.2.3             | zerocore-1.12-0.1.2.3.jar                          | None                                     |
       | L     | llibrary                          | 1.7.17                   | llibrary-1.7.17-1.12.2.jar                         | None                                     |
       | L     | immersiveengineering              | 0.12-89                  | ImmersiveEngineering-0.12-89.jar                   | None                                     |
  Loaded coremods (and transformers): SplashAnimationCoremod (SplashAnimation-0.2.1.jar)
                                        pl.asie.splashanimation.core.SplashProgressTransformer
                                      RandomPatches (randompatches-1.12.2-1.14.0.0.jar)
                                        com.therandomlabs.randompatches.core.RPTransformer
                                      BedPatch (bedpatch-2.2-1.12.2.jar)
                                        com.mordenkainen.bedpatch.BedPatchASM
                                      Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
                                        cubex2.cxlibrary.CoreModTransformer
                                      ForgelinPlugin (Forgelin-1.8.2.jar)
                                        
                                      CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      HCASM (HammerCore-1.12.2-2.0.4.1.jar)
                                        com.zeitheron.hammercore.asm.HammerCoreTransformer
                                      MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
                                        
                                      LoadingPlugin (RandomThings-MC1.12.2-4.2.6.jar)
                                        lumien.randomthings.asm.ClassTransformer
                                      IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
                                        blusunrize.immersiveengineering.common.asm.IEClassTransformer
                                      llibrary (llibrary-core-1.0.10-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      CorePlugin (SmoothFont-mc1.12.2-1.16.2.jar)
                                        bre.smoothfont.asm.Transformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
                                        lumien.resourceloader.asm.ClassTransformer
                                      EnderCorePlugin (EnderCore-1.12.2-0.5.45.jar)
                                        com.enderio.core.common.transform.EnderCoreTransformer
                                        com.enderio.core.common.transform.SimpleMixinPatcher
                                      EECore (ExpandedEquivalence-1.12.2-11b.jar)
                                        com.zeitheron.expequiv.core.EETransformer
  Suspected Mods: Unknown
  Profiler Position: N/A (disabled)
  Is Modded: Definitely; Server brand changed to 'fml,forge'
  Type: Dedicated Server (map_server.txt)

**Comment by Sunekaer** [comment]
No clue, are you hosting this server yourself?
