### ISSUE TITLE
Player model issues/Map issues

### ISSUE THREAD

**Issue by BlueSpirit180** [FTBTeam/FTB-Presents-Stoneblock-2#397]
Version: FTBPresentsStoneblock2-1.8.0-1.12.2.zip

Minecraft Version: 1.12.2

(modded) forge-14.23.5.2808

I was having memory problems so i tweaked some ingame settings and twitch launcher settings for playing, joined my single player server just fine but now my player models arms are spinning wildly and i keep falling through the map rendering it unplayable. 
 
its not crashing it runs fine with fine FPS just cant walk or turn around much

It is repeatable

**Comment by BlueSpirit180** [comment]
I recorded a video of it happening in game, if i dont get many responses in a few days im going to uninstall. I have a modpack called Breakout that is much like this one and i might as well beat it first. Link to video here https://youtu.be/9iLEXCyPehA

**Comment by Sunekaer** [comment]
Set you BetterFPS setting back to 
"algorithm":"rivens-alf",
"updateChecker":false,
"preallocateMemory":false,
"fog":true,
"beaconBeam":true,
"fastHopper":true,
"fastBeacon":false,
"fastSearch":true,
"asyncSearch":true
