### ISSUE TITLE
Attempt to Morph crashed client

### ISSUE THREAD

**Issue by OverloadedWolf** [FTBTeam/FTB-Presents-Stoneblock-2#4]
* **Modpack Version**: 1.0.0

* **Issue**: Attempting to morph to another mob or back to player model crashes the client.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/e463dbfc

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Morph, possibly PetRock (As that was what I tried to morph to)

* **Known Fix**: No known fix apart from removal of Morph

**Comment by iChun** [comment]
If it's just an issue with the Pet Rock then you could try and not morph into it. Since it's a crash with the player renderer you can turn off handRenderOverride in the Morph config to morph back to your player and out of the pet rock as a workaround for now.

**Comment by iChun** [comment]
Or... hold an item so that the mod doesn't try to render your hand.

**Comment by Sunekaer** [comment]
I can not reproduce this issue, does it happen with other entities?
Also could you try using a newer java version?

**Comment by OverloadedWolf** [comment]
Tried without petrock, seems to work. Will still keep an eye out on it.

**Comment by Sunekaer** [comment]
Thanks ill blacklist the petrock if i heard others having problems with that  one

**Comment by Sunekaer** [comment]
What OS are you on @OverloadedWolf  and @SuurflieG

**Comment by OverloadedWolf** [comment]
Windows 10

**Comment by SuurflieG** [comment]
Windows 10. I can confirm that changing to a itwm in your hand allows you to morph back and the crashes stop

**Comment by OverloadedWolf** [comment]
Just occured again. Didn't have anything in my hand when I was trying to transform from a bat back to human. And it crashed on start of animation.

**Comment by Snowman-25** [comment]
Just updated to Version 1.2.0 of Stoneblock 2 through Twitch client.
When morphing, my game crashes.
Running Windows 7.
Here's my log:
[crash-2019-01-23_18.40.42-client.txt](https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/files/2788476/crash-2019-01-23_18.40.42-client.txt)
