### ISSUE TITLE
Fluid Cow Dupe Bug

### ISSUE THREAD

**Issue by mtjohnson47** [FTBTeam/FTB-Presents-Stoneblock-2#40]
* **Modpack Version**: 1.0.1

* **Issue**: Moving Fluid cow stalls with a cardboard box dupes the cow.

* **Is it Repeatable?**: yes

* **Steps to repeat**: 

1. Place a cow in a cow stall.
2. Put a cardboard box on the stall.  A fluid cow will appear in world.
3. Move the box.  I'm not sure if this is necessary.
4. Remove the box.  The stall will appear empty, but still function, and the invisible cow can be removed.
5. Remove the cow.  You now have 2 of that cow.

* **Mod/s Affected**: Fluid Cows, Mekanism

* **Known Fix**: Blacklist Cow Stalls from the cardboard box, if possible.  Otherwise, disable the cardboard box, but I really hope you don't have to do that.

**Comment by Sunekaer** [comment]
Thanks for reporting

**Comment by Sunekaer** [comment]
Blacklist Cow Stalls from the cardboard box

**Comment by Sunekaer** [comment]
1.1.0
