### ISSUE TITLE
stone block 2 keep crashing 

### ISSUE THREAD

**Issue by necro367** [FTBTeam/FTB-Presents-Stoneblock-2#401]
stone block 2 keep crashing 
https://paste.dimdev.org/ikefajufin.mccrash
![Capture](https://user-images.githubusercontent.com/48497831/54241512-8fb31580-44f7-11e9-8289-09034c496730.JPG)

**Comment by Sunekaer** [comment]
Seem that the file has been corrupted or overwritten with a blank file.
I would recommend you restore the minetogether.cfg from the latest update of the pack to fix the issue.
