### ISSUE TITLE
AE2 Inventory Inaccessible Since 1.8.0

### ISSUE THREAD

**Issue by TheShadows645** [FTBTeam/FTB-Presents-Stoneblock-2#402]
Using Version 1.8.0 on Server and Client

AE2 Inventories appear correctly when opened, however unable to remove or input anything, and cannot "craft" using Auto-crafting set up in AE2, Worked fine in previous release

Bug is repeatable

AE2 seems to be the only Mod effected

**Comment by Sunekaer** [comment]
AE2 hasnt been update or change in many updates, my AE system works fine, does others have this problem on the server?

**Comment by TheShadows645** [comment]
Did check the change-log and saw nothing had changed with AE2, wonder if its perheps something else interferring with it or whether I managed to mess up the server update. 

Both myself and the other person playing on the server have issues.

**Comment by Sunekaer** [comment]
Can you show the issue, as i dont have any problems using my system

**Comment by TheShadows645** [comment]
Apologies for the delay, I'll grab in a screen capture when I get off work and post it here.

**Comment by tsuuii** [comment]
i have same problem, it doesn't let take or put anything to me network
(user of probably different server).

jei doesn't add recipe to crafting grid either. 
when looking "me crafting terminal" the crafting grid is grey (should be white?)
