### ISSUE TITLE
ALL FURNACES PROBLEM

### ISSUE THREAD

**Issue by JKNel** [FTBTeam/FTB-Presents-Stoneblock-2#403]
* **Modpack Version**: 
1.8.0
* **Issue**: 
None of the furnaces want to accept anything as a fuel source
* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 
Yes

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Sunekaer** [comment]
![image](https://user-images.githubusercontent.com/18720460/54304469-84c6b680-45c5-11e9-8f3e-5e17321a87dc.png)
Works just fine

**Comment by JKNel** [comment]
ever since I started with roost mod no fuel source works in furnaces in survival I even started a brand new world cause maybe it was just a glitch but once again when I started with roost my furnaces were rendered useless.

**Comment by JKNel** [comment]
I went back in and destroyed my chicken breeder and chicken rooster but my furnaces didn't work the only to make them work again is to break the breeder, break the chichen rooster , save and quit to main menu and then reenter map then my furnaces work once more but this means that I wont be able to use roost mod plz help it is very bothersome that I have to destroy my roost item, exit the map and reenter it in order for my furnaces to work.

**Comment by JKNel** [comment]
I sincerely apologize I just forgot to make my ore pieces into chunks everything is fine now I feel so stupid 
:_-(
