### ISSUE TITLE
bug ae2 autocraft

### ISSUE THREAD

**Issue by miouwarp** [FTBTeam/FTB-Presents-Stoneblock-2#404]
Hello

my problem is that applied energistics 2 does not want to craft my autocraft whereas i have all the resources and the autocrafteur are pretty powerful
it shows me the list of items and craft and when you click on strat it is nothing
i have resources that are directly in ae2 and other in drawers connect with a storage bus

example: crafter 10x 64k component storage impossible
but if i craft some item before, defies it well but 1 or 2 at the same time

same bug on version 1.7.0-1.12.1 and on 1.9.0-1.12.1

if you can help me find the cause
thank you

**Comment by JMFerg** [comment]
I am having the same/similar issue, Created a Red Matter with AE2 auto crafting it finished but now when I click "Next" on the screen where you select the number you want to create it closes the crafting pop up. Unable to craft anything. I have rebooted my system and this is a local game.

**Comment by miouwarp** [comment]
I will try this

**Comment by miouwarp** [comment]
![2019-03-18_11 22 37](https://user-images.githubusercontent.com/38194568/54523751-91099580-4970-11e9-8baa-e7320abb9ab9.png)
![2019-03-18_11 22 56](https://user-images.githubusercontent.com/38194568/54523753-91a22c00-4970-11e9-8388-81636b51de42.png)
![2019-03-18_11 23 04](https://user-images.githubusercontent.com/38194568/54523754-91a22c00-4970-11e9-9f1e-724010158af8.png)
![2019-03-18_11 23 11](https://user-images.githubusercontent.com/38194568/54523756-91a22c00-4970-11e9-8a6c-262ae0f52f87.png)


here is my setup with ae2
when i want to crate 10 64k
impossible

**Comment by Sunekaer** [comment]
To be honest with you, i dont know whats wrong with your setup, try creating an issue on https://github.com/AppliedEnergistics/Applied-Energistics-2/issues they will be able to help you find the problem with your setup, or fix the bug if its is one
