### ISSUE TITLE
Thaumcraft Sailis Mundus not usable

### ISSUE THREAD

**Issue by DeungDeung** [FTBTeam/FTB-Presents-Stoneblock-2#405]
* **Modpack Version**: 1.8.0

* **Issue**: I can´t use Salis Mundus on any blocks(Crafting Table, Bookshelf, etc.) and the crucible doesn´t work. Even after a restart it didn´t work.

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Thaumcraft

* **Known Fix**: none

**Comment by Naxanria** [comment]
You need to sleep first before you can put it on a bookshelf and get the book.
