### ISSUE TITLE
Inventory disappearng replaced with OLDER inventory

### ISSUE THREAD

**Issue by MithicFang** [FTBTeam/FTB-Presents-Stoneblock-2#407]
* **Modpack Version**: 1.8.0

* **Issue**:  occasionally i will lag real bad so i will restart, and sometimes my inventory will be replaced with a previous saved inventory, wasnt too bad before cause it was all normal stuff, but i just lost full draconic armour and tools, fully upgraded and enchated, along with several Higly important materials i needed 

* **Is it Repeatable?**: havent been able to successfully recreate

* **Mod/s Affected**: Unknown if its mod specific

* **Known Fix**:  Unable to fix problem

**Comment by Sunekaer** [comment]
Cant do anything about this

**Comment by MithicFang** [comment]
I just lost multiple days worth of items.... and you dont even have any ideas on how to fix it...? you just say cant do anything, and close it.... thats just fantastic. ok guess im done with both Stone block packs since SB1 wont even let me log into my current world. Uninstalling and deleting your mod pack, thanks for the "Help"

**Comment by Naxanria** [comment]
This sounds like you having hard disk problems, You might want to do a disk check. 
So that way, Sunekaer can not fix that for you.
