### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by iluvdemomanandjunkrat** [FTBTeam/FTB-Presents-Stoneblock-2#408]
* **Modpack Version**: 1.9.0

* **Issue**: Game crashes after trying to pick up stuff near cyclic diamond spikes

* **Link to Log or Crash File Paste**: https://paste.dimdev.org/xolanaqini.mccrash

* **Mod/s Affected**: RandomPatches, Realistic Item Drops

**Comment by Sunekaer** [comment]
is single player try updating to RandomPatches 1.12.2-1.15.0.2
