### ISSUE TITLE
Server Crash with mekanism generator and enderio conduits

### ISSUE THREAD

**Issue by lays24mc** [FTBTeam/FTB-Presents-Stoneblock-2#409]
* **Modpack Version**: 
1.9.0

* **Issue**: 
Server crashed, when i join!

* **Link to Log or Crash File Paste**: 

https://pastebin.com/vGGpyies

* **Is it Repeatable?**: 
I used Mekanisem Generator with EnderIO Conduits

**Comment by Sunekaer** [comment]
how are you using Conduits and Mekanisem together?

**Comment by Sunekaer** [comment]
This is not an issue i can fix, without a fix from one of the mod dev, so we need to find out who needs to fix it

**Comment by lays24mc** [comment]
I connected the fluid conduits to the Mekanism Reactor to pump out steam and pump water in

**Comment by Sunekaer** [comment]
Sorry for late reply, could you try with newest version of Mekanism

**Comment by Sunekaer** [comment]
https://www.feed-the-beast.com/projects/ftb-presents-stoneblock-2/files/2694788
