### ISSUE TITLE
Renderer: GUI is not open.

### ISSUE THREAD

**Issue by redawgts** [FTBTeam/FTB-Presents-Stoneblock-2#41]
* **Modpack Version**: 1.0.1

* **Issue**: Every time i push the 6 key on my keyboards numpad I get the following message.

Renderer
GUI is not open.

This isn't in anyway game breaking but I'm left handed and I remap the WASD keys to the numpad so I get the message every time I move right.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Not sure what mod does this.

[
![2019-01-03_19 08 46](https://user-images.githubusercontent.com/6427199/50735588-a055b100-117f-11e9-8cb9-2f6ede2d3844.png)
](url)

**Comment by Sunekaer** [comment]
Keybind conflict.
Change keybind for "[HC] Render Item"
