### ISSUE TITLE
Flat Transfer Nodes causing error

### ISSUE THREAD

**Issue by TearsOfLA** [FTBTeam/FTB-Presents-Stoneblock-2#410]
* **Modpack Version**: 1.8

* **Issue**: Placed a flat transfer node from Extra Utilities 2, received a popup stating there was an error

* **Link to Log or Crash File Paste**: https://paste.dimdev.org/nomizohota.mccrash

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Extra Utilities 2

* **Known Fix**: None, however it does not cause a crash, simply an error

**Comment by TearsOfLA** [comment]
Saw another issue for this that was dismissed by linking it to an unrelated problem. This does not involve placing stacks of blocks into a machine, it involves placing a flat transfer node of any kind onto any sort fo block.

**Comment by Sunekaer** [comment]
Please report this to extra utils, theres nothing i can do about this. 
Thanks
