### ISSUE TITLE
Crash when using RFTools Builder w/ ProjectRed lamps

### ISSUE THREAD

**Issue by russelferd** [FTBTeam/FTB-Presents-Stoneblock-2#411]
* **Modpack Version**: 1.8.0
* **Issue**: Building a hollow half dome with ProjectRed Illumination - Inverted Black lamps with the RFTools Builder. 

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/ff2efab3

* **Is it Repeatable?**: Yes, it has caused a crash on two backups - it will also cause repeated server crashes when rejoining the world if backup is not loaded.

* **Mod/s Affected**: RFTools and ProjectRed Illumination

* **Known Fix**: I haven't found any solution at this time.

**Comment by russelferd** [comment]
After some testing it appears these can't be placed with a building gadget or resonant exchanger.

**Comment by Sunekaer** [comment]
Could you please report this on ProjectRed´s issue tracker, so they can work on a fix
