### ISSUE TITLE
Starting spawn conditions when loading save.

### ISSUE THREAD

**Issue by TorvalHG** [FTBTeam/FTB-Presents-Stoneblock-2#413]
Modpack Version: 1.8.0

Issue: I have been playing for some time, and haven't had a problem until now. I exited the save, but didn't close the game. 30+min later I came back and opened the save, but I spawned in 0,90,0, as if I have started a new game (with the stone cube surrounding me and the starting inventory items). So I loaded a backup of max 15min before that save, and it happened again. I loaded an even older backup and happened again as expected. I checked the level.dat and i have my items in my inventory before loading as usual, but after starting they are deleted. I tried installing 1.9.0 beta and redownloaded 1.8.0 to test and it happened again in both. I restarted my PC and continues happening. I checked voidislandcontrol.cfg and forceSpawn is set to false.
Only settings I changed wre FTB backup timer and FTB utils max claimed and loaded chunks, but other than that it remains the same.

**Comment by TorvalHG** [comment]
Nevermind, I solved it. The solution was finding VICData.dat (name of save/data) from the already loaded save and copying it to the backup save. It's rare because none of the backups seem to use that file (If you open it with NBTEditor it's empty compared with the one after my problem). It's like if the mod (voidislandcontrol) changed how it behaves without updating.

**Comment by Sunekaer** [comment]
Thanks for the information, glad you found a solution, i will forward your solution to the mod developer
