### ISSUE TITLE
Storage Drawers render blocks without lighting

### ISSUE THREAD

**Issue by Chicken-Bones** [FTBTeam/FTB-Presents-Stoneblock-2#414]
* **Modpack Version**: 1.8.0

* **Issue**: 
When hammer core is installed certain mod tile entities render incorrectly. Currently observed incorrect lighting with Storage Drawers on the blockitem render.
Expected: https://i.imgur.com/sUjKAnT.png
Bug: https://i.imgur.com/I3Bp0k0.png

https://gitlab.com/DragonForge/HammerCore/issues/93

* **Is it Repeatable?**:  100%

* **Mod/s Affected**: 
HammerCore-1.12.2-2.0.4.2 and HammerCore-1.12.2-2.0.4.1
StorageDrawers-1.12.2-5.3.8

**Comment by Sunekaer** [comment]
Oh its hammer core causing it, interesting.. i have an issue open at Storage drawers from back in January but haven't heard anything on that one, ill keep an eye on your issue on hammercores page.

Thanks!

**Comment by vegeta897** [comment]
This was happening in 1.9.0 as well, but is fixed in 1.10.0, so I think this issue can be closed.
