### ISSUE TITLE
BetterFps Benchmarking Does Not Work

### ISSUE THREAD

**Issue by MithicSpirit** [FTBTeam/FTB-Presents-Stoneblock-2#415]
* **Modpack Version**: 1.8.0

* **Issue**: In BetterFps Options, Shift-clicking on the algorithm will load for a brief moment but does not appear to benchmark anything and will not change the selected algorithm. This will occur for any selected algorithm.

* ~~**Link to Log or Crash File Paste**: N/A~~

* **Is it Repeatable?**: yes

* **Mod/s Affected**: BetterFps 1.4.8

* ~~**Known Fix**: N/A~~

**Comment by Sunekaer** [comment]
please report to https://github.com/Guichaguri/BetterFps/issues
