### ISSUE TITLE
Recipes conflict

### ISSUE THREAD

**Issue by blarghhh** [FTBTeam/FTB-Presents-Stoneblock-2#416]
* **Modpack Version**: 1.8.0

* **Issue**: 

There is a recipe conflict between lime chickens and nickel chickens.

They both require the same cactus green chicken and bone white chicken.

"chickens:limechicken": {
    "name": "LimeChicken",
    "is_enabled": true,
    "lay_coefficient": 1.0,
    "lay_item": {
      "itemID": "minecraft:dye",
      "metaID": 10
    },
    "drop_item": {
      "itemID": "minecraft:dye",
      "metaID": 10
    },
    "spawn_type": "NONE",
    **"parent_1": "chickens:greenchicken",
    "parent_2": "chickens:whitechicken"**
  },

 "morechickens:nickelchicken": {
    "Name": "nickelchicken",
    "Is Enabled": true,
    "Lay Coefficient": 1.0,
    "Lay Item": "thermalfoundation:material:133",
    "Drop Item": "thermalfoundation:material:133",
    "Spawn Type": "NONE",
    **"Parent 1": "chickens:whitechicken",
    "Parent 2": "chickens:greenchicken"**
  },
* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: yes

* **Mod/s Affected**: 
N/A

* **Known Fix**:

**Comment by Sunekaer** [comment]
not an conflict... it has chance of giving the first one or the second one
