### ISSUE TITLE
Item duping with AE2 and black hole controller

### ISSUE THREAD

**Issue by kman012** [FTBTeam/FTB-Presents-Stoneblock-2#418]
* **Modpack Version**: 1.9

* **Issue**: Item duping with AE2 and black hole controller

* **Link to Log or Crash File Paste**: none

* **Is it Repeatable?**: Yes. Put a black hole unit inside of black hole controller and attach to a AE2 network  with storage bus. Insert item into AE2 network via terminal and the items in the black hole unit will change to whatever item was just put into AE2 network.

* **Mod/s Affected**: AE2 and Industrial Foregoing

* **Known Fix**: A fix for now is don't use black hole controller and just use black hole units.

**Comment by kman012** [comment]
Industrial foregoing got an update today that might supposedly fix it. When I get the chance later today I can update and see.

**Comment by Sunekaer** [comment]
ty

**Comment by kman012** [comment]
The new update fixes the issues.
