### ISSUE TITLE
Bad frame times

### ISSUE THREAD

**Issue by TheSnowyChickens** [FTBTeam/FTB-Presents-Stoneblock-2#419]
* **Modpack Version**: 1.9.0

* **Issue**: I have good FPS (120 stable), but my frame times (ALT + F3) are "bad". (micro stuttering, not smooth picture)

* **Link to Log or Crash File Paste**: Log ->https://paste.feed-the-beast.com/view/8258de35

* **Is it Repeatable?**: Yes, it should.

* **Mod/s Affected**: I don't know.

* **Known Fix**: Nope, sry.

Info: I ONLY have removed some client mods. (inventory tweaks, goggle eyes, and and and)
Info 2: I use Forge 2823, but also with 2808 this occurs.

Pictures:
(with Opti)
![grafik](https://user-images.githubusercontent.com/29357962/54884637-b5cfa280-4e73-11e9-9eaf-eef6121536d2.png)

(without Opti)
![grafik](https://user-images.githubusercontent.com/29357962/54884646-d0a21700-4e73-11e9-98bb-5bad3ae7887b.png)

**Comment by Sunekaer** [comment]
try lowering your assigned ram to 6gb

**Comment by TheSnowyChickens** [comment]
![2019-03-26_23 09 54](https://user-images.githubusercontent.com/29357962/55036912-552f9980-501c-11e9-85ad-6ea4ff4b70b2.png)

**Comment by Sunekaer** [comment]
the whole tabbing in and out thing i havent seen before, but it seems the big spikes are gone, the same spikes is something in your base coursing that

**Comment by TheSnowyChickens** [comment]
I can decrease the spikes by setting the max fps limit to more than my screen heart frequency.

(screen: 120h, FPS limit: higher than 120, V-Sync: on)

**Comment by Sunekaer** [comment]
Sounds like you found an solution to your problem?

**Comment by TheSnowyChickens** [comment]
50%^^
