### ISSUE TITLE
Baguette will not go into draconic chest

### ISSUE THREAD

**Issue by Denslat** [FTBTeam/FTB-Presents-Stoneblock-2#420]
* **Modpack Version**: 
1.90
* **Issue**: 
When attempting to shiftclick or move baguette into a draconic chest, it will not allow it in.
* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 
Yes.
* **Mod/s Affected**: 
Draconic Evolution
Actually Additions
* **Known Fix**: 
I imagine just adding the baguette to the allowable items in the draconic chests related data.

PS: Thanks for coming back for stoneblock 2, last modpack I played and finished was ages ago and it was stoneblock 1. (I am the guy who found the ic2/mekanism uranium ore dupe thing)

**Comment by Sunekaer** [comment]
There is no "allowable" list please report at https://github.com/Ellpeck/ActuallyAdditions
