### ISSUE TITLE
Thaumcraft not working in Stoneblock 2

### ISSUE THREAD

**Issue by jeddell** [FTBTeam/FTB-Presents-Stoneblock-2#421]
* **Modpack Version**: 1.8

* **Issue**: Tried to right click Salis Mundus onto the crafting table (Vanilla). Cant do it. So Thaumcraft cannot be started. Unless there is a different way of starting Thaumcraft?

* **Link to Log or Crash File Paste**: No Crash, just wont start

* **Is it Repeatable?**: Every time

* **Mod/s Affected**: Thaumcraft

* **Known Fix**: Unknown, Will try version 1.9.

**Comment by Sunekaer** [comment]
did you sleep after breaking crystals?
