### ISSUE TITLE
Rotary Condensentrator not outputting

### ISSUE THREAD

**Issue by TheLapisGoat** [FTBTeam/FTB-Presents-Stoneblock-2#422]
* **Modpack Version**: 1.9.0

* **Issue**: The rotary condensentrator from Mekanism does not output the liquid it has created when condensentrating a gas.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Mekanism-1.12.2-9.6.1.353

* **Known Fix**: The updated version of Mekanism seems to have fixed this issue.

**Comment by Sunekaer** [comment]
ty for the information

**Comment by Sunekaer** [comment]
https://www.feed-the-beast.com/projects/ftb-presents-stoneblock-2/files/2694788
