### ISSUE TITLE
My game crash

### ISSUE THREAD

**Issue by Eternalperil** [FTBTeam/FTB-Presents-Stoneblock-2#424]
Modpack version 1.9.0

Upon Loading the game an information screen said P455w0rd's Library had caused a crash

Version of P455word 2.0.36

Link to crash file
https://paste.dimdev.org/jawuniboxu.mccrash

Not repeated

**Comment by Sunekaer** [comment]
And you cant repeat this issue?

**Comment by Sunekaer** [comment]
Mod dev has been informed of the issue, and will look at changing some code to make sure this doesnt happen again
