### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by iSnakeBuzz** [FTBTeam/FTB-Presents-Stoneblock-2#425]
* **Modpack Version**: 1.9.0

* **Issue**: I Consumed a mana potion or something similar, and the game crash

* **Link to Log or Crash File Paste**: CLIENT: https://paste.feed-the-beast.com/view/d8e16bfc SERVER: https://paste.feed-the-beast.com/view/dca729d8

* **Is it Repeatable?**: Every time when i join the world

* **Mod/s Affected**: Random Patches, Realistic Item Drops

**Comment by iSnakeBuzz** [comment]
**UPDATE**
Error occurs when I pick up my head from the ground

**Comment by Sunekaer** [comment]
https://www.feed-the-beast.com/projects/ftb-presents-stoneblock-2/files/2694788
