### ISSUE TITLE
Severe lag issues and delayed movements

### ISSUE THREAD

**Issue by derpendary** [FTBTeam/FTB-Presents-Stoneblock-2#426]
* **Modpack Version**: 1.9.0

* **Issue**: A lot of times when I try to play, I can't play without one (or both) of two types of lag. It is either frame lag, or delayed reaction, meaning that one single press of the forward button sends me walking forward for THREE SECONDS. Often, without realizing it, I keep walking for two whole minutes, and just have to wait for it to stop. When it isn't doing that, it is bombing the frames instead.

* **Link to Log or Crash File Paste**: I apologize, but I don't actually know how to get this, since it isn't a crash.

* **Is it Repeatable?**: Yes; it does it whenever I try to play.

**Comment by Sunekaer** [comment]
Its hard to say whats the issue, its something or things in you world causing your server to lag, youll have to  use something like
```
/forge tps gives tickrate information for all dimensions. Pass in a dimension ID (like /forge tps 0) to get the tickrate for only that dimension.

/forge track allows you to track tick time information about tile entities, and it looks like entities are in the works too. I guess like Opis. Use it like /forge track te <some duration in seconds less than 60>.
```
or https://minecraft.curseforge.com/projects/laggoggles?gameCategorySlug=mc-mods&projectID=283525 to find it
