### ISSUE TITLE
Server crashes whenever i get to/near the chicken farm

### ISSUE THREAD

**Issue by Xfulminex** [FTBTeam/FTB-Presents-Stoneblock-2#427]
Hello, i've found an issue where everytime me or my friend walk to/by the chicken ores farm, the server crashes randomly. This also happens when you put eggs in the egg nest used to hatch the eggs, so i was thinking that the egg nest would be the problem. Can you please check the logs down here? Thank you in advance.

Latest version

Probably the issue is related to the chickens that give ores, not sure about that though.

this is the log to the crash: https://mclo.gs/ifZ8Y9t

**Comment by Sunekaer** [comment]
crash log?
