### ISSUE TITLE
Game crash supposedly due to "Framland"

### ISSUE THREAD

**Issue by derpendary** [FTBTeam/FTB-Presents-Stoneblock-2#428]
* **Modpack Version**: 1.9.0
* **Issue**: I was in the mining dimension, when randomly, Minecraft crashed (By the way, whoever got the crash handler is officially my favorite pack dev) I could tell that it was raining, due to a flash before the chunks loading. 

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/2a332299

* **Is it Repeatable?**: Unsure.

* **Mod/s Affected**: The crash handler pinned Framland as the only mod to blame (version 1.12.2-1.0.8)

**Comment by Sunekaer** [comment]
https://github.com/Gaz492/Framland/issues/3

**Comment by Sunekaer** [comment]
Can you test with this version https://minecraft.curseforge.com/projects/framland/files/2694869
