### ISSUE TITLE
Fluid Laser Relay + Mekanism reactor crash

### ISSUE THREAD

**Issue by Evoplatypus** [FTBTeam/FTB-Presents-Stoneblock-2#429]
* **Modpack Version**: 1.9

* **Issue**: putting a fluid laser relay on a mekanism reactor (running on full) and using the compass to change the mode causes server to crash. 

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/e7b7e614

* **Is it Repeatable?**: did it thrice. (3/3)

* **Mod/s Affected**: Actually Additions and Mekanism

* **Known Fix**: Give to people smarter than me.

**Comment by Sunekaer** [comment]
Are you playing SP or MP? if SP could you try and update all the Mekanism mods and see if that fixes the issue

**Comment by Evoplatypus** [comment]
I am playing on a MP server, but it is my own and the other peeps dropped out, so i can give it a try. 

I did notice that it is specifically around changing the FLR to "Out of adjacent blocks". It also happens with the Turbine, but not the Boiler.

**Comment by Evoplatypus** [comment]
Tested with version 9.6.7.360 of the 3 mekanism mods. Looks like it is fixed.

**Comment by Sunekaer** [comment]
Perfect! ty, ill make sure to update mekanism and get an update out soon

**Comment by Sunekaer** [comment]
https://www.feed-the-beast.com/projects/ftb-presents-stoneblock-2/files/2694788
