### ISSUE TITLE
Stoneblock 2 - Nitor/Crucible issues

### ISSUE THREAD

**Issue by OriginalHer0** [FTBTeam/FTB-Presents-Stoneblock-2#43]
* **Modpack Version**: 1.0.1

* **Issue**: The Yellow Nitor recipe doesn't seem to be working. I have tried several times to create Nitor using the Thaumcraft crucible but instead of creating Nitor it consumes the catalyst as it would a normal ingredient. I cheated in some Goggles of Revealing to check the essentia levels and all were above ten. I checked a few other crucible recipes to rule out crucible error and they seem to work fine.
For my essentia I was using coal/charcoal for the 10 ignis and potentia. Lux was provided for by either a couple torches or some glowstone dust.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: I've tried several times and had no success. Not seen another post on here yet so don't know if it's just me.

* **Mod/s Affected**: Thaumcraft

* **Known Fix**:  Other than cheating in the items, none as of yet.

**Comment by Sunekaer** [comment]
You need to right click the glow stone on the Crucible

**Comment by OriginalHer0** [comment]
I'm aware and it consumes the item. doesn't give me anything back.

**Comment by OriginalHer0** [comment]
Alchemical brass is another recipe that seems to be affected by this

**Comment by Sunekaer** [comment]
Do you have the research in the book to do it?

**Comment by OriginalHer0** [comment]
I do, it unlocks with "Discovering Alchemy" and/or "Basic Alchemy" which is right after you do all the work bench stuff and Thaumometer stuff. 

Interestingly, after cheating in a Nitor using JEI, I can now craft it using the crucible. Same with the alchemical brass.
