### ISSUE TITLE
minecraft crash stone block 2

### ISSUE THREAD

**Issue by jluca93** [FTBTeam/FTB-Presents-Stoneblock-2#430]
*stone block 2 release 1.9.0
* crash after death and crash every time I try to respawn
* ---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2019-03-29 10:37:04 CET
Description: Ticking block entity

java.lang.ClassCastException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Block entity being ticked --
  Name: randomthings:advanceditemcollector // lumien.randomthings.tileentity.TileEntityAdvancedItemCollector
  Block type: ID #832 (tile.advancedItemCollector // lumien.randomthings.block.BlockAdvancedItemCollector // randomthings:advanceditemcollector)
  Block data value: 1 / 0x1 / 0b0001
  Block location: World: (23,91,2), Chunk: (at 7,5,2 in 1,0; contains blocks 16,0,0 to 31,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Actual block type: ID #832 (tile.advancedItemCollector // lumien.randomthings.block.BlockAdvancedItemCollector // randomthings:advanceditemcollector)
  Actual block data value: 1 / 0x1 / 0b0001
  Block Entity NBT: {x:23,y:91,rangeX:5,z:2,id:"randomthings:advanceditemcollector",inventory:{slot0:{empty:1b}},rangeY:5,rangeZ:5}

-- Affected level --
  Level name: Stoneblock 2
  All players: 1 total; [EntityPlayerMP['jLuca93'/660, l='Stoneblock 2', x=27.76, y=90.00, z=1.32]]
  Chunk stats: ServerChunkCache: 625 Drop: 0
  Level seed: -7538618135792466220
  Level generator: ID 07 - voidworld, ver 0. Features enabled: true
  Level generator options: 
  Level spawn location: World: (0,90,0), Chunk: (at 0,5,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Level time: 1879503 game time, 1914338 day time
  Level dimension: 0
  Level storage version: 0x04ABD - Anvil
  Level weather: Rain time: 41769 (now: false), thunder time: 4901 (now: true)
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Mac OS X (x86_64) version 10.14.4
  Java Version: 1.8.0_201, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 947903840 bytes (903 MB) / 3783786496 bytes (3608 MB) up to 5726797824 bytes (5461 MB)
  JVM Flags: 3 total; -Xmx6G -Xms256m -XX:PermSize=256m
  IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
  FML: MCP 9.42 Powered by Forge 14.23.5.2808 259 mods loaded, 259 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
  
CRASH REPORT https://paste.dimdev.org/kuxamazulu.mccrash
* it happens every time I try to play

* *the error message says unknown problem

**Comment by Sunekaer** [comment]
ty

**Comment by jluca93** [comment]
> ty

what do you mean with "ty"?

**Comment by winnetrie83** [comment]
> ty
> 
> what do you mean with "ty"?

It means "thank you"

**Comment by jluca93** [comment]
oh ok sorry! hahahahah! I was thinking about some procedure with a code name ty! ahahahaha what a shame

**Comment by Sunekaer** [comment]
I been trying to see if i could recreate you crash, without luck does it happen for you everytime? can you show the setup?

**Comment by jluca93** [comment]
the first crash happened after I died in the game, then every time I try to respawn the game crashes. my setup is a MacBook Pro (Retina, 13-inch, Early 2015) with 2,7Ghz intel i5, 8GB RAM (I've dedicated 7GB in the launcher options), 256GB SSD and Intel Iris Graphics 6100 1536 MB

**Comment by Sunekaer** [comment]
i meant the setup using the Advanced Item Collector, and could you try updating
https://www.feed-the-beast.com/projects/ftb-presents-stoneblock-2/files/2694788

**Comment by jluca93** [comment]
oh, I've placed the item collector on top of a crystal chest near a mob spawner made with a mob fan and a mob grinder inside a dark room with cursed earth on the floor (made with drop of evil) I died trying to turn off the farm and end being killed by the mob grinder and than at the death title the crash happened

**Comment by jluca93** [comment]
I've upgraded and it happened again with this error code https://paste.dimdev.org/riqeyumexa.mccrash

**Comment by jluca93** [comment]
<img width="1018" alt="Schermata 2019-04-02 alle 21 53 37" src="https://user-images.githubusercontent.com/49061794/55431855-c679ca00-5591-11e9-8ab7-81d115dd3f58.png">

**Comment by xTheFox** [comment]
Same problem, i died at the spawn on a server with my friends. 
Now i can't even join because the server is still crashing.. 
https://pastebin.com/3QaRGj4H

**Comment by Sunekaer** [comment]
jluca did you update to 1.10.0? from what i see on the log it seems your still on 1.9.0

**Comment by jluca93** [comment]
i've tryed to upgrade from the twitch app, seems like something gone wrong, later I try again and check if works, thanks

**Comment by Sunekaer** [comment]
ty

**Comment by jluca93** [comment]
I've finally really upgrade to the lastest version and it WORKS!!! you've literally saved my world!! ahahahaha! thank you very much for helping so well
