### ISSUE TITLE
Ender IO Fatal Error

### ISSUE THREAD

**Issue by KvnqXp** [FTBTeam/FTB-Presents-Stoneblock-2#431]
So ... Every time I try to enter with this modpack installed in MultiMC, after a while starting it says that a fatal error occurred in the IO Ender, and also says that a Hopper is missing something like that and it happened in the first three versions and I just do not know what to do, because I'm not good at it so if you can help me I thank you
(This has been translated into Google Translate)
Bye.

**Comment by Sunekaer** [comment]
i cant help you with out logs.. i can load fine with MultiMC myself
