### ISSUE TITLE
LAN not working

### ISSUE THREAD

**Issue by GreenNinja427** [FTBTeam/FTB-Presents-Stoneblock-2#433]
* **Modpack Version**: 1.9.0

* **Issue**: LAN not working

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: Yes I cant join my friend

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Sunekaer** [comment]
Log? what happens? Errors? you give no information to work with
