### ISSUE TITLE
No in-game sound 

### ISSUE THREAD

**Issue by razulwolf** [FTBTeam/FTB-Presents-Stoneblock-2#434]
* **Modpack Version**: 1.9.0

* **Issue**: Outside of the main menu; I have no sound coming from the minecraft client

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: Yes, I can go to the main menu after loading into a game and will have sound on the menu again. And will lose sound when I load the world back up.

**Comment by Sunekaer** [comment]
Hmm, does it happen with other worlds? other packs? other versions of the pack?

**Comment by razulwolf** [comment]
Yes I have created multiple worlds of different types in versions 1.8.0 and 1.9.0. Plus I've even tried to change the version of forge. I've had no problems with other mod packs it has just been this one.

The only thing I haven't tried yet is a clean wipe of the mod pack and re-installing it. Which I'll try giving a shot this evening.

**Comment by razulwolf** [comment]
Oh I should have added that other mod packs have been fine have I've been getting sound form them no problem.

So I deleted the mod pack, downloaded a fresh copy, I even tested 1.10.0 and 1.0.0 on multiple different world types and still do not get any sound while loaded into a world.
I'm still getting sound just fine while I'm on the main title screen and its menus.
