### ISSUE TITLE
Stoneblock 2: How to remove pig head and sound after opened chance cube.

### ISSUE THREAD

**Issue by TheOwl27** [FTBTeam/FTB-Presents-Stoneblock-2#436]
* **Modpack Version**: StoneBlock 2  version 1.12.2
* **Issue**: I opened a chance cube in the game, then I got pig head (with pig sound) and I don't know how to remove them

* **Link to Log or Crash File Paste**: Don't know what it means, sorry

* **Is it Repeatable?**: Yes, it's permanent

* **Mod/s Affected**: Chance Cubes

**Comment by Sunekaer** [comment]
I havent seen that one before, i would recommend asking on https://github.com/Turkey2349/ChanceCubes/issues
