### ISSUE TITLE
Problem with storage in Applied Energistics 2

### ISSUE THREAD

**Issue by RudiHansen** [FTBTeam/FTB-Presents-Stoneblock-2#437]
* **Modpack Version**: 1.9.0

* **Issue**: 
I am importing Soularium Ingot's and Energetic Alloy Ingot's from an Ender chest, but they do not appear in my storage, (ME Drive)
And it also seems other items are glitching in the system, like you can see in these screenshots:
https://imgur.com/a/d3TaZAz
https://imgur.com/a/ybS3OiK
It does look like these items are seen as Fluid Tanks by the system, also if I take them out of the system, the item shows as fluid tank in my inventory, but with the icon of an Ingot.

* **Is it Repeatable?**: Yes 

* **Mod/s Affected**: Applied Energistics 2, rv6-stable-6

**Comment by Sunekaer** [comment]
Hmm i cant recreate this problem, have you added any mods, changed any settings?

**Comment by RudiHansen** [comment]
No I made no changes, I have attacked my world do you see the problem there?
[StoneBlock2.zip](https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/files/3033975/StoneBlock2.zip)

**Comment by RudiHansen** [comment]
I do not know why this issue was closed, must have done it by mistake.

**Comment by RudiHansen** [comment]
Had a little closer look at my storage and it seems the problem had to do with a Black Hole Unit.
I have one with Soularium Ingot's but for some reason, when I take the Ingots out of the tank they are named Fluid tanks ????
![SB04](https://user-images.githubusercontent.com/4745972/55431222-4b63e400-5590-11e9-905f-386ee46d73bb.jpg)
![SB03](https://user-images.githubusercontent.com/4745972/55431223-4b63e400-5590-11e9-8e5c-b331d27b4d1d.jpg)

So apparently it's a Black Hole Tank problem
