### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Ramen-God** [FTBTeam/FTB-Presents-Stoneblock-2#438]
I am trying to download Stoneblock 2 for the first time on the Twitch windows app. It goes through the installation, but when the program is almost done a message pops up that says "Object reference not set to an instance of an object." All I can do is hit "OK." And Stoneblock 2 still says "Install." What am I doing wrong pressing 1 button?

**Comment by Sabster** [comment]
Yup, I got it too.

**Comment by ConvincedGaming** [comment]
Getting this as well.  Reinstalled the Twitch app, other packs download just fine.

**Comment by PrincessLuna2253** [comment]
Same issue here. Hope this gets resolved quickly!

**Comment by LasXor** [comment]
Same issue here. Chockes after verifying the manifest.
Seems persistent between different versions.
Can download other Packs.

**Comment by LasXor** [comment]
just found out PO3 has this as well....
https://github.com/Cazadorsniper/PO3/issues/257

looks like it is the buggy twitch app again -.-

**Comment by Sunekaer** [comment]
Twitch issue not a pack issue, please contact twitch for support on this
