### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by RudiHansen** [FTBTeam/FTB-Presents-Stoneblock-2#439]
* **Modpack Version**: 1.9.0

* **Issue**: Game crashed while trying to get Fluid tank to pull fluid

* **Link to Log or Crash File Paste**: https://paste.dimdev.org/gijuxoyiza.mccrash
* **Is it Repeatable?**: Don't think so, it just happend.
A

**Comment by Sunekaer** [comment]
Could you try and update to 1.10.0 and see if that solves your problem

**Comment by RudiHansen** [comment]
Sure I am updating to the Beta right now, might take a little time before I see the results.
I will let you know tomorrow, what happened.

**Comment by RudiHansen** [comment]
Seemed it did help in some way, but I did get another crash today, when accessing my Material StoneWork Factory.

https://paste.dimdev.org/damuhiheli.mccrash

**Comment by RudiHansen** [comment]
And one more time when i started the game:
https://paste.dimdev.org/ruwocixaqu.mccrash
[crash-2019-04-04_22.39.18-server.txt](https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/files/3045379/crash-2019-04-04_22.39.18-server.txt)

**Comment by Sunekaer** [comment]
1. Does the Material StoneWork one do everytime?
2. okay could you report that one to extra util, nothing i can do about that one

**Comment by RudiHansen** [comment]
1, No just one time
2 ? report what to extra util?

**Comment by Sunekaer** [comment]
1. okay if you get it again report it to Industrial foregoing
2. the second crash you sent https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/issues/439#issuecomment-480055354
