### ISSUE TITLE
Stealing Items from chest during visit in claimed area

### ISSUE THREAD

**Issue by DerSoftwerker** [FTBTeam/FTB-Presents-Stoneblock-2#45]
* **Modpack Version**: 1.0.1

* **Issue**: While visiting another players cave, you can access the chests, regardless if the area is claimed or not. If you use the options to sort the chest it tempoarily puts items in your hand/inventory. By spamming the sorting, you can get items from the chest and keep it.

* **Is it Repeatable?**: Yes.
1.) /cave visit <player>
2.) Open any chest in the area
3.) Spam-click the sorting buttons in the UI or use hotkeys
4.) Wait for items to get stuck at your mouse pointer or in the inventory

* **Mod/s Affected**: Inventory Tweaks

* **Known Fix**: Possible temporary solution - do not let visitiors access the chests.

**Comment by Slyklaw** [comment]
Visitors can also drop items. Not sure what else they can do. Can "/cave visit" be disabled?

**Comment by Sunekaer** [comment]
1.1.0
