### ISSUE TITLE
- 1.6 stone block 2 - when i start the package it gives me some problems and won't let me play - https://paste.dimdev.org/hexemuzola.mccrash - ender io

### ISSUE THREAD

**Issue by vulkarion** [FTBTeam/FTB-Presents-Stoneblock-2#452]
* **Modpack Version**: 

* **Issue**: 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Sunekaer** [comment]
Answer to your problem is on line 8 of the file you linked... "please delete the 'EnderStorage' folder Here: C:\Users\Utente\Documents\Curse\Minecraft\Instances\FTB Presents Stoneblock 2\saves\Nuovo mondo\EnderStorage and start the server again."

**Comment by vulkarion** [comment]
is first time sorry for two issues
