### ISSUE TITLE
Too Many Efficiency Losses Config Refresh

### ISSUE THREAD

**Issue by JamieBrassel** [FTBTeam/FTB-Presents-Stoneblock-2#453]
* **Modpack Version**: 1.10.0

* **Issue**: The config for Too Many Efficiency Losses has duplicate and unused value in it.

* **Is it Repeatable?**: Yes. All users will have the issue if they used the included configuration files with the modpack.

* **Mod/s Affected**: Too Many Efficiency Losses

* **Known Fix**: Delete config/tmel.cfg and it will be auto-generated on next launch with correct values.

**Comment by Sunekaer** [comment]
Does this issue course any problems with the pack?
