### ISSUE TITLE
Radompatches crashing world

### ISSUE THREAD

**Issue by CoolandonRS** [FTBTeam/FTB-Presents-Stoneblock-2#454]
* **Modpack Version**: 1.9.0

* **Issue**: Randompatches is crashing my world

* **Link to Log or Crash File Paste**: https://paste.dimdev.org/izupafakil.mccrash

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Randompatches, Realistic Item Drops

* **Known Fix**: Disabling head stacking (Randompatches) and auto-pickup (Realistic Item Drops) features

CraftPresence was disabled during the crash, if that matters.

**Comment by CoolandonRS** [comment]
I just realized I have no information in this report, so here is some: My friend had just died (I was playing on lan) and I was going to get his stuff, and it crashed, and put me back to the main menu. I rejoined the world, and it crashed again. I then exited the game and disabled Randompatches, and it didn't crash. I think it might have been the head-stacking feature causing the crash as I had some shelves (from Missing Pieces? or something like that, it adds furniture) with several of his and my heads nearby. If it helps, he was also morphed as me, and I am using the FTB legacy launcher.

**Comment by CoolandonRS** [comment]
I reenabled the mod, and it doesn't crash. I still have no idea what caused the crash, as I have tried to recreate multiple times and nothing happens. I guess ill reopen it with the link to log if it happens again.

**Comment by CoolandonRS** [comment]
I am having the problem again, or a very similar one. There is another mod influencing it as well this time, and thought it better to reopen the similar one than to make a new one.

**Comment by CoolandonRS** [comment]
Im doing some testing, and it seems that the issue is really the autopickup of Realistic Item Drops.

**Comment by CoolandonRS** [comment]
Ok, I have prevented it from happening by: Disabling the Autopickup Feature, Burning the player skull with lava (I couldn't find a way to pick it up otherwise, because Autopickup was off, and reenabling the feature. It seems to have worked.

**Comment by Sunekaer** [comment]
try version 1.10.0

**Comment by CoolandonRS** [comment]
Ok. I'll use 1.10 from now on and reopen this issue if it happens again.
