### ISSUE TITLE
Stoneblock 2 crash

### ISSUE THREAD

**Issue by nmigo12** [FTBTeam/FTB-Presents-Stoneblock-2#456]
I was trying to break an "Enrichment Chamber" and when i broke it the game crashed. I tried joining back but it kept crashing when i join (i used a backup so i'm fine but i guess i should still report this)
Also, I was wearing "The spectator" from botania so that may have something to do with it because it said it's because of baubles and botania and another mod (sorry i forgot to save the picture)
crash report: https://paste.dimdev.org/badocagolo.mccrash

**Comment by Sunekaer** [comment]
try with version 1.10.0 of the pack
