### ISSUE TITLE
Server crash with Ticking Entity error

### ISSUE THREAD

**Issue by mdereus** [FTBTeam/FTB-Presents-Stoneblock-2#459]
* **Modpack Version**: 1.9.0

* **Issue**: Server crashes with Ticking Entity error on Thaumcraft Pech mobs - I have a cursed earth mob farm with witch water before a mob masher. 

* **Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/38f3fa75
https://paste.feed-the-beast.com/view/b35f9ea3
https://paste.feed-the-beast.com/view/b590bcd4

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: NA

* **Known Fix**: NA

**Comment by Sunekaer** [comment]
Sadly nothing i can do about this issue. needs to be fixed by the mod author 
Azanor/thaumcraft-beta#1612
