### ISSUE TITLE
Crashed making Coagulated Blood

### ISSUE THREAD

**Issue by KillerzGodZ** [FTBTeam/FTB-Presents-Stoneblock-2#460]
* **Modpack Version**: 1.10.0

* **Issue**: Was just sitting in the Tinkers Construct Smeltery getting coagulated blood by burning myself and then it just crashed. (Noted I'm playing Single Player) 

* **Link to Log or Crash File Paste**: Crash Log --> https://paste.feed-the-beast.com/view/d6ff6705

* **Is it Repeatable?**: Can not be recreated as I've tried doing it again myself.

* **Mod/s Affected**: It says in Crash Log what mods might be affected, but I'll put it here also:
extrautils2-1.12-1.9.9 (Extra Utilities 2)
appliedenergistics2-rv6-stable-6 (Applied Energistics 2)

* **Known Fix**: N/A

**Comment by Sunekaer** [comment]
Sorry nothing i can do about this. issue: https://github.com/rwtema/Extra-Utilities-2-Source/issues/236
