### ISSUE TITLE
Dirt/compressed dirt produces nothing when put through iron mesh

### ISSUE THREAD

**Issue by jwfiredragon** [FTBTeam/FTB-Presents-Stoneblock-2#462]
* **Modpack Version**: 1.10.0

* **Issue**: Putting dirt or compressed dirt through a sieve/heavy sieve with an iron mesh will not give any drops. No drops are listed in JEI or the Ex Nihilo Creatio config.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Ex Nihilo Creatio

My apologies if this is an intentional balance decision, but even then I think it's an odd choice to make.

**Comment by Sunekaer** [comment]
intended
