### ISSUE TITLE
Getting wrong Ingots from Mekanism and Game crashes when breaking EnderIO mashines

### ISSUE THREAD

**Issue by Grussel** [FTBTeam/FTB-Presents-Stoneblock-2#464]
Modpack Version:
 1.10.0

Issue:
 After the Update to 1.10.0 the Mekanism mashines are giving out Ingots and grindet dusts that are not listet in JEI. Getting wrong tin and copper ingots and iron dust aso.

Second thing: When breaking EnderIO mashines like the painter or the impulse hopper, the game crashes. I was able to get the world running again by deleting the dropped item with MC Edit.

Link to Log or Crash File Paste:
https://paste.dimdev.org/xurubukivu.mccrash

Is it Repeatable?:
Yes. tried taking off all item magnets but still the same

Mod/s Affected:
EnderIo and Mekanism

Known Fix:
For the ingots and dusts i'll take another mashine but for the EnderIo stuff i don't know.

**Comment by Sunekaer** [comment]
could you try 1.11.0

**Comment by Grussel** [comment]
Ingots and dusts are now from Thermal again. Will test the EnderIo mashines with the Botania Magnet Ring.

**Comment by Grussel** [comment]
No crash when breaking and picking up enderio stuff with the magnetic ring from botania anymore! Thx
