### ISSUE TITLE
Crashing when logging into world

### ISSUE THREAD

**Issue by Fiskpung** [FTBTeam/FTB-Presents-Stoneblock-2#465]
* **Modpack Version**: 1.10.0

* **Issue**: After upgrading the best satchel, not creative, with Holding IV it's making my game crash and tell me Cofh core and ftb quests is at fault.

* **Link to Log or Crash File Paste**: https://paste.dimdev.org/umesohegev.mccrash

* **Is it Repeatable?**: Yes, everytime i login to my world it crashes, between 3 and 10 seconds each time

* **Mod/s Affected**: Cofh core and FTB Quests

* **Known Fix**: Sadly not

**Comment by Sunekaer** [comment]
reported to FTB Quest 
https://github.com/FTBTeam/FTB-Quests/issues/222

**Comment by Fiskpung** [comment]
Thanks, hopefully it'll get fixed asap

**Comment by Fiskpung** [comment]
> reported to FTB Quest
> [FTBTeam/FTB-Quests#222](https://github.com/FTBTeam/FTB-Quests/issues/222)

I believe i've found the problem, when you have auto loot into satchel it crashes. i deleted it and mined some and i didnt crash.

**Comment by Sunekaer** [comment]
Fixed in 1.12.0
