### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by DeathOverYrHead** [FTBTeam/FTB-Presents-Stoneblock-2#466]
So i started a server prompt with my friend and I but we ran into an issue where only certain mods would load in, we have the "Not Enough Items" mod working but everything else seems to be bugged for some odd reason and i'm not too sure what the issue is. When we opened "Not Enough Items" it'll show all the mod items but nothing can be chosen form them. I preformed a troubleshoot world in single player and all them mods seem to work fine its just that multiplayer compatibility with the selected mods doesn't work properly. can you please get into contact with me so we can walk through this.

**Comment by DeathOverYrHead** [comment]
BTW the error goes something like "Petrock:rock doesn't exist"

**Comment by Sunekaer** [comment]
Whos your server host? How did you install the mods?
