### ISSUE TITLE
Can't make a Thaumanomicon, I took the Vanilla Bookshelf and the Salus Mundus but it doesn't work. I also tried with a Mechanical User from EU2

### ISSUE THREAD

**Issue by SteveNoobGeek** [FTBTeam/FTB-Presents-Stoneblock-2#467]
* **Modpack Version**: 1.10.0

* **Issue**:  Can't make a Thaumanomicon, I took the Vanilla Bookshelf and the Salus Mundus but it doesn't work. I also tried with a Mechanical User from EU2

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**:  No

* **Mod/s Affected**:  Thaumcraft

* **Known Fix**:

**Comment by Sunekaer** [comment]
did you break crystals with you hand and sleep?

**Comment by SteveNoobGeek** [comment]
> did you break crystals with you hand and sleep?

Sorry I didn't sleep. Thanks !
