### ISSUE TITLE
Ring of magnetizations picking up Ender IO machines crashing game

### ISSUE THREAD

**Issue by Amarger** [FTBTeam/FTB-Presents-Stoneblock-2#468]
**Modpack Version:** 

1.10.0

    **Issue:** 

The modpack is crashing every time a Botania magnet ring equipped tries to pick up an Ender IO machine from the ground. First time it happened, I had the Greater Ring of Magnetization equipped in my baubles slot and broke my simple alloy smelter and it shutdown internal server. I was unable to access my world until I MCEdit moved myself a distance away and unequipped ring. Second time I did it with a SAG mill and it repeated. After MCEdit again, I tried walking up to SAG mill with the ring on and it crashed again when i got within range. I crafted the manasteel version and it also crashed the game when i tried it out. Other magnet items do not seem to crash the game (I personally checked the Ender IO Electromagnet and Actually Addons Ring of Mangetizing as a controls)

    **Link to Log or Crash File Paste:** 

Crash from initially breaking SAG mill 
https://paste.dimdev.org/yujepofubi.mccrash

Crash from walking back to item with ring on
https://paste.dimdev.org/yutodokiyi.mccrash

    **Is it Repeatable?:** 

Yes, every time I break any ender io machine with a ring equipped. I repeated this crash many times checking which ones would cause it and it was both the Botania ones.

    **Mod/s Affected:** 

Ender IO, Botania, Baubles

     **Known Fix:**

Only in game fix, use other magnet items instead of Botania ones.

**Comment by Sunekaer** [comment]
could you try 1.11.0

**Comment by Amarger** [comment]
No crashes with either ring with the current 1.11.0 beta build. Tried on 4 different Ender IO machines. Thanks

**Comment by Sunekaer** [comment]
Perfect thanks!
