### ISSUE TITLE
StoneBlock 2 Crashes 

### ISSUE THREAD

**Issue by BossLP** [FTBTeam/FTB-Presents-Stoneblock-2#469]
* **Modpack Version**: 
1.10.0
* **Issue**: 
After putting a Item Translocator on a Dischantment Generator the game crashes and when i want to restart in the map the "internal server" is "shutting down" text is shown and the game crashes.
* **Link to Log or Crash File Paste**: https://paste.dimdev.org/eravevuqey.mccrash

* **Is it Repeatable?**:  Yes, every time I want to rejoin.

* **Mod/s Affected**:  Im not sure about it, but it could be the translocator.

* **Known Fix**: Unfortunately not.

**Comment by Sunekaer** [comment]
Hey 

Please create an issue here: https://github.com/TheCBProject/Translocators/issues

You can try this if your server still is crashing:
Make sure to take a backup of your world before doing this! edit the forge.cfg in the config folder. There are a couple of lines about removing erroring entities. Change both of them to true and load the world and see if the removes the block. REMEMBER to set these back to false again!.... If that doesn't work, then you need to create a issue on darkutils github and get help from them
