### ISSUE TITLE
No Aluminum Ore in Mining Dimension

### ISSUE THREAD

**Issue by Leo40Git** [FTBTeam/FTB-Presents-Stoneblock-2#470]
* **Modpack Version**: 1.11.10 (though AFAIK this has been an issue since 1.0.0)

* **Issue**: No Aluminum Ore is generated in the Mining Dimension. This completely prevents access to HV lines in Immersive Engineering without Ex Nihilo, and also makes reusable casts harder to create.

* **Link to Log or Crash File Paste**: *N/A*

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: CoFHWorld

* **Known Fix**: Adding [this JSON file](https://pastebin.com/jMUqbQWY) to the CoFHWorld config folder (and also regenerating JER world gen info)

So... neither Thermal Foundation's Aluminum Ore nor Immersive Engineering's Bauxite Ore generate in the Mining Dimension, meaning Aluminum Brass (an alloy of Copper and Aluminum that's used for making reusable casts) is inaccessible beyond Ex Nihilo.
Thus, if you *don't* want to sift for resources and want to get better Tinker's tools (which, considering you're mining, you do), you either have to get Gold (which is A. much rarer than Aluminum and Copper and B. cannot be mined by anything below Iron mining level) or Alchemical Brass (which requires Thaumcraft research, AFAIK) to get reusable casts; *or,* you have to use single-use clay casts (which, granted, clay isn't the hardest resource to make, but it's still annoying to constantly have to make those casts).

So... is this intentional? While Immersive Engineering's Bauxite is specifically disabled, the Mining Dimension features Thermal Foundation ores rather than equivalent ores from other mods, and Thermal Foundation's Aluminum has to be manually configured to generate.

**Comment by Leo40Git** [comment]
Another problem that this quirk causes: you can't get HV Immersive Engineering wires (since they require steel *and* aluminum wires to craft).

**Comment by Leo40Git** [comment]
...if this is intentional, just say so and close this issue.

**Comment by diamondpumpkin** [comment]
I don't think it is, kind of weird to exclude those ores specifically. Gold could be used yes, but that really only affects time played, you have to grind more. I honestly hate that, I see no other reason why disabling Aluminum would be reasonable to some sort of progression.
