### ISSUE TITLE
Server crash caused by Thaumcraft pech spawn

### ISSUE THREAD

**Issue by LeleKaos** [FTBTeam/FTB-Presents-Stoneblock-2#471]
* **Modpack Version**: 1.12.2-1.10.0 On server

* **Issue**:  Server crash ONLY, caused by Thaumcraft pech (any type) spawning in the overworld 

* **Link to Log or Crash File Paste**: https://pastebin.com/GnvNQhQr

* **Is it Repeatable?**: Yes, you should play for a long time with a mob farm with cursed earth

* **Mod/s Affected**: Thaumcraft 1.12.2-6.1.BETA26

* **Known Fix**: Disable Pech spawn in thaumcraft mod config

**Comment by Sunekaer** [comment]
Fixed in 1.12.0
