### ISSUE TITLE
[Suggestion] Oversaturation mod to get full food potential

### ISSUE THREAD

**Issue by attichicco** [FTBTeam/FTB-Presents-Stoneblock-2#473]
Top tier food gives more saturation than maximum saturation, since minecraft max saturation is 20 i think a mod like Oversaturation should be added.
This is to allow Food like Cosmic Meatballs to give out their full potential.
https://minecraft.curseforge.com/projects/oversaturation

**Comment by Sunekaer** [comment]
Hey 

Thanks for the suggestion, but there wont be added anymore mods. feel free to added it in your play through

**Comment by Leo40Git** [comment]
@attichicco If you plan on adding Oversaturation, use my version of it, it fixes a bug when changing dimensions: https://minecraft.curseforge.com/projects/oversaturation-patched
