### ISSUE TITLE
Chest Transporter & Yabba Item Barrel Bug

### ISSUE THREAD

**Issue by Wynterwolf** [FTBTeam/FTB-Presents-Stoneblock-2#474]
* **Modpack Version**: 
FTBPresentsStoneblock2-1.9.0-1.12.2

* **Issue**: 
When using the chest transporter to lift a yabba item barrel, it will drop an empty barrel. If you click with the full chest transporter on yet another yabba barrel it will drop another empty barrel. When setting down the barrels, it does not drop another item barrel. 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 
Yes

* **Mod/s Affected**: 
Chest Tranporter & Yabba Item Barrel

* **Known Fix**: 
None

**Comment by Leo40Git** [comment]
I'm not the pack dev, but you're using an outdated version. Download 1.11.0 and try again.

**Comment by Sunekaer** [comment]
try 1.11.0

**Comment by powerko11** [comment]
I am using 1.11.0 and that barrel bug is still there

**Comment by Sunekaer** [comment]
https://github.com/cubex2/chesttransporter/issues/32 nothing we can do about this issue until Chesttransporter releases a fix
