### ISSUE TITLE
Game crashed after breaking ender io alloy smelter - World corrupted.

### ISSUE THREAD

**Issue by ysonoko** [FTBTeam/FTB-Presents-Stoneblock-2#475]
* **Modpack Version**:  1.10.0

* **Issue**: I hit an ender io alloy smelter with a 128 rf/t spectre things attached, with a party pick axe. Game crashed. Each attempt to load the game after results in a crash.

* **Link to Log or Crash File Paste**: https://paste.dimdev.org/gojehugisa.mccrash
The link provided is the second crash report, when trying to load into the world after the initial crash.

* **Is it Repeatable?**: Yes. Reloading a backed-up version of the world and performing the same actions produces the same results.

* **Mod/s Affected**: Initial crash reported Ender IO, tinkers, and some others.

* **Known Fix**:  Change game mode to creative and break the block.

**Comment by ysonoko** [comment]
Here's another crash report after closing client and reloading.
Also, a picture with the affected mods or w/e.

https://paste.dimdev.org/opunofijek.mccrash

![image](https://user-images.githubusercontent.com/14120538/56449422-a0606380-62cd-11e9-8f1e-473b644cb5b5.png)

**Comment by ysonoko** [comment]
I loaded a back up, and removed the spectre coil attached to the alloy smelter. I then used a wrench to dismantle the alloy smelter, and the game crashed.

Here is the resulting crash report: 
https://paste.dimdev.org/vokiluhihu.mccrash

And the second crash report after trying to load in after the initial crash:
https://paste.dimdev.org/adosuqirod.mccrash

**Comment by ysonoko** [comment]
Apparently it's not just the alloy smelter. Breaking a painting machine did it too.
Not sure what's causing this, but it's making the game difficult to play.
I can't break or dismantle ender io machines ones I place them without corrupting the chunk.
It's random machines, in random places. Not all machines corrupt chunks, and some do even after being broken successfully before. No clue what is causing this.
Think I'll stop playing Stoneblock 2 for the moment, until this issue is fixed.

Crash report: https://paste.dimdev.org/niseratuto.mccrash

**Comment by ysonoko** [comment]
I guess this is a known issue.
Seems like the botania ring I have on is causing it, or something in botania.
Consider removing Botania from the pack, or disabling the magnet ring?
Not even sure if that is the fix. But, it's a very annoying bug to have your world corrupted every time you break an ender io machine. I'd imagine others will have this problem.

https://github.com/SleepyTrousers/EnderIO/issues/5086

**Comment by Sunekaer** [comment]
Botania is updated in version 1.11.0 of the pack, could you try that one?

**Comment by ysonoko** [comment]
Updated Stoneblock 2 Modpack to version 1.11.0.
Ender IO machines no longer crash the game and corrupt the chunk they were in, while wearing the Botania magnet ring and breaking the block.

Please mark this issue closed. Thank you! <3

**Comment by ArtfulDevotee** [comment]
I keep getting a very similar crash, except I do not have the anything from Botania yet... Seems to be a problem with EnderIO conduit integration mods...?
![image](https://user-images.githubusercontent.com/49645683/56816565-add09d00-683b-11e9-98c1-0e943638065f.png)

**Comment by Sunekaer** [comment]
@ArtfulDevotee make a new issue for yours
