### ISSUE TITLE
Watch of Flowing Time + Mekanism + Industrial Foregoing World Corruption Crash

### ISSUE THREAD

**Issue by Jesusfreakster1** [FTBTeam/FTB-Presents-Stoneblock-2#476]
* **Modpack Version**: Stoneblock 2 + Tree Chopper and Enchanting Plus V 1.11.0

* **Issue**: Game crashes upon loading into world, happened when linking Industrial foregoing brewery to crystal chest via a mekanism logistical transporter close to a Watch of Flowing Time on a Project E pedestal

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/0a04b5f2

* **Is it Repeatable?**: Cannot access world, crashes on every load up

* **Mod/s Affected**: ProjectE for sure, Mekansim possibly, Tesla Core Lib and Tesla Core Lib Registries are listed on the error screen

* **Known Fix**: None

![CrashReport](https://user-images.githubusercontent.com/49801101/56450352-16bf8e80-62eb-11e9-891b-042e2df8c705.JPG)

**Comment by Sunekaer** [comment]
Sorry for the late reply, have you been able to enter your world and continue playing?
ill report the crash to Tesla core as it looks to be their issue

**Comment by Sunekaer** [comment]
Closing this issue, keeping issue open at mod author

**Comment by byBackfish** [comment]
Please Help.I have the Same Problem

**Comment by zuckerwatte982** [comment]
use mcedit to remove the brewer
