### ISSUE TITLE
Ender IO/Big Reactor Crash

### ISSUE THREAD

**Issue by Alanon2011** [FTBTeam/FTB-Presents-Stoneblock-2#477]
* **Modpack Version**: 1.11.0

* **Issue**: Single Player Server Crashed.

* **Link to Log or Crash File Paste**: https://paste.dimdev.org/eqocihasot.mccrash

* **Is it Repeatable?**: Big reactor (RF power tap) exploded when Ender IO Vibrant Capacitor bank was attached. after the second time, it crashed the server.

* **Mod/s Affected**: Extreme Reactors & Ender IO

* **Known Fix**: IMO it's either a compatibility issue, or I just don't understand why it exploded.

**Comment by Sunekaer** [comment]
Please report to enderio
