### ISSUE TITLE
Game Unable to Load

### ISSUE THREAD

**Issue by ItsAstrobiology** [FTBTeam/FTB-Presents-Stoneblock-2#478]
Hi! I've had an issue since updating to 1.11.0 where the game will crash and tell me it is unable to continue loading the game. I then tried going back and starting the game in version 1.10.0 but the issue persisted. Any help with this issue would be greatly appreciated!

* **Modpack Version**: 1.11.0 and 1.10.0

* **Issue**: Game simply crashes, says it cannot continue loading 

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/8c8741d1

* **Is it Repeatable?**: Yes it occurs every time I try to load the game

**Comment by kranoza** [comment]
I have the same issue

**Comment by Leo40Git** [comment]
Minecraft Forge didn't install correctly, apparently? Try to reinstall the modpack.
If that doesn't work, you might want to post an issue on the [Minecraft Forge repo](https://github.com/MinecraftForge/MinecraftForge).

**Comment by ItsAstrobiology** [comment]
> 
> 
> Minecraft Forge didn't install correctly, apparently? Try to reinstall the modpack.
> If that doesn't work, you might want to post an issue on the [Minecraft Forge repo](https://github.com/MinecraftForge/MinecraftForge).

Would I lose my current world by doing this though?

**Comment by Leo40Git** [comment]
You can back up your existing world by going to the "worlds" directory in the modpack folder and copying the folder that's named like your world. Then you can reinstall and restore it.

**Comment by ItsAstrobiology** [comment]
ok thanks

**Comment by MaxUli** [comment]
salve, ho un problema con il pack, stavo giocando avevo appena fatto delle capacitor banck ho utilizzato la building wand per posizzionarle in modo più rapido, la prima volta è andata bene ma come l'ho fatto la seconda volta mi è crusciato tutto, da allora ogni volta che tento di accedere al mio mondo mi da errore e non mi fa più accedere 
- Versione pack: 1.10.0
- Problema: non riesco ad accedere al mio mondo 
- Link a Log o Crash File Paste: https://paste.dimdev.org/egunagofan.mccrash
- si ripete?: si ogni volta che tento di accedere al mondo

**Comment by Leo40Git** [comment]
@MaxUli 
1. Please post issues in English.
2. This needs to be a separate issue, as it's unrelated to this one.

**Comment by MaxUli** [comment]
sorry
