### ISSUE TITLE
Crafting duplication (or crafting without using items in multiplayer)

### ISSUE THREAD

**Issue by MrGREGhimself** [FTBTeam/FTB-Presents-Stoneblock-2#48]
* **Modpack Version**: FTB presents Stoneblock 2 (1.0.1)

* **Issue**: Item duplication with Tinkers Crafting Station.

In multiplayer Player1 puts items in the Tinkers Crafting Table (for example 4 blocks of sand), output shows 1 Sandstone. If before Player1 collects Sandstone, Player2 opens table's inventory then the output item will stay (get duplicated if crafted) or if Player1 puls the ingredients out, Player2 can still collect the output item.
This works for both vanilla and modded (multiple mods) items.
This is not the case in other crafting tables i.e. vanilla, Stone Crafting Table

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: N/A

* **Known Fix**: N/A

Issue has been reported on:
https://github.com/SlimeKnights/TinkersConstruct/issues/3714

**Comment by Sunekaer** [comment]
Closing this issue, as there´s nothing we can do about this other then wait and see if the mod dev fixes it
