### ISSUE TITLE
Continuous crashes on Stoneblock 2 server

### ISSUE THREAD

**Issue by federico2407** [FTBTeam/FTB-Presents-Stoneblock-2#480]
Modpack Version: 1.10.0

Issue: I ran into a crash while I was playing on a server, it continues crashing everytime I try entering, sometimes it makes me stay online for a few seconds and then crashes again, I've tryed playing in singleplayer and it works, I've also tryed uninstalling and reinstalling the modpack.
I'm the only player that crashes on this server.

Link to Log or Crash File Paste: https://paste.dimdev.org/zihijucago.mccrash

Mod/s Affected: I've seen a lot of mods related to Ender IO in the crash report, but (I think) most of them were out of the screen (all mods on a single line that overcomes the screen)

**Comment by qm3ster** [comment]
Do you have a weirdly shaped EnderIO capacitor bank, like donut shaped or something?
It's trying to use an air (empty) block as part of the capacitor bank multiblock.

**Comment by federico2407** [comment]
> Do you have a weirdly shaped EnderIO capacitor bank, like donut shaped or something?
> It's trying to use an air (empty) block as part of the capacitor bank multiblock.

Thank you, I've told a friend to remove the EnderIO capacitor bank and I've entered in the server succesfully
