### ISSUE TITLE
Mobs crash my game

### ISSUE THREAD

**Issue by Cozman** [FTBTeam/FTB-Presents-Stoneblock-2#481]
FTB Stoneblock 2 Stalls if I stand or attack a monster. I have waited close to a hour to see if Java would respond again. It didn't. If i click, hit a key, or hit esc. Screen will turn a slight transparent white and read blah-blah is not responding Wait for it to respond or close the program. i chose both options at separate times. when choosing close the app it will close and the MC launcher will appear and some generic crash screen without a code. I have optifine installed, BUT It was doing this before i put it in. If I avoid my mob farm it will run just fine. So I know it is the mobs causing it
I play outside any aftermarket Launcher like Twitch.
JVM  arguments 
-XX:+UseG1GC -Xmx5G -Xms5G -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M

PC
windows 10 up-to-date
MSI RTX Ventus 8GB GDDR6
8GB Crucible RMM
2TB HHD
AMD FX-8370 4.00GHz Wraith cooled
RX-850AE PSU
MSI 990 Gaming MB

**Comment by Cozman** [comment]
Tested 5GB ramm to game to see what would happen. I still got the crash but took longer. I will up it to 6 gigs of ramm (if my PC can handle that much oout of the eight I have!) will update soon.

**Comment by Cozman** [comment]
well turning it up to 6 gigs did nothing but slow the game down and still crashed as soon as I attacked a mob.

**Comment by Sunekaer** [comment]
Crash log?
You can try disable texture animation in foamfix but dont think that will help here

**Comment by Cozman** [comment]
https://paste.dimdev.org/ceqohucito.mccrash
Got this one last night, But it never generates a crash report. 
Unless there is a hidden report on JVM stall out. If so direct me to that file
and i will post it. I would also get a error while placing the flat as a pancake item/fluid rings.

**Comment by Sunekaer** [comment]
Are you on the newest version of the pack? as that crash should be fix in that version

**Comment by Sunekaer** [comment]
Please test with version 1.12.0

**Comment by Cozman** [comment]
I am using FTB Stoneblock 2 1.10.0-1.12.2
File.
Also I started playing Sky Factory 4 since it is a lot less stress on my PC. (Running it with same JVM and that pack does the same thing) I am considering trying with amped default JVM to test to see if it is those arguments.
