### ISSUE TITLE
Farmland 2 crashing Stoneblock 2 

### ISSUE THREAD

**Issue by sliderh2o** [FTBTeam/FTB-Presents-Stoneblock-2#482]
Played for a couple hours now this. I uninstalled and started a new game. Played several hours same crash, Farmland thing. :P 

Update: I tried the 1.11 version now it crashed and said p455w0rd's Library caused it. 

* **Modpack Version**: 1.10

* **Issue**: crashes and says Farmland caused a crash

* **Link to Log or Crash File Paste**: https://paste.dimdev.org/dapesehoje.mccrash

* **Is it Repeatable?**: does it every time i log into the game now.
* **Mod/s Affected**: Farmland...?

* **Known Fix**:

**Comment by Sunekaer** [comment]
this framland issue is fixed in version 1.11.0m whats the new crash?

**Comment by sliderh2o** [comment]
It's fixed! You guys rawk! thanks!
