### ISSUE TITLE
Enchanted Satchel (Holding) Server Crash

### ISSUE THREAD

**Issue by Coji4000** [FTBTeam/FTB-Presents-Stoneblock-2#483]
Server Crashes "gracefully" when opening a Satchel (Signalum) when enchanted with Holding IV. 

Issue is repeatable in singleplayer and multiplayer.

While tinkering I found that this issue occurs with the other  Thermal Expansion Satchels as well.

Version: 1.10.0
Minecraft Version: 1.12.2
(modded) forge-14.23.5.2808

Opening player inventory with the bag in inventory causes the server to throw a few ERRORS and a  FATAL  message (screenshot attached). If player opens the satchel server force quits after a second or two. crash report attached.

MP crash log
https://paste.feed-the-beast.com/view/9bdc431a
SP crash log
https://paste.dimdev.org/worunayifo.mccrash

![seeing the backpack errors](https://user-images.githubusercontent.com/11728324/56545353-584b7600-6545-11e9-8b52-adf396c5e9f4.PNG)

**Comment by Sunekaer** [comment]
Seems to be fixed in newer version of FTB quest as i dont get this crash in my dev pack

**Comment by Sunekaer** [comment]
#465
