### ISSUE TITLE
Game Crashing When loading

### ISSUE THREAD

**Issue by aervin85** [FTBTeam/FTB-Presents-Stoneblock-2#484]
* **Modpack Version**:  <1.5.7>

* **Issue**: <When playing the game crashed without being prompted that anything I can determine. I attempted to reload the game and it gave the same crash information detailed in the screenshot. The day prior a Java update did come through which may be the problem, however, I was able to load Stoneblock 1 without issue on the updated version of Java. 

* **Link to Log or Crash File Paste**: <https://paste.feed-the-beast.com/view/865a09f9>

* **Is it Repeatable?**: <Whatever crashed the game is still crashing the game, so it is repeatable every time I attempt to load the game. The game will go through the loading process and gets as far as showing the chat box in the lower left, then goes black and crashes.>

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Sunekaer** [comment]
1.5.7 is not a version of stoneblock? please report at EnderIO they might be able to assist you

**Comment by aervin85** [comment]
@Sunekaer You closed this so I don't know if you'll see this, but can you give me a site for EnderIO so I may  report this? Also, the version is 1.11.0, my apologies for entering the incorrect version.
