### ISSUE TITLE
Game Crashes Upon Starting World

### ISSUE THREAD

**Issue by ItsAstrobiology** [FTBTeam/FTB-Presents-Stoneblock-2#485]
* **Modpack Version**: 1.10.0

* **Issue**: Game crashes upon opening world

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/b6199536

* **Is it Repeatable?**: Yes

**Comment by Sunekaer** [comment]
Please try version 1.11.0 of the pack
