### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by aetasoul** [FTBTeam/FTB-Presents-Stoneblock-2#487]
* **Modpack Version**: 1.10.0

* **Issue**: I have just broken the capacitor bank (full of energy) with the party pickaxe and the server shutdown. When I start the world again, it load and send me to the crash report screen.

* **Link to Log or Crash File Paste**: [https://paste.dimdev.org/humezuzulo.mccrash]( https://paste.dimdev.org/humezuzulo.mccrash)

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Unknown

* **Known Fix**: Update to the version 1.11.0

**Comment by Leo40Git** [comment]
...why are you posting an issue for something that was already fixed?

**Comment by aetasoul** [comment]
To help the other people, as the community is supposed to do.
