### ISSUE TITLE
Broken Mekanism multiblock structures

### ISSUE THREAD

**Issue by SpielerB** [FTBTeam/FTB-Presents-Stoneblock-2#488]
* **Modpack Version**: 1.11.0

* **Issue**: In the version of Mekanism used by the modpack (9.7.0.369), there is bug causing clients to crash on world loading due to a NullPointerException.

* **Link to Log or Crash File Paste**: https://paste.dimdev.org/japoqegobo.mccrash

* **Is it Repeatable?**: Yes, load the world with a turbine or a boiler nearby

* **Mod/s Affected**: Mekanism, MekanismGenerators

* **Known Fix**: Has already been fixed in a newer Mekanism version (9.7.1.371) https://github.com/mekanism/Mekanism/issues/5388

**Comment by MrDj200** [comment]
Will this be fixed anytime soon?

**Comment by Sunekaer** [comment]
yes update should be out monday 29th

**Comment by Sunekaer** [comment]
Fixed in 1.12.0

**Comment by MrDj200** [comment]
Any update on when 1.12.0 will be released? As non Beta I mean
