### ISSUE TITLE
No Aluminum Ore in Mining Dimension

### ISSUE THREAD

**Issue by Leo40Git** [FTBTeam/FTB-Presents-Stoneblock-2#489]
* **Modpack Version**: 1.11.10

* **Issue**: No Aluminum Ore is generated in the Mining Dimension. This completely prevents access to HV lines in Immersive Engineering without Ex Nihilo, and also makes reusable casts harder to create.

* **Link to Log or Crash File Paste**: *N/A*

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: CoFHWorld

* **Known Fix**: Adding [this JSON file](https://pastebin.com/8ScQ9v91) to the CoFHWorld config folder (and also regenerating JER world gen info)

**Comment by Sunekaer** [comment]
Aluminum Ore is set to spawn in mining dim, have you check mining dim or only JER?

01_thermalfoundation_ores.json line 258

**Comment by Leo40Git** [comment]
Well, there are 2 entries named "aluminum", and the second one (for whatever `thermalfoundation:ore_fluid` with metadata 4 is, line 285) is probably overriding the first one. So uh, there's your problem. Probably also why there's no JER information for it.

**Comment by Sunekaer** [comment]
Second entry is for the end dim. as you see on line 293 it gens around endstone and on 304 its whitelisted for dim -8

**Comment by Leo40Git** [comment]
Yeah, but it still has the same name as the entry that's responsible for aluminum, so it's "replacing" that entry. Therefore, there is no aluminum in the mining dimension.

**Comment by Sunekaer** [comment]
that might be, let me try and change that

**Comment by Sunekaer** [comment]
well it spawns now, ill profile again so JER gets updated

**Comment by Sunekaer** [comment]
Fixed in 1.12.0
