### ISSUE TITLE
Also experiencing this problem with rendering hands

### ISSUE THREAD

**Issue by Satrman** [FTBTeam/FTB-Presents-Stoneblock-2#49]
* **Modpack Version**: 1.12.2-7.1.2.jarfor the morph mod, the Stoneblock 2 modpack version is 1.0.1

* **Issue**: So i saw this was an open issue already, but there is an issue when morphing into any mob with an empty hand;  It just fails to render the hand and the game crashes. I have tried turning into a creeper and a skeleton with an empty hand and both have crashed the game.  Upon re-launching and reloading the game, their hand seems to render fine, and i have the model, but if I try to morph back to my player model with an empty hand, the same thing happens.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/2ccd494e
* **Is it Repeatable?**: Yes

* **Mod/s Affected**: I do not know if any are, I can only say i'm playing the Stoneblock 2 modpack that is currently listed in the Twitch desktop app.

* **Known Fix**: currently, if I crash upon morphing with an empty hand, fix is to reload, scroll once I hear the little exp jingle noise so i load with a different hand that i know has an item, and morph back.

**Comment by Sunekaer** [comment]
https://github.com/iChun/Morph/issues/994

**Comment by DAmNRelentless** [comment]
I can confirm that. It adds several rendering glitches. When the morph is successful, player skins are messed up sometimes.

**Comment by DAmNRelentless** [comment]
Windows 10 Pro 64Bit 1809

**Comment by Satrman** [comment]
Windows 10 Home 64 Bit

**Comment by Sunekaer** [comment]
Closing issue as we disable render hands and there is a issue on the mods tracker about it
