### ISSUE TITLE
Chicken crafting issues

### ISSUE THREAD

**Issue by MajorCooke** [FTBTeam/FTB-Presents-Stoneblock-2#490]
* **Modpack Version**: 1.11.0

* **Issue**: The log, sand and lapis blue chickens are not craftable. They give nothing in the output receipt. 

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes.

* **Mod/s Affected**: Chickens

* **Known Fix**: Well, the blue chicken egg can be found from loot chests but the rest don't appear to be craftable. It would appear they were disabled, and they do not spawn naturally.

**Comment by MajorCooke** [comment]
It should be noted there are some mods I DISABLED, mainly because they're extraneous fluff that I personally don't see any use for having, and wanted to minimize how much resources they might be affecting:
 - Morph
 - Googly Eyes
 - MineTogether
 - PetRock
 - Smooth Fonts

**Comment by Sunekaer** [comment]
![image](https://user-images.githubusercontent.com/18720460/56866580-068a6c00-69db-11e9-9952-b6839fa9e298.png)
![image](https://user-images.githubusercontent.com/18720460/56866581-143ff180-69db-11e9-8e3a-c2da5d800c89.png)
![image](https://user-images.githubusercontent.com/18720460/56866585-228e0d80-69db-11e9-904a-574facbce439.png)

**Comment by Sunekaer** [comment]
Works fine for me
Mods you have disabled doesnt have anything to do with this

**Comment by MajorCooke** [comment]
Actually, it does. If you disable PetRock, you'll get minetweaker errors upon starting the game and they'll appear in the chat. Next thing you know, minetweaker isn't working as intended because you can also craft the transmutation table via the normal means instead of with the extreme crafting table.

Try it for yourself.

**Comment by Sunekaer** [comment]
ah then your issue should be fixed by deleting packrock.zs in the script folder
