### ISSUE TITLE
Crash and Crash...

### ISSUE THREAD

**Issue by averlyn30** [FTBTeam/FTB-Presents-Stoneblock-2#496]
* **Modpack Version**: 1.11.0

* **Issue**: Game crash before I can even get into the game. Tried again, different error message

* **Link to Log or Crash File Paste**: https://paste.dimdev.org/olimecamab.mccrash
https://paste.dimdev.org/edaxoyesol.mccrash

* **Is it Repeatable?**: Yes, even repeats itself after I click on Back to title screen
* **Mod/s Affected**:  Inventory Tweaks now it says Tinkers' Construct

* **Known Fix**: No, sorry! Going to try uninstalling and reinstalling just in case.

**Comment by Sunekaer** [comment]
"java.lang.OutOfMemoryError: GC overhead limit exceeded" assign more ram for it beable to load
