### ISSUE TITLE
Can't make an Advenced Control Seal : Store

### ISSUE THREAD

**Issue by SteveNoobGeek** [FTBTeam/FTB-Presents-Stoneblock-2#499]
* **Modpack Version**: 1.11.0

* **Issue**:  I can't use the Control Seal : Store on the crucible because it activates, I tried with a Mechanical User and with a Golem, no success. I also have all the researches in Golemancy
* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**:  Yes

* **Mod/s Affected**:  Thaumcraft

* **Known Fix**:

**Comment by Sunekaer** [comment]
some people sadly have had the same issue, theres nothing i can do about it, there is a issue on Thaumcraft github page. are you on a server? seems from old issues on Thaumcraft github that it maybe is a server issue

**Comment by SteveNoobGeek** [comment]
> some people sadly have had the same issue, theres nothing i can do about it, there is a issue on Thaumcraft github page. are you on a server? seems from old issues on Thaumcraft github that it maybe is a server issue

I'm in a single player world
