### ISSUE TITLE
Quest Book Issue

### ISSUE THREAD

**Issue by Melexan** [FTBTeam/FTB-Presents-Stoneblock-2#50]
* **Modpack Version**: 1.0.1

* **Issue**: Questing book will cause screen to blank except for top right hand corner. I cannot close the book to continue playing and cannot see the quests in the book.

* **Link to Log or Crash File Paste**: no crash log created

* **Is it Repeatable?**: yes

* **Mod/s Affected**: 

* **Known Fix**: Decreased resolution and it works. If I use recommended resolution for my computer it doesn’t work.

**Comment by LatvianModder** [comment]
Can you take a screenshot of the broken screen?

**Comment by Melexan** [comment]
![stoneblock2 questbook](https://user-images.githubusercontent.com/46437207/50810270-b9bd4100-12d6-11e9-90b6-0d87df8e0909.jpg)

**Comment by LatvianModder** [comment]
Huh wtf. You have any shader mods, optifine, anything outside ordinary? What's your screen resolution and minecraft gui scale?

**Comment by Melexan** [comment]
I literally downloaded it through the twitch launcher and pressed play.

GUI scale is normal and resolution is 1366 x 768. Recommended for my computer.

**Comment by LatvianModder** [comment]
I have absolutely no clue what could cause this

**Comment by LatvianModder** [comment]
Seems like another person has this issue. Now it counts as repeatable :P

**Comment by Melexan** [comment]
I wasn’t able to decrease my resolution and run the game... my quest book opened fine. Then I closed the game and changed it back and it stopped working. So I’ve just been playing at the decreased resolution.

**Comment by Sunekaer** [comment]
Closing this issue, as there´s nothing we can do about this other then wait and see if the mod dev fixes it
