### ISSUE TITLE
Game crashes every time upon loading up

### ISSUE THREAD

**Issue by Nosirromm** [FTBTeam/FTB-Presents-Stoneblock-2#501]
Modpack Version: V 1.11.0

Issue Description: Game crashes upon loading up the world after attempting to automate a Industrial Foraging Potion Brewer with Extra Utilities Transfer Pipes and Transfer Node and Ender IO Fluid Tank And Endervoir. 

Link to Log or Crash File Paste: https://paste.feed-the-beast.com/view/ffdb008e

Is It Repeatable?: No as I am unable to load into my world.

Mods Affected: Possibly Industrial Foregoing, Extra Utilities 2, and Ender IO. Tesla Core Lib and Tesla Core Lib Registries have been identified as potential causes when Minecraft crashes. 

Known Fix: No known Fix.

![Minecraft 1 12 2 2019-04-28 4_04_24 PM](https://user-images.githubusercontent.com/50084265/56869559-26686280-69d0-11e9-96e5-c5ecc49a02d0.png)

**Comment by Sunekaer** [comment]
#476

**Comment by byBackfish** [comment]
I have the Same Problem. Please Help
