### ISSUE TITLE
World crashes when i load up and try to move

### ISSUE THREAD

**Issue by MuhQuade** [FTBTeam/FTB-Presents-Stoneblock-2#502]
* **Modpack Version**: 1.12.2

* **Issue**: World crashes when i load up and try to move

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/564a0f13

* **Is it Repeatable?**: Everytime i load into a world and try to move

* **Mod/s Affected**: Toast Control
![Crash](https://user-images.githubusercontent.com/50128499/56940315-70069980-6b05-11e9-907a-7bcd8d1b999b.PNG)

* **Known Fix**: EDIT: i removed the mod from the modpack and everything works fine,

**Comment by PaxoTheParrot** [comment]
I have a similar issue, however the mods that potentially caused it is unknown.
Crash Report : https://paste.dimdev.org/izinimogus.mccrash
![StoneBlock2-Crash](https://user-images.githubusercontent.com/34402775/57159638-476cf100-6dde-11e9-90db-a381770c1dae.jpg)

**Comment by Sunekaer** [comment]
fixed in 1.13.0
