### ISSUE TITLE
Our world still crashing with people online or not

### ISSUE THREAD

**Issue by dragonborne** [FTBTeam/FTB-Presents-Stoneblock-2#503]
* **Modpack Version**: 1.11.0

* **Issue**: server still crashing

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/0ed73824

* **Is it Repeatable?**: any time server starting and hold for hour but anytime droped after one min after start after crash

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Sunekaer** [comment]
Some wireless redstone in the world causing the crash, where doesnt the log say
