### ISSUE TITLE
[Suggestion] Craftable Creative Items with Avarita?

### ISSUE THREAD

**Issue by Leo40Git** [FTBTeam/FTB-Presents-Stoneblock-2#504]
Currently, the modpack doesn't feature much of an "endgame" (apart from the Infinity tools, which are pretty much vanilla end-game).
Creative items, however, are pretty much the ultimate endgame items. However, they're (obviously) uncraftable.
...so why not give them crafting recipes (using endgame ingredients, obviously)?
It would also give Avarita a whole lot of more uses.
Heck, you could even extend the current "Extreme Crafting" questline into a Creative questline ~~and name it "Bragging Rights"~~!

**Comment by Sunekaer** [comment]
We are only doing bug fixing on this pack and adding anything new

**Comment by Leo40Git** [comment]
Ah, okay. Maybe something to consider for the next version of StoneBlock, then?
