### ISSUE TITLE
Crash whit fluids

### ISSUE THREAD

**Issue by 77Creeper77** [FTBTeam/FTB-Presents-Stoneblock-2#505]
Modpack Version: Stoneblock 2: 1.12.2

Issue: I connected an "ender tank (EnderIO)" full of water to a "potion brewer (industrial foregoing)" with some "pressurized fluid conduits (EnderIO)", but as soon as the machine started Minecraft ran into a problem and crushed.
Now I can no longer enter my world because as soon as I do this the error repeats itself.

Link to Log or Crash File Paste: https://paste.feed-the-beast.com/view/c3485ae7

Is it Repeatable?: I don't know because I can't return in my game

Mod/s Affected: Tesla Core Lib, Tesla Core Lib Registries

Known Fix: I don't know

[stoneblock.zip](https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/files/3141877/stoneblock.zip)

**Comment by Sunekaer** [comment]
https://github.com/MinecraftModDevelopmentMods/Tesla-Core-Lib/issues/50

**Comment by 77Creeper77** [comment]
So what should I do?

**Comment by Sunekaer** [comment]
You can try this:
Make sure to take a backup of your world before doing this! edit the forge.cfg in the config folder. There are a couple of lines about removing erroring entities. Change both of them to true and load the world and see if the removes the block. REMEMBER to set these back to false again!.... If that doesn't work, then you need to create a issue on darkutils github and get help from them

**Comment by 77Creeper77** [comment]
Thanks for your advice, I'm going to try it, but I don't known how to take a backup of my world, can you help me? Thanks for help

**Comment by Sunekaer** [comment]
make a copy of the world

**Comment by 77Creeper77** [comment]
Sorry but my question was "How can I make a copy"?

**Comment by Sunekaer** [comment]
if single player go to the instance folder, saves, and copy the world you wanna backup to your desktop
![image](https://user-images.githubusercontent.com/18720460/57703916-413e0680-7661-11e9-8173-dcf0dd4f8202.png)

**Comment by 77Creeper77** [comment]
thks you, I'll do it

**Comment by 77Creeper77** [comment]
it works!!
Thanks you
