### ISSUE TITLE
Crops are not growing

### ISSUE THREAD

**Issue by LazyCowee** [FTBTeam/FTB-Presents-Stoneblock-2#506]
* **Modpack Version**: 1.11.0

* **Issue**: Crops in the game stopped growing. Whenever i try to plant something the crop remains small and never grows. I tried to plant them in all of the dimensions. Different Y levels. I made sure that the areas are well lit. However they were growing in early game now i am mid to late game.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/4e147533

* **Is it Repeatable?**: All the crops in the game have this issiue.

* **Mod/s Affected**: All the mods that include crops including vanilla minecraft.

**Comment by Sunekaer** [comment]
Please test with version 1.13.0, if that doesnt fix the issue please create a new issue
ttps://www.feed-the-beast.com/projects/ftb-presents-stoneblock-2/files/2713667
