### ISSUE TITLE
Gem armor effects without wearing it.

### ISSUE THREAD

**Issue by LazyCowee** [FTBTeam/FTB-Presents-Stoneblock-2#507]
* **Modpack Version**: 1.11.0

* **Issue**: I am not wearing the Gem armor but the effects are on me: fly, walking on water etc.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/4e147533

* **Is it Repeatable?**: Don't know

* **Mod/s Affected**: ProjectE

**Comment by Sunekaer** [comment]
How did you change the armor off?
