### ISSUE TITLE
Stone Block 2 Crash While Loading Worlds

### ISSUE THREAD

**Issue by PaxoTheParrot** [FTBTeam/FTB-Presents-Stoneblock-2#508]
* **Modpack Version**: 1.11.0

* **Issue**: I am unable to load/ create a new world.

* **Link to Log or Crash File Paste**:  https://paste.dimdev.org/izinimogus.mccrash

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Unknown
![StoneBlock2-Crash](https://user-images.githubusercontent.com/34402775/57183019-d9d4c980-6e9e-11e9-9939-525f60ba9ace.jpg)

**Comment by Sunekaer** [comment]
Please test with version 1.13.0, if that doesnt fix the issue please create a new issue, and use the template
https://www.feed-the-beast.com/projects/ftb-presents-stoneblock-2/files/2713667
