### ISSUE TITLE
/cave does not work

### ISSUE THREAD

**Issue by ApolloMCC** [FTBTeam/FTB-Presents-Stoneblock-2#510]
* **Modpack Version**: 1.12

Hello I have a server and /cave does not work! It says you are not in a "void world type"
In my server properties I have level-type=voidworld

**Comment by Sunekaer** [comment]
Is it a new server?

**Comment by ApolloMCC** [comment]
No it's not, it used to be ok

**Comment by Sunekaer** [comment]
Did you try restarting the server?

**Comment by ApolloMCC** [comment]
Yes of course, many times

**Comment by Sunekaer** [comment]
Could you send me the level.dat file of the save

**Comment by ApolloMCC** [comment]
https://drive.google.com/file/d/1wMnpO29TTZc1lRpzwK5pHiKeDBTpMLBl/view?usp=sharing

**Comment by Sunekaer** [comment]
Hmm, it says the level.type is "default"
try and replace the level.dat with this one
[level.zip](https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/files/3145970/level.zip)

**Comment by ApolloMCC** [comment]
That's really really odd, thank you so much Sunekaer

**Comment by ApolloMCC** [comment]
Hello! Sorry for revi

**Comment by Sunekaer** [comment]
Hmm, sorry then i dont know to fix this issue, i talked with the dev of the mod and this is also the first he has seen this issue
