### ISSUE TITLE
Cyclic tank dupe

### ISSUE THREAD

**Issue by kamyu2** [FTBTeam/FTB-Presents-Stoneblock-2#511]
* **Version**: 

FTBPresentsStoneblock2-1.12.0-1.12.2

* **Issue**:  

Putting a bucket of fluid into an empty Cyclic Fluid Storage Tank adds two buckets worth of fluid.  If the tank already has some fluid then it adds the correct single bucket worth.  Seems to happen with any fluid.

* **Is it Repeatable?**:  

100%

**Comment by Sunekaer** [comment]
Please test with version 1.13.0, if that doesnt fix the issue please create a new issue, and use the template
https://www.feed-the-beast.com/projects/ftb-presents-stoneblock-2/files/2713667
