### ISSUE TITLE
Thaumcraft research not working

### ISSUE THREAD

**Issue by sallie123** [FTBTeam/FTB-Presents-Stoneblock-2#512]
* **Modpack Version**: FTB: PresentsStoneblock2-1.12.0-1.12.2

* **Issue**: Thaumcraft first steps advancement is not initiating and I've tried just about everything. I've even restarted the hole mod pack .

* **Link to Log or Crash File Paste**: not applicable 

* **Is it Repeatable?**: yes 
* **Mod/s Affected**: 

* **Known Fix**: none

**Comment by Sunekaer** [comment]
Did you sleep after breaking crystals?
