### ISSUE TITLE
Extra Utilities 2 crashes my client

### ISSUE THREAD

**Issue by AllForMonkey** [FTBTeam/FTB-Presents-Stoneblock-2#513]
Modpack Verison: 1.12.0

Issue: when I am looking at my chicken breeders it crashes my client it happens every time and I think it is because of the item transfers.

https://pastebin.com/EYcbCVbF

Yes, it is repeatable.
 
Extra Utilities and Just Enough Items.

I don't know how to fix it.

**Comment by Sunekaer** [comment]
Log says CraftPresence not Extra Utilities

**Comment by Sunekaer** [comment]
Could you send your "craftpresence.properties" from the config folder.

**Comment by Sunekaer** [comment]
Could you check the version of CraftPresence in the mod folder? 
log says you have version v1.4.5 which is from November 2018, and we are using v1.5.3.1 now

**Comment by AllForMonkey** [comment]
umm i have the lastest update tho

**Comment by AllForMonkey** [comment]
here is the file you asked for :D


[craftpresence.zip](https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/files/3163677/craftpresence.zip)

**Comment by AllForMonkey** [comment]
i am using v1.5.3.1

**Comment by AllForMonkey** [comment]
wait thats the wrong crash report ...3

**Comment by AllForMonkey** [comment]
https://pastebin.com/E6HiG2zk here this the actual crash file

**Comment by Sunekaer** [comment]
Okay, yes its because of extra util, theres nothing i can do about, i reported the issue https://github.com/rwtema/Extra-Utilities-2-Source/issues/315, but dont expect a fix from the dev.
