### ISSUE TITLE
removing/ exit, spectator mode, after /cave visit "name"

### ISSUE THREAD

**Issue by out2ku** [FTBTeam/FTB-Presents-Stoneblock-2#516]
* **Modpack Version**: 1.12.2

* **Issue**: Hi , I have a problem where i can not get out of spectator mode after using /cave visit "playername". When i try to use /home from other players spot, it keeps me in spec mode. I tried to /cave visit my own place and that dont work either. The only way i have got out of it was delete my cave and start a new one , once in spawn. Any help? Thanks

* **Link to Log or Crash File Paste**:  No crashes or errors , just stuck in spec mode after visit, admin /gamemode 0 does not correct it, it will place you back in survival, but can still fly thru stuff, like spec mode.

* **Is it Repeatable?**:  Yes , every time 

* **Known Fix**:  Delete cave/island spot for player stuck in spec mode ,they delete, loose everything, restart server and start again.

Thanks for any feedback.

**Comment by Sunekaer** [comment]
You need to use /cave home or /cave spawn

**Comment by out2ku** [comment]
> You need to use /cave home or /cave spawn

Wow, that is all it was, it worked. Sorry to waste your time, i looked everywhere and did not find anything on it. Thanks for the fast reply, Can be closed now.
