### ISSUE TITLE
Mod Extreme Reactors hasn't been updated in 5 months.

### ISSUE THREAD

**Issue by OrakMoya** [FTBTeam/FTB-Presents-Stoneblock-2#517]
I'm using MultiMC to download this modpack.

- Modpack Version: 1.12.0
- Issue: Version of a mod is 5 months old.
- Is it Repeatable?: Yes, as long the mod isn't updated
- Mod/s Affected: Extreme Reactors
- Known Fix: Update the mod and its dependency, ZeroCore

**Comment by Sunekaer** [comment]
You give no reason for why i should update? the version we are on is stable

**Comment by OrakMoya** [comment]
This isn't a serious issue. I don't think anything has changed in gameplay, so I can live without it until a new reactor tier is added. But using a newer version of a beta could be more stable than using an older beta.

**Comment by Sunekaer** [comment]
Its gonna be a no to updating Extreme Reactors, do to many changes in the mod
