### ISSUE TITLE
FTB STONEBLOCK 2, crash EnderIO and Thinker's

### ISSUE THREAD

**Issue by AlotaZ** [FTBTeam/FTB-Presents-Stoneblock-2#519]
Hello guys I need help, before I clicked with an Unbreakable Wand over a battery, Vibrant Capacitor Bank and then I crashed. Everytime I start the world this crash. Mod pack version is 1.12.0 
*Crash log*
The mod that do crash the pack are EnderIO and Tinker's
[crash-2019-05-15_21.11.16-client.txt](https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/files/3184136/crash-2019-05-15_21.11.16-client.txt)
Please help me, ty

**Comment by Sunekaer** [comment]
https://github.com/portablejim/BetterBuildersWands/issues/101
To get back in to your world, you can try this:
Make sure to take a backup of your world before doing this! edit the forge.cfg in the config folder. There are a couple of lines about removing erroring entities. Change both of them to true and load the world and see if the removes the block. REMEMBER to set these back to false again!.... If that doesn't work, then you need to create a issue on darkutils github and get help from them
