### ISSUE TITLE
[v1.0.1] Gold Chickens give nuggets

### ISSUE THREAD

**Issue by Boomflex** [FTBTeam/FTB-Presents-Stoneblock-2#52]
Hello there,

I am working my way through having a chicken of each type... (Don't judge me, I have a 1 week old baby and have to stay up all night ha) and I have noticed that ALL other Ore/Ingot based chickens give ingots but for some reason the Gold one gives nuggets?

Line 473 of chickens.json in the chickens config folder.

Not sure if this is by design or it is just how the mod is, but feels like it should be uniform as gold is no rarer than other ingots.

:)

```  "chickens:goldchicken": {
    "name": "GoldChicken",
    "is_enabled": true,
    "lay_coefficient": 1.0,
    "lay_item": {
      "itemID": "minecraft:gold_nugget",
      "metaID": 0
    },
    "drop_item": {
      "itemID": "minecraft:gold_nugget",
      "metaID": 0
    },
    "spawn_type": "NONE",
    "parent_1": "chickens:ironchicken",
    "parent_2": "chickens:yellowchicken"
  },

**Comment by Sunekaer** [comment]
This is how the mod default generates the config, but ill change it to ingots

**Comment by Boomflex** [comment]
<3

**Comment by Sunekaer** [comment]
1.1.0
