### ISSUE TITLE
I don't know what I into the end

### ISSUE THREAD

**Issue by butter1732** [FTBTeam/FTB-Presents-Stoneblock-2#520]
I fill boring,so I dig up.
But when I dig to y=200
The screen become to drist(like the loning,but it have anything)
And I sigh out and sigh in,I was damaged and die,when I resurrection,I into the end 
Made by ender stone,and little ender ore .

**Comment by Sunekaer** [comment]
How much ram you have assigned? 
you need to go to 254 to TP normally
