### ISSUE TITLE
Launcher freezes during load

### ISSUE THREAD

**Issue by LordFizban** [FTBTeam/FTB-Presents-Stoneblock-2#521]
* **Modpack Version**: 
1.12
* **Issue**: 
Forge launcher freezes during initial load. Launcher freezes either at init 4/7 while loading ender io or at 7/7. I am using multimc to launch the pack.
* **Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/7fbea878
* **Is it Repeatable?**: 
Yes
* **Mod/s Affected**: 

* **Known Fix**:

**Comment by LordFizban** [comment]
![image](https://user-images.githubusercontent.com/26019280/57980974-b2533480-7a3a-11e9-823a-f75bd433749d.png)

**Comment by Sunekaer** [comment]
Hmm "Process crashed with exitcode -805306369." i dont know what that code means and couldnt find anything on google about it, could you try launching via twitch launcher

**Comment by LordFizban** [comment]
I have the same issue on twitch launcher, unfortunately. It freezes at exactly same part @ 4/7 Ender IO and then I have to manually kill the process. I can load Ender IO as a stand-alone mod in a custom pack via twitch launcher. 

Crash log is the same, except that exit code in Twitch launcher. Last sentence I see before app freeze is:
[18:12:43] [Client thread/INFO] [draconicevolution]: Finished Initialization.

Did a couple more tests, I have this issue in some other packs as well. However, some packs which have both ender IO and draconic revolution works ok while some do not. Couldn't establish pattern here. For reference: Stoneblock 1 loads fine.

Anyway, I do not think this is modpack related.

**Comment by Sunekaer** [comment]
Please test with version 1.13.0
https://www.feed-the-beast.com/projects/ftb-presents-stoneblock-2/files/2713667

**Comment by LordFizban** [comment]
tried with 1.13, there is no change, unfortunately. Memory and cpu usage will not change while mc is not responding.

![image](https://user-images.githubusercontent.com/26019280/58043509-026aed80-7b46-11e9-897b-119412ede8ce.png)

**Comment by LordFizban** [comment]
Update: I was able to progress a bit by disabling splash screen in config. Here is the last line I see with my current log:
[19:45:10] [ThaumicJEI Aspect Cache/INFO] [thaumicjei]: Finished Aspect ItemStack Thread.

Right after this, loader starts freezing as it used to do during Ender IO load.  Here is the new log: 
https://paste.feed-the-beast.com/view/dcaca810

**Comment by Sunekaer** [comment]
Well, then comparing your log with mine, you show be at the main menu... have you tried giving a few min before force closing it

**Comment by LordFizban** [comment]
I have fixed the issue by setting MC resolution to my desktop size and reducing max memory to 6gb. It still gets kind of stuck at Ender IO load, however after some time modpack loads. 

Thank you for your help.
