### ISSUE TITLE
StoneBlock 2 LAG

### ISSUE THREAD

**Issue by Fr3hz** [FTBTeam/FTB-Presents-Stoneblock-2#522]
In my pc StoneBlock 2 run not bad but frequently there is a frame lag to 0/20/6 FPS, i allocated 12 GB RAM and i use my Ryzen 2400g, any idea to fix this issue??
Below ScreenShots

![2019-05-19_13 17 26](https://user-images.githubusercontent.com/50796753/57981514-cb5ae600-7a38-11e9-83b7-d585ab22232e.png)
![2019-05-19_13 14 51](https://user-images.githubusercontent.com/50796753/57981515-cb5ae600-7a38-11e9-9013-6b9f3024d72b.png)
![2019-05-19_13 14 56](https://user-images.githubusercontent.com/50796753/57981516-cb5ae600-7a38-11e9-8118-f0799b561ad5.png)
![2019-05-19_13 15 56](https://user-images.githubusercontent.com/50796753/57981517-cb5ae600-7a38-11e9-9f32-dea50f4b0003.png)
![2019-05-19_13 16 58](https://user-images.githubusercontent.com/50796753/57981518-cbf37c80-7a38-11e9-9b86-75a10ccf19a8.png)
![2019-05-19_13 17 00](https://user-images.githubusercontent.com/50796753/57981519-cbf37c80-7a38-11e9-94b7-cb5d3d2a8f0a.png)

**Comment by Sunekaer** [comment]
try disabling texture animation in foamfix

**Comment by Sunekaer** [comment]
And lower your assign ram to 6gb

**Comment by JujuGonz** [comment]
im having the same problem and i disabled texture animation in foamfix but i dont know how to assign ram

**Comment by ShaedFangGH** [comment]
@Sunekaer Thank you so much dude it's perfectly clear of lag now. Oh, and @JujuGonz go into the profile for the modpack on Twitch, click the gear icon then Profile Settings. After that, click the box that says Use System Memory Settings (Make sure it isn't checked) and then set the slider to about 6000.
