### ISSUE TITLE
Project Intelligence, Brandons Core and Draconic Evolution Language Manager

### ISSUE THREAD

**Issue by w696392** [FTBTeam/FTB-Presents-Stoneblock-2#524]
* **Modpack Version**: 1.12.2

* **Issue**: Alright, this crash is a bit weird. There are several crashes that can occur while I play the game, all stating the language Manager in the crash logs. I'll state the reasons given by VanillaFix.

1.  Opening Project Intelligence      (reason: Project Intelligence, Brandon's Core)
2.  Using the Draconic Evolution Information Tablet      (reason: Project Intelligence, Brandon's Core, Draconic Evolution)
3.  Opening the Language Settings      (reason: Unknown)

* **Link to Log or Crash File Paste**: 
[Language Setting](https://paste.feed-the-beast.com/view/940ff8f0)
[Tablet](https://paste.feed-the-beast.com/view/ae9e00d0)
[Project Intelligence](https://paste.feed-the-beast.com/view/333ffbdc)

* **Is it Repeatable?**: Yes, I just use the Tablet, oben PI or the language Setting

* **Mod/s Affected**: Definitely Draconic Evolution and other Brandon's Core related Mods.

* **Known Fix**: ???

**Comment by Sunekaer** [comment]
Please test with version 1.13.0
https://www.feed-the-beast.com/projects/ftb-presents-stoneblock-2/files/2713667
