### ISSUE TITLE
world crash!

### ISSUE THREAD

**Issue by Andre402** [FTBTeam/FTB-Presents-Stoneblock-2#527]
i seriusly need help!
after i built a mechanism the world chrashed...and if i try to open it , it sent me a crash report(photo)
![Screenshot (7)](https://user-images.githubusercontent.com/50889725/58132389-73330800-7c21-11e9-9ecb-4b85f3970306.png)

**Comment by Sunekaer** [comment]
Please create an new issue and fill out the template.. i need all the information its asking for...

**Comment by Andre402** [comment]
sorry but i don't know how to do it i'm new on the site

**Comment by Sunekaer** [comment]
read the text in the box and not just delete when creating a issue

**Comment by Andre402** [comment]
no problem i solve the problem
