### ISSUE TITLE
Thaumcraft Crimson Rites can't be created

### ISSUE THREAD

**Issue by grossik** [FTBTeam/FTB-Presents-Stoneblock-2#528]
* **Modpack Version**: 1.12.0-1.12.2 and 1.13.0-1.12.2 

* **Issue**: I tried to make Crimson Rites, but crafting on Infusion Altar make error. [My Altar](https://imgur.com/ypXcqLa)

* **Link to Log or Crash File Paste**:  [https://paste.feed-the-beast.com/view/3e2b29e0](https://paste.feed-the-beast.com/view/3e2b29e0)

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Thaumcraft

**Comment by Kucus77** [comment]
Does those rings have Shield 3 enchant? If not, it is crashing.

**Comment by Sunekaer** [comment]
Relevant question by Kucus77 not aswered
