### ISSUE TITLE
Extra Cells Drives incorrect "item bytes used"

### ISSUE THREAD

**Issue by krisjenner** [FTBTeam/FTB-Presents-Stoneblock-2#529]
* **Modpack Version**: 
FTBPresentsStoneblock2-1.12.0-1.12.2
* **Issue**: 
Extra Cells 2 drive displays incorrect "item bytes" used for items resulting in them filling rapidly
* **Is it Repeatable?**: 
Yes SP and MP
* **Mod/s Affected**: 
Extra Cells 2
* **Known Fix**: 
:/ 

(64k drive shows only 513 bytes used)

https://gyazo.com/62ab6d55655ccba8539867f9f304c9eb

**Comment by Sunekaer** [comment]
Sadly not anything i can do about this, could you please create an issue with the mod author
