### ISSUE TITLE
Resetting Quests Doesnt Reset Rewards

### ISSUE THREAD

**Issue by QuadTab** [FTBTeam/FTB-Presents-Stoneblock-2#53]
* **Modpack Version**: < Stoneblock 2  - Version 1.0.1 >

* **Issue**: When you enable FTB-QUEST Editing mode and reset all quests you cant collect rewards from the quests  if re-completing them 

* **Link to Log or Crash File Paste**:

* **Is it Repeatable?**: <Yes (Can reset quests multiple times without it ```Fixing```)>

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Sunekaer** [comment]
https://www.feed-the-beast.com/projects/ftb-presents-stoneblock-2/files/2673992
