### ISSUE TITLE
Big Spender Quest not working.

### ISSUE THREAD

**Issue by BoBoXD** [FTBTeam/FTB-Presents-Stoneblock-2#530]
* **Modpack Version: 1.12.0 on 1.12.2

* **Issue: The quest ''Big Spender'' the maximum EMC on a table doesn't work, I filled it to max but instead of the 9,223,372,036,854,775,807 it does it to 9,223,372,036,854,776,000 and it doesn't complete the quest, I've completed the rest of the quests on the page and clicking Quick Complete comes up with the rewards screen but blank.

no crash and it's on a server

* **Is it Repeatable?**:  N/A

* **Mod/s Affected**: Possibly the quest book mod.

* **Known Fix**:  No, sorry

**Comment by Kucus77** [comment]
I can confirm. This is repeatable for me.
But for me it creates crash report - https://paste.dimdev.org/ovukozumip.mccrash
[crash-2019-05-23_02.53.32-server.txt](https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/files/3209912/crash-2019-05-23_02.53.32-server.txt)
Clicking Quick Complete comes up with blank rewards screen and crash info

**Comment by BoBoXD** [comment]
i haven't completed it at all it never completed

**Comment by Kucus77** [comment]
![image](https://user-images.githubusercontent.com/20968043/58220511-74daf980-7d0f-11e9-90c5-a82aaeaf3163.png)
![image](https://user-images.githubusercontent.com/20968043/58220524-83291580-7d0f-11e9-894e-749e12d721eb.png)
![image](https://user-images.githubusercontent.com/20968043/58220572-b10e5a00-7d0f-11e9-9599-29bcc8987c48.png)

Yes. Same here.
Never completed.

**Comment by Kucus77** [comment]
Clicking on Quick Complete create blank Rewards and Crash report.
But never complet quest

![image](https://user-images.githubusercontent.com/20968043/58220689-1f531c80-7d10-11e9-9794-6bd3143876fc.png)

**Comment by BoBoXD** [comment]
my number looks higher than yours so thats probably why

**Comment by BoBoXD** [comment]
idk im confused, wait for the dev

**Comment by BoBoXD** [comment]
also mine never says an error or crash report, i have over the ''maximum'' limit of emc so it doesn't complete and i cant get it to the exact amount

**Comment by Sunekaer** [comment]
Downgrade to FTBQuests version 1.5.1.146 will fix this issue

**Comment by BoBoXD** [comment]
how do I do this? i'm using the modpack downloaded through twitch launcher and the server I use automatically put all the mods in for me

**Comment by Sunekaer** [comment]
Go to profile Options 
https://s1.sunekaer.com/i/24-05-2019_15-11-29_TwitchUI.png
Removed tick in "Locked" and click "Okay"
https://s1.sunekaer.com/i/24-05-2019_15-12-00_TwitchUI.png
Scroll down find "FTB Quests" and click on it
Click on "Versions"
https://s1.sunekaer.com/i/24-05-2019_15-12-56_TwitchUI.png
Find "FTBQuests-1.5.1.146.jar" and click the download arrow
https://s1.sunekaer.com/i/24-05-2019_15-13-20_TwitchUI.png
Then the arrow will turn in to "installed" once its done, now load the pack

**Comment by BoBoXD** [comment]
amazing, thanks for all the help 👍

**Comment by Virtmo** [comment]
What about if you are playing on a server? Downgrading isn't an option. Is there a command to complete a quest?

**Comment by BoBoXD** [comment]
> What about if you are playing on a server? Downgrading isn't an option. Is there a command to complete a quest?

I was using a server, all I did is went into the FTP file access and switched the mod for the downgraded version and restarted it

**Comment by Dokupepa** [comment]
Just want to point out that this quest wouldn't turn in (for me) with FTBQuests-1.5.2.151.jar.  Downgrading to FTBQuests-1.5.1.146.jar worked.  Pack complete!
