### ISSUE TITLE
1.13.0 Stone crook works as fuel

### ISSUE THREAD

**Issue by Xetaxheb** [FTBTeam/FTB-Presents-Stoneblock-2#532]
* **Modpack Version**: 1.13.0

* **Issue**: Stone crooks have 200 ticks of fuel

**Comment by Sunekaer** [comment]
Which stone crook?

**Comment by Xetaxheb** [comment]
The one made out of pebbles, from one of the Ex mods

**Comment by Sunekaer** [comment]
Thanks
