### ISSUE TITLE
Mining Dimension isnt loading

### ISSUE THREAD

**Issue by Th3K0ntr4** [FTBTeam/FTB-Presents-Stoneblock-2#533]
* **Modpack Version**: 1.10.0

* **Issue**: Every time me or my friend try to go into the mining dimension there is nothing and we only can get back to the normal world by /spawn.

* **Is it Repeatable?**: yes

**Comment by Sunekaer** [comment]
First of your on a old version, try updating

i tested this with a locally hosted server I dont have this issue, maybe your head is stuck in a block? 
Do you see any caves if you fly around in spectator? is the server runnig sponge or any plugins?

**Comment by Th3K0ntr4** [comment]
The Server is a Nitrado server, that‘s why it‘s running an old Version. I‘m
sure that i am not stuck in a Block. I tried many things for example
gamemode 1 or 3 and it seems like the whole Dimension isn‘t loading. I
tried the same thing in singleplayer in the same version and it was
loading. The Dimension was completly normal.

Sunekaer <notifications@github.com> schrieb am Do. 30. Mai 2019 um 01:50:

**Comment by Sunekaer** [comment]
Hmm idk what is causing this issue for you, i have tested on dedicated servers and locally hosted server and cannot replicate this issue

**Comment by Th3K0ntr4** [comment]
Okay that‘s unfortunate. But thank you very much for trying to help me. If
you should find a solution for this issue you can message me again.

Sunekaer <notifications@github.com> schrieb am Fr. 31. Mai 2019 um 22:53:

**Comment by Sunekaer** [comment]
Same issue as #537
