### ISSUE TITLE
Minetogether Stoneblock 2 crashing

### ISSUE THREAD

**Issue by ItsTexx** [FTBTeam/FTB-Presents-Stoneblock-2#535]
Modpack Version: 1.12.2

Issue: Trying to load world, crashes after about half a minute and completely prevents me from playing that specific world

Is it Repeatable?: Yes 

Link to Log or Crash File Paste: https://paste.dimdev.org/xurujidihe.mccrash

Mod/s Affected: MInetogether/minetogetherserver

Known Fix: i dont know

**Comment by Sunekaer** [comment]
Seem that the file has been corrupted or overwritten with a blank file.
I would recommend you restore the minetogether.cfg from the latest update of the pack to fix the issue.
