### ISSUE TITLE
Crashing when i try to load save

### ISSUE THREAD

**Issue by Twinkas** [FTBTeam/FTB-Presents-Stoneblock-2#538]
Modpack Version -1.13.0

Issue - when i try to load my save it crashes. if i create a new world its okey untill i try to open it the next day.

Link to Log or Crash File Paste - https://paste.feed-the-beast.com/view/8a433e17                                Is it Repeatable? - Yes

Mod/s Affected - MineTogether , MineTogheterServer

Known Fix - Nope

**Comment by Sunekaer** [comment]
Seem that the file has been corrupted or overwritten with a blank file.
I would recommend you restore the minetogether.cfg from the latest update of the pack to fix the issue.
