### ISSUE TITLE
Mekanism is causing server crashes. Update Mekanism to fix it!

### ISSUE THREAD

**Issue by NLBlacky** [FTBTeam/FTB-Presents-Stoneblock-2#539]
* **Modpack Version**: 1.14.0

* **Issue**: Server is crashing due some kind of incompatible power transfer between Meckanism and Extra Utilities 2

* **Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/a11b1295
https://paste.feed-the-beast.com/view/96706a76
https://paste.feed-the-beast.com/view/bfafdd11

* **Is it Repeatable?**: It happens each time we start the server. 

* **Mod/s Affected**: 
Mekanism-1.12.2-9.7.6.377.jar
extrautils2-1.12-1.9.9.jar

* **Known Fix**: I have not found a fix yet. I might try to downgrade the version till this has been fixed. There are no coords given so I have no clue where exactly it is happening and the few seconds I have after the startup aren't enough to find the coords.

**Comment by NLBlacky** [comment]
Can confirm that downgrading fixed the constant crashing once the server came up. Extra Utilities 2 was unchanges in the update so it must have something to do with Mekanism's update. Changes were:


Mekanism-1.12.2-9.7.4.375.jar to Mekanism-1.12.2-9.7.6.377
MekanismGenerators-1.12.2-9.7.4.375.jar to MekanismGenerators-1.12.2-9.7.6.377
MekanismTools-1.12.2-9.7.4.375.jar to MekanismTools-1.12.2-9.7.6.377

**Comment by NLBlacky** [comment]
A possible fix has been posted here: https://github.com/mekanism/Mekanism/issues/5509#issuecomment-500037098

**Comment by NLBlacky** [comment]
Issue is still happening. Not sure why the latest version is marked as release while this crashing issue is still happening and even confirmed by Mekanism. Please update Mekanism.

**Comment by Sunekaer** [comment]
https://www.feed-the-beast.com/projects/ftb-presents-stoneblock-2/files/2727613
