### ISSUE TITLE
Cant turn in quest

### ISSUE THREAD

**Issue by avidgamer5918** [FTBTeam/FTB-Presents-Stoneblock-2#54]
* **Modpack Version**: 1.0.1

* **Issue**: Cant turn in wireless terminal quest in the storage tab in the quest book. We have tried it when it is unpowered, powered, unlinked, linked and we cant get it to turn in. 

* **Is it Repeatable?**: n/a

* **Mod/s Affected**: Ftb quest and ae2

**Comment by Sunekaer** [comment]
1.1.0

**Comment by Nebbacutta** [comment]
What is the fix for this?
