### ISSUE TITLE
Constant Lag, Server Crashes

### ISSUE THREAD

**Issue by DrTHC** [FTBTeam/FTB-Presents-Stoneblock-2#540]
* **Latest Release**: 

* **Stoneblock becomes very laggy and crashes constantly when further in game when no other mod pack does the same. I have had to force close the cmd 6 times tonight. **: 

* **Easily...**: 

I am running a dedicated server with i5 6600k 3.5ghz 3.9 boost 16gb DDR4 RAM and a SSD with 200mb/s internet connection. We have gotten quite far in the game and it starts to lag and become unplayable we've returned 3 times now as its such a amazing pack but please sort the lag issues out i honestly beg!!

**Comment by NLBlacky** [comment]
Post your crashlogs here if you want help. Without the crashlogs there is no telling what is causing it.
About your tps issues, this can have several reasons. Maybe use Tickprofiler or LagGoggles to track the cause of it as it might be something inside your server as well. Also maybe raise your server RAM to 8gb (in case you're lower) to confirm it is not just an issue with RAM that is causing your tps drops.

**Comment by Sunekaer** [comment]
Not really anything i can do about this as its something in your world causing the issue
Drop this mod into your server mods folder.
https://minecraft.curseforge.com/projects/tickprofiler
Then, try running /profile e, this will help you pinpoint lagging entities if there are any.
