### ISSUE TITLE
Deleting files, Missing Registry Entries 

### ISSUE THREAD

**Issue by DrTHC** [FTBTeam/FTB-Presents-Stoneblock-2#541]
* **1.13**: 

So I have made a complete new server as we where having issues, Now when you start it up it says its missing registry entries. Even though i have replaced the mod file 3 times.... The server remains up for 10 mins then crashes completely. Copy of the crash report is below 

https://paste.feed-the-beast.com/view/0572bfd6

* **yes i can repeat it**: 

* **ALL MODS, Keeps deleting stuff... **:

**Comment by Sunekaer** [comment]
Duplicate Mods:
    autoreglib : C:\Users\server\Desktop\New folder\.\mods\AutoRegLib-1.3-29.jar
    autoreglib : C:\Users\server\Desktop\New folder\.\mods\AutoRegLib-1.3-30.jar
    blockcraftery : C:\Users\server\Desktop\New folder\.\mods\blockcraftery-1.12.2-1.2.0.jar
    blockcraftery : C:\Users\server\Desktop\New folder\.\mods\blockcraftery-1.12.2-1.3.1.jar
    bonsaitrees : C:\Users\server\Desktop\New folder\.\mods\bonsaitrees-1.1.2-b144.jar
    bonsaitrees : C:\Users\server\Desktop\New folder\.\mods\bonsaitrees-1.1.3-b156.jar
    bookshelf : C:\Users\server\Desktop\New folder\.\mods\Bookshelf-1.12.2-2.3.581.jar
    bookshelf : C:\Users\server\Desktop\New folder\.\mods\Bookshelf-1.12.2-2.3.577.jar
    cofhcore : C:\Users\server\Desktop\New folder\.\mods\CoFHCore-1.12.2-4.6.2.25-universal.jar
    cofhcore : C:\Users\server\Desktop\New folder\.\mods\CoFHCore-1.12.2-4.6.3.27-universal.jar
    cofhworld : C:\Users\server\Desktop\New folder\.\mods\CoFHWorld-1.12.2-1.3.0.6-universal.jar
    cofhworld : C:\Users\server\Desktop\New folder\.\mods\CoFHWorld-1.12.2-1.3.1.7-universal.jar
    crafttweaker : C:\Users\server\Desktop\New folder\.\mods\CraftTweaker2-1.12-4.1.17.jar
    crafttweaker : C:\Users\server\Desktop\New folder\.\mods\CraftTweaker2-1.12-4.1.18.jar
    crafttweakerjei : C:\Users\server\Desktop\New folder\.\mods\CraftTweaker2-1.12-4.1.17.jar
    crafttweakerjei : C:\Users\server\Desktop\New folder\.\mods\CraftTweaker2-1.12-4.1.18.jar
    cyclicmagic : C:\Users\server\Desktop\New folder\.\mods\Cyclic-1.12.2-1.19.9.jar
    cyclicmagic : C:\Users\server\Desktop\New folder\.\mods\Cyclic-1.12.2-1.19.10.jar
    fastbench : C:\Users\server\Desktop\New folder\.\mods\FastWorkbench-1.12.2-1.7.1.jar
    fastbench : C:\Users\server\Desktop\New folder\.\mods\FastWorkbench-1.12.2-1.7.2.jar
    flatcoloredblocks : C:\Users\server\Desktop\New folder\.\mods\flatcoloredblocks-mc1.12-6.8.jar
    flatcoloredblocks : C:\Users\server\Desktop\New folder\.\mods\flatcoloredblocks-mc1.12-6.7.jar
    ftbbackups : C:\Users\server\Desktop\New folder\.\mods\FTBUtilitiesBackups-1.0.0.3.jar
    ftbbackups : C:\Users\server\Desktop\New folder\.\mods\FTBUtilitiesBackups-1.0.0.4.jar
    ftbquests : C:\Users\server\Desktop\New folder\.\mods\FTBQuests-1.5.2.151.jar
    ftbquests : C:\Users\server\Desktop\New folder\.\mods\FTBQuests-1.5.1.146.jar
    hatchery : C:\Users\server\Desktop\New folder\.\mods\hatchery-1.12.2-2.2.1.jar
    hatchery : C:\Users\server\Desktop\New folder\.\mods\hatchery-1.12.2-2.2.2.jar
    integrateddynamics : C:\Users\server\Desktop\New folder\.\mods\IntegratedDynamics-1.12.2-1.0.12.jar
    integrateddynamics : C:\Users\server\Desktop\New folder\.\mods\IntegratedDynamics-1.12.2-1.0.14.jar
    integrateddynamicscompat : C:\Users\server\Desktop\New folder\.\mods\IntegratedDynamics-1.12.2-1.0.12.jar
    integrateddynamicscompat : C:\Users\server\Desktop\New folder\.\mods\IntegratedDynamics-1.12.2-1.0.14.jar
    integratedtunnels : C:\Users\server\Desktop\New folder\.\mods\IntegratedTunnels-1.12.2-1.6.8.jar
    integratedtunnels : C:\Users\server\Desktop\New folder\.\mods\IntegratedTunnels-1.12.2-1.6.9.jar
    integratedtunnelscompat : C:\Users\server\Desktop\New folder\.\mods\IntegratedTunnels-1.12.2-1.6.8.jar
    integratedtunnelscompat : C:\Users\server\Desktop\New folder\.\mods\IntegratedTunnels-1.12.2-1.6.9.jar
    jei : C:\Users\server\Desktop\New folder\.\mods\jei_1.12.2-4.15.0.279.jar
    jei : C:\Users\server\Desktop\New folder\.\mods\jei_1.12.2-4.15.0.280.jar
    mcjtylib_ng : C:\Users\server\Desktop\New folder\.\mods\mcjtylib-1.12-3.5.2.jar
    mcjtylib_ng : C:\Users\server\Desktop\New folder\.\mods\mcjtylib-1.12-3.5.3.jar
    mekanism : C:\Users\server\Desktop\New folder\.\mods\Mekanism-1.12.2-9.7.6.377.jar
    mekanism : C:\Users\server\Desktop\New folder\.\mods\Mekanism-1.12.2-9.7.4.375.jar
    mekanismgenerators : C:\Users\server\Desktop\New folder\.\mods\MekanismGenerators-1.12.2-9.7.6.377.jar
    mekanismgenerators : C:\Users\server\Desktop\New folder\.\mods\MekanismGenerators-1.12.2-9.7.4.375.jar
    mekanismtools : C:\Users\server\Desktop\New folder\.\mods\MekanismTools-1.12.2-9.7.4.375.jar
    mekanismtools : C:\Users\server\Desktop\New folder\.\mods\MekanismTools-1.12.2-9.7.6.377.jar
    mysticallib : C:\Users\server\Desktop\New folder\.\mods\mysticallib-1.12.2-1.2.1.jar
    mysticallib : C:\Users\server\Desktop\New folder\.\mods\mysticallib-1.12.2-1.1.1.jar
    randomtweaks : C:\Users\server\Desktop\New folder\.\mods\randomtweaks-1.12.2-2.5.0.6.jar
    randomtweaks : C:\Users\server\Desktop\New folder\.\mods\randomtweaks-1.12.2-2.5.0.5.jar
    redstonearsenal : C:\Users\server\Desktop\New folder\.\mods\RedstoneArsenal-1.12.2-2.6.2.17-universal.jar
    redstonearsenal : C:\Users\server\Desktop\New folder\.\mods\RedstoneArsenal-1.12.2-2.6.3.18-universal.jar
    smoothfontcore : C:\Users\server\Desktop\New folder\minecraft.jar
    thermalcultivation : C:\Users\server\Desktop\New folder\.\mods\ThermalCultivation-1.12.2-0.3.2.11-universal.jar
    thermalcultivation : C:\Users\server\Desktop\New folder\.\mods\ThermalCultivation-1.12.2-0.3.3.12-universal.jar
    thermaldynamics : C:\Users\server\Desktop\New folder\.\mods\ThermalDynamics-1.12.2-2.5.5.21-universal.jar
    thermaldynamics : C:\Users\server\Desktop\New folder\.\mods\ThermalDynamics-1.12.2-2.5.4.18-universal.jar
    thermalexpansion : C:\Users\server\Desktop\New folder\.\mods\ThermalExpansion-1.12.2-5.5.3.41-universal.jar
    thermalexpansion : C:\Users\server\Desktop\New folder\.\mods\ThermalExpansion-1.12.2-5.5.4.43-universal.jar
    thermalfoundation : C:\Users\server\Desktop\New folder\.\mods\ThermalFoundation-1.12.2-2.6.2.26-universal.jar
    thermalfoundation : C:\Users\server\Desktop\New folder\.\mods\ThermalFoundation-1.12.2-2.6.3.27-universal.jar
    thermalinnovation : C:\Users\server\Desktop\New folder\.\mods\ThermalInnovation-1.12.2-0.3.3.12-universal.jar
    thermalinnovation : C:\Users\server\Desktop\New folder\.\mods\ThermalInnovation-1.12.2-0.3.2.11-universal.jar

**Comment by DrTHC** [comment]
They are not... there is one of each mod in the file i can upload a screenshot?

**Comment by DrTHC** [comment]
Why have you closed this???? its not resolved.....
