### ISSUE TITLE
Ex Nihilo: Creatio - Auto Sieve crashes server when Fed Chorus Fruit.

### ISSUE THREAD

**Issue by Ikarsu** [FTBTeam/FTB-Presents-Stoneblock-2#543]
* **Modpack Version**:  1.13.0 

* **Issue**: Ex Nihilo Creatio: Crashing when auto heavy sieve interacts with Chorus Fruit

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**:  Server crashes as soon as you feed Chorus Fruit to an Auto Heavy Sieve while in operation. 

* **Mod/s Affected**:  Ex Nihilo Creatio 1.12.2-0.4.3.1, Extra Utilities 1.12-1.9.9 (if you use the mechanical user) 

* **Known Fix**: Must remove Chorus Fruit from mechanical user via MC edit or server will crash in an infinite loop. Loading from the last backup reverts any damage inflicted from said infinite loop. If Chorus Fruit is fed by hand, you must load your last backup.

**Comment by Sunekaer** [comment]
Not a sifting material in this pack, please report to Ex Nihilo Creatio
