### ISSUE TITLE
Issue with open Chest's

### ISSUE THREAD

**Issue by IIc3peak** [FTBTeam/FTB-Presents-Stoneblock-2#544]
Modpack Version: 1.13.0

Issue: i Can't open any chest's

Link to Log or Crash File Paste: 
https://paste.dimdev.org/wuwowaxuse.mccrash

Is it Repeatable?: Yes

Mod/s Affected: Unkown

Known Fix: I Try to repair the Modpack, i try to create a New World, same issue

When i Try to open a Chest, become i a Ingame error on the top Right
(see screenshot)

![Unbenannt](https://user-images.githubusercontent.com/51754867/59366019-3c44a380-8d42-11e9-8d72-bee7f848cbed.png)

**Comment by Sunekaer** [comment]
Could you try with 1.14.0

**Comment by IIc3peak** [comment]
how can i change the Version? 
Sry, this is my first time to play a Modpack..

**Comment by Sunekaer** [comment]
![image](https://s1.sunekaer.com/i/17-06-2019_23-46-13_TwitchUI.png)
or 
![image](https://s1.sunekaer.com/i/17-06-2019_23-46-43_TwitchUI.png)
