### ISSUE TITLE
Error with Random Things

### ISSUE THREAD

**Issue by chezpaul** [FTBTeam/FTB-Presents-Stoneblock-2#545]
* **Modpack Version**: 1.14.0

* **Issue**: Game launcher won't finish launching. Tried three times. I get the same error every time. Random Things issue.

* **Link to Log or Crash File Paste**: https://paste.dimdev.org/iyiturevet.mccrash

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Random Things

* **Known Fix**: Nope

**Comment by Sunekaer** [comment]
Hmm, weird.
Please try reinstalling the pack and remember to backup your world before

**Comment by chezpaul** [comment]
So I changed my RAM allocation from 6 Gigs to 8 Gig and it went through.
Now it's Compact Machine that three times out of 4 will crash the launch.
[https://paste.dimdev.org/apatafecew.mccrash](https://paste.dimdev.org/apatafecew.mccrash)

**Comment by chezpaul** [comment]
BTW, re install didn't change anything on Compact machine crashing

**Comment by chezpaul** [comment]
Does this say anything?
[https://paste.dimdev.org/gitisufavu.mccrash](https://paste.dimdev.org/gitisufavu.mccrash)
I have to launch 4 times before it goes through. And then I can leave it on all day, it doesn't crash.

**Comment by chezpaul** [comment]
I maybe forgot to say that I added OptiFine_1.12.2_HD_U_E3 to be able to play with Shaders

**Comment by Sunekaer** [comment]
Hmm thats weird it is having problems the Dim id´s "Invalid dimension id", even tho those are valid ids and works for everyone else, could you try without adding or modifying the pack?
