### ISSUE TITLE
Ender storage 

### ISSUE THREAD

**Issue by Guagmire** [FTBTeam/FTB-Presents-Stoneblock-2#546]
1.13

Enderstorage crashes on start up.

https://paste.dimdev.org/wuzonewiqe.mccrash

It has happend multiple times, last time was in version 1.12, i updatet the pack and nothing was wrong, but now out of nothing i get the same error, and it wont go away.
Also cant start the world with this error.

Enderstorage 

* **Known Fix**:

**Comment by Sunekaer** [comment]
EnderStorage was unable to read it's data, please delete the 'EnderStorage' folder Here: C:\Users\Cedric\Documents\Curse\Minecraft\Instances\FTB Presents Stoneblock 2 (1)\saves\New World-\EnderStorage

**Comment by TimMaass** [comment]
I have the same problem also in version 1.12 but i downloadet it from Twitch so when i update, my save files are gone. 

https://paste.dimdev.org/enaxukunot.mccrash

**Comment by TimMaass** [comment]
I had the same problem and followed the steps and eaven solverd it. But when i entered in my world the starting room had spawned in the middle of my chest room and all my items were liyng on the ground and were making so much lag. So my question is how can i reload a reacend backup, plus deleating enderstorage without resetting the spawn area.
