### ISSUE TITLE
My Spawn room was resetted after fixing a other bug

### ISSUE THREAD

**Issue by TimMaass** [FTBTeam/FTB-Presents-Stoneblock-2#547]
* **Modpack Version**: 1.12.0

* **Issue** I had a problem with EnderStorage so i deleted the ender storage file like comments tolt me to and started the world again but when i entered the main spawn cave had come again all around was fine, only the sphere were you spawn in was back and all my items were on the ground, because i had my chest room were the spawn had reapeared. so how can i go back to a nother backup and fix the Ender storage think at the same time.

* **Link to Log or Crash File Paste**: There is no file 

* **Is it Repeatable?**: No

* **Mod/s Affected**: Ender Storage.

* **Known Fix**:Reset world to reasent backup but dont know how.

**Comment by Sunekaer** [comment]
In Minecraft\Instances\FTB Presents Stoneblock 2 you should have a backup folder, there in youll find zip files containing backups of your world

**Comment by TimMaass** [comment]
Ok thank You.

Now i just tryed to recover most iems and just rebuild the stuff that broke but is there a way to make manual backups so i can save it every dey because in the backup folder are only seven folders and i would loose eaven more progress if i loadet them ( how do i load a backup folder?).

**Comment by Sunekaer** [comment]
/backup start 
Will generate a new backup in the backup folder
its a complete copy of the world there is in the zip file so you can just copy it in to a folder in you saves folder

**Comment by TimMaass** [comment]
were do i past the copied folder?

**Comment by TimMaass** [comment]
but thanks for the backup start
