### ISSUE TITLE
Crash caused by "Unknown"

### ISSUE THREAD

**Issue by Guagmire** [FTBTeam/FTB-Presents-Stoneblock-2#548]
1.14

I tried launching my game but it was unable because of a problem with "Unknown"

https://paste.dimdev.org/pijikegoya.mccrash

i tried running it again but wont help.
It said "Unknown"

**Comment by Guagmire** [comment]
second time it was hammer Core so could also be a problem with Hammercore.

**Comment by Sunekaer** [comment]
What launcher/client you using?
Log for second time?

**Comment by Guagmire** [comment]
I am using forge, second time and third and so on the problem was hammer
core, i never had these kind of problems before with stoneblock 1

I will send logg when im possible dont have it rn

Op vr 21 jun. 2019 22:22 schreef Sunekaer <notifications@github.com>:

**Comment by Guagmire** [comment]
I updatet to 1.15 and get the same error. again its hammercore
https://paste.dimdev.org/ewahogoqat.mccrash this is the logg of it.

**Comment by Guagmire** [comment]
Here is the Log for Hammercore fail
https://paste.dimdev.org/ewahogoqat.mccrash

Op vr 21 jun. 2019 om 22:22 schreef Sunekaer <notifications@github.com>:

**Comment by Sunekaer** [comment]
Please test with 1.17.0, if you still have this issue, please reopen this issue
