### ISSUE TITLE
Auto Pickup Items

### ISSUE THREAD

**Issue by Lucian0301** [FTBTeam/FTB-Presents-Stoneblock-2#55]
Hello i got a problem after i got a crash i relaunched the game and auto picking up items is not working, the only way i can pick up items form the gorud is shift+right click on them, i want to mention that i try to load now map aswell and i still got the same problem, i let attached the last crash log here. Thank you!
[https://pastebin.com/AZczvw5x](url)

**Comment by Sunekaer** [comment]
Copy your save folder out to your desktop and reinstall the pack and copy it back again and test

**Comment by Lucian0301** [comment]
Problem solved, reinstalled the pack, thank you!
