### ISSUE TITLE
Stoneblock 2 crashing while trying to load world

### ISSUE THREAD

**Issue by Tiremanager** [FTBTeam/FTB-Presents-Stoneblock-2#550]
* **Modpack Version**: 1.14.0

* **Issue**: After placing coal generator (RFTools) atop a spawner (RFTools), the game crashed and now always crashes when trying to load the world. 

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/0e5df043

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: RFTools

**Comment by Sunekaer** [comment]
Sorry for the late reply, link to log isnt working, please reupload the load if this still is a issue
