### ISSUE TITLE
Stoneblock 2 Crash

### ISSUE THREAD

**Issue by Alkiebob** [FTBTeam/FTB-Presents-Stoneblock-2#551]
1.14.0

after placing garden cloche (mekanism) watering (sink) putting in dirt and inferium seed  (teir 2) everything was fine until i placed the wireless power relay (extra utils 2) then it immediatley crashed to title and now wont load the world 

https://paste.feed-the-beast.com/view/15a69461

* **Is it Repeatable?**: yes every time i try to load

* **Mod/s Affected**: extra utils 2,  mekanism
* **Known Fix**: possible to use different power source unfounded as cant load world to test.

**Comment by Guagmire** [comment]
have you tried to pick an older save or start without the RF Mod, ?

**Comment by Alkiebob** [comment]
no i gave up looking so deleted the world 
thanks anyway
