### ISSUE TITLE
Crash on start with the new launcher.

### ISSUE THREAD

**Issue by Orelaterad** [FTBTeam/FTB-Presents-Stoneblock-2#552]
* **Modpack Version**: Version: 1.14.0

* **Issue**: crash on startup

* **Link to Log or Crash File Paste**: none avalible, tried getting it but unresponsive.

* **Is it Repeatable?**: everytime
* **Mod/s Affected**: all

* **Known Fix**: id like to know, love the modpack.

**Comment by Sunekaer** [comment]
log?
