### ISSUE TITLE
RFTools Builder doing Crash on Preview

### ISSUE THREAD

**Issue by Kratzwurst** [FTBTeam/FTB-Presents-Stoneblock-2#553]
* **Modpack Version**: 1.14.0

* **Issue**: when i change to every corner to display the mining area (dimension 256x256x256) and when i press to disabled the preview, than get's be a crash. After reload or restart the game is the preview button active

* **Is it Repeatable?**: yes, after reload the World and after client restart, get's the same issue

* **Mod/s Affected**: RFTools v. 1.12-7.71

* **SP/MP**: SP
* **Crashlog**: 

- https://paste.feed-the-beast.com/view/ec660677 (in game crash log)
- https://paste.feed-the-beast.com/view/a8e36796 (latest client log)

**Comment by Sunekaer** [comment]
Sorry for the late reply, link to log isnt working, please reupload the load if this still is a issue

**Comment by Kratzwurst** [comment]
Sorry, i have no any Profile of your Modpack to reupload the log files. 

*close*
