### ISSUE TITLE
FluidCows 

### ISSUE THREAD

**Issue by Shybella** [FTBTeam/FTB-Presents-Stoneblock-2#554]
* **Modpack Version**: 
1.15.0
* **Issue**: 

In the 1.15.0 update FluidCows wasn't updated even though SB2 FluidCows is 2 versions behind and the latest has been set to release for over a month for the latest version of FluidCows.

**Comment by Sunekaer** [comment]
Because I haven't had a reason to update that specific mod.

**Comment by Shybella** [comment]
Multiple crashes are fixed cannot get into my singleplayer world because of 2 crashes that are fixed in new version my friend has the same issue

**Comment by Shybella** [comment]
Please, Sunekaer, we need a update for mods in Stoneblock2.
