### ISSUE TITLE
Hammercore crash still not fixed

### ISSUE THREAD

**Issue by Guagmire** [FTBTeam/FTB-Presents-Stoneblock-2#559]
<!--

1.15.0
Hammercore aint working so when i try to start up world it wont load because hammecore isnt working.

https://paste.dimdev.org/ewahogoqat.mccrash

Yes last month every time

Hammercore

no fix seen

**Comment by Sunekaer** [comment]
what crash, log?

**Comment by Sunekaer** [comment]
Have you informed HammerCore about it?
