### ISSUE TITLE
stoneblock2  crashed

### ISSUE THREAD

**Issue by sunvrzoSUNVRZO554** [FTBTeam/FTB-Presents-Stoneblock-2#561]
ลิงค์ไฟล์ที่เสีย .  https://paste.dimdev.org/omapagobep.mccrash

**Comment by Sunekaer** [comment]
Seem that the file has been corrupted or overwritten with a blank file.
I would recommend you restore the minetogether.cfg from the latest update of the pack to fix the issue.
