### ISSUE TITLE
Xaero's World Map - can't transport between dimensions, contains ad

### ISSUE THREAD

**Issue by aminecraftplayerx** [FTBTeam/FTB-Presents-Stoneblock-2#564]
As the title says, it won't let me transport between dimensions, which is obviously pretty important in this modpack. This also contains an advertisement on all their screens, which should be against any modpack maker's policies, so I'm assuming it's against your policy as well.

* **Modpack Version**: 

* **Issue**: 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Sunekaer** [comment]
What dim are you trying to go to? log?
What adds are you talking about?

**Comment by aminecraftplayerx** [comment]
1) I'm trying to go from mining dimension to home ("overworld") dimension and vice versa. This mod does NOT allow you to transport between any dimensions, ever, they do not provide that capability.

 

2) Every time you go into their settings or waypoints screens, there's an ad at the top for another game.

**Comment by Sunekaer** [comment]
1)  works fine for me and others.
2) this is a thing there has been added to the mod loooong after this pack as released and i cant replace this mod this far into the pack
