### ISSUE TITLE
Stoneblock 2 Game Crash

### ISSUE THREAD

**Issue by UnbreakableHoe** [FTBTeam/FTB-Presents-Stoneblock-2#565]
* **Modpack Version**: 1.15.0
* **Issue**: Continuous crashes, happen every so often

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/bbedff31
* **Is it Repeatable?**: Yes, happens every so often, doesn't appear to be triggered by any player actions

* **Mod/s Affected**: Crash Screen says that the possible mods with issues may be Random Things or p4ssword's Library

**Comment by UnbreakableHoe** [comment]
I've done some testing - crashes happen when entering certain chunks. I've moved all infrastructure out of that area, although crashes happen consistently when entering said chunks. If it helps, I'm on a multiplayer server.

**Comment by mhoch0** [comment]
This should be fixed having the same problem on my server. It kicks me out of my server then my client seems to get a darker tint each time it kicks me. After about three or so times my client is ultimately all black and can not rejoin the server and am forced to restart the client. VERY ANNOYING PLEASE FIX ASAP

https://paste.dimdev.org/ovigehebun.mccrash

**Comment by Sunekaer** [comment]
https://github.com/p455w0rd/p455w0rds-Library/issues/30

**Comment by Sunekaer** [comment]
https://www.feed-the-beast.com/projects/ftb-presents-stoneblock-2/files/2792347

**Comment by mhoch0** [comment]
Thanks for the reply. You guys replied super fast took almost 2 months! Too
bad I stopped playing the pack due to the game breaking bug. Probably won’t
play ur trash pack again but I’m glad u fixed the GAME BREAKING BUG two
months later.
