### ISSUE TITLE
Modpack Problem

### ISSUE THREAD

**Issue by TheSpooky531** [FTBTeam/FTB-Presents-Stoneblock-2#567]
* **Im trying to start the Stoneblock 2 modpack on 1.12.2 version -->

* **https://paste.feed-the-beast.com/view/e3c1e58fe -->

* **It happens everytime -->

* ** Dont know if any mod affects it -->

* **Known Fix**:

**Comment by Sunekaer** [comment]
Log doesnt work, please report it
