### ISSUE TITLE
Crash while loading creating world

### ISSUE THREAD

**Issue by Jackey33** [FTBTeam/FTB-Presents-Stoneblock-2#568]
Game always crash if I try to load an existing or create a new world(old world was made by another computer and it worked good), and after this there is no even crush report document, only latest log.
here it is: https://paste.feed-the-beast.com/view/bd327d08

Version of minecraft 1.12.2

Version of Stoneblock2 1.15.0

Forge 14.23.5.2838

**Comment by Sunekaer** [comment]
Sorry for the late reply, link to log isn't working, please reupload the log if this still is an issue
