### ISSUE TITLE
Hellish Quest Issue - Hell Biome disabled for Quantum Quarry

### ISSUE THREAD

**Issue by n3twoik** [FTBTeam/FTB-Presents-Stoneblock-2#57]
Modpack version: 1.0.1

Repeatable: Yes

Issue: I've completed the "Hellish" quest and have the Hell Biome Marker. I created the quantum quarry and inserted the biome marker into it.  It keeps mining overword blocks. 

Findings: The Hell Biome is disabled by Quantum Quarry in the extra utils config file. I've checked this in the config/extrautils2.cfg file.

**Comment by Sunekaer** [comment]
Not really an quest issue...
The only reason why the Hell Biome Marker quest is there, is because you need the biome for thaumcraft, but ill reenable it in the Quarry

**Comment by n3twoik** [comment]
Thanks, I agree it's not really a quest issue.  

I was just sad to see that the biome marker that the quest gives you for the Hell biome was disabled for use in QQ.  

Thanks for all your hardwork on this. This modpack and the Stoneblock 1 modpack before it are a lot of fun. You've done a great job.

**Comment by Sunekaer** [comment]
1.1.0
