### ISSUE TITLE
FTB Stoneblock 2. 

### ISSUE THREAD

**Issue by RegisteredPanda** [FTBTeam/FTB-Presents-Stoneblock-2#570]
FTB Presents Stoneblock 2 | Version: 1.15.0

it wont let me play. just gives me the issue 

https://paste.dimdev.org/uladarufel.mccrash

Crash File  https://paste.feed-the-beast.com/view/8cb73cb4

it has happend twice now.

i dont know if any mods are doing this.

**Comment by Sunekaer** [comment]
OutOfMemoryError = assign more ram to the pack
