### ISSUE TITLE
Cannot Join Server

### ISSUE THREAD

**Issue by XilefTech** [FTBTeam/FTB-Presents-Stoneblock-2#571]
* **Modpack Version**: 1.15.0

* **Issue**: installed a nitrado server with the server pack that i downloaded from curseforge
and when I tried to join, I got disconnectrd with the Message: "Server Mod Rejections" and a list of the versions of mods that are not the same.

* **Link to Log or Crash File Paste**:  https://paste.feed-the-beast.com/view/7db56e92

* **Is it Repeatable?**: yes, everytime I try to Join

* **Mod/s Affected**: AE2Wireless Terminals, Chisels&bits, CraftTweaker2, Iron Chests, Just Enough energistics, Mekanism, Mekanism Generators, Mekanism Tools, PSI, Tiny progressions, Wireless Crafting Terminal 2, p455w0rd's Lib

* **Known Fix**: I haven't tried yet, but just update the mods in the server pack

**Comment by Sunekaer** [comment]
our server pack is update, this is a problem at your server host, that might be using the wrong version or isnt updated
