### ISSUE TITLE
pulverizer does not work on Aluminum ore chunck from ex nihlo creatio

### ISSUE THREAD

**Issue by Mr-Clay** [FTBTeam/FTB-Presents-Stoneblock-2#572]
Mod version 1.15.0
The Aluminum ore chunk from ex nihlo creatio does not work with the thermal foundation pulverizer. Does not cause any problems just can't get the pulverizer to take or pulverize the Aluminum ore chunk

**Comment by Sunekaer** [comment]
solved in newer version of the pack
