### ISSUE TITLE
Instant travel to the End

### ISSUE THREAD

**Issue by FrenchCrouton** [FTBTeam/FTB-Presents-Stoneblock-2#573]
Version 1.15.0

Small bug with the Ender Orb Translocator involving using it on the bedrock that teleports you to the mining dimension. Doing so oddly overlaps your y value, looping to max height in the mining dimension. Essentially instantly taking you to the end dimension from the base stone over-world. Although this is nice, I'm pretty sure it's not intended.

No crashing, just an instant teleport to the end dimension

Every time I shoot the orb at the ceiling, the results are the same.

I thought this may be a problem as I easily got the orb from one of my beginner challenges, and I got to the end in no time.

**Comment by Sunekaer** [comment]
Sadly the only thing i can do about this is disabling Ender Orb Translocator
