### ISSUE TITLE
World gone

### ISSUE THREAD

**Issue by Bossman2303** [FTBTeam/FTB-Presents-Stoneblock-2#575]
version : 1.15.0
Issue : I closed my modpack next day i get back on to play and the world isnt there i go into the backups file copied that into the saves folder and it still didnt work
 crash log : https://paste.feed-the-beast.com/view/3c822f5a

not repeatable cant see the world in the start up screen it still is the in the save file tho

Not sure what mod is affecting this

Back up world
[2019-07-09-20-56-34.zip](https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/files/3394170/2019-07-09-20-56-34.zip)

**Comment by Sunekaer** [comment]
hmm very weird, i havent found a fix for it, try reporting it to bibliocraft
