### ISSUE TITLE
AE autografting - ProjectEX problem

### ISSUE THREAD

**Issue by FreakyFarm86** [FTBTeam/FTB-Presents-Stoneblock-2#577]
* **Modpack Version**: 1.15.0

* **Issue**: i'm trying in a creative world because i know this problem that in the previous release the world crash, in this release, AE autocrafting really too slow to calculate for example 16 stick with a 2 Oak Log. The AE system is link with a storage bus to a compress refine EMC link. I'm also try it to update every single mod in this pack to the latest version, nothing really change.

* **Link to Log or Crash File Paste**: no crash in this version

* **Is it Repeatable?**: Yes always and with all the object(s)

* **Mod/s Affected**: Applied Energistics 2 - ProjectEX

* **Known Fix**: --

**Comment by Sunekaer** [comment]
Nothing i can do about this sorry
