### ISSUE TITLE
won't launch pack because of extra cells

### ISSUE THREAD

**Issue by yeager111** [FTBTeam/FTB-Presents-Stoneblock-2#578]
* **Modpack Version**: 

* **Issue**: 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by yeager111** [comment]
every time I try loading it it takes about 20min then it says can not load anymore because of extra cells 2 then it says quit

**Comment by Sunekaer** [comment]
log?
