### ISSUE TITLE
chunks not loading while walking (not a crash)

### ISSUE THREAD

**Issue by Atomibus** [FTBTeam/FTB-Presents-Stoneblock-2#579]
* **Modpack Version**: 1.15.0

* **Issue**: Seems like chunks aren't loading while walking, but if I stay still for a while they loads.

* **Link to Log or Crash File Paste**: https://pastebin.com/itcK05Cc

* **Is it Repeatable?**: I don't think it is

* **Mod/s Affected**: I don't think it's affected by any mods

* **Known Fix**: none

**Comment by Sunekaer** [comment]
Seems like your CPU/pc might just be to slow for this pack
