### ISSUE TITLE
Stoneblock won't run properly

### ISSUE THREAD

**Issue by AsO43** [FTBTeam/FTB-Presents-Stoneblock-2#580]
* **Modpack Version**: 1.12.2 for Minecraft, Modpack 1.15.0

* **Issue**: When I use my mac to run Stoneblock 2 it won't run properly, I have been successful running it once with lag spikes happening around every 10 seconds, then when I accidentally shut it down, the mod Extra Cells 2 from Just Enough Items prevented another startup.

* **Link to Log or Crash File Paste**: 
https://paste.dimdev.org/efefelamuq.mccrash

* **Is it Repeatable?**: The same thing happened 5 times on different occasions, I uninstalled Stoneblock 2 twice and it still doesn't work

* **Mod/s Affected**: Extra Cells 2, Just Enough Items(Maybe)
<img width="988" alt="Screen Shot 2019-07-18 at 22 16 27" src="https://user-images.githubusercontent.com/53052640/61470700-b7395380-a9ab-11e9-86f7-5471b806c3ba.png">

**Comment by Sunekaer** [comment]
OutOfMemoryError = add more ram
