### ISSUE TITLE
p455word mod

### ISSUE THREAD

**Issue by nate4343** [FTBTeam/FTB-Presents-Stoneblock-2#582]
* **Modpack Version**: 

* **Issue**: 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by nate4343** [comment]
it crashes my game fix?

**Comment by Sunekaer** [comment]
log.....?

**Comment by lovelylizzie1031** [comment]
https://paste.dimdev.org/iricupazoq.mccrash

**Comment by lovelylizzie1031** [comment]
![image](https://user-images.githubusercontent.com/25827625/61738631-54034480-ad50-11e9-93c0-f3921031436b.png)

**Comment by Sunekaer** [comment]
#565
