### ISSUE TITLE
Random Things, p455w0rd's Library crash

### ISSUE THREAD

**Issue by brandenvas** [FTBTeam/FTB-Presents-Stoneblock-2#583]
![Screenshot (5)](https://user-images.githubusercontent.com/53241756/61755980-f5f25380-ad87-11e9-902f-dec98f341c22.png)

**Modpack Version:** 1.15.2

**Issue:** when ever i go south like 100+blocks from center on my own hosted server i get kicked my minecraft crashes so i loaded that world in solo and it still does it so its a modpack problem.

**Link to Log or Crash File Paste:** https://paste.dimdev.org/hesudahiqa.mccrash

**Is it Repeatable?:** yes

**Mod/s Affected:** Random Things, p455w0rd's Library

**Known Fix:**

**Comment by QuantumAssassin** [comment]
![Shader Patch](https://user-images.githubusercontent.com/53306409/61882755-196fe800-aec7-11e9-9291-a278d4b3b1e8.jpg)


DirtCraft Has found the fix for this.

**Comment by brandenvas** [comment]
that didnt fix anything still does it.

**Comment by Sunekaer** [comment]
#565

**Comment by QuantumAssassin** [comment]
t. Not sure then. Figured if it worked for me and others it would work for yall

**Comment by brandenvas** [comment]
not closed there was nothing there?

**Comment by brandenvas** [comment]
nothing to help me
