### ISSUE TITLE
Game crash mid playing

### ISSUE THREAD

**Issue by Cronos4** [FTBTeam/FTB-Presents-Stoneblock-2#588]
* **Modpack Version**: 1.15
* **Issue**: i can start the game, after a few seconds it just crashes. No idea why. Can not "reproduce it / can not undo it, since i don´t know the root cause
* **Link to Log or Crash File Paste**: https://paste.dimdev.org/sulageyoya.mccrash

* **Is it Repeatable?**:It repeats itself. Can´t tell how you can create it.
* **Mod/s Affected**:  It says it has something to do with extra utilities, but i am not totaly sure

* **Known Fix**: ---

**Comment by Cronos4** [comment]
I removed all Extra Utilities item from my world. I only placed down 4 Watermills the Wireless RF Baterie and the Transmitter and one Resonator. Maybe it is caused by the combination of Energy Cable from Cyclik in combination with the transmitter or the batterie, since the transmitter has 32 connection points next to the cables,
i hope i was able to help with the issue

**Comment by Cronos4** [comment]
after removing the wireless stuff it worked again

**Comment by Sunekaer** [comment]
XU2 is buggy and theres nothing i can do about it sorry
