### ISSUE TITLE
RFTools spawner not accepting any living matter.

### ISSUE THREAD

**Issue by OinkGoesThePiggy** [FTBTeam/FTB-Presents-Stoneblock-2#589]
With RFtools, the spawner is taking bones + dirt , however living matter doesnt seem to be working. I have tried many different types of living matter and even checked the config for which were enabled.

Im in the Stoneblock 2 FTB pack. How can i Fix this?

Picture to show setup: http://prntscr.com/okon1n

I have also tried this in single player, with the same bug occuring.

**Comment by Sunekaer** [comment]
Please report this at https://github.com/McJtyMods/RFTools/issues

**Comment by s1mples** [comment]
Have this problem too.
This is NOT a mod trouble - this is CONFIG trouble (info from mod author - checked & confirmed).
So - plese fix it.

**Comment by laundmo** [comment]
@s1mples after looking into this, theres a open issue about it in the rftools repo here: https://github.com/McJtyMods/RFTools/issues/1943

the fix is deleting config files and letting it regenerate them
