### ISSUE TITLE
Save doesn't show up in Single Player

### ISSUE THREAD

**Issue by ItalianStallion13** [FTBTeam/FTB-Presents-Stoneblock-2#592]
* **Modpack Version**: Stoneblock2 Version 1.1.1 Minecraft Version 1.12.2 Forge 14.23.5.2796

* **Issue**: Was perfectly fine the other day. Now that I try to play today all my settings are back to Default and my world is gone... When I check the file folder under Saves my world name is there and all my stuff is still available. I tried taking the level.dat file and rename it then take the OLD file and renamed it to level.dat and still nothing shows up. The game did not crash I closed it just like any other day. I copied the save folder then uninstalled the mod and did a reinstall and moved the save file to the new spot but to no avail. Also when installing it gave me the new version 1.15.0. So now I guess I'm REALLY lost.

* **Link to Log or Crash File Paste**: NONE

* **Is it Repeatable?**: I can open Stoneblock over and over and it's still not there.

* **Mod/s Affected**: None that I know of.

* **Known Fix**: I hope so!

Thank you for all the help.

**Comment by Sunekaer** [comment]
Hi
Is this still an issue?
Can you see the world in the save folder?

**Comment by AssassinQuest** [comment]
is this on curseforge because it happened to me too
