### ISSUE TITLE
i'e downloaded this pack and everytime i try opening it it says "luanching the game failed, attempting to move download uncessful and ive tried everything launching from twitch, from vanilla launcher one of the few times ive tried downloading mods and failed its getting very tedious and making me want to just quit any help? (minecraft stoneblock ftb 2)

### ISSUE THREAD

**Issue by commandough14** [FTBTeam/FTB-Presents-Stoneblock-2#594]
* **Modpack Version**: 

* **Issue**: 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Duallyz** [comment]
This also happened to me. What I did was, uninstall "Bytefence Anti-Malware". First, go to Control Panel then click "Uninstall a program", after that right click the Anti-Malware ( In case, reinstall Stoneblock 2 ).
(Sorry if there are grammar mistakes) Hope this can help you. :)
