### ISSUE TITLE
Minecraft crash (Singleplayer)

### ISSUE THREAD

**Issue by Loloncio** [FTBTeam/FTB-Presents-Stoneblock-2#595]
* **Modpack Version**: 1.15.0

* **Issue**: The world (singleplayer) just crashes and shows a message with a link to the crash report. I don´t know what is causing it, i´ve recently started with the power grid making 6 water mills. I also made 14 magmatic generators with 2 speed upgrades each and i´m using a wireless rf trasmiter and a batery to feed some ex compresum machines. Definetly it has something to do with extra utilities because if i get away of the machines it works perfectly but when i try to continue with that the game crashes after a couple of minutes. My pc specs: CPU: I7-6700K RAM: 16 GB DDR4 2666 mhz (8GB dedicated to Minecraft) GPU: GTX 1060 6GB PCB: MSI Z170A GAMING M3 SSD: 120 GB SAND DISK.
![Sin título-1](https://user-images.githubusercontent.com/53757112/62460914-99c60100-b783-11e9-8bb7-6698474a1b2e.jpg)
![Sin título-1](https://user-images.githubusercontent.com/53757112/62462937-0099e900-b789-11e9-8655-0ef6b53f399c.jpg)

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/b77b334e
[crash-2019-08-05_12.36.25-server.txt](https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/files/3467249/crash-2019-08-05_12.36.25-server.txt)
[crash-2019-08-05_12.58.33-server.txt](https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/files/3467250/crash-2019-08-05_12.58.33-server.txt)

* **Is it Repeatable?**:  Yes, i just have to mess around with the machines and it crashes after a couple of minutes.

* **Mod/s Affected**: It says Extra Utilities 2

* **Known Fix**: No, probably removing extra utilities 2.  I tried to get back from 1.9.9 to 1.9.8 but just gave me a couple minutes more before crashing.

**Comment by Sunekaer** [comment]
There is nothing i can do about this crash, and its too late to remove that mod
