### ISSUE TITLE
Trees arent growing in hopping bonsai, and dirt in pots arent rendering properly

### ISSUE THREAD

**Issue by Monarch7950** [FTBTeam/FTB-Presents-Stoneblock-2#596]
* **Modpack Version**: 1.15.0

* **Issue**: Hopping bonsai pot not working. Dirt in pot doesnt render properly or at all, and trees in the pot doesnt grow.

* **Link to Log or Crash File Paste**: No crash

* **Is it Repeatable?**: Yes. none of my pots work.

* **Mod/s Affected**: Bonsai Trees 1.1.3-b156

**Comment by Moose1301** [comment]
is there dirt in the pot?

**Comment by bloodscon** [comment]
Hopping Bonsai pots need a 2 block space above them to grow the tree if they don't have that room the dirt does not render and the tree will not grow

**Comment by Monarch7950** [comment]
> Hopping Bonsai pots need a 2 block space above them to grow the tree if they don't have that room the dirt does not render and the tree will not grow
Oh wow Thank You! Solved it
