### ISSUE TITLE
Crash when loading modpack(on 2/7)

### ISSUE THREAD

**Issue by phadac** [FTBTeam/FTB-Presents-Stoneblock-2#599]
Modpack Version:1.15.0

Issue:crash when i try to open modpack(it wont load)

Link to Log or Crash File Paste:  https://paste.dimdev.org/cocepalequ.mccrash

Is it Repeatable?:yes

Mod/s Affected:p455w0rdslib i think

Known Fix:

**Comment by Sunekaer** [comment]
https://www.feed-the-beast.com/projects/ftb-presents-stoneblock-2/files/2792347
