### ISSUE TITLE
Main Menu is "texture missing"

### ISSUE THREAD

**Issue by cpw** [FTBTeam/FTB-Presents-Stoneblock-2#6]
* **Modpack Version**: 1.0

* **Issue**: Main menu is texture missing instead of "Stoneblock" screen.

* **Is it Repeatable?**: Yes. Use linux or other OS with case sensitive file system

* **Mod/s Affected**: CustomMainMenu: your config refers to illegally named resource       "image": "mainmenu:BG_Text.png", and       "image": "mainmenu:BG.png",

No resource should be named using anything other than strictly lowercase. The on-disk resources are named incorrectly as BG.png and BG_Text.png. They don't load as a result (lowercasing is FORCED in minecraft and has been for 1.12's lifecycle). This  only shows as a problem because on case sensitive filesystems, "bg.png" != "BG.png".

* **Known Fix**: Rename the resources to bg.png and bg_text.png, and the references in the mainmenu.json file as well.

Have a good day!

**Comment by Sunekaer** [comment]
Thanks CPW

**Comment by kleshas** [comment]
Ah, so THAT's what's causing it - linux's case sensitivity.  Thanks cpw.
As an addendum, there's a very rare ore with the same issue.  Only seen it once in 3 hours of caving in the mining world.  Didn't think to check what ore it was.

**Comment by louis123456** [comment]
I can confirm I have this issue as well under my Linux installation.

**Comment by Sunekaer** [comment]
1.1.0
