### ISSUE TITLE
StoneBlock 2 Crash

### ISSUE THREAD

**Issue by DeadlyDream** [FTBTeam/FTB-Presents-Stoneblock-2#601]
* **Modpack Version**: 1.15

* **Issue**: Crashes when trying to load/ Empty file

* **Link to Log or Crash File Paste**:
[latest.log](https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/files/3475604/latest.log)
 

* **Is it Repeatable?**: Yes by pressing play

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Sunekaer** [comment]
"your vanilla jar may be corrupt"
Reinstall mc
