### ISSUE TITLE
Actually Additions auto-placer doesn't get pulse from EnderIO Redstone Conduit

### ISSUE THREAD

**Issue by JohnAxae** [FTBTeam/FTB-Presents-Stoneblock-2#602]
* **Modpack Version**: 1.15.0

* **Issue**: When we try to make [this ](https://www.youtube.com/watch?v=cXm7leBODto) auto wither farm, the auto placers don't get their pulse.

* **Link to Log or Crash File Paste**: Nothing in log.

* **Is it Repeatable?**: Yes, even with vanilla levers directly connected to the auto placers.

* **Mod/s Affected**: Actually Additions, EnderIO

* **Known Fix**: none

**Comment by Sunekaer** [comment]
Mod interaction issue nothing I can do about, please report it to the mod authors
