### ISSUE TITLE
crash on server join

### ISSUE THREAD

**Issue by Moose1301** [FTBTeam/FTB-Presents-Stoneblock-2#603]
* **Modpack Version**: 1.15.0

* **Issue**: my game crashes on server join

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/1839739a

* **Is it Repeatable?**: IDK how to 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Moose1301** [comment]
it firsted started happen when i was just mining and it kicked me off the server and then in the top right errors started showing. I try to rejoin the server and my game crashes

**Comment by Smiller96** [comment]
Aj mne to robí a neviem čo s tým.

**Comment by Sunekaer** [comment]
Not sure whats causing your issue, do you still have this problem?
