### ISSUE TITLE
how do i start?

### ISSUE THREAD

**Issue by Higuu** [FTBTeam/FTB-Presents-Stoneblock-2#605]
Really confused? Just spawned on a dirt block in the void. What's happening? what do I do? All I have is 3 books and I don't want to cheat anything in. How do I spawn in the cave that everyone else seems to be  spawning in?

I tried figuring it out on YouTube but cant make sense of anything. 

Please help. Im bad at this stuff. ;-;

**Comment by Moose1301** [comment]
are  you on a server?

**Comment by Higuu** [comment]
I'm not on a server, its single player ^^;;
