### ISSUE TITLE
Issue with /Dank/Null making the game unplayable.

### ISSUE THREAD

**Issue by Jure64** [FTBTeam/FTB-Presents-Stoneblock-2#606]
Version : 1.15.0

Issue :  I was in my base scrolling through my /Dank/Null MK VI and while I was scrolling with shift + scrollwheel, it crashed and I was sent to the main menu. I can't even make a new world.

https://paste.feed-the-beast.com/view/c2715a1d

Repeatable : No clue, never happened before though. Can't test it, as I can't make a new world, it just crashes.

Mod :  /Dank/Null idk if that's just the mod or if it's included in OpenBlocks

**Comment by Sunekaer** [comment]
https://www.feed-the-beast.com/projects/ftb-presents-stoneblock-2/files/2792347
