### ISSUE TITLE
not able to load world due to mine together mod 

### ISSUE THREAD

**Issue by jJAIPLAYZZ** [FTBTeam/FTB-Presents-Stoneblock-2#607]
* **Modpack Version**: 

* **Issue**: 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**: 
[crash-2019-08-06_22.30.35-server.txt](https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/files/3486242/crash-2019-08-06_22.30.35-server.txt)

**Comment by Sunekaer** [comment]
Seem that the file has been corrupted or overwritten with a blank file.
I would recommend you restore the minetogether.cfg from the latest update of the pack to fix the issue.
