### ISSUE TITLE
Stoneblock2 Serverfiles are outdated..

### ISSUE THREAD

**Issue by f0xx3r** [FTBTeam/FTB-Presents-Stoneblock-2#609]
Hey,

the Serverfiles from Stoneblock 2 are outdated, is there an update possible?
Please help wanna play with my friends...

best regards

f0xx3r

**Comment by Sunekaer** [comment]
outdated how?

**Comment by f0xx3r** [comment]
Server version is 1.14 and client version is 1.15

**Comment by Sunekaer** [comment]
https://www.feed-the-beast.com/projects/ftb-presents-stoneblock-2/files/2727712
this one?

**Comment by f0xx3r** [comment]
Thanks a lot man 👍 
Rlly appreciated <3
