### ISSUE TITLE
Killing Enderman Gives Unique Morph Every Time

### ISSUE THREAD

**Issue by MacAndSwiss** [FTBTeam/FTB-Presents-Stoneblock-2#61]
* **Modpack Version**: 1.0.1

* **Issue**: Every enderman killed provides a new morph, thus slowing or potentially crashing the game when attempting to open the option

* **Link to Log or Crash File Paste**:  https://imgur.com/a/VLHfUkk

* **Is it Repeatable?**: 
1. Craft a spawner using the recipe.
2. Use a spawner changer to change mob to enderman.
3. Use a Draconic Evolution Core (Basic, Wyvern, etc.) to create a stabilized spawner.
4. Place the spawner and kill the mobs.

* **Mod/s Affected**: Morph, may be caused by Draconic Evolution or Actually Additions, or may be due to "unique" mobs created by Googly Eyes.

* **Known Fix**: None.

**Comment by Sunekaer** [comment]
What are you spawning them with and does it happen with other weapons

**Comment by Sunekaer** [comment]
Restart the game and run command "/morph remove PLAYERNAME minecraft:enderman" next time you kill one you should only get one
