### ISSUE TITLE
Distorted/disapearing textures

### ISSUE THREAD

**Issue by DrTerry11** [FTBTeam/FTB-Presents-Stoneblock-2#610]
Using most updated version of stoneblock 2

When joining a world or multiplayer, all textures are fine but once going to another dimension or loading screen, textures bug out and begin distorting and disapearing. Some models effected by this are hostile mobs, pets, players, cobblestone chests. When looking for fixes everything says optifine but optifine isn't in the pack

https://m.imgur.com/aER4dDx

**Comment by Sunekaer** [comment]
thats a new one, did you add anymods or change some settings?
