### ISSUE TITLE
Corrupt world issues?

### ISSUE THREAD

**Issue by Dakota220** [FTBTeam/FTB-Presents-Stoneblock-2#614]
So basically i tried to bait a chicken and then it said that my game might be corrupt and then i couldnt crucible leaves anymore but it would take the item i just hope this gets fixed. it was a normal chicken bait. 2 seeds right next to each other. i was also wondering if there was a way i can fix my world. or not. But anyways thanks In Regards, Dakota

**Comment by Sunekaer** [comment]
any crash log or anything?
