### ISSUE TITLE
unstackable items cause crash if stack attempted in shelves

### ISSUE THREAD

**Issue by Linkgamer12** [FTBTeam/FTB-Presents-Stoneblock-2#619]
found a weird bug while storing a torch launcher. the item isn't stackable but i didn't know this at the time. i attempted to place it in an oak shelf by shift clicking it into the space of a second launcher. the game crashed. is it possible to prevent the game from attempting to stack the item in the shelves?

**Comment by Sunekaer** [comment]
If you still have this issue, please open a new issue and follow the template
