### ISSUE TITLE
Feature request: Agricraft

### ISSUE THREAD

**Issue by DAmNRelentless** [FTBTeam/FTB-Presents-Stoneblock-2#62]
* **Modpack Version**: 1.0.1

* **Issue**: It's not an issue. It's a feature request. As much as I like this pack, it definitely needs AgriCraft. I know it's been a while since it was updated but it works flawlessly. Furthermore Mystical Agriculture is a lot better with it and farming in general too. I needs some adjustments to avoid it being too OP but I find it could definitely come in handy.

* **Link to Log or Crash File Paste**: /

* **Is it Repeatable?**: /

* **Mod/s Affected**: /

* **Known Fix**: /

**Comment by DAmNRelentless** [comment]
I can provide the necessary config files if you guys are interested in adding it. I already implemented in my modpack. There are some things that need changes especially for mystical agriculture.

**Comment by Sunekaer** [comment]
Agricraft wont be added as its still in Alpha
