### ISSUE TITLE
My fps is capped at 60

### ISSUE THREAD

**Issue by LefTTwixx** [FTBTeam/FTB-Presents-Stoneblock-2#621]
* **Modpack Version**: Stoneblock specifically but i tried stoneblock 1 and 2 aswell as skyfactory 3 and it was all the same

* **Issue**:i am getting upwards of 170 fps but visually it is 60 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by VirxEC** [comment]
That's because of your monitor. It's a 60fps monitor. This has NOTHING to do with ANY GAME, nevermind a modpack!
