### ISSUE TITLE
Won't download on twitch because of Missing Addon ID: 277047

### ISSUE THREAD

**Issue by ZooZoo39** [FTBTeam/FTB-Presents-Stoneblock-2#625]
* **Modpack Version**: 

* **Issue**: 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by duartelourenco** [comment]
It was fixed because I just installed it via Twich!
Thanks to however fixed it!
