### ISSUE TITLE
crash xaeros minimap crash

### ISSUE THREAD

**Issue by KrafciSKy** [FTBTeam/FTB-Presents-Stoneblock-2#627]
* **Modpack Version**:  crash xaero minimap

* **Issue**: 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by epic-jargon** [comment]
had to delete this modpack because of this bug still an issue installed through twitch
