### ISSUE TITLE
Extreme Crafting Typos

### ISSUE THREAD

**Issue by FireSpawnster** [FTBTeam/FTB-Presents-Stoneblock-2#63]
Modpack: FTB-Presents-Stoneblock-2 version 1.0.1

Under the extreme crafting tab in the quest book, these items either have typos, messed up descriptions, the wrong words etc. It's stays that way in both multiplayer and single. Doesn't affect gameplay or anything, just thought it should be known.

![unknown 1](https://user-images.githubusercontent.com/46470806/50808843-5242c980-12b5-11e9-8578-d51299138535.png)
![unknown 2](https://user-images.githubusercontent.com/46470806/50808845-5242c980-12b5-11e9-9c65-03f234ff1d11.png)
![unknown 3](https://user-images.githubusercontent.com/46470806/50808846-5242c980-12b5-11e9-9512-7fd36c5b19af.png)
![unknown 4](https://user-images.githubusercontent.com/46470806/50808847-5242c980-12b5-11e9-9c16-88936257c7ff.png)
![unknown](https://user-images.githubusercontent.com/46470806/50808848-5242c980-12b5-11e9-92f2-a57c92c966be.png)

**Comment by aaronhowser1** [comment]
Woah yeah I have no idea what happened with that, I'll get it fixed ASAP

**Comment by Sunekaer** [comment]
1.1.0

**Comment by kreezxil** [comment]
In version 1.1.0 there are still typos in extreme crafting, this one is for the ore singularities.

![Iron Singularity, Bock?](https://www.kreezcraft.com/wp-content/uploads/2019/01/Screenshot_2.png)
![I get it a chicken was writing the descriptions, bock bock bock](https://www.kreezcraft.com/wp-content/uploads/2019/01/Screenshot_3.png)
![woo hoo, here we go again](https://www.kreezcraft.com/wp-content/uploads/2019/01/Screenshot_4.png)
![chickens everywhere!](https://www.kreezcraft.com/wp-content/uploads/2019/01/Screenshot_5.png)
![diamond singularity](https://www.kreezcraft.com/wp-content/uploads/2019/01/Screenshot_6.png)
do you need more screen shots?
- emerald
- copper
- tin
- lead
- silver
- nickel

# oddly enough
the following were correct
- fluxed
- lapis
