### ISSUE TITLE
out of memory error

### ISSUE THREAD

**Issue by bfc1974** [FTBTeam/FTB-Presents-Stoneblock-2#630]
Loaded from twitch launcher and then goes into java Minecraft launcher

* **Modpack Version**: 1.15.0

* **Issue**: crashes on loading and reports that mods are the issue

* **Link to Log or Crash File Paste**: https://paste.dimdev.org/ohuvuvopij.mccrash

* **Is it Repeatable?**: yes

* **Mod/s Affected**: several mods

* **Known Fix**:

**Comment by DankWafflez67** [comment]
Stoneblock 2 requires 4-6GB of ram(memory). Looks like your computer is only allocating just under 3 GB "Memory: 359970824 bytes (343 MB) / 2863661056 bytes (2731 MB) up to 2863661056 bytes (2731 MB)"
