### ISSUE TITLE
Iron Backpacks EMC 

### ISSUE THREAD

**Issue by TheForceteam** [FTBTeam/FTB-Presents-Stoneblock-2#64]
* **Modpack Version**: 1.1 

* **Issue**: EMC the Diamond Backpack from the mod Iron Backpacks and it will give you something like this https://gyazo.com/7d551c83067077cd2743e20b3718e36c

* **Is it Repeatable?**: Its easy you just need a transmutation Table and get the bag on it

* **Mod/s Affected**: ProjectE / IronBackpacks

* **Known Fix**: Remove EMC value from the Backpacks from Iron Backpacks

**Comment by Sunekaer** [comment]
Iron backpack will be removed next update so that won’t be a problem
