### ISSUE TITLE
Get lithium dust issue

### ISSUE THREAD

**Issue by Phelone** [FTBTeam/FTB-Presents-Stoneblock-2#640]
Hi!

I try to craft a mekanism's basic induction cell and a basic induction provider. However we need lithium dust and the recipe obligate us to use thermal evaporator and advanced solar generator. The issue is you enabled advanced solar generator in the modpack. So how can I resolve my problem without a modpack update? Moreover if a modpack update is necessary you can add the recipe to transform the brine into liquid lithium using a chemical crystallizer by example. Indeed the recipe to get brine is already encoded.

Best regards,

Stoneblock 2
Modpack version: 1.15.0

Phelone.

**Comment by ResTinZero** [comment]
Just build a Brine-Tower like you normally would and instead of Solar Gens you place normal Thermal Evaporation Blocks. If you want it to heat up place a Risistive Heater at a Fluid port and there you go.
