### ISSUE TITLE
cant join multiplayer games

### ISSUE THREAD

**Issue by joehaddad11** [FTBTeam/FTB-Presents-Stoneblock-2#641]
* **Modpack Version**: 
Stoneblock2

* **Issue**: 
in multiplayer next to online there is an x and when I put in my username and password it sais wrong credantials witch is not wrong I tried it at least like 20 times

* **Link to Log or Crash File Paste**: no crash logs

* **Is it Repeatable?**: so I basically cant join multiplayer servers because I cant login in the multiplayer tab

* **Mod/s Affected**: 

* **Known Fix**: no known fix

**Comment by Sunekaer** [comment]
Maybe the minecraft authentication was down, please try again
