### ISSUE TITLE
Stoneblock2 Update

### ISSUE THREAD

**Issue by Shybella** [FTBTeam/FTB-Presents-Stoneblock-2#643]
The modpack requires a basic mod update. Lots of crashes fixed and improvements.

Thank you for the hard work.

**Comment by linktlh** [comment]
Main mod I'd like to see updated; [https://github.com/p455w0rd/p455w0rds-Library/issues/33](p455w0rds-Library)
Recent version fixed the issue with loading worlds.

**Comment by Phelone** [comment]
Have you already an idea when the modpack will have an update? Next week? Next month?

Thank you for your work!

**Comment by Sunekaer** [comment]
Once I have time, life is really busy

**Comment by Sunekaer** [comment]
https://www.feed-the-beast.com/projects/ftb-presents-stoneblock-2/files/2792347
