### ISSUE TITLE
Instantly crashing on startup

### ISSUE THREAD

**Issue by Allen2331** [FTBTeam/FTB-Presents-Stoneblock-2#646]
https://pastebin.com/cpBmXKgK

I've got 8GB of ram allocated to my game right now, updated all drivers, and tried reinstalling. None of which fixed my problem. Everything will load and then as soon as I hear the sound, it crashes.

**Comment by Sunekaer** [comment]
Hi 
Please report your issue here: https://gitlab.com/DragonForge/HammerCore/issues
