### ISSUE TITLE
Cyclic Crashing Old World

### ISSUE THREAD

**Issue by Sithic** [FTBTeam/FTB-Presents-Stoneblock-2#647]
* **Modpack Version**: 1.12.1 - Minecraft 1.15.0 - Stoneblock 2

* **Issue**: I was playing normally around my mob farm and then I crashed with an error stating that Cyclic was conflicting, I tried to run my world again, same thing happened, I closed Minecraft and tried again, same thing, I repaired the profile through Twitch client, and still happens.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/623633f7

* **Is it Repeatable?**: It happens every time I try to play my world.

* **Mod/s Affected**: Cyclic - Version: 1.19.10

**Comment by Sunekaer** [comment]
https://www.feed-the-beast.com/projects/ftb-presents-stoneblock-2/files/2792347
