### ISSUE TITLE
Crashing client (p455w0rdslib/RandomThings, hard crash where Vanilla Fix doesn't stop it also fixes to remedy issues listed

### ISSUE THREAD

**Issue by shortybsd** [FTBTeam/FTB-Presents-Stoneblock-2#648]
* **Modpack Version**: 
StoneBlock 2 v1.15.0 for MC v1.12.2

* **Issue**: 
1.) Crashing when teleporting back to base with the known bug "Cannot get property PropertyDirection" from bad library (p455w0rdslib) and caused by Spectre coils, even if you don't have any. 
2.) Flux Networks magically stops sending power. Incoming always works. Fixed in new version as it was issues with network packets.

* **Is it Repeatable?**: 
Absolutely, all mods listed below are out of date and fixed in current versions.

* **Mod/s Affected**: 
fluxnetworks-1.12.2-3.0.19-21
p455w0rdslib-1.12.2-2.2.151
RandomThings-MC1.12.2-4.2.7.1

* **Known Fix**: 
Update affected mods mentioned above and those crashes/problems will cease.
Specifically:
[Flux-Networks-1.12.2-4.0.7](https://www.curseforge.com/minecraft/mc-mods/flux-networks/files/2786554) **Note: This is a Beta version**
[p455w0rdslib-1.12.2-2.2.156](https://www.curseforge.com/minecraft/mc-mods/p455w0rds-library/files/2745046)
and
[RandomThings-MC1.12.2-4.2.7.3](https://www.curseforge.com/minecraft/mc-mods/random-things/files/2751591)

**Comment by Sunekaer** [comment]
https://www.feed-the-beast.com/projects/ftb-presents-stoneblock-2/files/2792347

**Comment by shortybsd** [comment]
I know this is closed, but Flux Networks updated from Beta to a Release and fixed a serious server issue.
Release version [Flux-Networks-1.12.2-4.0.10](https://www.curseforge.com/minecraft/mc-mods/flux-networks/files/2792153)
