### ISSUE TITLE
Extra Utilities 2 -> Flat Transfer Nodes

### ISSUE THREAD

**Issue by xjamesm** [FTBTeam/FTB-Presents-Stoneblock-2#649]
* **Modpack Version**:  1.15.0
* **Issue**: Using the Flat Transfer Nodes from Extra Utilities 2 causes Null Pointer Exception. 

* **Link to Log or Crash File Paste**: https://paste.dimdev.org/ahesozuzoh.mccrash

* **Is it Repeatable?**: Yes
* **Mod/s Affected**: Extra Utilities 2 (extrautils2-1.12-1.9.9.jar)

* **Known Fix**:

**Comment by Sunekaer** [comment]
Issue is reported to Extra Utilities, cant do anything about it
