### ISSUE TITLE
My Game is "pausing" for about a second

### ISSUE THREAD

**Issue by RedNexxus** [FTBTeam/FTB-Presents-Stoneblock-2#650]
1.15.0

"Pausing" is really the wrong word, so whenever I boot up the game everything works fine until I am on the menu screen, it will run fine for a moment but after that every few seconds there will be a pause for about a second where the game freezes, this will repeat continuously and it does it in my world as well.

There actually doesn't seem to be a log relating to this issue.

It happens every time I boot up the game

**Comment by Sunekaer** [comment]
Could be a lag issue from cpu not good enough, or to much or little ram assigned.
How much ram do you have assigned?

**Comment by trevbox** [comment]
I have the same issue. It’s due to scheduled executables. It’s happening since the update. I have completed the pack before and I have a good PC so had no issues. Stoneblock still works fine but the issue above causes little pauses. Thanks for your time. Great pack btw.

**Comment by mstarp1** [comment]
And how do you fix tha problem now ? It annoys me that I can´t play stoneblock / stoneblock 2

**Comment by trevbox** [comment]
I just re installed an older version and it works fine. You can do this in the FTB launcher.

**Comment by mstarp1** [comment]
Thx, I was using just twitch to play modded but now I will use FTB
launcher.

trevbox <notifications@github.com> schrieb am Do., 10. Okt. 2019, 22:41:

**Comment by clovercorone** [comment]
I Solved this!
Just avoid Tylor's Algorism, by BetterFPS.
I try VanillaAlgorism, it's alright.

BetterFPS is locate for setting menu.
good luck guys.

Detail:
I use Twitch Launcher, but i think not relate this.

**Comment by mstarp1** [comment]
Twitch launcher and FTB launcher are the same..
Does this solution work in the newest version?
Thx for help

clovercorone <notifications@github.com> schrieb am So., 13. Okt. 2019,
07:45:
