### ISSUE TITLE
Repeat Crashes When Joining Server

### ISSUE THREAD

**Issue by Muu79** [FTBTeam/FTB-Presents-Stoneblock-2#651]
* Version 1.9: 

* I'm playing on a server and I clicked on a smeltery controller then my game crashed and instantly crashes when I try to join the server. Normal single-player worlds still work.

* https://paste.feed-the-beast.com/view/6d45e4e4

* I've only noticed it in this server

* VanillaFix says Unknown but I was clicking on a smeltery controller when it happened

**Comment by Sunekaer** [comment]
Does the server crash too?
Can anyone else join the server?
