### ISSUE TITLE
StoneBlock 2 crashes before loading (Twitch)

### ISSUE THREAD

**Issue by reploid** [FTBTeam/FTB-Presents-Stoneblock-2#656]
* **Modpack Version**: 1.15.0

* **Issue**: StoneBlock 2 crashes while loading forge mods

* **Link to Log or Crash File Paste**: https://paste.dimdev.org/cuqexitimo.mccrash

* **Is it Repeatable?**: has repeated 5 times all from launching twitch client version

* **Mod/s Affected**: not sure which mod it stops on, but it gets to step 6/7 Cleaning Up

**Comment by RossBlitz413** [comment]
Im having the same issue, quiet sad really

**Comment by Sunekaer** [comment]
Assign more ram to the pack

**Comment by Sunekaer** [comment]
https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/blob/master/README.md
