### ISSUE TITLE
Extra Utilities 2 - Flat Transfer Node

### ISSUE THREAD

**Issue by ViniciusFXavier** [FTBTeam/FTB-Presents-Stoneblock-2#658]
* **Modpack Version**: 
V1.15.0 Minecraft 1.12.2

* **Issue**: 
When you put the Cobblestone Generator Tier 3[Extra Utilities 2] and put the Flat Transfer Node (Items)[Tiny Progressions] to extract the items the game closes.

![image](https://user-images.githubusercontent.com/40774281/65811863-7e7cde00-e195-11e9-8939-91ac933de2a8.png)

https://github.com/rwtema/Extra-Utilities-2-Source/issues/354

* **Link to Log or Crash File Paste**: 
crash-2019-09-28_01.49.08-client - https://paste.feed-the-beast.com/view/61c69610
crash-2019-09-28_01.24.20-client - https://paste.feed-the-beast.com/view/cf93d2cc

* **Is it Repeatable?**: 
Yes, If the problem does not occur the first time just break the items and replace them in the same place that the game closes again.

* **Mod/s Affected**: 
Tiny Progressions and Extra Utilities 2

* **Known Fix**:

**Comment by Xelat84** [comment]
For me same issue, but it not crashe game. Just an exception thrown each time you place it with held Control key. Also it leads to miscounting transfer nodes in item bar, at least until you open and close your inventory.

**Modpack Version:**
- V1.16.1 Minecraft 1.12.2

**Comment by taropoo** [comment]
I have the exact same issue as OP.

**Comment by Sunekaer** [comment]
Closing this issue as we can't do anything before the is a mod update, and it seems unlikely there will be on
