### ISSUE TITLE
3x3 Inventory Crafting Upgrade kicks from server

### ISSUE THREAD

**Issue by Bartman8989** [FTBTeam/FTB-Presents-Stoneblock-2#66]
* **Modpack Version**: 1.0.1

* **Issue**: Clicking on the button for the 3x3 crafting table in the inventory after eating a inventory upgrade will crash you out of a multiplayer game

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/61f186ba

* **Is it Repeatable?**: Yes it is, I have repeated it at least 4 times

* **Mod/s Affected**: Cyclic

* **Known Fix**: N/A

**Comment by Sunekaer** [comment]
Is the server running sponge?

**Comment by Bartman8989** [comment]
> Is the server running sponge?

No idea, is there any specific way in order to check?

**Comment by Sunekaer** [comment]
Ask the server owner he/she should know if they installed sponge on it

**Comment by Bartman8989** [comment]
its the minewonderland servers, I'll see if i can get onto the owner or an admin and I'll get back

**Comment by djoey123** [comment]
Got the same problem, and we(the server where i am playing) is using sponge ;)

**Comment by Bartman8989** [comment]
there we go, might be an incompatibility with sponge

also the rest of cyclic seems to be working just that inventory upgrade is the issue

**Comment by Sunekaer** [comment]
Yeah this crafting table is incompatible with sponge, please create an issue with sponge
