### ISSUE TITLE
ProjectE items no longer EMCable

### ISSUE THREAD

**Issue by unlimitedsola** [FTBTeam/FTB-Presents-Stoneblock-2#666]
* **Modpack Version**: 1.16.0

* **Issue**: 
ProjectE items are no longer EMCable after upgrading to 1.16.0

* **Is it Repeatable?**: Y

* **Known Fix**: 
This is likely caused by losing EMC values for Covalence Dusts from ProjectE

**Comment by Sunekaer** [comment]
Fixed in newer version of the pack
