### ISSUE TITLE
Can't Craft Draconic Armor

### ISSUE THREAD

**Issue by PoyudiHytori** [FTBTeam/FTB-Presents-Stoneblock-2#668]
* **Modpack Version**: 1.16.0

* **Issue**: Trying to upgrade the Wyvern Armor to the Draconic Armor. The Fusion crafting recipe is not working for me. I tried with the armor being fully powered, no powered, not upgraded, fully upgraded. I can't get it to work. The Fusion crafting core doesn't seem to recognize I'm trying to craft using the Wyvern Armor. I've crafted other items already with the Draconic level injectors without any issues. So I don't think this is user error.
![2019-10-08_19 54 24](https://user-images.githubusercontent.com/30440454/66441544-5dbe4f00-ea05-11e9-93c7-68e2d8f4f137.png)
![2019-10-08_19 54 28](https://user-images.githubusercontent.com/30440454/66441546-5dbe4f00-ea05-11e9-8d02-8e7d633d5176.png)

**Comment by Sunekaer** [comment]
Please test with a newer version of the pack available on the FTB APP, if that doesn't work reopen the issue
