### ISSUE TITLE
I can't play because when I try to play there is an error because of jna-4.4.0.jar

### ISSUE THREAD

**Issue by Zwierzynoxis** [FTBTeam/FTB-Presents-Stoneblock-2#669]
[launcher_log.txt](https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/files/3707851/launcher_log.txt)

Somethig is wrong with my Stoneblock 2.

* **Modpack Version**: All versions

* **Issue**: jna-4.4.0.jar

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: yes

* **Mod/s Affected**: jna-4.4.0.jar

* **Known Fix**:

**Comment by zarte13** [comment]
Simply delete the file and download from the link given.. It's just a corrupted file

**Comment by Sunekaer** [comment]
Twitch launcher issue, please reinstall the pack if that doesn't work report it to Twitch
