### ISSUE TITLE
Mod suggestion

### ISSUE THREAD

**Issue by djoey123** [FTBTeam/FTB-Presents-Stoneblock-2#67]
The mod i really miss is Refined Storage,
Is ther an reason why it isnt in stoneblock 2?

Would love to see that mod back in the game :)

**Comment by Sunekaer** [comment]
Had to many issues we refined storage in prevers pack, and simply haven’t had to to extendly test the mod to check it been fixed, it won’t be added to stoneblock 2

**Comment by maicol07** [comment]
@Sunekaer I've manually added Refined storage and I didn't see any issues. If you have time, please add it to the pack!
(I'm available to test the mod if you want)
