### ISSUE TITLE
Disabled due to bug issue?

### ISSUE THREAD

**Issue by ZedFontaine** [FTBTeam/FTB-Presents-Stoneblock-2#670]
* **1.16.0**: 

* **most of the bags/sacks state "Disabled due to bug". bags include Iron Backpacks, actually additions, extra utilities 2, Quest chest from FTB Quest, **: 

* **https://paste.feed-the-beast.com/view/d360435b**: 

* **No matter what I try, the bug consists.**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Sunekaer** [comment]
Yes?
