### ISSUE TITLE
iChunUtil crashes StoneBlock 2

### ISSUE THREAD

**Issue by JackBroGaming** [FTBTeam/FTB-Presents-Stoneblock-2#671]
* **Modpack Version**: 1.16.0

* **Issue**: When I load the pack all the mods load exept for when it gets to iChunUtil. It just crashes

* **Link to Log or Crash File Paste**: I cant find the crash-reports folder, it doesn't exist

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: iChunUtil-1.12.2-7.2.1

* **Known Fix**: None

**Comment by Gunner76th** [comment]
@JackBroGaming if you do not have a crash reports folder, then go to your logs folder and upload the latest.log file from there. That should have any information they will need to address the situation.

**Comment by JackBroGaming** [comment]
[latest.log](https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/files/3942930/latest.log)

**Comment by Sunekaer** [comment]
Please test with a newer version of the pack available on the FTB APP, if that doesn't work reopen the issue
