### ISSUE TITLE
FluxNetwork wireless charge not working

### ISSUE THREAD

**Issue by Kr4u7** [FTBTeam/FTB-Presents-Stoneblock-2#672]
* **Modpack Version**: 1.16.0

* **Issue**: The wireless charging of the FluxNetwork mod doesn't work.  I have all three parts (Plug, Point, Controller) and yet it won't charge items in my inventory

* **Is it Repeatable?**: yes

* **Mod/s Affected**: FluxNetworks

**Comment by cptsk1ttles** [comment]
I have the same issue

**Comment by Sunekaer** [comment]
fixed in newer version of the pack
