### ISSUE TITLE
stoneblock 2 freezes all the time.

### ISSUE THREAD

**Issue by Kr031life1** [FTBTeam/FTB-Presents-Stoneblock-2#673]
stoneblock freezes everytime i get on it and i want to play stoneblock. i don't know why but i have a good pc and it gets freeze all the time please fix that for me.

**Comment by LuckyStrikeOriginal** [comment]
What does "Good PC" mean to you ? can you specify the components?

**Comment by LPP7** [comment]
I have the same behaviour on my old 2013 gaming PC. 
I set xmx to 6G and xms to 4G.
No freeze since then.
