### ISSUE TITLE
Can't join servers

### ISSUE THREAD

**Issue by Averageone23** [FTBTeam/FTB-Presents-Stoneblock-2#674]
* **Modpack Version**: 1.16
* **Issue**: Any time I attempt to join a server it gives an error about the wooden door recipe
* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: N/A

* **Known Fix**: N/A

**Comment by cr998** [comment]
which is the version of the modpack in the client and the server
