### ISSUE TITLE
Unknown problem

### ISSUE THREAD

**Issue by MacrossGalaxy** [FTBTeam/FTB-Presents-Stoneblock-2#675]
I have a problem, in the middle of the stream the modpack Stoneblock2 just crashed and always displayed a bug with the mods DankNull and Code chicken LIB.
Reinstalling didn't work

https://paste.dimdev.org/pojaquqote.mccrash

Modpack version: 1.16.2

**Comment by Sunekaer** [comment]
Please test with a newer version of the pack available on the FTB APP, if that doesn't work reopen the issue

**Comment by Sunekaer** [comment]
Please test with a newer version of the pack available on the FTB APP, if that doesn't work reopen the issue
