### ISSUE TITLE
StoneBlock 2 Crash Wireless crafting terminal

### ISSUE THREAD

**Issue by Anohito05** [FTBTeam/FTB-Presents-Stoneblock-2#676]
* **Modpack Version**:  1.16.0 1.16.1 
* **Issue**: Shutting down internal server + Minecraft have crashed

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/48298083e

* **Is it Repeatable?**: Yes, just use crafting table in the wireless crafing terminal or put block into system

* **Mod/s Affected**: Suspected Mods: Wireless Crafting Terminal 2 (wct)

* **Known Fix**: No idea

**Comment by MadPandaLord** [comment]
Me and my friends have found the same issue we suspect it might be the Halloween event... thing since we were having no issues till today i've opened an issue with the extra cells 2 github

happy spooky day

**Comment by Gunner76th** [comment]
@Anohito05 The link you posted is no longer valid. Also, is this still an issue, or has it been resolved?

**Comment by Anohito05** [comment]
Yes It is only a bug with halloween event
