### ISSUE TITLE
Crashing when creating new Flux Network.

### ISSUE THREAD

**Issue by ukdyl94** [FTBTeam/FTB-Presents-Stoneblock-2#677]
Modpack Version: 1.16.1

    Issue: When I try to create a new network on Flux Networks the client crashes

    Link to Log or Crash File Paste: https://paste.dimdev.org/cufebogivu.mccrash

    Is it Repeatable?: Yes

    Mod/s Affected: Flux Networks

Reference: https://github.com/SonarSonic/Flux-Networks/issues/327

**Comment by LahiruVIP** [comment]
Crash happens to me too when i create a network in the network selection tab. Creating a network on the create network fixed it for me.

**Comment by ouroborus** [comment]
Apparently still unresolved. I'm experiencing this as well.

**Comment by Shadowgar** [comment]
Bumping this back because I had a similar crash. 
https://paste.dimdev.org/ugegejitiq.mccrash

**Comment by itsjusttriz** [comment]
Also happening to one of the users on a server i manage.. Needs to be updated/fix ASAP please.. https://paste.dimdev.org/qasefolexu.mccrash

**Comment by MishaczeQ** [comment]
Happened on my server too.
https://paste.dimdev.org/umapuwamuc.pl

**Comment by Sunekaer** [comment]
Should be fixed in newer version of the pack available on the FTB APP, if that doesn't work reopen the issue

**Comment by rikusen0335** [comment]
It seems Cursed Forge (Twitch) Version isn't updated yet. Could you please update it?

**Comment by itsjusttriz** [comment]
> It seems Cursed Forge (Twitch) Version isn't updated yet. Could you please update it?

FTB don't work with Curseforge anymore and have re-built their own application so 99.9999999999% chance, it will not be updated on the Curseforge site or any "non-ftb" app.

**Comment by rikusen0335** [comment]
Oh thank you for the information. Well I will move to FTB App.
