### ISSUE TITLE
[Mod Suggestion] Construct's Armory

### ISSUE THREAD

**Issue by MonfGeiger** [FTBTeam/FTB-Presents-Stoneblock-2#678]
I haven't played this in a while and came back to it, and wondered if construct's armory could be added to it.  It'd provide players a way of getting better armor than basic iron/whatever-other-mats exist, and add in an extra layer of challenge in getting the right mix of mats/effects to survive stoneblock 2

Whatever response is tacked on, I thank you for at least reading this

**Comment by Sunekaer** [comment]
No more mods will be added to this pack
