### ISSUE TITLE
Auxiliary Venting Port quest requires to visit the nether

### ISSUE THREAD

**Issue by tonby** [FTBTeam/FTB-Presents-Stoneblock-2#68]
* **Modpack Version**: 1.0.1

* **Issue**: At the Thaumcraft tab of the quest book, an Auxiliary Venting Port is required. To make this, I should complete some researches of Thaumonomicon. It requires me to "visit a hellish place" to complete "Infernal Furnace" research. I assume that I should go to a place with hellish biome. However, I can't go to the nether in this modpack. I can't make progress on the Thaumonomicon.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Thaumcraft

* **Known Fix**: 1. make it possible to go to the nether or to change biomes to the hell biome, or 2. change the required item from an Auxiary Venting Port to another.

**Comment by tonby** [comment]
I noticed that I can rewrite the biome to the nether using ExU2 Terraformer. It must be written on the quest description.

**Comment by Sunekaer** [comment]
Well it already says on the Biome Marker quest that this is the only way to get hell biome

**Comment by Sunekaer** [comment]
But ill add a "tip"

**Comment by Sunekaer** [comment]
1.1.0
