### ISSUE TITLE
Resolution Issues

### ISSUE THREAD

**Issue by Raresori2** [FTBTeam/FTB-Presents-Stoneblock-2#680]
* **Modpack Version**: Version: 1.16.1 Minecraft Version: 1.12.2

* **Issue**: Can't change my resolution I tried even in the new launcher to change it but it just puts me in fullscreen everytime

* **Link to Log or Crash File Paste**: There's no crash file / log

* **Is it Repeatable?**: Yes,because it just doesn't let me change resolution

* **Mod/s Affected**: There's no mods that affect the problem I think

* **Known Fix**: Nope,that's why I'm asking

**Comment by Gunner76th** [comment]
Go to the Options > Video settings  and turn off Fullscreen. You can also open the options.txt file in your modpack installation folder and change fullscreen:true to fullscreen:false If you are using Notepad++ it should be around line 28

**Comment by Drathonix** [comment]
I had the same problem. Changing the Fullscreen option to false does not fix the problem. Adding the mod "It's the little things" by Zlepper fixes the problem and allows changing the screen size. DL link on curse: https://www.curseforge.com/minecraft/mc-mods/its-the-little-things

This mod is client side only so there won't be any issues joining servers.

**Comment by Sunekaer** [comment]
Fix given by @Gunner76th Thanks
