### ISSUE TITLE
i can't open stoneblock 2 Bcuz of jna-4.4.0.jar

### ISSUE THREAD

**Issue by ptlBTW** [FTBTeam/FTB-Presents-Stoneblock-2#681]
* **Modpack Version**: 1.16.1

* **Issue**: when i try running the game from the launcher it won't let me saying jna-4.4.0.jar is not correctly installed 

* **Link to Log or Crash File Paste**: Failed to download file, the file contents differ from what was expected.
Name: jna-4.4.0.jar
URL: https://libraries.minecraft.net/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
Filename on disk: jna-4.4.0.jar
Path: C:\Users\Yair\Twitch\Minecraft\Install\libraries\net\java\dev\jna\jna\4.4.0\jna-4.4.0.jar
Exists: File

* **Is it Repeatable?**:  yes

* **Mod/s Affected**: 

* **Known Fix**:  nope, pls help me, thx

**Comment by TheUnprofeshonal** [comment]
This is happening to me too, please help

**Comment by TheUnprofeshonal** [comment]
I found a fix, in your twitch settings, set it to open with the JAR launcher, and use at least 5GB of ram. Hope this helps

**Comment by Gunner76th** [comment]
Related articles regarding this issue. @ptlBTW and @TheUnprofeshonal do either of you have any of the listed software on your system?

https://bugs.mojang.com/browse/MCL-5546
https://www.minecraftforum.net/forums/support/java-edition-support/2953236-it-says-unable-to-save-download-jna-4-4-0-jar
https://minecraftirc.net/support-articles/known-incompatible-software/

**Comment by excalidor4** [comment]
Had the same issue, and the fix for me was super easy.

On the error page, click the link, it will download that .jar file
Simply go to the location of where it says it should be located, delete the one in the folder, and replace it with the one you downloaded.

For some reason, the automatic downloaded one gets corrupt.
