### ISSUE TITLE
Draconic evolution portals cause crash loop

### ISSUE THREAD

**Issue by Michael-Gibbons** [FTBTeam/FTB-Presents-Stoneblock-2#682]
* **Modpack Version**: 1.16.1-1.12.2

* **Issue**: Draconic evolution portals crash game, and prevent you from logging back into your world. Crash loop.

* **Link to Log or Crash File Paste**: https://paste.dimdev.org/afiwohadun.mccrash

* **Is it Repeatable?**: Yes, just have to jump into a draconic evolution portal

* **Mod/s Affected**: Draconic evolution

* **Known Fix**: None that I know

**Comment by Michael-Gibbons** [comment]
I restored to a previous version to test with the regular dislocators and those are broken too.

**Comment by Michael-Gibbons** [comment]
Another update, I was able to fix the crash loop and the functionality of the draconic items by updating draconic evolution and Brandon's core manually in the mods folder to their latest versions.

**Comment by Sunekaer** [comment]
Fixed in 1.17.0
