### ISSUE TITLE
[Question] Inquiry on Mana Infused Metal

### ISSUE THREAD

**Issue by MonfGeiger** [FTBTeam/FTB-Presents-Stoneblock-2#683]
* **Modpack Version**: 1.16.0

* **Issue**: None; A Question

* **Mod/s Affected**: Thermal Foundation

Everytime I see thermal foundation, I see mana infused metal, and in JEI, the ONLY uses I see for it is to make metal plates out of it that go to nothing, or to turn it into coins for the numismatic dynamo, or to make it into hardened glass; absolutely nothing else related to it is in the modpack, and its bugging the hell out of me, so **please**, I need to know

**IS** there ANY interaction with any of the other mods in stoneblock 2 with mana infused metal from the thermal foundation mod, or is the only practical use for it is just to turn it into coins for numismatic dynamo fuel?

**Comment by Sunekaer** [comment]
That material does not have a use
