### ISSUE TITLE
Stoneblock Crashing Issue

### ISSUE THREAD

**Issue by MonfGeiger** [FTBTeam/FTB-Presents-Stoneblock-2#684]
* **Modpack Version**: 1.16.0
* **Minecraft Platform Used**: MultiMC (Dev Version)
* **Java Version Used**: jre-8u192-windows-x64
* **Issue**: In rare times when playing, I crash out of the MC Complex Stoneblock 2 server, my minecraft screen window goes completely black, but with only a small rectangle of visible....well, anything, forcing me to reload the app

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/9544bfe9

* **Is it Repeatable?**: yes and no; this did happen a few days ago, but I thought it was a one time thing. I see now I'm wrong

* **Mod/s Affected**: none that I know of

* **Known Fix**: a temporary fix, but just reloading the program seems to be fine

One thing I did was un-bind any keys bringing up the MineTogether friends screen, and essentially turned off some settings in the MineTogether config in-game that, for ONE reason  or another, brought up the friends screen everytime, even my keyboard's (Logitech G910 Orion Spark) mute button; I did not disable the MineTogether mod in question either in-game, or through MultiMC, because I thought it would break this modpack more than switching a few in-game menus off

**Comment by MonfGeiger** [comment]
At the time of this post, my minecraft crashed yet again, I will post the link to the copy of the MultiMC log screen, crash report is included

https://paste.feed-the-beast.com/view/70f4e769

**Comment by Draylynn** [comment]
Did you try deleting the MineTogether.cfg and seeing if it happens again? (The game will generate a fresh one on startup). If it happens again, head over to MineTogether's GitHub and report it: https://github.com/CreeperHost/CreeperHostGui/issues
