### ISSUE TITLE
Chicken Egg recipes are not working!

### ISSUE THREAD

**Issue by Argonile** [FTBTeam/FTB-Presents-Stoneblock-2#688]
* **Modpack Version**: 1.16.1

* **Issue**: Chicken Egg recipes will not work half the time

* **Is it Repeatable?**: Yes. Putting the full recipe into the crafting grid doesn't allow any output from it

* **Mod/s Affected**: I believe it is CraftTweaker affecting the recipes (as it shows "Recipe By: CraftTweaker2"

**Comment by Sunekaer** [comment]
No log file, please reopen with logs
