### ISSUE TITLE
FTB-Stoneblock-2-LAN-Issues

### ISSUE THREAD

**Issue by DuckWithPTSD** [FTBTeam/FTB-Presents-Stoneblock-2#692]
I'm trying to join my friend's world in FTB Stoneblock 2 by connecting via Hamachi LAN, but I get the following message:

io.netty.channel.AbstractChannel$AnnotatedSocketException: Network is unreachable: no further information:

Does anyone have a fix for this problem?

Screenshot:
![Issue](https://user-images.githubusercontent.com/59317125/71547682-99174c80-2968-11ea-8832-885b6ab02195.png)

**Comment by Sunekaer** [comment]
Not a pack issue.

**Comment by Sunekaer** [comment]
You can buy a server at http://partners.creeper.host/r/sunekaerjzn
