### ISSUE TITLE
stoneblock2 crash

### ISSUE THREAD

**Issue by KesidiWilliams** [FTBTeam/FTB-Presents-Stoneblock-2#695]
Please help. I can´t fix it.
![chyba](https://user-images.githubusercontent.com/59807767/72226386-d26ad180-3590-11ea-89ab-8b82c78251f4.jpg)

**Comment by manmaed** [comment]
* **Modpack Version**: ¯\_(ツ)_/¯

* **Issue**: ¯\_(ツ)_/¯

* **Link to Log or Crash File Paste**: https://paste.dimdev.org/kuhekozute.mccrash

* **Is it Repeatable?**: ¯\_(ツ)_/¯

* **Mod/s Affected**: Industrial Foregoing?? teslacorelib??

* **Known Fix**: ¯\_(ツ)_/¯

**Comment by Sunekaer** [comment]
MinecraftModDevelopmentMods/Tesla-Core-Lib#50
