### ISSUE TITLE
Crushed endstone has no flint stiffened mesh entry

### ISSUE THREAD

**Issue by Guinaro** [FTBTeam/FTB-Presents-Stoneblock-2#697]
* **Modpack Version**: 1.16.1

* **Issue**: Crushed endstone has no flint stiffened mesh entry.
Only String Mesh, Iron and Diamond Stiffened Mesh Entries.

I can only assume this is an oversight.
Suggested is doubling drop rates from String Mesh:
End result being Chorus Flower 5%, Ender Shard 4% and Ender Lily 1%
Possibly Draconium Dust at 0.5 - 1.5 % could be added aswell (Iron has that at 3.7%)

**Comment by Sunekaer** [comment]
Working as designed, wont be changed
