### ISSUE TITLE
Soulsand has no iron stiffened mesh entry

### ISSUE THREAD

**Issue by Guinaro** [FTBTeam/FTB-Presents-Stoneblock-2#698]
* **Modpack Version**: 1.16.1

* **Issue**: Soulsand has no iron stiffened mesh entry

Again possibly an oversight:
Suggestion is 1 Nether Quartz entry at 37.5%, 1 Nether Quartz Entry at 50% and 1 Black Quartz Entry at 15%

**Comment by Sunekaer** [comment]
Working as designed, wont be changed
