### ISSUE TITLE
TOP Readme file is missing

### ISSUE THREAD

**Issue by grannymc** [FTBTeam/FTB-Presents-Stoneblock-2#7]
* **Modpack Version**: 2.0.2

* **Issue**: TheOneProbe readme file is not in the starting inventory. This is a problem for those of us who want to reposition the text.

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: all day long

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by ChosenArchitect** [comment]
You can run the command /topcfg and it will fix your issue.

**Comment by Sunekaer** [comment]
As ChosenArchitect said use /topcfg
ty  @ChosenArchitect
