### ISSUE TITLE
Staying AFK for a while crashes the game

### ISSUE THREAD

**Issue by Angelos33** [FTBTeam/FTB-Presents-Stoneblock-2#70]
* **Modpack Version**: Modpack Version 1.0.1

* **Issue**: Staying AFK for a while crashes the game.( I went through all the issues posted here, didn't find anything related! Sorry if i missed something.)

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/804212e1

* **Is it Repeatable?**: It is repeatable for me every time i leave the game running and go AFK it crashes

**Comment by Sunekaer** [comment]
Cant recreate this issue, please report it to Thaumcraft, as we cant do anything about that
