### ISSUE TITLE
StoneBlock crashing on Launcher

### ISSUE THREAD

**Issue by DestroyerChing** [FTBTeam/FTB-Presents-Stoneblock-2#701]
* **Modpack Version**: 1.12.2

* **Issue**: StoneBlock is crashing on the launcher. 

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/631f7373

* **Is it Repeatable?**: yes

* **Mod/s Affected**: I dont know

* **Known Fix**: None so far

**Comment by Sunekaer** [comment]
Please report it to the launcher your using
