### ISSUE TITLE
Dup bug with barrels and Displacement Wand

### ISSUE THREAD

**Issue by ouroborus** [FTBTeam/FTB-Presents-Stoneblock-2#704]
* **Modpack Version**: 1.16.1

* **Issue**: Using a Displacement Wand on an Item Barrel causes the barrel to move but also pops a duplicate barrel (with duplicate contents).

* **Is it Repeatable?**: Yes

* **Known Fix**: Add Item Barrel to the Wand's blacklist.

**Comment by gavin3958** [comment]
the same thing happens with chest transporter
