### ISSUE TITLE
MineTogether Crash

### ISSUE THREAD

**Issue by BforBaloney** [FTBTeam/FTB-Presents-Stoneblock-2#707]
Stone Block 2    1.16.1

When I try to load my world before I get anywhere it simply tells me that Minecraft has crashed. I am able to quit to the title screen. When I create a fresh world file it loads perfectly. It's only the world that I have used that crashes. It has been working fine for the three weeks that I've been playing and now it doesn't want to load. I am using Twitch to load the mod pack.  

https://paste.feed-the-beast.com/view/831fe1a0

It is repeatable. I have restarted my computer several times, restarted Minecraft several times, I have even copied the entire save file to another world and still the crash happens. 

Specifically, MineTogether and MineTogetherServer are the culprits

**Comment by BforBaloney** [comment]
After figuring out how to disable mods on Twitch it turns out that my entire save file is corupted

**Comment by drakeyboi** [comment]
Do you always save/quit or did you maybe alt+f4 or turn your pc off? I'm just wondering because I have the same issue and i forgot to save/quit.

**Comment by Sunekaer** [comment]
Should be fixed in newer versions of the pack
