### ISSUE TITLE
Server crashes very often when attempting to start it.

### ISSUE THREAD

**Issue by kocyk5125** [FTBTeam/FTB-Presents-Stoneblock-2#708]
* **Modpack Version**: 1.16.0

* **Issue**: While attempting to host the modpack on Aternos.org, I have run into numerous and repetitive problems. The server very often crashed at the end of the startup, for seemingly no reason even if it previously did start. The issue is most likely not on Aternos, as other modpacks boot-up and work fine, regardless of settings. 
I have tried numerous things, but the issue does seem to come back no matter what.

* **Link to Log or Crash File Paste**: https://mclo.gs/OfWRJ0w

* **Is it Repeatable?**: Yes, it happens almost every time when attempting to host.

* **Mod/s Affected**: Don't know.

* **Known Fix**: N/A, don't know.

**Comment by Sunekaer** [comment]
report the issue to Aternos
