### ISSUE TITLE
Game Reverted Back to Beginning with all Items Scattered

### ISSUE THREAD

**Issue by alio314** [FTBTeam/FTB-Presents-Stoneblock-2#709]
* **Modpack Version**: 1.16.1

* **Issue**: Just logged in after playing for several weeks and my entire base is back to the original room with all of my machines and items scattered on the floor. If you look at the map in upper right corner, you will see my base as it last was.

* **Link to Log or Crash File Paste**: No crash file

* **Is it Repeatable?**: Yes, logged out and back in with same result. Also closed the program completely and opened back up through Twitch launcher.

* **Mod/s Affected**: All
![Stoneblock 2 Issue 3-5-20](https://user-images.githubusercontent.com/39442868/76004407-701ab700-5ed7-11ea-813e-0ec0152f3dc6.jpg)

* **Known Fix**:

**Comment by Sunekaer** [comment]
The mod dev cant find the cause of this issue, please revert to a backup
