### ISSUE TITLE
MineTogheter problem

### ISSUE THREAD

**Issue by Dubl33** [FTBTeam/FTB-Presents-Stoneblock-2#71]
* **Modpack Version**: 1.0.1

* **Issue**:  When I got kicked from the global MineTogheter chat I saw that i was being reconnected but upon waiting a few minutes nothing happened and I tested to see if I could speak in chat but my messages didn't appear, nor other's messages

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**:  I just got kicked... nothing else

* **Mod/s Affected**: 

* **Known Fix**: didn't find any fix... tried reinstalling the mod.

**Comment by Boomflex** [comment]
This sounds more like a MineTogether issue, not a Modpack issue.

Report it here: https://github.com/CreeperHost/CreeperHostGui/issues

**Comment by Dubl33** [comment]
thanks

**Comment by Draylynn** [comment]
Users who cannot reconnect their MineTogether chat have likely been banned; There are no warnings about the ban, it just happens. The mod will disconnect and stay disconnected.
Make sure to abide the rules of chat that are listed on entering chat.
