### ISSUE TITLE
Wouldn't download, did third time?

### ISSUE THREAD

**Issue by Reioflight** [FTBTeam/FTB-Presents-Stoneblock-2#714]
I think the problem is partially fixed? But I just want to know what happened so I can fix it myself in the future.

Version: FTBPresentsStoneblock2-1.16.1-1.12.2.zip

Issue: Tried downloading a few times, first two times there is was file that could not be retrieved. First time it was oreberries, the second was a redstone mod. Third time it worked?

Link to Log or Crash File Paste: There was no log, it only said failed to retrieve file on the twitch download.

Is it Repeatable?: Did it 2 times, third worked.

Mod/s Affected: Oreberries and a redstone mod

Thanks!

**Comment by Sunekaer** [comment]
This is an issue with the twitch launcher, you cant do anything about it
