### ISSUE TITLE
Breaking a framed drawer destroys it contents.

### ISSUE THREAD

**Issue by batcack** [FTBTeam/FTB-Presents-Stoneblock-2#715]
* **Modpack Version**: 1.16.1

* **Issue**: Breaking a framed drawer destroys it contents.

* **Link to Log or Crash File Paste**:N/A

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Storage Drawers

* **Known Fix**: Update to version 5.4.1 of Storage Drawers

**Comment by Sunekaer** [comment]
fixed in 1.17.0
