### ISSUE TITLE
No Cursor Bug

### ISSUE THREAD

**Issue by Wolford6** [FTBTeam/FTB-Presents-Stoneblock-2#716]
``
Version 15.2.0

* **Issue**: Cursor does not show up when The Stoneblock main screen and so on comes onto the screen. It does show when Stoneblock is loading though. This is very annoying and hard to track as I cannot see where my mouse is going and it only lights around buttons and objects. This will make it almost impossible for me to play.

* **Link to Log or Crash File Paste**  

[latest.log](https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/files/4379037/latest.log)

[crash-2020-03-24_18.11.53-client.txt](https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/files/4379066/crash-2020-03-24_18.11.53-client.txt)

* **Is it Repeatable?**: It is VERY repeatable.

Please help,

Thank you              -Wolf ``

**Comment by Sunekaer** [comment]
Please reopen this issue, if you still have the issue with version 1.17.0 of the pack
