### ISSUE TITLE
Salis Mundus not working [Stoneblock 2]

### ISSUE THREAD

**Issue by DaBomb42** [FTBTeam/FTB-Presents-Stoneblock-2#718]
Modpack Version: 1.16.1

Issue: Salis mundus from Thaumcraft doesn't seem to be working at all. I am able to craft it, but not able to use it in any way. I've tried using it on a bookshelf and a crafting table, but neither have worked.

I would appreciate any help so that I can actually do stuff in Thaumcraft.

**Comment by PhiVape** [comment]
Go to sleep in a bed and try again

**Comment by Sunekaer** [comment]
Yeah you need to sleep
