### ISSUE TITLE
Crafting the Base Chickens

### ISSUE THREAD

**Issue by LoafOFB3ans** [FTBTeam/FTB-Presents-Stoneblock-2#719]
Modpack Version: 1.12.2

Issue: I have been playing the mod pack a lot recently and have just started on the chickens and more chickens mod and I am unable to craft the base chickens such as the log chicken, Sand chicken, this is only happening to the recipes that take up the entire crafting grid, as the eggs you craft using the dyes are fine, except when using the entire crafting grid
 
Mod/s Affected: not sure if a mod is causing the issue or I am doing something wrong

**Comment by Sunekaer** [comment]
What version of the pack are you using, it works in 1.17
