### ISSUE TITLE
v1.0.1 thaumocraft book shelf manic is not working.

### ISSUE THREAD

**Issue by toonslayerking** [FTBTeam/FTB-Presents-Stoneblock-2#72]
* **Modpack Version**: 

* **Issue**: 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by toonslayerking** [comment]
1.0.1  thaumcraft bookshelf macnic doesnt work with salis mundis

**Comment by Sunekaer** [comment]
did you sleep after breaking the crystals?

**Comment by DAmNRelentless** [comment]
I tested it and it works. You first need to pick up crystals and then sleep. Only then the salis mundis will work.
