### ISSUE TITLE
[Mod Suggestion] Name Pain

### ISSUE THREAD

**Issue by naqaden** [FTBTeam/FTB-Presents-Stoneblock-2#720]
* **Modpack Version**: 1.0.35

* **Issue**: Stoneblock 2 doesn't have [Name Pain](https://www.curseforge.com/minecraft/mc-mods/name-pain). :nerd_face:
Name Pain is just a light tweak mod for nameplates. It visualizes the health of named entities without cluttering the screen by coloring the text and bg of nameplates. RGBA configs offer the ability to hide names instead, for immersion or extra difficulty.

* **Is it Repeatable?**: Yes

* **Known Fix**: Add Name Pain to Stoneblock 2

**Comment by Sunekaer** [comment]
There wont be added anymore mods to this pack

**Comment by naqaden** [comment]
Fair enough, thanks anyway.
