### ISSUE TITLE
Texture missing

### ISSUE THREAD

**Issue by Suscepto** [FTBTeam/FTB-Presents-Stoneblock-2#721]
So, i've been playing stone block 2 a little while now and wanted to start making a reactor with molten Enderium as a cooling when I found this "bug" in the texture... I've searched some sites and tried to figure it out myself, but I can't find a solution. The texture is in a pink/black pattern and on it u can see a scripture which says 'fluId_block#entconstruct' and below i think it says 'molten enderium'. I also tried to use a resource pack the F32 but it didn't show any results...
![2020-04-06_14 17 10](https://user-images.githubusercontent.com/53646823/78557611-61465d80-7811-11ea-8026-c28cd92f8f8f.png)
![2020-04-06_14 18 43](https://user-images.githubusercontent.com/53646823/78557733-994da080-7811-11ea-833a-42082314f15a.png)

Modpack version 1.16.1 downloaded from twitch 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Sunekaer** [comment]
Could you test with a newer version?
