### ISSUE TITLE
Server loading crash.

### ISSUE THREAD

**Issue by leeyuang** [FTBTeam/FTB-Presents-Stoneblock-2#722]
* **Modpack Version**: <Stoneblock 2  1.16.0 Server>

* **Issue**: <Can't lauch the server >

* **Link to Log or Crash File Paste**: <

  | 14971 lines
-- | --
14972 | [14:42:20] [Server thread/ERROR] [net.minecraft.advancements.AdvancementManager]: Parsing error loading built-in advancement minecraft:recipes/redstone/trapdoor
14973 | com.google.gson.JsonSyntaxException: Unknown recipe 'minecraft:trapdoor'
14974 | at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:171) ~[l$a.class:?]
14975 | at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:147) ~[l$a.class:?]
14976 | at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
14977 | at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
14978 | at com.google.gson.Gson.fromJson(Gson.java:952) ~[Gson.class:?]
14979 | at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[TreeTypeAdapter$GsonContextImpl.class:?]
14980 | at net.minecraft.util.JsonUtils.deserializeClass(SourceFile:439) ~[rc.class:?]
14981 | at net.minecraft.util.JsonUtils.deserializeClass(SourceFile:455) ~[rc.class:?]
14982 | at net.minecraft.advancements.Advancement$Builder.deserialize(SourceFile:203) ~[i$a.class:?]
14983 | at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
14984 | at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
14985 | at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
14986 | at net.minecraft.util.JsonUtils.gsonDeserialize(SourceFile:492) ~[rc.class:?]
14987 | at net.minecraft.util.JsonUtils.fromJson(SourceFile:532) ~[rc.class:?]
14988 | at net.minecraft.advancements.AdvancementManager.loadBuiltInAdvancements(AdvancementManager.java:184) [ns.class:?]
14989 | at net.minecraft.advancements.AdvancementManager.reload(AdvancementManager.java:68) [ns.class:?]
14990 | at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60) [ns.class:?]
14991 | at net.minecraft.world.WorldServer.init(WorldServer.java:156) [oo.class:?]
14992 | at net.minecraft.server.MinecraftServer.loadAllWorlds(MinecraftServer.java:298) [MinecraftServer.class:?]
14993 | at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:270) [nz.class:?]
14994 | at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
14995 | at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
14996 | [14:42:22] [Server Shutdown Thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
14997 | [14:42:22] [Server Shutdown Thread/INFO] [net.minecraft.server.MinecraftServer]: Saving players
14998 | [14:42:22] [Server Shutdown Thread/INFO] [net.minecraft.server.MinecraftServer]: Saving worlds
14999 | [14:42:22] [Server Shutdown Thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'world'/overworld
15000 | [14:42:22] [Server Shutdown Thread/DEBUG] [FML]: Gathering id map for writing to world save world

 >

* **Is it Repeatable?**: < Yes >

* **Mod/s Affected**: < no clue >

* **Known Fix**: < Don't know any >

**Comment by Sunekaer** [comment]
please copy the content of latest.log to https://pste.ch/ and click save and paste the link here
