### ISSUE TITLE
crashing to main menu when trying to exit out of extended inventory (MP)

### ISSUE THREAD

**Issue by LeafSalt** [FTBTeam/FTB-Presents-Stoneblock-2#724]
* **Modpack Version**: <-Stoneblock-2 1.16.1->

* **Issue**: <-When I try to exit my extended inventory- >

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/524c7f37
* **Is it Repeatable?**: <Yes, it has happened four times, one of these have crashed to the desktop>

* **Mod/s Affected**: <-unknown->

* **Known Fix**: <-unknown->

**Comment by Sunekaer** [comment]
Did you add that mod yourself to the pack?

**Comment by LeafSalt** [comment]
no

**Comment by LeafSalt** [comment]
what I meant was the inventory upgrade cake from cyclic

**Comment by Sunekaer** [comment]
Could you test with 1.17.0 from the FTB App

**Comment by LeafSalt** [comment]
ok it only happens when I have lasers and laser amps from mekanism in my inventory
