### ISSUE TITLE
Removed mod from Curseforge, update required!

### ISSUE THREAD

**Issue by NLBlacky** [FTBTeam/FTB-Presents-Stoneblock-2#725]
https://www.reddit.com/r/feedthebeast/comments/g3fekk/looks_like_plus_tic_and_all_of_landmasters_mods/

The mod plustic is no longer available on Curseforge due to breaking Curseforge's ToS. Since Stoneblock 2 is using this mod, Stoneblock 2 might soon no longer be downloadable till this mod has been removed from the modpack. I believe a few other mods below this developer were removed as well but I have no names.

**Comment by VielenKaat** [comment]
That doesn't seem to be the case actually, I just redownloaded Stoneblock 2, and Plustic still installs.

**Comment by Sunekaer** [comment]
I can instal the pack just fine, if you have any issues report it to curseforge/twitch
