### ISSUE TITLE
how to turn off music?

### ISSUE THREAD

**Issue by SAMURIADI** [FTBTeam/FTB-Presents-Stoneblock-2#726]
there is music constantly playing and it is deafining i cant figure out how to turn it off, its not under music or enviroment/ambient 
please help i cant hear anything other than this music

* **Modpack Version**: 1.16.1

* **Issue**: music

* **Link to Log or Crash File Paste**: none

* **Mod/s Affected**: dont know

* **Known Fix**:

**Comment by Sunekaer** [comment]
We dont add any music to the pack

**Comment by SAMURIADI** [comment]
ill try to record it when it happens again, it sounded like the minecraft style but wasnt from mc

**Comment by CrankySupertoon** [comment]
1.16.1 is outdated update to 1.17.0

**Comment by SAMURIADI** [comment]
well i set the server's music and ambience to 0 and that solved the issue
might have been a client de-sync
