### ISSUE TITLE
Crashing to title screen when joining a server

### ISSUE THREAD

**Issue by LeafSalt** [FTBTeam/FTB-Presents-Stoneblock-2#728]
* **Modpack Version**: 1.16.1

* **Issue**: When joining a server I play on, it crashes to the title screen

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/ee7f8cb6

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Draconic Evolution, CodeChicken Lib, JEI

**Comment by Sunekaer** [comment]
Could you test with a newer version of the pack?
