### ISSUE TITLE
sneak to grow crops not working

### ISSUE THREAD

**Issue by teaaitchsea** [FTBTeam/FTB-Presents-Stoneblock-2#730]
* **Modpack Version**: 1.16.1

* **Issue**: i cannot sneak to grow crops faster.

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: i re opened world multiple times still nothing

* **Mod/s Affected**: 
* **Known Fix**:

**Comment by Sunekaer** [comment]
does you crops have water and light?

**Comment by teaaitchsea** [comment]
It was a tree I didn’t think they needed water and light, I gave up cause
of it lol

**Comment by Sunekaer** [comment]
Oh okay, did it have space enough?

**Comment by teaaitchsea** [comment]
I thought that so I made the room really tall and wide and it still didn’t
work

**Comment by Sunekaer** [comment]
Hmm could i get you to test with a newer version of the pack, because it works for me

**Comment by teaaitchsea** [comment]
Yes, I’m already on v1.16.1 atm is there a more up to date version?
