### ISSUE TITLE
Unable to Auto Sieve. 

### ISSUE THREAD

**Issue by JaseyBear** [FTBTeam/FTB-Presents-Stoneblock-2#731]
When trying to create an Auto sieve, no items are going into the auto sieve. I have tried manually placing items, I have tried conduits, I have tried item Transfer pipes, and I have tried hoppers. Power is going to everything, and everything is working fine EXCEPT the auto sieve. Any ideas?

**Comment by Meminjo** [comment]
Do you have an actual mesh inside your auto-sieve? 
I.e.
String
Flint
Iron
Diamond mesh?

**Comment by Sunekaer** [comment]
Do you feed it power and have a mesh in it?
