### ISSUE TITLE
3x3 thermal foundation hammers lag the game and veinmine question

### ISSUE THREAD

**Issue by nixord** [FTBTeam/FTB-Presents-Stoneblock-2#732]
EDIT: Turns out its not just hammers. Its the mining of multiple blocks quickly that lags the game (by lag I mean server lag not fps lag). Is it getting fixed next version or what? Cause I tried 1.16 and it runs a lot better.

Title says it all but when I go and mine with a hammer, the game lags for a second and then procs the mining. Im playing on the latest version of the pack (1.17.0). Also why is it that ore Excavate was removed from the pack?

**Comment by UntouchedWagons** [comment]
I'm getting ridiculous lag while mining with hammers too, tinkers hammers and thermal hammers equally.
