### ISSUE TITLE
picking up item barrel with the chest transporter duplicates it

### ISSUE THREAD

**Issue by gavin3958** [FTBTeam/FTB-Presents-Stoneblock-2#733]
version: 1.16.1

Issue: I picked up a yabba item barrel with wood chest transporter and it picked it up and dropped it at the same time.

Is it Repeatable?: it has happened every time

Mod/s Affected: YABBA, and chest transporter

**Comment by Sunekaer** [comment]
https://github.com/cubex2/chesttransporter/issues/32
