### ISSUE TITLE
Extreme Visual Glitch when moving character

### ISSUE THREAD

**Issue by oreodivideroero** [FTBTeam/FTB-Presents-Stoneblock-2#739]
* **Modpack Version**:  1.16.1

* **Issue**: After loading into the game, as soon as I am near a wall, when I move my character with WASD the entire screen bugs out and I can't see any textures on any blocks. The whole screen is blue/white (depending on where I am facing relative to light source) and flickers horribly. After a few seconds, the visual returns to normal. Throughout this issue, the HUD is completely normal.

I've tried changing every video setting independently with no change in performance. My fps seems fine. I can mine blocks when standing still with no issue, but as soon as I move it bugs out again.

I increased my available RAM to 8GB. I am running on an ASUS laptop GL552VW.
16GB ram
Nvidia GTX 960M
i7 6200 @ 2.6ghz

* **Link to Log or Crash File Paste**: Game didn't crash.

* **Is it Repeatable?**: Yes, Happens anytime I move my character using WASD.

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Sunekaer** [comment]
Can you show the issue?

**Comment by pao3007** [comment]
Hi, I had the same issue with StoneBlock 2 when I loaded game the visual bug started almost immediately, day before I changed BetterFPS algoritm to Taylors and after that it started, so I changed it back to Rivens "Half" and visual bug was no more.
