### ISSUE TITLE
Draconic Evolution missing dependency 

### ISSUE THREAD

**Issue by YourMCGeek** [FTBTeam/FTB-Presents-Stoneblock-2#74]
* **Modpack Version**: 1.01

* **Issue**: When attempting to open the in game draconic information tablet, you are presented with an error messaging stating that it is missing a dependency, see below.

* **Link to Log or Crash File Paste**: This is a link to the error message presented <img src="http://yourmcgeek.ga/u/16.33.07-08.01.19.png"
     alt="Error Message"
     style="float: left; margin-right: 10px;" />

* **Is it Repeatable?**: Yes, open the tablet in game.

* **Mod/s Affected**: Draconic Evolution

* **Known Fix**: Add https://minecraft.curseforge.com/projects/project-intelligence to the game as per the error message

**Comment by Sunekaer** [comment]
1.1.0
