### ISSUE TITLE
Error until joining to server as player 

### ISSUE THREAD

**Issue by Gruszii** [FTBTeam/FTB-Presents-Stoneblock-2#742]
* **Modpack Version**: 
FTB-Presents-Stoneblock-2 version 1.12.2

* **Issue**:  Error until joining to  the server as player 

* **Link to Log or Crash File Paste**:  https://prnt.sc/sfl9rg

* **Is it Repeatable?**: no it's first time

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Sunekaer** [comment]
Inconsistent between the client in mods/recipes, try reinstall the client or the server
