### ISSUE TITLE
Crashing to title screen during world gen

### ISSUE THREAD

**Issue by Auraleas** [FTBTeam/FTB-Presents-Stoneblock-2#744]
* **Modpack Version**: 1.17.0 

* **Issue**: When entering a world, it crashes and says the Hammer Core mod is a potential cause. 

* **Link to Log or Crash File Paste**: clicking on the link does nothing, and clicking on the get link button results in "[Failed]" 

* **Is it Repeatable?**:  yes 

* **Mod/s Affected**: Hammer Core

* **Known Fix**:

Edit: It only affects one of my worlds. I created a new one and I was able to access that one just fine.

**Comment by Auraleas** [comment]
![Screenshot (128)](https://user-images.githubusercontent.com/65381710/82011802-ea2f9080-962a-11ea-82e4-b0f286e05885.png)

**Comment by Auraleas** [comment]
I've tried deleting and redownloading Hammer Core, and I've also tried creating a new world and copying the saves over. Neither works

**Comment by Sunekaer** [comment]
Please click the green link and copy the text to https://pste.ch/ click the save icon and send paste the link here
