### ISSUE TITLE
Server file on website

### ISSUE THREAD

**Issue by mortenh1234** [FTBTeam/FTB-Presents-Stoneblock-2#746]
* **Modpack Version**:  Stoneblock 2 1.17.0

* **Issue**:  When i look in the "Versions" tab of the stoneblock 2 page on FTB website, it downloads the mod itself, not a server. Is there anywhere i can get a server file to run a server myself?

* **Link to Log or Crash File Paste**:  (https://user-images.githubusercontent.com/65510951/82159621-c7ea7c80-988f-11ea-95b4-72e549985bbb.png)

* **Is it Repeatable?**:  idk

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Sunekaer** [comment]
In the dropdown select the operating system where you would like to install your server.
Once the file has downloaded, copy it to an empty folder and run it, then it will download all the server files for the downloaded pack/version
