### ISSUE TITLE
Tinkers construct smeltery

### ISSUE THREAD

**Issue by Mizuragi** [FTBTeam/FTB-Presents-Stoneblock-2#747]
* **Modpack Version**: 1.12.2 Stoneblock 2

* **Issue**: can not create the tinkers forge i have tried multiple ways will smelter controller will not ignite unsure if its just locked by prerequisites but i have done the questline up to it 

* **Is it Repeatable?**: every time i try to make the smeltery

* **Mod/s Affected**: tinkers construct

**Comment by Sunekaer** [comment]
Do you have a Seared Tank, Smeltery controller, and some seard bricks? 
I just tested in my world with those and it works

**Comment by Mizuragi** [comment]
I apologize I was trying to make it an older way because at an older time was able to make it with a seared tank in the corner and now it has changes
