### ISSUE TITLE
How do you get Dragon's Breath?

### ISSUE THREAD

**Issue by PunnyGamerGirl** [FTBTeam/FTB-Presents-Stoneblock-2#75]
Hello! This is for Stone Block 2 I am playing with some friends and we have just finished fighting the Ender Chicken but he did not breath anything and dragon breath is needed for the philsophers stone is there another way to get it or is it not possible to get it thank you and have a great day!

**Comment by Sunekaer** [comment]
Laser leaves it, but you need to be quick to get it
