### ISSUE TITLE
Game won't load

### ISSUE THREAD

**Issue by hiimstupid** [FTBTeam/FTB-Presents-Stoneblock-2#750]
* **Modpack Version**: 1.16.1

* **Issue**: Clicking play on the modpack in Minecraft launcher but nothing happens * **(doesn't give crash message either)**, I have tried making Twitch and Minecraft administrator but neither work. When I try to load it again, it tells me the game is already running.
I have also tried switching to the jar version. It did not work.

* **Link to Log or Crash File Paste**: No crash message

* **Is it Repeatable?**: Yes, I have tried several times

* **Mod/s Affected**: N/A

* **Known Fix**: N/A

**Comment by Sunekaer** [comment]
Please test with a newer version of the pack available on the FTB APP, if that doesn't work reopen the issue
