### ISSUE TITLE
Newest version won't load at all.

### ISSUE THREAD

**Issue by Talan122** [FTBTeam/FTB-Presents-Stoneblock-2#751]
* **Modpack Version**: 1.18.0

* **Issue**: I press play on the launcher and it does its loading thingy and closes like its supposed to, but nothing happens afterwards. I've waited for about 10 minutes and nothing. There is something on the log which I think is note worthy though (near the bottom of the log). No crash report however.

* **Link to Log or Crash File Paste**: https://pastebin.com/LXrpwPJS

* **Is it Repeatable?**: Yes, doing this over and over yields the same log and won't load.

* **Mod/s Affected**: Don't know.

* **Known Fix**: Downgrading to 1.17.0 seems to work.

**Comment by Sunekaer** [comment]
Just pushed a fix
