### ISSUE TITLE
help with one of the mods

### ISSUE THREAD

**Issue by animelover090397** [FTBTeam/FTB-Presents-Stoneblock-2#752]
This is kind of simple to explain basically Vienminer is not working when I use the hammer. Should I use an older version or what? I'm also not sure if it's conflicting with another key when I go into controls.

**Comment by hiimstupid** [comment]
Veinminer doesn't work on stone

**Comment by Attagoat** [comment]
Veinminer was replaced with FTB ultimine, You can look at your settings in your keybinds by specifying category and FTB ultimine.
