### ISSUE TITLE
When loaded into world texture cannot be loaded in

### ISSUE THREAD

**Issue by BryantheBrosk** [FTBTeam/FTB-Presents-Stoneblock-2#755]
* **1.18.1**

* **Every time I would load into my world at certain points the textures wouldn't load in and it frightens me cause this had happened before and deleted one of my worlds and im afraid that this would happen again if i try to fix the problem.**

* **crash-2020-06-08_15.21.17-client.txt*

* **Yes you can repeat the issue**

* **Extra Utilities 2 from what the crash report suspects**

* **No there is no solution i can think of besides restarting the world or the app help me fix this please**

**Comment by Sunekaer** [comment]
Hmm i havent heard of any solutions to this issue other then relog
