### ISSUE TITLE
Big Spender quest not working

### ISSUE THREAD

**Issue by Attagoat** [FTBTeam/FTB-Presents-Stoneblock-2#756]
* **Modpack Version**: 1.18.1

* **Issue**:  When I go to submit the "Big Spender" quest, The one where you need to get the maximum amount of EMC, I get a notification from VanillaFix saying "FTB quests ran into a problem!" and the quest cannot be submitted, It is also worth noting that I have personal EMC links running and that even when the EMC reaches the max limit the personal EMC links still add EMC. However I cannot add EMC myself.

* **Link to Log or Crash File Paste**:  https://paste.feed-the-beast.com/view/3ce385e1

* **Is it Repeatable?**: Yes, By submitting the big spender quest

* **Mod/s Affected**: FTB quests 1.8.0.237 , FTB library 5.4.7.0

* **Possible Fix**: replacing the EMC quest with an item that you can only obtain from getting  the maximum amount of EMC

**Comment by Sunekaer** [comment]
fix has been released
