### ISSUE TITLE
soundmanger crash

### ISSUE THREAD

**Issue by alexHunter854** [FTBTeam/FTB-Presents-Stoneblock-2#759]
* **Modpack Version**:FTBPresentsStoneblock2-1.16.1-1.12.2

* **Issue**:  Crashes and lag spikes occur because of extar utils 2 sound muffler (I think), crashes and lag spikes happen at most 
                    every 10 minutes 

[Crash log](https://pastebin.com/5fxBZN3F) 

* **Is it Repeatable?**: No i cannot repeat it, but, as a said it happens to me every ten minutes or so and i can provide more crash logs from the same issue if it helps

**Comment by Sunekaer** [comment]
Please test with a newer version of the pack available on the FTB APP, if that doesn't work reopen the issue
