### ISSUE TITLE
(1.16.1) Trying to make new flux network crashes game

### ISSUE THREAD

**Issue by ItsAstrobiology** [FTBTeam/FTB-Presents-Stoneblock-2#761]
As stated in the title, when I hit "create new network" on my flux plug the game instantly crashed. Tried multiple times, happened every time. Happens with flux controllers, plugs, and points.

Report: https://paste.feed-the-beast.com/view/7055c574

**Comment by Sunekaer** [comment]
Please test with new version of the pack, which can be downloaded from the FTB App
