### ISSUE TITLE
Items sometimes get stuck in the air

### ISSUE THREAD

**Issue by Communism202** [FTBTeam/FTB-Presents-Stoneblock-2#762]
* **Modpack Version**: 1.16.1, Locally hosting server on 1.16 tho (There doesnt seem to be a Server Pack for 1.16.1, maybe this is causing it?)

* **Issue**: Some Items will occasionally get stuck in the Air and spazz out up and down on the Spot theyre stuck on
![glitch](https://user-images.githubusercontent.com/67879039/86543138-32c54500-bf1c-11ea-989a-2a8f1a76544b.png)
, it seems to be only a visual glitch because reconnecting causes them to vanish, but its still annoying

* **Is it Repeatable?**: I dont know

* **Mod/s Affected**:

* **Known Fix**:

**Comment by Sunekaer** [comment]
Not much i can do about this, could you test with a newer version of the pack available on the FTB APP, a lot of mod updates has happened, if that doesn't work reopen the issue

**Comment by Communism202** [comment]
Ah i see, the twitch version seems to be very old and theres server files aswell on the feed the beast website, thank you this will probably fix it
