### ISSUE TITLE
Osmium not generating

### ISSUE THREAD

**Issue by DaveArtz** [FTBTeam/FTB-Presents-Stoneblock-2#763]
* **Modpack Version**: 1.19

* **Issue**: Osmium (Mekanism'S ore) is not naturally generating in the default world. 

* **Link to Log or Crash File Paste**: no crash

* **Is it Repeatable?**: it appears at every world generation

* **Mod/s Affected**: Mekanism

**Comment by Sunekaer** [comment]
![image](https://user-images.githubusercontent.com/18720460/89103054-32cb3e80-d40f-11ea-92dd-1005be8e433e.png)
Osmium spawns for me, are you in the mining dim?
