### ISSUE TITLE
bugs when creating a new world

### ISSUE THREAD

**Issue by ThySiho** [FTBTeam/FTB-Presents-Stoneblock-2#765]
stoneblock 2 1.19.0

if you try creating a new world and then minimize the game and do something else while waiting, the game tends to break.

let me clarify (even tho its so weird that its hard to explain) when you come back to your game once its done and un pause, instead of loading into a confined area of stone you load ontop of a single piece of glass, and thats it, the rest is void.

and so the obvious fix is just to well, not minimize the game when creating a new world.

it was quite of an interesting and odd bug and i just thought i should bring it to light.

side note: itemphysic full prevents the game from opening properly (didnt mention it before because its a mod outside of this modpack, but i was a little sad when i found out i couldnt use it with this modpack)

**Comment by Sunekaer** [comment]
yaeh i dont think theres anything we can do about this
Do you have some logs of it happening?
