### ISSUE TITLE
So Much Lagging

### ISSUE THREAD

**Issue by mariannh17** [FTBTeam/FTB-Presents-Stoneblock-2#766]
* **Modpack Version**: 1.16.1

* **Issue**: I can get into the game just fine, but when i start playing, it will play normally for about 10 seconds, and then freeze up for about 5. I've tried to delete it and then redownload it, but it still happens. Also, I downloaded it off of the twitch desktop app.

* **Link to Log or Crash File Paste**: none

* **Is it Repeatable?**: yes

* **Mod/s Affected**: none known

* **Known Fix**: none known

**Comment by hiulok** [comment]
I know how but Idk is work for u btw should try it when you dowloaded the modpack go to edit profile and u will see the ram setting and cancel the 'tick' and then move the circle  to like 4000MB to 6000MB

**Comment by hiulok** [comment]
I try that I work doe

**Comment by Sunekaer** [comment]
Assign more ram, like hiulok said
