### ISSUE TITLE
Mod Suggestion: Blockcraftery and MalisisDoors

### ISSUE THREAD

**Issue by Explosivee** [FTBTeam/FTB-Presents-Stoneblock-2#77]
Hello, can you guys please add "Blockcraftery" mod into this mod package, it'd be really awesome, i know there is "ArchitectureCraft" but "Blockcraftery" is more useful in some places, also it'd be really, really, really awesome to add "MalisisDoors" as well, basically i want some more building mods :P Thanks!

**Comment by Explosivee** [comment]
Ikr? It'd be awesome if they add those two mods, especially for people who likes to build. DEV please answer to this.

**Comment by Salnex** [comment]
I suspect blockcraftery has been left out as ArchitectureCraft is present.
