### ISSUE TITLE
Computer freezing on twitch version

### ISSUE THREAD

**Issue by id-NaN** [FTBTeam/FTB-Presents-Stoneblock-2#771]
* **Modpack Version**: latest twitch

* **Issue**: my computer freezes every few hours when I am playing and I need to restart it using the power button

* **Is it Repeatable?**: I don't know when and why it happens

* **Added Mods**: latest cctweaked but the issue was there before
[saves.zip](https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/files/5022279/saves.zip)

**Comment by Sunekaer** [comment]
Twitch version isnt supported.
