### ISSUE TITLE
Unable to get Addon: FTB Presents Stoneblock 2 (310396) - File ID: 2818169

### ISSUE THREAD

**Issue by fortekon** [FTBTeam/FTB-Presents-Stoneblock-2#773]
* **1.12.2**: 

* **so when i try to download the modpack via twitch it installs and then adventualy it starts to deinstal and giving an error going like this: Unable to get addon: FTB Presents Stoneblock 2 (310396) - File ID: 2818169**: 
![Knipsel](https://user-images.githubusercontent.com/69522356/89916024-5f453e80-dbf7-11ea-9280-e05ad6318ccc.PNG)

* *yes it happens everytime when i try to download the modpack**: 

* **No :/**

**Comment by Sunekaer** [comment]
Please report to Twitch or use the FTB App
