### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by tankinnwow** [FTBTeam/FTB-Presents-Stoneblock-2#776]
* **Modpack Version**: Twitch Launcher Version 1.16.1

* **Issue**: Console Spam [Server thread/WARN] [net.minecraft.world.WorldServer]: Tried to add entity minecraft:item but it was marked as removed already

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/729fb625

* **Is it Repeatable?**: It has been going on for over a day now. Non stop spam.

* **Mod/s Affected**: None

While this issue does not seem to effect performance. It has been putting non spot messages in the server console.
![Capture](https://user-images.githubusercontent.com/10708240/90563510-940e4400-e169-11ea-8672-c79573e53505.PNG)

**Comment by Sunekaer** [comment]
Thats vanilla MC nothing we can do about it
