### ISSUE TITLE
Could not resolve harvestcraft:harvestpumpkinitem

### ISSUE THREAD

**Issue by jwfiredragon** [FTBTeam/FTB-Presents-Stoneblock-2#780]
* **Modpack Version**: 1.16.1

* **Issue**: On entering a world, the chat console logs the following error:
`ERROR: Avaritia.zs:24: Could not resolve <harvestcraft : harvestpumpkinitem>`
Indeed, there is no item with the ID `harvestcraft:harvestpumpkinitem` in the current version of HarvestCraft (1.12.2zf), though it used to exist in some older version. This is part of the Ultimate Stew recipe, and the error makes Ultimate Stew uncraftable.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Pam's HarvestCraft, Avaritia

* **Known Fix**: I've currently modified the offending line in Avaritia.zs to use `minecraft:pumpkin` instead, but changing it to any valid ID would fix this.

**Comment by Sunekaer** [comment]
Please use a newer version of the pack

**Comment by jwfiredragon** [comment]
Sorry for the late reply, but the Twitch launcher indicates that version 1.16.1 is the latest version available.
