### ISSUE TITLE
Inconsistent smeltery recipe for destabilized redstone

### ISSUE THREAD

**Issue by jwfiredragon** [FTBTeam/FTB-Presents-Stoneblock-2#783]
* **Modpack Version**: 1.16.1

* **Issue**: There are two recipes listed in JEI for smelting redstone into destabilized redstone - one produces 900mB per block, the other produces 1296mB per block. There are also two recipes listed for pouring out redstone blocks - one requires 900mB per block, the other requires 1296mB. It seems that the smeltery prioritizes the 1 block to 900mB recipe for smelting, but the 1 block to 1296mB recipe for pouring, which means you would lose 396mB of redstone every time you smelt and pour out a redstone block with the smeltery.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Tinkers' Construct, Thermal Foundation

* **Known Fix**: Currently trying to fix this via Tinkers' Construct's ModTweaker file, will report back.

**Comment by jwfiredragon** [comment]
Fixed by adding the following lines to Tinkers.zs:
`mods.tconstruct.Casting.removeBasinRecipe(<minecraft:redstone_block>);
mods.tconstruct.Casting.addBasinRecipe(<minecraft:redstone_block>, null, <liquid:redstone>, 900, false, 200);`
Using the 1 block to 900mB recipe to keep it consistent with the Magma Crucible recipe.

**Comment by Sunekaer** [comment]
version 1.21.0
