### ISSUE TITLE
Big Spender quest fails if submitted partially.

### ISSUE THREAD

**Issue by Slyklaw** [FTBTeam/FTB-Presents-Stoneblock-2#789]
* **Modpack Version**: 1.20

* **Issue**: If you submit a partial amount first (less than 100%), then when you submit the rest that adds up to max EMC it resets back to 0 instead of completing the quest.

* **Is it Repeatable?**: Yes.

* **Known Fix**: Get max EMC in transmutation table before submitting the quest.

**Comment by Sunekaer** [comment]
fix in version 1.21.0
