### ISSUE TITLE
my world keeps crashing due to most probably due to translocators

### ISSUE THREAD

**Issue by ainz666** [FTBTeam/FTB-Presents-Stoneblock-2#79]
* **Mod pack Version**: 1.0.1

* **Issue**: I used item translocators to send items from small storage crate into drawer controller. It didn't send items properly (like it didn't recognize compact drawers but not sure about it) and while i was checking what happened, i clicked the translocator with an iron ingot in my hand and the game froze for a full 30 mins. (i was using in full screen and so I restarted my PC ). When i loaded my world again, it kept crashing.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/73a1e48b

**Comment by Sunekaer** [comment]
https://github.com/Chicken-Bones/Translocators/issues/29
