### ISSUE TITLE
No mods downloaded 1.21.0

### ISSUE THREAD

**Issue by Carl10101** [FTBTeam/FTB-Presents-Stoneblock-2#794]
* **Modpack Version**: StoneBlock 2 1.21.0

* **Issue**: I updated the game and none of the mods are installed and it loads normal Forge

* **Is it Repeatable?**: I think I can repeat this issue, I reinstalled the Pack and FTBApp

**Comment by Naxanria** [comment]
This is an issue with the FTB App, not the pack.

**Comment by Carl10101** [comment]
> This is an issue with the FTB App, not the pack.

oh ok, thanks for the update

**Comment by platinum8317** [comment]
Is there a fix for the App? thanks.

**Comment by Naxanria** [comment]
They are working on it :)

**Comment by platinum8317** [comment]
> They are working on it :)

Thank you, I looked at the issue log for the App but didn't see one specific to this mod pack.  Is this a general issue?  I installed the unstable 1.16 from the app and it worked fine from what I can tell.  
Should we create a new issue for specifically stoneblock in the app?

**Comment by Naxanria** [comment]
They know of the issue so that shouldn't be needed. But if it persists after today, then go make an issue.

**Comment by platinum8317** [comment]
I re-installed 1.20 stoneblock 2 and it installed fine. Cool. I'll check again tomorrow.
thanks

**Comment by Sunekaer** [comment]
fix been pushed, restart the app, and install the new version
