### ISSUE TITLE
Empty Clay Bucket crafts into Fresh Water

### ISSUE THREAD

**Issue by StratCat00** [FTBTeam/FTB-Presents-Stoneblock-2#8]
* **Modpack Version**: Version 1.0.0

* **Issue**: Empty Clay Bucket crafts into Fresh Water from Pam's 

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Ceramics and Pam's Harvestcraft

**Comment by Sunekaer** [comment]
Thanks for reporting
Hmm okay, looks like oredict from full buckets is getting transferred to the empty bucket
https://github.com/KnightMiner/Ceramics/issues/45

**Comment by Sunekaer** [comment]
1.1.0
