### ISSUE TITLE
Wither builder

### ISSUE THREAD

**Issue by Qaz17** [FTBTeam/FTB-Presents-Stoneblock-2#80]
* **Modpack Version**: 
1.0.1
1.1.0
* **Issue**: 
Wither builder from Industrial Foregoing is not craftable/disabled in the config. 
What is the reason for that.
* **Link to Log or Crash File Paste**: 
--
* **Is it Repeatable?**: 
--
* **Mod/s Affected**: 
Industrial Foregoing
* **Known Fix**: 
Enable in the configs. Line: 846

**Comment by Sunekaer** [comment]
The reason is that i find it to easy, to use that for an auto wither farm
