### ISSUE TITLE
A bug - but no crash (and not reproducable) - but has happened twice now.

### ISSUE THREAD

**Issue by Sabster** [FTBTeam/FTB-Presents-Stoneblock-2#81]
* **Modpack Version**: 
1.0.1 (latest release - will try beta tonight)

* **Issue**: 
From the "overworld" I dug up into the "mining dimension" (not sure what to call them) - and instead of appearing at the bottom of the mining level (where I had already started a few tunnels) I suddenly appeared at the top of the mining dimension (one or two blocks away from the end 'entrance') in a 1 block wide by 2 block high 'room'

This happened twice - both times on a server.  No errors - didn't see anything in the logs...  I had to use the tp command to get back to where I was...)

* **Is it Repeatable?**: 
Could not repeat - but it had happened at least twice...

* **Mod/s Affected**: 
None

* **Known Fix**: 
None that I know of - I simply OP'd myself and used /tp 1, 1, 1 and reappeared back in the overworld...

**Comment by Sunekaer** [comment]
Is the server running sponge?

**Comment by Sabster** [comment]
I'm not sure what sponge is to be honest.

**Comment by iKurama** [comment]
https://www.spongepowered.org/ The "spigot" software, but Sponge is for modded servers, enabling you to have plugins designed for Sponge, eg. market, valuta, voting etc.

**Comment by nzminecraftDOTcom** [comment]
Run /sponge version in game as a command, you'll either get "unknown command" or a reply, or "no permission"

**Comment by Sunekaer** [comment]
How long is your load in time when switching dim?

**Comment by Sabster** [comment]
/sponge resulted in "unknown command"

I updated to the latest beta build (1.1.1-1.12.2 (Beta))

Everything was working fine until just now, it happened again (no server crash, but I was booted from the server so I grabbed the client log: Pastebin:  https://pastebin.com/Hxc5iGLS

I logged back in, and I'm somehwere in the end.  I went from overworld to mining dimension - kicked out (never saw mining) - logged back in and was suffocating in end stone.  It looks like I'm near the bottom of the end.

Load times aren't very long at all - but I do have a very fast computer.  

Hope that helps out.

**Comment by Sabster** [comment]
I was watching my server to see what happens - and it happened again (this time I did see myself in the mining dimension, but it was like I was at the top of it - and then ended up in the end).  My server said I was "kicked for floating too long!" and flying was not enabled on this server.

**Comment by Sabster** [comment]
It definitely has something to do with floating - I just did it again (this time in reverse - went from mining to overworld - kicked for flying - and then was at the bottom of the overworld...) - I'm going to enable flying and see if I can recreate it later tonight.

**Comment by Sunekaer** [comment]
I need to know how long the takes, from starting tp to you can move

**Comment by Sabster** [comment]
I think I have a video of it - I'll upload to youtube

**Comment by Sabster** [comment]
https://youtu.be/KguCHgd8ktA - this was when i was trying to recreate it - and it's one of the ones that kicked me from the server from like the log above.  There were a few others where I didn't get booted (that would send me to the bottom of the end...)  In the video, you'll see me point at a couple cobble stone blocks, that's a small tunnel I covered up where I had come down, even though I was using my big tunnel you'll see in the video.  Also, just for clarity:  This is coming from the mining dimension to the overworld - booted - and then being at bedrock when I logged back in...  (I have the map up, so you can see coord's)

**Comment by Sabster** [comment]
I did enable flying yesterday - and no issues since so far.  I'll change the cooldown as well.  Thanks.
