### ISSUE TITLE
Philosopher Stone JEI recipe(s) list

### ISSUE THREAD

**Issue by MonfGeiger** [FTBTeam/FTB-Presents-Stoneblock-2#811]
* **Modpack Version**: 1.21.1

* **Issue**: The TL;DR of it is the JEI recipe list for what the philosopher stone can do is fucked. it lists not only what it can transmute stuff into in a crafting table (gold into diamond, the steps for alchemical coal and such), but it also lists every other normal recipe. If possible, maybe not have every recipe on what the stone crafting table can make since its essentially useless? or just move all that into a new JEI tab

* **Is it Repeatable?**: A constant

* **Mod/s Affected**: JEI Recipe List

* **Known Fix**: None that I can do

**Comment by R93950X** [comment]
This is because the philosopher's stone can also be used as a portable crafting table with its extra function.

**Comment by MonfGeiger** [comment]
The C key, right? I dont have a stone, yet I can still access it in the server I play it in. But I get you, so how's about a revision of my idea

Mods like actually additions, cyclic, and possibly others im forgetting have those Blue Info JEI tabs that give a short description of what said machine/item does. Maybe just include its own Blue JEI info tab that explains it can open its own crafting grid to make all things you can do in a standard crafting table, so it would not need a massive 4000+ JEI entry page. Honestly, if I took the time to left click all the way from start to end of what the stone can craft in the crafting tab, my left mouse button would probably start dying. You have to admit its a tad bit excessive

**Comment by R93950X** [comment]
That's a suggestion for the ProjectE dev.

**Comment by MonfGeiger** [comment]
so thats an issue for that dev instead of this one......alrighty then, sorry for wasting a ticket
