### ISSUE TITLE
impossible quest 

### ISSUE THREAD

**Issue by michaelpaulsen** [FTBTeam/FTB-Presents-Stoneblock-2#816]
there is a quest that says to go to the mining dimension yet the mod "aroma1997s dimensional world" (adds the mining dimension) and its dependencies are not in the modpack by default.
![image](https://user-images.githubusercontent.com/14143704/99620288-195bfb80-29da-11eb-82bb-ac089f9beb6a.png)

**Comment by Sunekaer** [comment]
Click the quest and read the quest.
