### ISSUE TITLE
DUPE with the dank null

### ISSUE THREAD

**Issue by Caleb220** [FTBTeam/FTB-Presents-Stoneblock-2#82]
* **Modpack Version**: 1.0.1 (release)

* **Issue**:  You can dupe any item with the dank null by setting the item to extract all but 1 then take the item out and when you back into the dank null the items will be still in the dank null and you will still have the items you took out before 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**:  yes! 

* **Mod/s Affected**:  /dank/null

* **Known Fix**:

**Comment by iKurama** [comment]
https://github.com/p455w0rd/DankNull/issues/143

**Comment by Sunekaer** [comment]
1.2.0
