### ISSUE TITLE
help please help

### ISSUE THREAD

**Issue by kodecole** [FTBTeam/FTB-Presents-Stoneblock-2#831]
i loaded up stoneblock 2 server pack 1.21.1 on aternos and launched stoneblock 2 version 1.16.2 on twitch but when joining the server it says the server pack is out dated what version do i need to launch in twitch?

**Comment by Megatron3988** [comment]
I'm pretty Sure U cant use Twitch anymore when I'm typing this, and I am looking at the versions for StoneBlock 2 on the CurseForge launcher and it isn't showing 1.21.1 or wat ever BS Aternos says, My guess is either Aternos messed up and updated mods on its own or CurseForge Launcher hasn't had the update. I'm leaning on the first option though :/

**Comment by kodecole** [comment]
ty

    On Wednesday, April 21, 2021, 11:17:12 AM PDT, Sunekaer ***@***.***> wrote:  
 
 


Closed #831.
