### ISSUE TITLE
Draconic Evolution Information Tablet Blank

### ISSUE THREAD

**Issue by Rethgual** [FTBTeam/FTB-Presents-Stoneblock-2#84]
* **Modpack Version**: 1.1.0

* **Issue**: Draconic Evolution Information Tablet opens blank with an error trying to download info from a web address
![2019-01-10_19 15 12](https://user-images.githubusercontent.com/36059797/50965533-2a4da300-150d-11e9-9a80-26e1768fd22f.png)

* **Link to Log or Crash File Paste**: Does not crash the game

* **Is it Repeatable?**: I saved my world onto a external folder and deleted StoneBlock 2 Instance and reloaded the game to the same symptoms.  I did not try it on the current release 1.0.1.

* **Mod/s Affected**: Draconic Evolution

* **Known Fix**:

**Comment by LIGITPICKLE** [comment]
I'm having the same issue.

**Comment by brandon3055** [comment]
This is an issue with the outdated java version shipped with Twitch. 
For now you can fix this by ether manually updating the twitch java install or you can install the fallowing mod.
https://minecraft.curseforge.com/projects/vanillafix?gameCategorySlug=mc-mods&projectID=292785
And I will look into adding this fix directly to PI

**Comment by r-mc2** [comment]
@brandon3055 Which version of Java would you recommend to update to? I'm on v1.8.0_201. This a case of needing 1.9?

**Comment by Sunekaer** [comment]
Thanks @brandon3055, ill add that fix
