### ISSUE TITLE
Please BUFF the Roost Collectors

### ISSUE THREAD

**Issue by Explosivee** [FTBTeam/FTB-Presents-Stoneblock-2#85]
Those are way too slow, literally useless it was fast in Stoneblock1 but for some reason it's nerfed, please but please buff those.

**Comment by iKurama** [comment]
I'd recommend you to post here: https://github.com/timrwood/roost/issues , as there aren't any config files for the Roost collector.
The only configs from roost are "The speed multiplier for the breeder. Higher is faster." & "The speed multiplier for the roost. Higher is faster."

**Comment by Sunekaer** [comment]
I haven't changed the speed on, they are on default. they won't be buffed
