### ISSUE TITLE
Exit Code 0 when trying to launch

### ISSUE THREAD

**Issue by LossCross** [FTBTeam/FTB-Presents-Stoneblock-2#853]
* **Modpack Version**: 1.12.2 

* **Issue**:  Hi, so I have been trying to play and whenever I try to play the game disappears and reappears with fun crash report of Exit code 0

![Screenshot 2021-01-24 143227](https://user-images.githubusercontent.com/77941834/105645831-0ab61880-5e51-11eb-83a4-39ad5003f93b.jpg)

I have uninstalled minecraft, twitch, java, the FTB app, and Overwolf, only to recieve this error each and every time to my wits end. 

* **Link to Log or Crash File Paste**: There is no crash report I can get

* **Is it Repeatable?**:  yes 

* **Mod/s Affected**: unknown

* **Known Fix**: Deleting and restarting but it doesn't work

**Comment by LossCross** [comment]
Okay, so I found a save in a different place with a, I think, corruption which has been force closing my client. 

Deleting it, restarting, re-downloading has fixed it fully.

**Comment by DothSypris** [comment]
where was the corruption file located
