### ISSUE TITLE
EU2 Enchanter crashes game

### ISSUE THREAD

**Issue by lewhitekid** [FTBTeam/FTB-Presents-Stoneblock-2#86]
* **Modpack Version**: 1.0.1
* **Issue**: Whenever you shift click into an EU2 Enchanter, the game crashes. I believe this only happens if what you're shift clicking in is too much to fit. Like if there is already 50 gold and you go to shift click another stack in. Or if there are 3 speed upgrades and you go to click more more than 1 more in. Has happened a few times in a row for me.

* **Is it Repeatable?**: yes

* **Mod/s Affected**: EU2

**Comment by iKurama** [comment]
https://github.com/rwtema/Extra-Utilities-2-Source/issues/226
