### ISSUE TITLE
Flux Network not drawing power from Cyclic Battery

### ISSUE THREAD

**Issue by MadLarkin25** [FTBTeam/FTB-Presents-Stoneblock-2#860]
Hi all, 

As the title says, I'm having an issue in Stoneblock 2 in which I can't get a Flux Plug to draw power. I have magmatic dynamos set up, feeding power to a Cyclic Battery, but connecting the Flux Plug to either doesn't draw any power. What can I do to fix this problem?

I'm currently using Stoneblock 2 version 1.16.1

There is no crash report as this issue does not crash my game, it just doesn't work the way it should

**Comment by SuperHydroman** [comment]
Hi MadLarkin25,

I have kind of the same issue. I am trying to have a flux network setup. Very basic etc etc. When I try to powr the plug via a Cyclic Wireless Transfer Node. It doesn't work. However, when I place it directly onto the Magmatic Dynamo. It works. It receives +973 RF/t. I don't know what causes this, but it is driving me crazy..

**Comment by MadLarkin25** [comment]
After much tinkering in a separate creative world, it seems to be working. I just have to make sure I've got everything set up, flux controller and flux storage included. I haven't tried using the Cyclic battery again, I'm just going straight off the dynamos (per SuperHydromans suggestion) and this is making the flux network actually do it's job.
