### ISSUE TITLE
Watch of Flowing Time does not work

### ISSUE THREAD

**Issue by thelapisfox** [FTBTeam/FTB-Presents-Stoneblock-2#87]
* **Modpack Version**: 1.0.1
* **Issue**: Watch of Flowing Time is not affecting tick rate on anything. I have it in the middle of a farm, put it on a pedestal, and turn it on (both while gold and not). You get the normal purple sparkles and ender looking stuff, but other then that, nothing else happens. Nothing grows like it should with the watch activated. 

* **Link to Log or Crash File Paste**: http://batman.gyptis.org/zerobin/?f6b193a754afd293#+ZNkoo2lguQdW9LYcIDDPXmv2EmgKgdZHsLfjHLB1kk=

* **Is it Repeatable?**: Yes
* **Mod/s Affected**: ProjectE

* **Known Fix**:

**Comment by Sunekaer** [comment]
Server, single player?

**Comment by iKurama** [comment]
Can you provide a gif or a video with proof too?

**Comment by thelapisfox** [comment]
Single Player. Also, don't know what happened but upon starting up the game today, it now works. It's weird because I tried restarting MC multiple times when it wasn't working and that did not fix it. I will keep an eye on it and if it happens again, I will take a video.
