### ISSUE TITLE
Crash when looking in JEI for Avaritia.

### ISSUE THREAD

**Issue by ttechr** [FTBTeam/FTB-Presents-Stoneblock-2#88]
* **Modpack Version**: 1.0.1

* **Issue**: When scrolling through JEI once it is to go to the Avaritia items minecraft stops responding. I have tried with searching @avaritia in jei and can only type the a before it stops responding. 

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/d62bd0f7

* **Is it Repeatable?**: Tried multiple times on server and single player 

* **Mod/s Affected**: Seems like Avaritia and JEI

* **Known Fix**:  Not sure.

**Comment by Sunekaer** [comment]
Hmm, so its only sometimes, havent had it happen to me before
Crash log?
I dont see anything in the log

**Comment by ttechr** [comment]
> 
> 
> Hmm, so its only sometimes, havent had it happen to me before
> Crash log?
> I dont see anything in the log

It happens every time and it doesn't fully crash it just stops responding.

**Comment by Sunekaer** [comment]
Could you try updating JEI and see if it still happens

**Comment by ttechr** [comment]
> 
> 
> Could you try updating JEI and see if it still happens

Updated it and seems to be working. Thanks!

**Comment by Sunekaer** [comment]
1.1.1
