### ISSUE TITLE
Axe of the Stream quest can't be completed

### ISSUE THREAD

**Issue by tonby** [FTBTeam/FTB-Presents-Stoneblock-2#89]
* **Modpack Version**: 1.1.0 (and also 1.0.1)

* **Issue**: I made an Axe of the Stream using TC alchemical infusion. However, the quest wasn't completed. Other elemental tools quests were completed when I finished infusion. I assume the quest may not be able to detect the success of the infusion. I tried it three times at two versions, but the quest didn't work at all. It might be caused because the order of the two enchantments "Burrowing" and "Collector" are reversed.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Thaumcraft, FTB Quests

* **Known Fix**: reverse the order of the enchantments or change the requested item

**Comment by Sunekaer** [comment]
1.1.1
