### ISSUE TITLE
Crimson Rites can't be created

### ISSUE THREAD

**Issue by tonby** [FTBTeam/FTB-Presents-Stoneblock-2#90]
* **Modpack Version**: 1.1.0 (and also 1.0.1)

* **Issue**: I tried to make Crimson Rites using TC infusion crafting. However, the infusion didn't start despite right-clicking the Runic Matrix with a Caster's Gauntlet. I checked the items' NBT and all the items were correct. One of the two Mundane Rings has "Runic shield +3". All the required essentias are enough. 
I couldn't identify the cause of this problem. It needs more information.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Thaumcraft

* **Known Fix**: Change the recipe to simpler one

**Comment by Sunekaer** [comment]
The recipe worked on our test server, are you have all the items correct? the recipe wont be made easier, as the quest unlocks the reset of thaumcraft research

**Comment by DinnerBeef** [comment]
yea for some reason jei is wrong you need both of them to be tier shield + 3 also pro tip you i would make sure you have backups of everything and alot of stuff to make sure the infusion does not go BOOM
