### ISSUE TITLE
Can't Damage Chaos Chicken

### ISSUE THREAD

**Issue by KarizmaHD** [FTBTeam/FTB-Presents-Stoneblock-2#91]
* **Modpack Version**: 1.1.0

* **Issue**: I killed the End chicken fine but then when i spawned Chaos Chicken i couldn't damage it

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: not sure

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Sunekaer** [comment]
The Chaos chicken has a lot of HP maybe thats why your not seen it, plus the Force field regens so you might just need to hit it again with the chicken stick
What are you trying to kill it with

**Comment by KarizmaHD** [comment]
i have spammed it with the chicken stick and my sword

**Comment by Sunekaer** [comment]
And how much damage does that do, it’s has 1400 hp.. Did you even hit it? It has abilities to push you away from it

**Comment by KarizmaHD** [comment]
i even tried to kill it in creative mode still did no damage at all

**Comment by iKurama** [comment]
I can't kill it in Creative, but I can in survival. I used Chaos Shurikens (made from chaos cores, before that, supremium shurikens), after hitting it with the stick. Does it take long? Yes. Can it be one-shot with sword of the cosmos, no.

**Comment by KarizmaHD** [comment]
ok i try again later and it was just bugged out or something

**Comment by RobertLSnead** [comment]
Seems impossible to kill this chicken, not sure what armor to use but I can tell you nothing is working against this chicken.  Is there any armor the chicken can not penetrate?

**Comment by iKurama** [comment]
Awakened Draconium armor.

**Comment by RobertLSnead** [comment]
Thanks, that was a major help, having it fully upgraded with a max flux cap. helped! :D
