### ISSUE TITLE
Can't visit Hellish place so cant get Infernal Furnace done in Thaumcraft

### ISSUE THREAD

**Issue by KarizmaHD** [FTBTeam/FTB-Presents-Stoneblock-2#92]
* **Modpack Version**: 1.1.0

* **Issue**: Because you cant go to nether i'm unable to complete the Infernal Furnace bit in Thaumcraft

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Sunekaer** [comment]
Read the tip in the Flux Filter quest

**Comment by ChromeFlux** [comment]
> Read the tip in the Flux Filter quest

Hey I know this is closed and all but quick question: For those of us who play on Wuss mode and haven't unlocked anything in terms of flux, what's the tip you're talking about? I'm stuck on the "visit a hellish place" bit as well. Thanks.
