### ISSUE TITLE
Quest "Crafting On the Go" will not complete

### ISSUE THREAD

**Issue by JosephHelland** [FTBTeam/FTB-Presents-Stoneblock-2#95]
* **Modpack Version**: 1.0.1

* **Issue**: Task "Crafting On the Go" will not complete. I have completed the previous "Items On the Go" and nothing works to complete this task. Tried with unpowered unlinked, powered linked, powered unlinked, and unpowered linked, tried using it in each state and nothing. Task will not complete. This is on a MP community server.

* **Link to Log or Crash File Paste**: no log or crash generated.

* **Is it Repeatable?**:  very

**Comment by Sunekaer** [comment]
#54
