### ISSUE TITLE
Upgrade speed - transfer node - generators

### ISSUE THREAD

**Issue by ESnmc** [FTBTeam/FTB-Presents-Stoneblock-2#96]
* **Modpack Version**:  1.0.1
* **Issue**:  When placing upgrade speed ( EU2 ) in a transfer node ( any )  , magmatic generators ( EU2 )          will stop working. Saying     " grid is overloaded " 

* **Is it Repeatable?**:  Yes , even when i put the upgrade in another dimension. the magmatic generators will stop working.

* **Mod/s Affected**:  Extrautils2-1.12-1.9.8

* **Known Fix**:

**Comment by nzminecraftDOTcom** [comment]
Do you have any GP generators, water mills, lava mills etc running? To use those upgrades you must have the required GP (Grid power) to operate the upgrades.
