### ISSUE TITLE
Thaumcraft Aspects not displaying in AE system

### ISSUE THREAD

**Issue by Cmoor** [FTBTeam/FTB-Presents-Stoneblock-2#97]
* **Modpack Version**: 1.0.1

* **Issue**: While viewing the AE system, you cannot see the Thaumcraft Aspects while holding shift but if you move the item in your inventory, you can then see them, while you're still in AE system GUI.
![ee3097e613347019bf6888eb778873b2](https://user-images.githubusercontent.com/8010625/51005870-a2689880-150e-11e9-9328-fee74120f6cb.gif)

* **Link to Log or Crash File Paste**: No crash

* **Is it Repeatable?**: Constant

* **Mod/s Affected**: Thaumcraft, Applied Energistics 2, JEI

* **Known Fix**: N/A

**Comment by Sunekaer** [comment]
https://github.com/Azanor/thaumcraft-beta/issues/1244
Doesnt seem like an issue the dev is gonna fix
