### ISSUE TITLE
Pack Won't Launch

### ISSUE THREAD

**Issue by x1reap** [FTBTeam/FTB-Presents-Stoneblock-2#99]
* **Modpack Version**: 1.1.1

* **Issue**: 
I've installed the pack and as soon as I go to play it, it won't open and says "The system cannot find the file specified." I've modified ram allocated, switched to the native launcher, and re-installed numerous times all with the same result.

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by nzminecraftDOTcom** [comment]
What file? Did it give a path where it expected it to be?

**Comment by istrysii** [comment]
[stone Block 2 log.txt](https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/files/2749649/stone.Block.2.log.txt)

**Comment by Sunekaer** [comment]
@istrysii please create your own issue, and use paste.feed-the-beast.com

**Comment by nzminecraftDOTcom** [comment]
try running the launcher as administrator - right click - run as administrator, if that fails then try re-installing the whole thing. Launcher and all.

**Comment by x1reap** [comment]
![log thing](https://user-images.githubusercontent.com/46587416/51062943-6a209300-15be-11e9-8516-0d4cfe069288.JPG)

**Comment by x1reap** [comment]
Sorry, just realized I didn't specify I was using the twitch launcher.

**Comment by x1reap** [comment]
I've run as administrator, same result. I'm currently trying to repair mc through the twitch launcher.

**Comment by nzminecraftDOTcom** [comment]
Ok so this error occurs when you go to launch the twitch launcher from your desktop, using the icon?
Or when you clikc "Mods" --> Minecraft --> FTB Sb2 [play]

**Comment by x1reap** [comment]
It happens when I go to play the pack through the twitch launcher.

**Comment by x1reap** [comment]
I wish I had more info for you, there really isn't much there.

**Comment by Sunekaer** [comment]
Please contact twitch, somethings wrong with your launcher
